### ISSUE TITLE
Website Internationalization Roadmap

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#100]
As the new website is being built out bit-by-bit, we're adding support for internationalized content on a per-section basis. I've been working with l33t speak under the language "vo" to test out the infra as it is built.

I expect there are (at least) four main components for creating content on a per-language basis:

- Website copy (navigation bar, index page, community page etc)
- Website (and handbook) content (markdown files mainly)
- Playground examples content, and on-screen copy 
- TSConfig reference content, and on-screen copy

Each one of these needs:

- Working English documentation as reference
- Infra for supporting the creation of internalized content
- Infra for supporting the presentation of internationalized content

Current state of internationalization:

- Website copy. 
  - [x] English
  - [x] Creation
  - [x] Users

- Website content (e.g. the handbook). 
  - [x] English
  - [x] Creation
  - [x] Users

- Playground examples:
  - [x] English
  - [x] Creation
  - [x] Users

- TSConfig:
  - [x] English
  - [x] Creation
  - [x] Users

## How To Contribute

1. Join the [TypeScript Discord](https://discord.gg/typescript) - come say hi the [`ts-web-translate`](https://discord.gg/gG7nsGA)

2. Clone the repo. The work will happen on the [`v2`](https://github.com/microsoft/TypeScript-Website/tree/v2) branch. Deploys of the TS website have this static site set up at http://www.typescriptlang.org/v2/

  ```sh
  git clone https://github.com/microsoft/TypeScript-Website
  cd TypeScript-Website

  code .
  code README.md

  # Follow setup instructions in README
  # then start up the server
  yarn start
  ```

3. Look below to see the sections, then come back up here

4. Read this PR to see an example of adding a language: https://github.com/microsoft/TypeScript-Website/pull/181

5. Pick one of the below sections to start with, it might be easiest to work with samples in the Playground first FWIW.

#### Website

The website supports localization via React-intl, as of today only the navigation bar it translatable, but with time this will grow. The infra just came in with https://github.com/microsoft/TypeScript-Website/pull/180

There are a series of keys and values for each language, with a fallback to English if you miss something. The TypeScript compiler will keep it all in check.

#### Playground

You can cover the examples in the dropdown in the playground (and in the site footer on desktops.) [Full docs here](https://github.com/microsoft/TypeScript-Website/tree/v2/packages/playground-examples)

- Make a subfolder with the code of the language [in the copy folder of the 'playground-examples'](https://github.com/microsoft/TypeScript-Website/tree/v2/packages/playground-examples)
- Ensure the _filename_ are the same as English, (you can provide a different title via the JSON headers in the ts/js files) 

#### TSConfig

Each TSConfig file is a unique markdown file which can be uniquely handled per language. Any markdown file not found will be replaced with English. [Full docs here](https://github.com/microsoft/TypeScript-Website/tree/v2/packages/tsconfig-reference)

-  [Check out this folder](https://github.com/microsoft/TypeScript-Website/tree/v2/packages/tsconfig-reference/)
- Ensure the _filename_ is the same (we can provide a different title via the YML headers in the markdown files) 

---

## Recommendations

I'm pretty new to the translation game, but here's some notes from working with people so far on how translations can culturally work in the TS website.

#### Translate code to be a cultural fit. E.g.

```ts
const helloWorld = "Hi" 
``` 

to

```ts
const olaMundo = "Olá`
```

####  Translate names in example 

```ts
const user =  { name: "John" }
``` 

to

```ts
const usar =  { name: "João" }
```

Note: we aim to have a diverse set of nationalities and genders in our examples, so I'd recommend not changing _all_ of them, but try keep it feeling like it was written with that in mind also.

#### Translate Technical Terms, but keep English around

This one is nuanced, but a term like `Mapped Type` is _the name_ for this:

```ts
type MyPartialType<Type> = {
  // For every existing property inside the type of Type
  // convert it to be a ?: version
  [Property in keyof Type]?: Type[Property];
};
```

So, if you translate it to "mapeada type", then provide a reference to the original name the first time it is used: "mapeada type (Mapped Type em inglês)" so that readers can know how to find the English resources on a topic.

**Comment by orta** [comment]
My long term goal will be to support the same style of infra which Gatsby and React use, but that requires having a full site ready with existing content for folks to work from - so it'll be piecemeal as I built it out

**Comment by orta** [comment]
https://github.com/microsoft/TypeScript-Website/pull/163 adds the ability to create and present internationalized playground samples

**Comment by glaucia86** [comment]
@orta hi! I was talking to Daniel, that you can count on me about to translate this pages to Portuguese. :)

**Comment by orta** [comment]
Woooo!

**Comment by Naturalclar** [comment]
@orta
Hello! I can help translating the website into Japanese :)
Also, the invite link to the TypeScript Discort in the Issue seems to be invalid.

**Comment by evanSe** [comment]
Hey @orta I would like to help out, are there any parts that still need internationalization support? (code wise) as I only know English so translations would be useless 😅

**Comment by orta** [comment]
Hi @evanSe - Yeah, there's still quite a lot of English text in JSX which hasn't moved to the internationalization pattern yet! 

For example there's the '[documentation](https://www.typescriptlang.org/v2/en/documentation/)' page ([code](https://github.com/microsoft/TypeScript-website/blob/46baa2238c5072ba03792fef993bf09cb843e4c0/packages/typescriptlang-org/src/pages/documentation.en.tsx#L1)), the same with the playground/tsx/handbook templates too

Here's an example of how the i8n works in the topnav as a reference

- Create a file for [the template](https://github.com/microsoft/TypeScript-website/blob/46baa2238c5072ba03792fef993bf09cb843e4c0/packages/typescriptlang-org/src/copy/en/nav.ts#L1)
- Link that to the [english language](https://github.com/microsoft/TypeScript-website/blob/46baa2238c5072ba03792fef993bf09cb843e4c0/packages/typescriptlang-org/src/copy/en.ts#L2)
- Create an `i` function in [the React component](https://github.com/microsoft/TypeScript-website/blob/46baa2238c5072ba03792fef993bf09cb843e4c0/packages/typescriptlang-org/src/components/layout/TopNav.tsx#L14-L19)
- Use [`i("key")`to get the text](https://github.com/microsoft/TypeScript-website/blob/46baa2238c5072ba03792fef993bf09cb843e4c0/packages/typescriptlang-org/src/components/layout/TopNav.tsx#L59-L60)

Documentation is a solid place to start, think about bits which _would_ change between languages (subheadings probably) vs which would never "React", "Angular" etc

**Comment by oalbacha** [comment]
I can help with Arabic translation support?

**Comment by orta** [comment]
https://github.com/microsoft/TypeScript-Website/pull/790 wraps up localizing docs content (e.g. the handbook etc), at this point every page and string _should_ be localized or localizable. 

If it's not, that's my fault and generally 'getting it shipped'-ness for the site. I'm going to start making a list of 'safe to translate' docs later in the week which means we're not planning on making changes to the actual content of the page.

**Comment by orta** [comment]
My general recommendations for reviewing localization are:

 - Does it provide enough english technical terms that you could google for the answer in English?
 - Is it readable without a deep knowledge of computer science?
 - Does it avoid overly gendered language?
 - Did you feel like you learned something from it?
 - General typoes etc I'm not too worried about, people will send PRs to fix them with time

**Comment by orta** [comment]
Hi folks, I have a question - what do you think is better when it comes to making big updates to some docs already translated. For example in #873 I drastically rewrote the docs for the TSConfig `esModuleInterop` and `allowSyntheticDefaultImports`. This basically deprecates the Japanese and Portuguese translations.

When I do this should I:

1. Delete the translations and have them fall back to English?
1. Make an issue for replacing the specific files in a specific language?

I lean towards 1, but have reservations. So I'm asking people their opinions.

1, is a little rude! Someone worked hard on that translation, and deleting it sucks. However, deleting it *does not* force someone else to do work under any timeframe. The gap will show up in the internationalization issue for your language as something to pick up eventually.

I don't plan on doing this often (most of the English docs are solid) but I'd like to at least get a sense of whether this is the right idea if it comes up again.

**Comment by KingDarBoja** [comment]
I would opt for the second choice and have some sort of automated issue to keep track which files requires translation updates so translators don't get confused which file got already the new translation.

**Comment by orta** [comment]
Hrm, yeah, maybe I could add a `outdated: "08/07/2020"` to the yml front-matter on those files and then the issue script can pick it up and place it at the top of the issue.

**Comment by danilofuchs** [comment]
Perhaps it is an over engineered approach, but perhaps if the english content is newer than the translated content, a warning could be placed on top of the article, saying something like:


> This documentation in Portuguese may be outdated. The original article was updated on 2020/08/07, but the last translation is from 2020/06/01. Maybe you can help us make it up to date! (Github Pinned Issue)

**Comment by khaosdoctor** [comment]
I like @KingDarBoja's idea, I think we can mix both of them. We could add an `outdated` label and also fallback these contents to the English Version.

**Comment by orta** [comment]
Interlinking my proposal for moving to a separate repo for translations, which should be happening Feb 2021 -  https://github.com/microsoft/TypeScript-Website/issues/1480

**Comment by orta** [comment]
It's February, and it's happening: https://github.com/microsoft/TypeScript-Website-Localizations/

**Comment by orta** [comment]
This is done and shipped
