### ISSUE TITLE
Docs: wrong example about CommonJS

### ISSUE THREAD

**Issue by marc2332** [microsoft/TypeScript-Website#1003]
**Page URL:** https://www.typescriptlang.org/tsconfig#commonjs

**Issue:** The CommonJS compiled output example is not accurate

**Recommended Fix:** Replace it with:
```ts
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.twoPi = void 0;
const constants_1 = require("./constants");
exports.twoPi = constants_1.valueOfPi * 2;
```

This output is extracted from this reproducible example I made: https://github.com/marc2332/tsc-module-commonjs

**Browser:** Firefox

**Comment by marc2332** [comment]
I must say this really confuses me. I dont really know if its a compiler issue or a docs issue.

Having the "__esModule" thing even when its a CommonJS module is really weird.

**Comment by orta** [comment]
Thanks - Found it, the cut off point for the code sample was in the wrong place, fixed in: https://github.com/microsoft/TypeScript-Website/pull/1007/commits/c89972d9fc374f0fa0747281fd79286c3ac05080
