### ISSUE TITLE
Idea: ts=dev

### ISSUE THREAD

**Issue by ShuiRuTian** [microsoft/TypeScript-Website#1006]
In fact I do not know whether this is an idea or issue......

**Improvement Idea:** in the README of playground, it says `ts=dev` is a special condition, but I could not find the choice. It would be great for TS developing.

I would be glad to help implement this feature, but I found it is not working in the way I familiar with(like I could not found the click callback in the tsx file), what should I know to start?

**Why:** Emm, it is said so in README ?

**Alternative ideas:**

**Comment by orta** [comment]
Good point, I never came back to this side to add docs - #1007 includes docs

There is a script inside the compiler codebase: https://github.com/microsoft/TypeScript/blob/master/scripts/createPlaygroundBuild.js

Which lets you run TS from your computer and hook into it via the playground

**Comment by ShuiRuTian** [comment]
Great, thanks!

**Comment by Peeja** [comment]
@orta That script no longer exists. What's the replacement?

E: It looks like [it was removed intentionally](https://github.com/microsoft/TypeScript/pull/51166). Is this feature just nonexistent now? Should the docs be updated to match?

E2: Reading that PR more closely, it sounds like the current solution is to get a maintainer to ask TS-bot to `pack this`. Is there an equivalent we mere mortals can run locally?

**Comment by orta** [comment]
Yep, you need to ask a team member to make you a build from a PR
