### ISSUE TITLE
Docs: tsconfig.json is not a json5 file

### ISSUE THREAD

**Issue by BlackGlory** [microsoft/TypeScript-Website#1019]
**Page URL:** https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Issue:**
`tsconfig.json` is not a json5 file, it is a jsonc file.
Therefore, `tsc` cannot recognize the example in the page.

**Recommended Fix:** 
```jsonc
{
  // Change this to match your project
  "include": ["src/**/*"],

  "compilerOptions": {
    // Tells TypeScript to read JS files, as
    // normally they are ignored as source files
    "allowJs": true,
    // Generate d.ts files
    "declaration": true,
    // This compiler run should
    // only output d.ts files
    "emitDeclarationOnly": true,
    // Types should go into this directory.
    // Removing this would place the .d.ts files
    // next to the .js files
    "outDir": "dist",
  },
}
```

**Comment by ahtee** [comment]
I see your recommended fix would be to only change the wording in the sentence before: _The TSConfig is a json5 file..._ from file to jsonc.

**Comment by BlackGlory** [comment]
@ahtee So, can you create a PR for this?
