### ISSUE TITLE
Playground: TypeScript version is not exported correctly to CodeSandbox/StackBlitz

### ISSUE THREAD

**Issue by karol-majewski** [microsoft/TypeScript-Website#102]
Hello and thank you for your work.

I noticed a small bug related to exports introduced in https://github.com/orta/typescript-play/pull/30. If you choose `3.7-Beta` from the list of available TypeScript versions and try to export your Playground to another tool:

- StackBlitz will ignore it (the default `package.json` will be used, no dependency will be added)
- CodeSandbox will respect it and try to install `3.7-Beta`, but it won't work since the `3.7-Beta` tag doesn't exist on `npm`. The users will see _Resolving Dependencies..._ forever.

**Comment by orta** [comment]
Hrm, this would require an extra mapping stage for these versions because they "exist" in the nightly build pipeline and don't correlate to official releases - good catch though
