### ISSUE TITLE
Saving sometimes causes `alert(undefined)`

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#1023]
https://github.com/microsoft/TypeScript-Website/blob/5ad258ccc5f4a68fc7a946a38fefa249d8c4f5c2/packages/playground/src/index.ts#L316

I'm not sure what causes this, but I periodically hit <kbd>Ctrl</kbd>+<kbd>S</kbd> and occasionally get an alert window with `undefined`.

**Comment by orta** [comment]
interesting, that's the error state I believe (when the function doesn't have access to write to your clipboard) - will see if I can trigger it. Edgium?

**Comment by DanielRosenwasser** [comment]
Firefox
