### ISSUE TITLE
Bug: Could not add nested page on Windows

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript-Website#1043]
**Bug:**

In trying to make a new `dt/search` page in https://github.com/microsoft/TypeScript-Website/pull/1017 while working on Windows (Cmd -> VS Code), we found that the page couldn't be found when developing. We debugged a bit on the stream and fixed it by modifying `createRootPagesLocalized.ts`:

* `fullpath = ` ... `.replace("..//", "../")`
* `originalSitePath = originalSitePath.split("\\").join("/")`

**Why:**

Something spooky was happening with path joins on Windows.

**Alternative ideas:**

Copying over to an issue for posterity in case others hit this. https://github.com/microsoft/TypeScript-Website/pull/1017/files#r483699178

**Comment by orta** [comment]
Fixed in #1017

**Comment by JoshuaKGoldberg** [comment]
Wait @orta I actually removed the fix changes from #1017, to keep the PR small
