### ISSUE TITLE
Undo doesn't work on code actions in the playground

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#107]
http://www.typescriptlang.org/play/index.html?ts=3.7-Beta&noImplicitAny=false&e=167#example/infer-from-usage-changes

Try applying the quick fixes and then hitting `Ctrl+Z` on Windows to undo. Currently it does nothing.

**Comment by orta** [comment]
This is a monaco bug I'm afraid - blocked on https://github.com/microsoft/monaco-editor/issues/1548

**Comment by orta** [comment]
Sent a quick PR: https://github.com/microsoft/vscode/pull/83938

**Comment by orta** [comment]
This got merged and will eventually make it's way upstream to us
