### ISSUE TITLE
Docs: Code sample in decoration files

### ISSUE THREAD

**Issue by yyaremenko** [microsoft/TypeScript-Website#1117]
**Page URL:**https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#use-optional-parameters

**Issue:** Missing signature in the 'WRONG' code block.

```
interface Example {
  diff(one: string, two?: string, three?: boolean): number;
}
```
allows to call
```
diff(one: 'abc', three: false)
```
meaning there has to be a method signature
```
diff(one: string, three: boolean);
```
which is absent in the 'WRONG' code block

**Recommended Fix:** Please add the mentioned signature into the 'WRONG' code block 

**Browser:** Firefox

**Comment by orta** [comment]
JavaScript uses positional arguments, not named ones, so you can't jump to the third param in the call.

Perhaps I misunderstood, can you show me what you mean in a full code sample or PR to the document?

**Comment by yyaremenko** [comment]
hey, thank you for the prompt reply;
if you go straight by the link I pointed out, you'll see the following

```
/* WRONG */
interface Example {
  diff(one: string): number;
  diff(one: string, two: string): number;
  diff(one: string, two: string, three: boolean): number;
}
```
```
/* OK */
interface Example {
  diff(one: string, two?: string, three?: boolean): number;
}
```
sorry, I got confused with the way methods are called in JS;
still, the interface in 'OK' section allows the following:
```
diff('one', undefined, true);
```
this is not possible with interface in the 'WRONG' section;

thus, the interface in 'OK' section is not the same as (does not provide the same functionality as) the interface in the 'WRONG' section and such, the example in the documentation is incorrect

**Comment by yyaremenko** [comment]
@orta may I have your update on this issue please?

**Comment by orta** [comment]
Yep, I agree that:

```ts
interface Example {
  diff(one: string): number;
  diff(one: string, two: string): number;
  diff(one: string, two: string, three: boolean): number;
}
```

Can differ from:

```ts
interface Example {
  diff(one: string, two?: string, three?: boolean): number;
}
```

When `strict` is turned on. We do try to imagine our docs as in strict mode, so I'm open to improvements.

**Comment by yyaremenko** [comment]
great, thank you
