### ISSUE TITLE
Docs: Readonly modifier explanation is spread accross several sections (Interfaces and Classes)

### ISSUE THREAD

**Issue by yyaremenko** [microsoft/TypeScript-Website#1123]
**Page URL:**
readonly properties (interfaces section)
https://www.typescriptlang.org/docs/handbook/interfaces.html#readonly-properties

readonly vs const (interfaces section)
https://www.typescriptlang.org/docs/handbook/interfaces.html#readonly-vs-const

readonly modifier (classes section)
https://www.typescriptlang.org/docs/handbook/classes.html#readonly-modifier

**Issue:** Information on readonly is not consolidated in one place, one should jump forth and back to get it all;
also, the explanation about actual mutability of objects referenced by a readonly property is not distinct (some info is given about arrays in particular, but not about objects in general)

**Recommended Fix:**
1. Consolidate info about readonly in one stand-alone subsection
2. Write a more distinct documentation about objects referenced by readonly properties mutability (and ways to remove that mutability if needed)

**Browser:** Firefox

**Comment by orta** [comment]
I disagree, we can't create special spaces for every interesting sub-topic - especially one which crosses as many boundaries as immutability. 

Perhaps the [immutability section in the playground](https://www.typescriptlang.org/play?q=460#example/immutability) can also add the classes examples but I don't see this happening otherwise.

**Comment by yyaremenko** [comment]
May I ask you why you think you can't create additional spaces? It sounds to me like you value the structure of the tutorial more than the actual experience / effectiveness of the tutorial, that said, 'a tutorial  in sake of tutorial'. No offence.

I believe the very idea of any tutorial is to: 
1) educate 
2) be a quick-peak glossary.
If I can't find the explanation and usage examples of readonly in one place, the tutorial is structured improperly.

As you mentioned, the readonly belongs to immutability, so probably it would make sense to create a separate section 'Immutability' and consolidate all related info there. I believe it's better to have more smaller sections with specific topics than fewer larger sections with topics mixed-up

What do you think?

**Comment by orta** [comment]
The handbook is a guided tutorial though all of TypeScript in a logical order, not a wiki, where lots of small scoped docs makes sense.

We have reference pages outside of the handbook for certain deep dives, but those are only valuable for large topics.
