### ISSUE TITLE
Playground: typing a twoslash option adds a lot of parameters to url

### ISSUE THREAD

**Issue by j-oliveras** [microsoft/TypeScript-Website#1124]
Typing a twoslash option on playground adds a new parameter into url after each character. See:

![imatge](https://user-images.githubusercontent.com/15308683/93998093-65047700-fd94-11ea-9d77-e7856ba69ce8.png)
![imatge](https://user-images.githubusercontent.com/15308683/93998143-751c5680-fd94-11ea-9be4-a7ce5158aa07.png)
![imatge](https://user-images.githubusercontent.com/15308683/93998253-8d8c7100-fd94-11ea-8a68-79125ff3184e.png)

**Repro:**
I tested it with Firefox 80 and Chrome 85:
* Open a empty playground (or clean it) and ensure the url not contains parameters. Add the header of a twoslash option: `// @` (Can use [this with both steps](https://www.typescriptlang.org/play?#code/PTAEAEg)).
* Start typing anything after the @ (can be a valid option, for example `noImplicitAny`). Do not copy it.
* See that after each character is typed a new parameter is added to the url (except the last one if the typed option is valid).

**Code**
Not needed, see repro.

**Expected behavior:**
Url parameters are not added, or only added if a valid compiler option is typed.

**Actual behavior:**
Typing a twoslash option on playground adds a new parameter into url after each character.

**Comment by orta** [comment]
Thanks - this is fixed on staging in https://github.com/microsoft/TypeScript-Website/pull/1115, I should just do a deploy
