### ISSUE TITLE
Docs: "Global: Modifying Module" template

### ISSUE THREAD

**Issue by mbelsky** [microsoft/TypeScript-Website#1125]
Hi,

**Page URL:** https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html#identifying-global-modifying-modules 

**Issue:** global module template contains export declarations. But import/export declarations convert ambient modules to "local". 

Should be these `export` lines removed from the template?

**Comment by orta** [comment]
I think it probably makes sense to have two examples,  these current examples are generally quite definitely typed focused right now where script vs module is less of an issue.
