### ISSUE TITLE
Documentation :Ability to collapse sidebar navigation and TOC to have middle column wider.

### ISSUE THREAD

**Issue by MNF** [microsoft/TypeScript-Website#1131]
## Search Terms
Documentation collapse sidebar navigation

## Suggestion

I am using 2017 iPad (5th Generation) with 2048x1536 Resolution(https://www.lifewire.com/what-is-ipads-screen-resolution-ips-display-1994325) to read documentation ( e.g. https://www.typescriptlang.org/docs/handbook/functions.html)
 and the main middle content column is quite narrow. Often I don’t care about both left and right sidebars and wish to hide them to have bigger real estate for main column.

Can sidebars be collapsible to be very narrow to just show expand buttons?
Alternatively can content column have toggled ‘full-screen’ button to show it on full real-estate and ‘show sidebars’ icon to return to current 3-columns view?

Good layout example :Page https://code.visualstudio.com/Docs/languages/javascript#_jsdoc-support, where sidebars do exist, but do not take so much real estate, and the middle column takes about 3/4 of the total width.It will be good if your layout will be similar.

## Use Cases

Read documentation on smaller screens with less scrolling.

## Examples

https://www.typescriptlang.org/docs/handbook/functions.html

## Checklist

My suggestion meets these guidelines:

* [ v] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [v ] This wouldn't change the runtime behavior of existing JavaScript code
* [ v] This could be implemented without emitting different JS based on the types of the expressions
* [v ] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [v ] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by orta** [comment]
Hi,  both sidebars are collapsable depending on the width of your browser (or zoom level) 

![2020-09-24 16-50-47 2020-09-24 16_51_34](https://user-images.githubusercontent.com/49038/94198840-e8ea5c00-fe85-11ea-9570-5a1cdd5b18ea.gif)

And for a side by side comparison, they are basically the sites have the same content widths, just with the TS site using more colors which I can see making it feel like there's less space

![Screen Shot 2020-09-24 at 4 52 32 PM](https://user-images.githubusercontent.com/49038/94198946-11725600-fe86-11ea-9006-7cca8c2b28df.png)

That said, I'm _generally_ open to design ideas and PRs for hiding the sidebars - they'd have to be accessible and support keyboard navigation.

**Comment by MNF** [comment]
For the my iPad resolution the layouts are different ![Image](https://i.imgur.com/8nMnSws.jpg)
And
![Image](https://i.imgur.com/W1dlAGd.jpg)

Responsive design of the page is good, but you make decision for the user instead of providing flexible control by the user.

When user reading the page, they concerned about content and do not need navigation at most of the time.
I suggest to give to user control by providing explicit buttons (expand/collapse) to see content on the full real estate of the page or only on the middle column.

**Comment by hamirmahal** [comment]
I'm running into the same issue right now.

**Comment by hamirmahal** [comment]
![image](https://github.com/microsoft/TypeScript-Website/assets/43425812/1f86cdc8-922f-411d-a478-7aae301339eb)

**Comment by hamirmahal** [comment]
Should I open a new issue for this?
