### ISSUE TITLE
Playground: Target ESNext setting displays "ES3" when loaded

### ISSUE THREAD

**Issue by tchetwin** [microsoft/TypeScript-Website#1136]
The query parameter `target=99` should select Target: "ESNext", but it displays "ES3" in the settings. (It turns out it's actually correctly set to ESNext under the hood as can be seen in the example below based on the down-level).

**Repro:**

When setting the TS Config -> Target setting to **ES2020** (for example):
✔ the query params update with `target=7` (for example)
✔ loading this URL results in ES2020 being selected [example](https://www.typescriptlang.org/play?target=7#code/DYUwLgBAhhC8FgE4FcQG4CwAoGAyX8UaQA)

When setting the TS Config -> Target setting to **ESNext**:
✔ the query params update with `target=99`
❌ loading this URL results in **ES3 being displayed** as selected [example](https://www.typescriptlang.org/play?target=99#code/DYUwLgBAhhC8FgE4FcQG4CwAoGAyX8UaQA)

The **expected behaviour** in the latter case is that "ESNext" will be _displayed_ in the settings as well as used by the compiler.

**Comment by mjpieters** [comment]
Ah, looks like I [filed a dupe](https://github.com/microsoft/TypeScript-Website/issues/1437). Sorry!
