### ISSUE TITLE
"Copy as Markdown Issue" doesn't reflect current selections in compiler options without reload

### ISSUE THREAD

**Issue by keithlayne** [microsoft/TypeScript-Website#114]
I found this when looking at the lib.d.ts issues, and thought for a second that it was related, but I think it's a red herring.  Didn't test every option, but it appears that the generated compiler options in the markdown only reflect the state at page load.

Seems like this could be problematic potentially when using this *awesome* feature to file issues.  The playground link should be good, but incorrect compiler options int the new issue could cause confusion.

Side note, when you load the playground without the code in the URL, the generated playground link matches, which (not likely a practical concern) doesn't match what's actually in the window.  Maybe replace the URL on load if you read from localStorage would fix that?  Not sure if that's a good idea or not.

**Comment by keithlayne** [comment]
orta-bot please label "Playground"  🚎

**Comment by keithlayne** [comment]
good bot

**Comment by orta** [comment]
Agree - I'd also like to cut down the example tsconfig - but the defaults for typescript are not the defaults for the playground (strict mode for example)
