### ISSUE TITLE
Docs: in the JSDoc Reference page, some "Unsupported tags" may be supported

### ISSUE THREAD

**Issue by DavidBruant** [microsoft/TypeScript-Website#1164]
**Page URL:** https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#unsupported-tags

**Issue:** 
> Unsupported tags
> (...)
> @readonly (issue [17233](https://github.com/Microsoft/TypeScript/issues/17233))

But the references issue is closed, so it looks like this is supported now

I haven't looked at the other issues, but possibly, some of the other tags listed as "unsupported" may be supported too

**Comment by orta** [comment]
thanks
