### ISSUE TITLE
Docs: README.md invalid markdown for links in Docs issue

### ISSUE THREAD

**Issue by sharechiwai** [microsoft/TypeScript-Website#1193]
The links in README.md for the Docs section is now shown as hyperlink, this is cause by the document has spaces, which markdown could not treat it as hyperlink

![image](https://user-images.githubusercontent.com/843624/94932226-5daf3d00-04fb-11eb-9843-d77cb23b4187.png)

**Page URL:** https://github.com/microsoft/TypeScript-Website

**Issue:** README.md Docs section, hyperlink does not work 

**Recommended Fix:** fix the spacing issue on the link or avoid having space in filename.

**Browser:** Google Chrome, Edge

**Comment by soub4i** [comment]
I will take this

**Comment by sharechiwai** [comment]
> I will take this

I have created a pull-request already https://github.com/microsoft/TypeScript-Website/pull/1194

**Comment by sharechiwai** [comment]
as #1194 has been merged and links is shown correctly, I will close this issue
![image](https://user-images.githubusercontent.com/843624/95095103-3788d780-075d-11eb-9e3a-9f2650601c00.png)
