### ISSUE TITLE
Playground: Does not work when Definition files are turned off

### ISSUE THREAD

**Issue by rredford6** [microsoft/TypeScript-Website#1210]
The playground fails to load when definition files are turned off

![image](https://user-images.githubusercontent.com/25091457/95155353-d0612800-0748-11eb-9424-438355e381fa.png)

**Repro:**
1. Load playground
2. Click settings
3. Uncheck "Definition Files"
4. Click `Browser Refresh Required`
5. Wait for page to reload
6. Notice `Uncaught (in promise) TypeError: Cannot read property 'getCurrentPlugin' of undefined` in browser console
7. Notice that the editor is light when it should be dark.  Other features act haphazardly

**Expected behavior:**
No error, code editor retains dark background

**Actual behavior:**
See 7 above

**Comment by rredford6** [comment]
https://github.com/microsoft/TypeScript-Website/blob/fa6cd939b6f0b7d5c216c4774014dfeba5a17b34/packages/playground/src/sidebar/settings.ts#L56

**Comment by orta** [comment]
Thanks, good spot - this should be fixed when #1275 is merged
