### ISSUE TITLE
Playground: Unable to use imports from npm

### ISSUE THREAD

**Issue by vaindil** [microsoft/TypeScript-Website#1215]
I imported a module from npm using the playground setting to do so, and tried importing types from that package to test something, but it does not work. I tried using [the official import/export example](https://www.typescriptlang.org/play#example/import-export), and it has the same problem, so I'll reference that instead of my own code.

In Firefox 81, I get this error when running the example with no changes:

> [ERR]: import declarations may only appear at top level of a module

In Chrome 86, I get this error:

> [ERR]: Cannot use import statement outside a module

**Repro:** Open [the official Import/Export example](https://www.typescriptlang.org/play#example/import-export), wait for the page to load, and click Run.

**Expected behavior:** The code should run.

**Actual behavior:** The code does not run, with the errors given above.

**Comment by orta** [comment]
Thanks, this should be fixed by the deploy today - the fix is https://github.com/microsoft/TypeScript-Website/pull/1209

**Comment by iyegoroff** [comment]
Seems like it is broken again. Running the repro produces the same errors in Chrome 101 & Firefox 99 and `Unexpected token '{'. import call expects exactly one argument.` in Safari 15.4
