### ISSUE TITLE
Docs: Able to return values inside void function

### ISSUE THREAD

**Issue by DHIKSHITH** [microsoft/TypeScript-Website#1234]
**Page URL:** https://www.typescriptlang.org/docs/handbook/interfaces.html#hybrid-types

**Issue:** I am new to typeScript. In Hybrid-types section i ran the sample code.
```Typescript
interface Counter {
  (start: number): string;
  interval: number;
  reset(): void;
}
```
In the above Interface the method reset() is void . That means it should not have the return type right? 
But when i return number i am getting no error.

```Typescript
function getCounter(): Counter {
  let counter = function (start: number) {} as Counter;
  counter.interval = 123;
  counter.reset = function () {return 2*3};
  return counter;
}

let c = getCounter();
c.reset();
```

If i define the return type in function like below . It behaves as expected. I am getting error.
```Typescript
function getCounter(): Counter {
  let counter = function (start: number) {} as Counter;
  counter.interval = 123;
  counter.reset = function ():void {return 2*3};
  return counter;
}
```

**If i change the reset() method's return type as number in interface and inside same function if i return the string i am getting Error. why not for void?** 
```typescript
interface Counter {
  (start: number): string;
  interval: number;
  reset(): number;
}

function getCounter(): Counter {
  let counter = function (start: number) {} as Counter;
  counter.interval = 123;
  counter.reset = function () {return "23"};
  return counter;
}

let c = getCounter();
c(10);
c.reset();
c.interval = 5.0;
```

**why should we declare void type for reset() method in interface?**

**I used typescript playground.**

**Comment by orta** [comment]
I believe this is because these functions are still assignable, for example all of this code is legal in TypeScript:

```ts
type VoidFunc = () => void

const a:VoidFunc = () => 23
const b:VoidFunc = () => "123"
const c:VoidFunc = () => {}
```

because never you've told the type system it the `void` means it us unused which means any value can be assigned there and you can still treat them as structurally the same in a structural type system
