### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by xiao-shu-sheng** [microsoft/TypeScript-Website#1240]
I think your document is suspected of misleading

**Page URL:** 

https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

**Issue:** 
![image](https://user-images.githubusercontent.com/23214175/95958652-03d04080-0e34-11eb-8932-11f3d266591c.png)

Even if you change the string type to the number type, it will report an error :ReferenceError: backpack is not defined

**Recommended Fix:** 

As a beginner, he may not know that there will be errors after the modification, I think you need to add this hint, or change to a more suitable example

**Browser:**

**Comment by orta** [comment]
Thanks for the issue. The example explains that it is declaring an constant which doesn't exist on the line above - I think this is fine 👍🏻

**Comment by jameszenartist** [comment]
I would have to agree with @gui-gu-zi 

As someone who is attempting to gain a deeper understanding of Typescript, unnecessarily adding additional concepts into such a supposedly simple example , not only creates needless frustration but wastes time.
