### ISSUE TITLE
running scripts/createLanguage.ts got an error

### ISSUE THREAD

**Issue by aladdin-add** [microsoft/TypeScript-Website#1244]
I was trying to create a zh-cn copy for tsconfig-reference, and following the [contributing guide](https://github.com/microsoft/TypeScript-Website/tree/1c7fa745190010607a46dd7d2207e25013122976/packages/tsconfig-reference#contributing-a-new-language):

> If you'd like to create a new language:
> 
> Do you plan on making an evening or two on it and go all out? then you can use the script ./scripts/createLanguage.ts to set up a new language.

but got an error like:

```bash

/Users/weiran/repo/github/TypeScript-Website/packages/tsconfig-reference/scripts/createLanguage.ts:24
options.forEach(opt => {
        ^
TypeError: options.forEach is not a function
```

not sure if I missed something, or a bug in here?

**Comment by orta** [comment]
Oh yeah, I've not been keeping that up to date. I think I'm just going to remove that script entirely - thanks!
