### ISSUE TITLE
Idea: Remove Closed-Source Tracking From 'Microsoft and our third-party partners'

### ISSUE THREAD

**Issue by resynth1943** [microsoft/TypeScript-Website#1250]
**Improvement Idea:**

> **Manage cookie preferences**
> Most Microsoft websites use cookies. Cookies are small text files placed on your device to store data so web servers can use it later. Microsoft and our third-party partners use cookies to remember your preferences and settings, help you sign in, show you personalized ads, and analyze how well our websites are working. For more info, see the Cookies and similar technologies section of the Privacy Statement.
>
> **Required**
We use required cookies to perform essential website functions. For example, they're used to log you in, save your language preferences, provide a shopping cart experience, improve performance, route traffic between web servers, detect the size of your screen, determine page load times, improve user experience, and for audience measurement. These cookies are necessary for our websites to work.
>
> **Analytics**
> We allow third parties to use analytics cookies to understand how you use our websites so we can make them better and the third parties can develop and improve their products, which they may use on websites that are not owned or operated by Microsoft. For example, they're used to gather information about the pages you visit and how many clicks you need to accomplish a task. We use some analytics cookies for advertising.
>
> **Social Media**
> We and third parties use social media cookies to show you ads and content based on your social media profiles and activity on our websites. They’re used to connect your activity on our websites to your social media profiles so the ads and content you see on our websites and on social media will better reflect your interests.
>
> **Advertising**
> We and third parties use advertising cookies to show you new ads by recording which ads you've already seen. They're also used to track which ads you click on or purchases you make after clicking on an ad for payment purposes, and to show you ads that are more relevant to you. For example, they're used to detect when you click on an ad and show you ads based on your social media interests and website browsing history.

Can you *please* remove this user-hostile "Accept our tracking" banner at the top of the [TypeScript website](https://typescriptlang.org)?

We do *not* need this insane commercialisation of an **open-source product.** These are two *completely* separate ideologies.

Forcing this capitalistic tracking onto people is not a good look, especially when Microsoft claims to **"love" open-source**. While I applaud the TypeScript project as a whole, it's time to put your money where your mouth is, first off by removing this **closed-source** **tracking** from the [TypeScript website](https://typescriptlang.org).

Please.

**Why:**

Capitalistic tracking does not go hand in hand with an open-source product, *especially* when said tracking bears absolutely no relevance to the product. It is definitely not appropriate to ask people to accept nefarious spyware projects being led by underground advertising companies.

Let's go through some of the items in the cookie banner:

> Most Microsoft websites use cookies. 

But it's not a Microsoft website. It's *our* website, not yours.

> use cookies to remember your preferences and settings,

Aside from dark mode (and this cookie banner), I can't really see any preferences on the TypeScript website. Am I looking in the wrong place?

> help you sign in, show you personalized ads, 

Is Microsoft selling my data to 'third-party partners'? I'd like to know how 'personalised ads' are relevant to an open-source product?

Why is this pervasive tracking present on the website of an open-source product? Do you not have the financial means to maintain this website without adversarial tracking? 🤔 

**Alternative ideas:**

**Completely remove this from the website.** While having a cookie banner is commonplace, I cannot fathom as to why Microsoft requires my consent for 'third-party partners' to track me via 'advertising'. 

This notion is bewildering, most especially in such a widely-used technology like this. 😅 

Are we getting analytics in the TypeScript CLI next? Where do we draw the line?

**Comment by resynth1943** [comment]
I have pictures.
![2020-10-17_17-01_2](https://user-images.githubusercontent.com/49915996/96347581-80645880-109a-11eb-8bc8-85abb4210d91.png)
![2020-10-17_17-01_1](https://user-images.githubusercontent.com/49915996/96347582-80fcef00-109a-11eb-8103-022944cbd169.png)
![2020-10-17_17-01](https://user-images.githubusercontent.com/49915996/96347584-81958580-109a-11eb-907c-e8ee82cbaccc.png)
![2020-10-17_17-00](https://user-images.githubusercontent.com/49915996/96347586-822e1c00-109a-11eb-9839-1eceacdd5abb.png)

**Comment by resynth1943** [comment]
Just a sidenote: I'd be happy to send a PR that removes the cookie banner. Anything to help. 👍🏼

**Comment by orta** [comment]
Nope, that has to be on every Microsoft property regardless of our cookie usage (which I believe only comes from the analytics platform we host) - the site itself uses localStorage a lot which some could argue is similar.

I'd rather not have it, obviously, but we don't have a choice in the matter. 

Microsoft puts millions of dollars into TypeScript every year in salaries, I think the company is entitled to cover itself with the law on its own websites.
