### ISSUE TITLE
Playground: cant scroll options 

### ISSUE THREAD

**Issue by talhag3** [microsoft/TypeScript-Website#1259]
![image](https://user-images.githubusercontent.com/16940319/96587431-c1a77300-12fb-11eb-988b-9787789d13d5.png)

cant scroll options 
**Repro:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Comment by orta** [comment]
I'm afraid this is a monaco issue - https://github.com/microsoft/monaco-editor/ - you're welcome to re-file upstream, or take a look at fixing it there.
