### ISSUE TITLE
No "Code ran. Check the console" if code throws an exception

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#126]
http://www.typescriptlang.org/play/index.html?target=1&ts=3.8.0-dev.20191105&ssl=7&ssc=1&pln=8&pc=1#code/JYOwLgpgTgZghgYwgAgPICMBWyDeBYAKGWOTgH4AuXQk25dS5AZzClAHMaSBfQ3gwgBsIYZAHssVDNgC81IiThV8CuvSoAiOOgQauxfv0IIxIJmOEA6QWPYAKCZkvlL6AISWmAB0HAwdjXQNAEpgoA

```ts
interface Obj {
    a?: {
        b?: string
    }
}

let obj: Obj = {
    a: {
        b: "abc"
    }
}

console.log(obj.a?.b!.split("b"))
``

**Comment by orta** [comment]
This is fixed in v3
