### ISSUE TITLE
Docs: How about renaming MouseEvent with one that is compatible with built-in types

### ISSUE THREAD

**Issue by m-shaka** [microsoft/TypeScript-Website#1267]
**Page URL:**
https://www.typescriptlang.org/docs/handbook/type-compatibility.html#function-parameter-bivariance

**Issue:**
In TypeScript playground, interface `MouseEvent` is a built-in type,
so the example code raises error ([playground](https://www.typescriptlang.org/play?#code/KYOwrgtgBAogbqALgFQJ4AdhQN4FgBQUUAsgPZgDOwANAUQNLCoBGpAhgE4Amt+AvgQIBLEImAcAZmwDGWeEhx0oiIRGAVEbCOgBcUcBGbiA3AQH5ho8VNklyVeaMWEiUAB56DRjqZdFUnpDevuZAA)).

This is confusing for learners.

**Recommended Fix:**
`MouseEvent` should be renamed with another one, for example `MyMouseEvent`.

**Browser:**
All.

**Comment by orta** [comment]
Thanks, I've prefixed it in the code samples in #1275
