### ISSUE TITLE
Docs: include default is missing in tsconfig reference

### ISSUE THREAD

**Issue by pelepelin** [microsoft/TypeScript-Website#1269]
**Page URL:** https://www.typescriptlang.org/tsconfig#include

**Issue:** 

Old reference had a paragraph starting with:

> If the `"files"` and `"include"` are both left unspecified, the compiler defaults to including all TypeScript (`.ts`, `.d.ts` and `.tsx`) files in the containing directory and subdirectories except those excluded using the `"exclude"` property. JS files (`.js` and `.jsx`) are also included if `allowJs` is set to true.

https://github.com/microsoft/TypeScript-Handbook/blob/master/pages/tutorials/tsconfig.json.md#details

It's missing in new reference. New reference only states that `include` default is `false`.

**Recommended Fix:** 

Copy the paragraph from the old reference.

**Comment by orta** [comment]
Looks like a typo in the code for extracting the default, should be fixed when #1275 is merged - thanks!
