### ISSUE TITLE
The type search page does not seem to appear in the navigation

### ISSUE THREAD

**Issue by stof** [microsoft/TypeScript-Website#1272]
#1017 added a new type search page which replaces https://microsoft.github.io/TypeSearch/ but I cannot find it anywhere in the navigation of the website.

I would find it logical to access it through the `tools` section.

**Comment by orta** [comment]
Agree!

**Comment by orta** [comment]
Hrm, not as simple as I'd like - I'm not too far off wrapping up the designs for the DT page. So for now, this is gonna have to stick out as a gap ATM
