### ISSUE TITLE
Docs: TypeScript-Website/packages/sandbox/README.md

### ISSUE THREAD

**Issue by Akxe** [microsoft/TypeScript-Website#1283]
**Page URL:** https://www.typescriptlang.org/dev/sandbox/

**Issue:** The code sample is not working.

The code (same as in TypeScript-Website/packages/sandbox/README.md), has links, that point to 404! The "https://www.typescriptlang.org/v2/js/vs.loader.js" response with error 404. However, after fixing this, there more errors emerged.

**Recommended Fix:** 
I found out, that `https://www.typescriptlang.org/js/vs.loader.js` the URL should not include `v2/`. After that, I am sadly lost.

**Additional node:**
The `const isOK = main && window.ts && sandbox` is not a safe function. If either `main`, or `sandbox` is not defined. The code will throw rather than set `isOk` to false.

**Browser:** 
Maybe? Not sure I am using Chrome

**Comment by SMAKSS** [comment]
I agree that we should fix the broken link to the hosted `vs.loader.js` and there is a note in front of the provided link:

> *(note, we will eventually deprecate the /v2/ in all routes)*

which mention the deprecation of the `/v2/` in the routing system, so I think we can safely change the link without any problem.

Also, the code sample is the same as one that mentioned in the #1267, so I think we have a couple of them to fix.

And lastly, for your additional note, I think we already have the `main` and `sandbox` in the earlier lines of our code there and to use the sandbox having them is a necessity so there is no reason for them to being not defined. But on the other hand the code structure there is a bit messy I guess because all of the work should be done in the `onload` event and the `main` and `sandbox`  are accessible through the process. So I think we have to reformat the `initialCode` part to prevent inconsistency.

**Comment by Akxe** [comment]
The point is that after I fixed the URL of loader, the next error was `ReferenceError: "sandbox" is not defined`...

**Comment by SMAKSS** [comment]
Oh, I forgot to mention we are using the `sandbox` in the following function as `tsSandbox` because we are accessing the `index` of the sandbox and so on, so to use it you need to replace the `sandbox` in grabbing Monaco section with `tsSandbox`. I wonder why is this typo is still there 😏. Also, `createTypeScriptSandbox` won't return a promise so it will lead to confusion and error since we used `.then` in the follow up of creating the sandbox.

Anyway, for now, you can use this following temporary code instead of the one provided on the website.

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
</head>
<div id="loader">Loading...</div>
<div id="monaco-editor-embed" style="height: 800px;" />
<script>
  // First set up the VSCode loader in a script tag
  const getLoaderScript = document.createElement('script')
  getLoaderScript.src = 'https://www.typescriptlang.org/js/vs.loader.js'
  getLoaderScript.async = true
  getLoaderScript.onload = () => {
    // Now the loader is ready, tell require where it can get the version of monaco, and the sandbox
    // This version uses the latest version of the sandbox, which is used on the TypeScript website

    // For the monaco version you can use unpkg or the TypeSCript web infra CDN
    // You can see the available releases for TypeScript here:
    // https://typescript.azureedge.net/indexes/releases.json
    //
    require.config({
      paths: {
        vs: 'https://typescript.azureedge.net/cdn/3.7.3/monaco/min/vs',
        // vs: 'https://unpkg.com/@typescript-deploys/monaco-editor@3.7.3/min/vs',
        sandbox: 'https://www.typescriptlang.org/js/sandbox',
      },
      // This is something you need for monaco to work
      ignoreDuplicateModules: ['vs/editor/editor.main'],
    })

    // Grab a copy of monaco, TypeScript and the sandbox
    require(['vs/editor/editor.main', 'vs/language/typescript/tsWorker', 'sandbox/index'], (
      main,
      _tsWorker,
      tsSandbox
    ) => {
      const initialCode = `import {markdown, danger} from "danger"

export default async function () {
    // Check for new @types in devDependencies
    const packageJSONDiff = await danger.git.JSONDiffForFile("package.json")
    const newDeps = packageJSONDiff.devDependencies.added
    const newTypesDeps = newDeps?.filter(d => d.includes("@types")) ?? []
    if (newTypesDeps.length){
        markdown("Added new types packages " + newTypesDeps.join(", "))
    }
}
`

      const isOK = main && window.ts && tsSandbox
      if (isOK) {
        document.getElementById('loader').parentNode.removeChild(document.getElementById('loader'))
      } else {
        console.error('Could not get all the dependencies of sandbox set up!')
        console.error('main', !!main, 'ts', !!window.ts, 'sandbox', !!tsSandbox)
        return
      }

      // Create a sandbox and embed it into the the div #monaco-editor-embed
      const sandboxConfig = {
        text: initialCode,
        compilerOptions: {},
        domID: 'monaco-editor-embed',
      }

      const createTypeScriptSandbox = new Promise((resolve, reject) => {
        resolve(tsSandbox.createTypeScriptSandbox(sandboxConfig, main, window.ts));
      });

      createTypeScriptSandbox.then(tsSandbox => {
        tsSandbox.editor.focus()
      })
    })
  }

  document.body.appendChild(getLoaderScript)
</script>

</html>
```

**Comment by orta** [comment]
Thanks folks, I've updated the sample code in #1275 - it'll go live pretty soon

![Screen Shot 2020-10-27 at 11 26 57 AM](https://user-images.githubusercontent.com/49038/97323582-54d63080-1847-11eb-90b3-ded8a08f8b2d.png)

**Comment by orta** [comment]
I've also done a run through the codebase for any other `/v2/` references, thanks!

**Comment by Akxe** [comment]
With this very simple code:
```ts
import { fromEvent } from "rxjs";
import { map } from "rxjs/observable";

fromEvent('click').pipe(
    map(e => e.name),
);
```

I am getting an error:
```
Access to fetch at 'https://www.unpkg.com/undefined@0.1.0/rxjs/observable.d.ts' (redirected from 'https://www.unpkg.com/undefined/rxjs%2Fobservable.d.ts') from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by Akxe** [comment]
I have one more request. I am working on replacing [rxviz.com](//rxviz.com) old editor with the one TS team made. 

I have added a path to require to automatically resolve `rxjs`, but the `rxjs/operators` gives me trouble.

```js
require.config({
  paths: {
    vs: 'https://typescript.azureedge.net/cdn/3.7.3/monaco/min/vs',
    sandbox: 'https://www.typescriptlang.org/js/sandbox',
    rxjs: 'https://unpkg.com/@reactivex/rxjs/dist/global/rxjs.umd.js',
  },
  // This is something you need for monaco to work
  ignoreDuplicateModules: ['vs/editor/editor.main'],
})
```

------
PS: Why is the editor fixed to version `3.7.3`?

**Comment by Akxe** [comment]
@orta May I ask for assistance?

**Comment by orta** [comment]
Hi, I'm afraid I've never used rxjs in a UMD context so I can't be of much use there. 

I'd recommend reading up on how UMD works and the rxjs documentation for it. 👍🏻

**Comment by Akxe** [comment]
The UDM part is not a problem. The problem is that type resolver crashes. As it tries to load wrong URL.

This however might be up for an other issue.

```ts
import { of } from 'rxjs';
import { map } from 'rxjs/operators';

of([1]).pipe(
  map(n => n ** 2),
);
```

@orta the wierd part is that TS can usually figure out that `rxjs/operators` is part of `rxjs` but not in this case...

**Comment by orta** [comment]
It looks like it's an AMD module loader FWIW

You're running in a browser context, the way in which the require function from the [vs loader](https://github.com/Microsoft/vscode-loader) might not work how you expect, if you're happy with your own existing browser module loader then you can also use that once the loader for monaco/sandbox are set up

**Comment by Akxe** [comment]
A am prototyping, I used the code given in your example. But the error is also present in the [typescript playground](https://www.typescriptlang.org/play?ssl=4&ssc=5&pln=4&pc=10#code/JYWwDg9gTgLgBAbzhAZnAvnFUIjgcigA8ArAZ3wG4AoUSWROEAQzAyxz0NLIHoIwAUyjMY0CjWqoAFAG0AjABoATIoDMAXQCUAOjDAh06nCatpROAF4AfHAsBqAgEIX+LYupbKQA).

**Comment by Akxe** [comment]
@orta what package should I report to the error of not downloading correct types for `rxjs/operators`?

**Comment by orta** [comment]
You're welcome to make a fresh issue on this repo 👍🏻 or look into it yourself, the code is here: https://github.com/microsoft/TypeScript-website/blob/v2/packages/sandbox/src/typeAcquisition.ts

**Comment by Akxe** [comment]
Hi, I would like to point out, that the code in README.MD has error once again:

https://github.com/microsoft/TypeScript-Website/blame/v2/packages/sandbox/README.md#L93-L94
```js
sandboxFactory.createTypeScriptSandbox(sandboxConfig, main, window.ts)
sandbox.editor.focus()
```

Code above produces an error as `sandbox` is not defined. Code bellow solves this.

```js
const sandbox = sandboxFactory.createTypeScriptSandbox(sandboxConfig, main, window.ts)
sandbox.editor.focus()
```
