### ISSUE TITLE
Idea: Link in Translated Page Should Navigate on Translated Page as Well

### ISSUE THREAD

**Issue by jefrydco** [microsoft/TypeScript-Website#1284]
**Improvement Idea:**

Currently when we open translated page, let say `typscriptlang.org/id/` and we click the docs menu, we will navigate to default english version.

**Why:**

I think its better for user to stay on the translated page when they are navigating any link. It's inconvenient to navigate back and forth between english and translated version.

**Alternative ideas:**

**Comment by SMAKSS** [comment]
Well, I think it is a good idea, but ATM I think we don't have any translation available for that [specific page](https://www.typescriptlang.org/id/docs/), so I think that is the reason behind the redirect to the English version.

**Comment by orta** [comment]
Yep, what you want is how it works today - so long as there is a translated version, we should be keeping people in their same locales.

**Comment by orta** [comment]
Last month I improved some of the places where it was accidentally leaking back to English, it should be much better now at _not_ going back to English when there's localized content

Its hard for me to catch these ( as I only read the English docs ) so please bring this back up if it happens again!
