### ISSUE TITLE
String is not compiled successfully in Playground

### ISSUE THREAD

**Issue by abdallamourad** [microsoft/TypeScript-Website#1287]
String in playground does not compile successfully. When there are new lines in string I tried to console log the value, the new lines weren't there.

## Code
![image](https://user-images.githubusercontent.com/29834890/97299101-64796780-188f-11eb-8daa-6396ec52c5bb.png)
![image](https://user-images.githubusercontent.com/29834890/97299045-4d3a7a00-188f-11eb-8bbd-c89e8f848a7d.png)

## Output
![image](https://user-images.githubusercontent.com/29834890/97297830-8376fa00-188d-11eb-888a-af4261f44ec6.png)

**Repro:**
- Go to Handbook -> Basic Types -> String example *Both examples*
- Navigate to playground 
- append console.log(sentence) at the end of the script
- Click Run
- *The Output does not match the code* 

**Code**
```
let fullName: string = `Bob Bobbington`;
let age: number = 37;
let sentence: string = `Hello, my name is ${fullName}.

I'll be ${age + 1} years old next month.`;

console.log(sentence)
```
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
[LOG]: "Hello, my name is Bob Bobbington. 

I'll be 38 years old next month."
**Actual behavior:**
[LOG]: "Hello, my name is Bob Bobbington. I'll be 38 years old next month."

**Comment by orta** [comment]
Looks like we need to do `white-space: pre` on the logs to retain white spacing, thanks.

**Comment by abdallamourad** [comment]
Thank you! I will close the issue
