### ISSUE TITLE
Docs: Dead TSConfig Options link in the documentation footer ('Popular Documentation Pages' section).

### ISSUE THREAD

**Issue by 7ze** [microsoft/TypeScript-Website#1291]
**Page URL:** https://www.typescriptlang.org/tsconfig.html

**Issue:** The above mentioned link to [TSConfig Options](), given in the footer section of the documentation appears to be broken. Apparently, the resource has been removed, had its name changed, or is temporarily unavailable.

**Recommended Fix:**  Update the link to the appropriate resource. Perhaps, the intended link was meant to be [this](https://www.typescriptlang.org/tsconfig) instead of [this](https://www.typescriptlang.org/tsconfig.html).

**Browser:**  Firefox

I'll be interested to fix this if I can get a chance.

**Comment by orta** [comment]
Yep, great spot! 

It shouldn't have the .html in the link, you can find it here:

https://github.com/microsoft/TypeScript-website/blob/v2/packages/typescriptlang-org/src/components/layout/SiteFooter.tsx#L48

**Comment by 7ze** [comment]
Ah I see. So if I update the `url` field, then the link gets updated I believe?
[Pardon me, I'm just a beginner 🙇🏻 ]

**Comment by orta** [comment]
Yes 👍🏻
