### ISSUE TITLE
Playground: Log tab breaks when running the code without `console.log` statement

### ISSUE THREAD

**Issue by abdallamourad** [microsoft/TypeScript-Website#1300]
Log tab breaks when running the code without `console.log` statement when clicking run dashed-line is displayed each time regardless there is new log statements or not.

![image](https://user-images.githubusercontent.com/29834890/97580889-dd62f580-1a2e-11eb-89a6-f98f55924c6d.png)

**Repro:**
 - Go to playground
 - Click log tab **notice No logs statement is displayed.**
 - Click run with no `console.log` statements in the code **No logs statement disappear.**
 - Click Run multiple times, with each time new dashed line is displayed.
**Code**
```let isDone: boolean = false;```
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
- **No Logs** statement shouldn't be replaced when **Run** button is clicked without `console.log` statement for first time.
- No New dashed line displayed unless there is a change in `log` tab.
**Actual behavior:**
- **No logs** statement disappears when clicking **Run** for the first time.
- Dashed line is displayed regardless new log is appended or not.

**Comment by orta** [comment]
This is on purpose, but I'm open to this changing 👍🏻

**Comment by abdallamourad** [comment]
I see. I was actually surprised when I couldn't find any part of the code that handles it. I didn't know it was on purpose 😃

**Comment by hahmadia** [comment]
@orta 
I believe this can be closed. Seems to not be reproducible anymore. Please advise.
![image](https://user-images.githubusercontent.com/17804942/110195822-08f75180-7e0e-11eb-949b-7ffb6a3c5ff7.png)

**Comment by abdallamourad** [comment]
@hahmadia
Unfortunately It's not completely fixed. It's still producible.

### Step to produce 
* click run multiple times without `console.log` in the source code.
* add `console.log` to your source code and click run

### Result
Multiple lines display before the current log statement
![image](https://user-images.githubusercontent.com/29834890/110212190-26432300-7ed5-11eb-95f9-769180bf0768.png)

### Expected behaviour
Log statement should display at the very top line as no logs occurred before that

**Comment by hahmadia** [comment]
Not to worry, I've created a PR https://github.com/microsoft/TypeScript-Website/pull/1625 which resolves this problem
