### ISSUE TITLE
Playground: Page won't load...

### ISSUE THREAD

**Issue by VashJuan** [microsoft/TypeScript-Website#1308]
using last Firefox, if I go to:
https://www.typescriptlang.org/play#
It hangs on "downloading Typescript"

The Console lists this error:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://typescript.azureedge.net/cdn/4.0.5/monaco/min/vs/editor/editor.main.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

This isn't critical for me, but if many folks get this error then they won't be happy & possibly even be confused!

![image](https://user-images.githubusercontent.com/8594671/97747307-ff00c300-1aa8-11eb-9129-3b00a7355c4c.png)

**Repro:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Comment by orta** [comment]
Do you have custom network settings in Firefox? I get no errors on my computer

![Screen Shot 2020-10-30 at 4 56 38 PM](https://user-images.githubusercontent.com/49038/97756223-e99f8f00-1ad0-11eb-9d7a-9e7a23ea3e2f.png)

**Comment by VashJuan** [comment]
I have ghostery running, but otherwise am pretty Plain Jane in my settings. After failing repeatedly in Firefox, it did work on Chrome, and now a few hours later when I try it again from Firefox (no changes that I can think of!) it works.

Maybe just verify with someone who knows about Cross-Site issues to verify others won't have the issue?

![image](https://user-images.githubusercontent.com/8594671/97758589-6e33e280-1abc-11eb-91eb-ed2397f729dd.png)

**Comment by orta** [comment]
Thanks
