### ISSUE TITLE
Playground: `install-plugin` query not working

### ISSUE THREAD

**Issue by antfu** [microsoft/TypeScript-Website#1313]
`?install-plugin=xxxx` for playground does not seem to take effects. Neither on staging nor prod.

**Repro:**

https://www.staging-typescript.org/play?install-plugin=playground-collaborate
https://www.typescriptlang.org/play?install-plugin=playground-collaborate

**Expected behavior:**

Should work as the docs: https://github.com/microsoft/TypeScript-Website/tree/v2/packages/playground#link-syntax

**Actual behavior:**

No modal for installing. No console errors. Plugins not enabled.

**Comment by orta** [comment]
Great catch, I bet this is from the query being normalized by the compiler earlier in the boot up process, thanks!

**Comment by orta** [comment]
This is working, but it loses any query params that came with the link before a plugin can see it
