### ISSUE TITLE
incorrect type acquisition Sandbox & Playground

### ISSUE THREAD

**Issue by Akxe** [microsoft/TypeScript-Website#1316]
> You're welcome to make a fresh issue on this repo 👍🏻 or look into it yourself, the code is here: https://github.com/microsoft/TypeScript-website/blob/v2/packages/sandbox/src/typeAcquisition.ts

_Originally posted by @orta in https://github.com/microsoft/TypeScript-Website/issues/1283#issuecomment-721097480_

For [this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzhAZnAvnFUIjgcigA8ArAZ3wG4AoUSWROEAQzAyxz0NLIHoIwAUyjMY0CjWqoAFAG0AjABoATIoDMAXQCUAOjDAh06nCatpROAF4AfHAAGAQgAkCIugd2ti6lspA)
```ts
import { of } from 'rxjs';
import { map } from 'rxjs/operators';

of([1,2,3]).pipe(
  map(x => `!${x}!`),
);
```

The `rxjs/operators` will not work. I have looked into the code thanks to @orta and found some clues.

The function `convertToModuleReferenceID` seems to return invalid id `"undefined-rxjs/operators"`.
https://github.com/microsoft/TypeScript-Website/blob/d987ed24d5540019551b687e2f2aa557fdf9d38c/packages/sandbox/src/typeAcquisition.ts#L134-L144

PS: The same lines are just a few lines bellow too:
https://github.com/microsoft/TypeScript-Website/blob/d987ed24d5540019551b687e2f2aa557fdf9d38c/packages/sandbox/src/typeAcquisition.ts#L355-L358

I am not sure what the correct value for `rxjs/operators` should be, at least it's something! :)

**Comment by orta** [comment]
yeah, looks like the playground ATA only looks at scope packages for splitting and would need to look inside for modules in a module

**Comment by orta** [comment]
This is improved, but not 100% - rxjs now works out of the box, and so does resolving identifiers out of `rxjs/operators` 

![Screen Shot 2021-03-10 at 9 48 22 AM](https://user-images.githubusercontent.com/49038/110610133-d2129a00-8185-11eb-967c-463e8f4e9a1d.png)

But that `map` seems to be basically an any

**Comment by Akxe** [comment]
Thank you! I did think this issue was dead in water by now... I like that we do have type competition in the import statement. 

The type of `map` is `import map`, so yes, it is basically `any`. 



From my observations, the URL is wrongly interpreted as `https://www.unpkg.com/rxjs/operators.d.ts` while it should be `https://www.unpkg.com/rxjs/operators/index.d.ts`.

On one hand, I can understand why, but probably it should in case of error try also `/index.d.ts`... I have made an [issue at unpkg](https://github.com/mjackson/unpkg/issues/292), asking for `extensions` query param to prevent multiple roundtrips and also to be able to strip adding `index.d.ts`, `.d.ts` at end of every requested URL.

I have made a

**Comment by orta** [comment]
Oh, cool idea about having that feature upstream!

**Comment by Akxe** [comment]
@orta if you like it please comment on the issue there. Your word as a member of TS is much better than mine 🙂

**Comment by Akxe** [comment]
Hi @orta, here is the link to the issue https://github.com/mjackson/unpkg/issues/292.

-----

> This is improved, but not 100% - rxjs now works out of the box, and so does resolving identifiers out of `rxjs/operators`
> 
> ![Screen Shot 2021-03-10 at 9 48 22 AM](https://user-images.githubusercontent.com/49038/110610133-d2129a00-8185-11eb-967c-463e8f4e9a1d.png)
> 
> But that `map` seems to be basically an any

How did you manage to get anything from `rxjs/operators`? I tried today once again, but nothing changed. I thought that since RXJS 7.x changed the way it is imported, it might work :/

**Comment by orta** [comment]
RxJS changed their types: https://www.unpkg.com/rxjs@7.1.0/package.json

Now refers to a types file which doesn't exist: https://www.unpkg.com/rxjs@7.1.0/index.d.ts

**Comment by orta** [comment]
Looks like they just used a feature I didn't know existed. You're welcome to take a look at adding that to the ATA resolver, or add support for typesVersions in the package JSON parser for the playground

**Comment by Akxe** [comment]
> Looks like they just used a feature I didn't know existed. You're welcome to take a look at adding that to the ATA resolver, or add support for typesVersions in the package JSON parser for the playground

I will look into it during the weekend.

------

I have a question you might know the answer to. I want to have code like:

```ts
import { of } from 'rxjs';
import { map } from 'rxjs/operators';

of([1,2,3]).pipe(
  map(x => `!${x}!`),
);
```

But at the same time, I want to disable type acquisition. I only want types of rxjs to be known to this TS/VS Code instance. Also if `sandbox.getRunnableJS()` would be able to use the given imported library. I could easily see the rise of TS sandbox at doc pages of libraries.

The reason, I think that the type of acquisition should be disabled is to be able to build the code with only provided libraries. It could then be easily used in issues of the given package. Same as Typescript does.

**Comment by orta** [comment]
Check out the code for https://github.com/orta/octokit-playground where  I do this for octokit

**Comment by Akxe** [comment]
@orta tough luck... The best I could manage is 
![image](https://user-images.githubusercontent.com/2001798/121802197-8f0c0b00-cc3b-11eb-89fb-a67ee870659b.png)

I will leave it here, for now, might come back to it next week or so. Don't want to sink all time to it. https://github.com/Akxe/rxjs-playground

**Comment by orta** [comment]
I bet you're probably missing the package.json in the root for the dts map

**Comment by Akxe** [comment]
You are right, if I include everything, it results in the error: 
```
Could not find a declaration file for module 'rxjs'. 'file:///node_modules/rxjs/dist/cjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/rxjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'rxjs';`(7016)
```

**Comment by jcalz** [comment]
This is biting me.  The "You can do this" label makes me feel like I should be able to contribute, but I wouldn't really know how to begin.  Any pointers?

**Comment by Akxe** [comment]
I struggle a lot too, look at the files that are in the comments of this thread, it is a good start. After that I tried to step through the code when it tries to get the `.d.ts` bits... Sorry that I can't help more, but if I could I would have solved by by now :(

**Comment by orta** [comment]
The type acquisition code is one single file of ~350 lines of well commented code, (and one or two tests) - https://github.com/microsoft/TypeScript-Website/blob/v2/packages/sandbox/src/typeAcquisition.ts

While it's not perfect, it should be reasonable to study and figure out how it works to make the improvements you want to see

**Comment by Akxe** [comment]
I submitted https://github.com/mjackson/unpkg/pull/305 that would (with a small change in [typeAcquisition.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/sandbox/src/typeAcquisition.ts)) fix it all together without further hacks to guess if a path is a file or a folder.

-----

From:
https://github.com/microsoft/TypeScript-Website/blob/0376dbaa4f61648ad8d8004fdf13b392da87f079/packages/sandbox/src/typeAcquisition.ts#L23
to
``https://www.unpkg.com/${encodeURIComponent(actualName)}/${encodeURIComponent(actualPath)}?extension=ts&extension=d.ts``
