### ISSUE TITLE
emit() does not actually create js files

### ISSUE THREAD

**Issue by akutruff** [microsoft/TypeScript-Website#1328]
program.emit() does not actually create JavaScript files.  I ran into this in my own code and came across this skipped test.

https://github.com/microsoft/TypeScript-Website/blob/1c27887e2537918466b636d5500a98e6af75ed7b/packages/typescript-vfs/test/index.test.ts#L87

**Comment by orta** [comment]
Yeah, I need to look into what's going on there at some point.
