### ISSUE TITLE
Module: gatsby-remark-shiki-twoslash/dom not found

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript-Website#1339]
In document of https://github.com/microsoft/TypeScript-Website/tree/v2/packages/gatsby-remark-shiki-twoslash it says I need to setup like this:

```js
import React, { useEffect } from "react"
import { setupTwoslashHovers } from "gatsby-remark-shiki-twoslash/dom";

export default () => {
  // Add a the hovers
  useEffect(setupTwoslashHovers, [])

    // Normal JSX for your component
  return </>
}
```

But `/dom` doesn't exist.

**Comment by orta** [comment]
I think this is now on a different module, probably shiki-twoslash - I'll need to update the docs

**Comment by orta** [comment]
I've got all these references fixed 👍🏻
