### ISSUE TITLE
Module: gatsby-remark-shiki-twoslash should not stop the "gatsby develop" if there're type error

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript-Website#1340]
it should only fail the build, not the develop

**Comment by orta** [comment]
This is intentional for me, it throws - that's what I want. 

Though, I guess it probably could instead somehow show the code sample as not valid somehow.

**Comment by Jack-Works** [comment]
Throwing in the production build is expected. But throwing and exiting the node process in the development build is annoying

**Comment by orta** [comment]
Weird - it doesn't exit the node process on the ts website, just stops that page from rendering

**Comment by Jack-Works** [comment]
can you reproduce in a normal gatsby setup?

I made a patch to make it work https://github.com/Jack-Works/async-call-rpc/blob/master/site/patches/gatsby-remark-shiki-twoslash%2B0.7.0.patch
