### ISSUE TITLE
Module: gatsby-remark-shiki-twoslash: Can I use external types?

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript-Website#1341]
I tried this code

```ts twoslash
import { useState } from 'react'
const [a, b] = useState(0)
```

But it reports

```
  Error: Errors were thrown in the sample, but not included in an errors tag: 2307
  Expected:
  // @errors: 2307
    [2307] - Cannot find module 'react' or its corresponding type declarations.
  ## Code
  '''ts
  import { useState } from 'react'
  const [a, b] = useState(0)
  '''
```

**Comment by Jack-Works** [comment]
There is an undocumented option provided by `shiki-twoslash` call `useNodeModules`. If I set it to true in the debugger, it will work.

But it's not possible to set this option in gatsby-config.js in my setup. Here is the reason:

![image](https://user-images.githubusercontent.com/5390719/99161491-04f3d680-272e-11eb-9b27-7bc90cee4085.png)

`node_modules/gatsby-plugin-mdx/utils/get-source-plugins-as-remark-plugins.js` calls `gatsby-remark-shiki-twoslash` with 2 arguments.

![image](https://user-images.githubusercontent.com/5390719/99161533-3b315600-272e-11eb-831f-4b0ed3d7405c.png)

But `node_modules/gatsby-remark-shiki-twoslash/dist/gatsby-remark-shiki-twoslash.cjs.development.js` requires the 3rd argument as `settings` object passed to `shiki-twoslash` therefore the options can never be set.

**Comment by Jack-Works** [comment]
Here is a workaround:

Add this in your gatsby-config.js

```js
{
    // https://github.com/microsoft/TypeScript-Website/issues/1341
    const twoslash = require('gatsby-remark-shiki-twoslash')
    const old = twoslash.default
    twoslash.default = (...args) => old(...args, { useNodeModules: true })
}
```

**Comment by Jack-Works** [comment]
Then I found I can import react but not my own lib. I found that shiki-twoslash only add `@types` into the compile.

![](https://user-images.githubusercontent.com/5390719/99161779-7cc30080-2730-11eb-9f41-d60a8da70b33.png)

**Comment by orta** [comment]
I feel like I added proper support for this, will need to look at the code

**Comment by orta** [comment]
I definitely added proper support for this recently, though I wonder if it's documented well enough
