### ISSUE TITLE
Add UI for setting the lib option in playground

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript-Website#136]
You can set the `--lib` option in the playground by adding a URL parameter with the file you want to load - http://www.typescriptlang.org/play/index.html?lib=lib.esnext.d.ts, well, kind of. It doesn't load any referenced lib files, so you have to manually add those you need.

This doesn't seem to be documented anywhere. It would be great to be able to load lib files with a UI and have them properly load dependencies too.

**Comment by orta** [comment]
Yeah, agree - kinda blocked on https://github.com/orta/make-monaco-builds/issues/2 in order to have a set of them all per TS version

**Comment by orta** [comment]
This is now unblocked by https://github.com/orta/make-monaco-builds/pull/3

**Comment by orta** [comment]
This became feasible via `// @lib: dom, es2015` - I don't think we'll ever expose the lib options in the UI

**Comment by WORMSS** [comment]
Can I put a plus one in for this..

I kinda wanna target a lower version, but add the es2019 lib so I can see what the polyfill output of certain lines of code would be.

**Comment by KristjanTammekivi** [comment]
> This became feasible via `// @lib: dom, es2015` - I don't think we'll ever expose the lib options in the UI

Currently putting a space before es2015 results in only dom being used, but `// @lib: dom,es2015` works
