### ISSUE TITLE
Docs: await Completions on Promises truncated paragraph in typescript 3.6 release noted

### ISSUE THREAD

**Issue by xanatos** [microsoft/TypeScript-Website#1362]
**Page URL:** https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html#await-completions-on-promises

**Issue:** The paragraph is truncated/incomplete. It is

> In TypeScript 3.6, completions on an

and then nothing.

**Comment by orta** [comment]
Thanks, I've removed it
