### ISSUE TITLE
Docs: undocumented "this is T" type guard syntax

### ISSUE THREAD

**Issue by HoldYourWaffle** [microsoft/TypeScript-Website#1363]
**Page URL:** https://www.typescriptlang.org/docs/handbook/advanced-types.html

**Issue:** I just discovered that I can use the following syntax to narrow down "the current interface" with a type guard:
```ts
interface Request {
    user?: User;
    isAuthenticated(): this is AuthenticatedRequest;
    isUnauthenticated(): this is UnauthenticatedRequest;
}

interface AuthenticatedRequest extends Request {
    user: User;
}

interface UnauthenticatedRequest extends Request {
    user?: undefined;
}
```
As far as I can see this syntax isn't documented anywhere.

**Recommended Fix:** Add documentation on this syntax.

**Browser:** Proud Firefox user, although I don't think that's relevant here...

**Comment by orta** [comment]
linking the original notes: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-8.html#this-based-type-guards

Will try get this in the v2 handbook

**Comment by orta** [comment]
Will be fixed by https://github.com/microsoft/TypeScript-Website/pull/1630
