### ISSUE TITLE
Docs: Missing 4.1 Release Notes, Homepage link broken

### ISSUE THREAD

**Issue by laughinghan** [microsoft/TypeScript-Website#1364]
**Page URL:** https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html

**Issue:** 4.1 was released [4 days ago](https://github.com/microsoft/TypeScript/releases), and the [homepage](https://www.typescriptlang.org) has a prominent broken link to the 4.1 release notes:

<p align="center"><img src="https://user-images.githubusercontent.com/225809/99999457-0a2bd380-2d75-11eb-812c-d408c9b11005.png" width="423"></p>

**Recommended Fix:** Either add 4.1 release notes, or at least change the homepage link to point to [the 4.1 release announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/)

**Comment by orta** [comment]
Good catch, the curse of autmation - will ship 4.1 now
