### ISSUE TITLE
Docs: Why say you likely want CommonJS?

### ISSUE THREAD

**Issue by davidsk** [microsoft/TypeScript-Website#1366]
- https://www.typescriptlang.org/tsconfig#module
- https://github.com/microsoft/TypeScript-Website/blob/695541b6912f2a493672178c6bdd249f34cf3fa1/packages/tsconfig-reference/copy/en/options/module.md

The docs say that ```You very likely want "CommonJS"``` but without any explanation.  This was mentioned in #594 also.

It would be very helpful to know _why_ CommonJS is assumed to be the preferred module format over the other options.

**Comment by orta** [comment]
Cool, good feedback. I've changed it to "You very likely want "CommonJS" in node projects" which is generally the dominant way people use TypeScript. 👍🏻

**Comment by Sti2nd** [comment]
Can I suggest thinking through this sentence again one year later? 😅 @orta (EDIT: linked a new issue, perhaps better to discuss there)

Now that all active Node versions support the EcmaScript module system it makes sense to encourage to use the standard; which ended up being ESM.

Some information on the state of EcmaScript module (ESM) support in the Node world: Node 10 didn't support ESM but reached end of life earlier this year, Node 12 supports ESM behind a flag, and from Node 14 ESM is considered a stable feature according to the docs.
