### ISSUE TITLE
Config for target based on Monaco TS details not tsconfig schema showing JSON

### ISSUE THREAD

**Issue by peterblazejewicz** [microsoft/TypeScript-Website#139]
It seems the config options for playground configuration are based on Monaco editor TS support details, not on actual TS compiler options and config schema:
https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/tsconfig.json#L252
This is minor, but can be intriguing for people playing with the options in the playground.
Thanks!

**Comment by orta** [comment]
This could change now that there's a global `window.ts` available to the runtime, potentially the compiler options can be generated from that (which means it isn't hardcoded to every version)

We do this for the TSConfig reference: https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/scripts/generateJSON.ts
