### ISSUE TITLE
Playground: The JSX compiler option dropdown should show options for the `react-jsx` and `react-jsxdev` transforms

### ISSUE THREAD

**Issue by weswigham** [microsoft/TypeScript-Website#1394]
The JSX compiler option dropdown should show options for the `react-jsx` and `react-jsxdev` transforms for TS 4.1+.

![image](https://user-images.githubusercontent.com/2932786/101087373-f9deda00-3566-11eb-85e0-742a14ede938.png)

**Comment by orta** [comment]
Dang it @kingwl, I just got around to figuring it out 🍡  - thanks!

**Comment by orta** [comment]
I'll get your PR automatically pulled into the playground builds, should appear in the upcoming 4.1 patch

**Comment by hahmadia** [comment]
@orta

Can this be closed? Thanks

**Comment by Kingwl** [comment]
I think so.

**Comment by orta** [comment]
It can, I recently switched from Monaco's version of the enum to TypeScript's
