### ISSUE TITLE
Idea: hard to see the code in Normal Mode

### ISSUE THREAD

**Issue by seunghee114** [microsoft/TypeScript-Website#1399]
**Improvement Idea:**
: The color of the comments in normal mode are too dark. It doesn't go well with other colors.
![image](https://user-images.githubusercontent.com/43427305/101246245-6ae3e480-3755-11eb-93a2-af196b162ae9.png)

**Why:**
I wish the color of the comments was brighter. Then it will look better.

**Alternative ideas:**

**Comment by R99bbit** [comment]
I think this issue should be worked with quickly 👍👍

**Comment by Begachu** [comment]
I think so!
I think it would be nice to increase the brightness and saturation

**Comment by orta** [comment]
This colour works with the accessibility baselines that we want for the website, I'm afraid changing them to be closer to the background would break our contrast ratios. We don't plan on changing it.
