### ISSUE TITLE
Docs: The documentations contain a dead link.

### ISSUE THREAD

**Issue by seunghee114** [microsoft/TypeScript-Website#1400]
**Page URL:** 
[Something Went Wrong.md](https://github.com/microsoft/TypeScript-Website/blob/v2/docs/Something%20Went%20Wrong.md) -> [web.config](https://github.com/microsoft/TypeScript-website/blob/92a9585d033e7cf802fae14v22baa73250fd610266/packages/typescriptlang-org/static/Web.config) 
[tsconfig.json.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/pt/project-config/tsconfig.json.md) -> [Referencias TSConfig](https://github.com/microsoft/TypeScript-Website/blob/v2/pt/tsconfig)
[Module Resolution.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/pt/reference/Module%20Resolution.md) -> [ambient module declaration](https://github.com/microsoft/TypeScript-Website/blob/v2/docs/handbook/modules.html#ambient-modules)
[Modules.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/pt/reference/Modules.md) -> [SystemJS](https://github.com/systemjs/systemjs/blob/master/docs/overview.md#plugin-syntax) / [Namespaces e Modulos](https://github.com/microsoft/TypeScript-Website/blob/v2/docs/handbook/namespaces-and-modules.html) 
[JSX.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/id/reference/JSX.md) -> [tsconfig.json](https://github.com/microsoft/TypeScript-Website/blob/v2/docs/handbook/tsconfig-json.html)
[Publishing.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/declaration-files/Publishing.md) -> [--declaration](https://github.com/microsoft/TypeScript-Website/blob/v2/tsconfig#declaration)
[Library Structures.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/declaration-files/Library%20Structures.md) -> [Templates](https://github.com/microsoft/TypeScript-Website/blob/v2/docs/handbook/declaration-files/templates.html)
[global-plugin.d.ts.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/declaration-files/templates/global-plugin.d.ts.md) -> [module.d.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/docs/handbook/declaration-files/templates/module-d-ts.html) / [module-class.d.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/docs/handbook/declaration-files/templates/module-class-d-ts.html) /  [module-function.d.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/docs/handbook/declaration-files/templates/module-function-d-ts.html)
[Overview.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/release-notes/Overview.md) -> [Isomorphic](https://www.buydomains.com/lander/isomorphic.net?domain=isomorphic.net&version=aprtest&utm_campaign=tdfs-AprTest&traffic_id=AprTest&traffic_type=tdfs) / [SystemJS](https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md)
[TypeScript 1.8.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/release-notes/TypeScript%201.8.md) -> [latest version of react.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/react)
[TypeScript 2.0.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/release-notes/TypeScript%202.0.md) -> [SystemJS documentation](https://github.com/systemjs/systemjs/blob/master/docs/overview.md#map-config) / [SystemJS](https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md)
[TypeScript 2.1.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/release-notes/TypeScript%202.1.md) -> [Custom Elements](https://w3c.github.io/webcomponents/spec/custom/#htmlelement-constructor)
[TypeScript 3.7.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/release-notes/TypeScript%203.7.md) -> [Playground](https://github.com/microsoft/TypeScript-Website/blob/v2/play/#example/optional-chaining)
[Integrating with Build Tools.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/project-config/Integrating%20with%20Build%20Tools.md) -> [Setting Compiler Options in MSBuild projects](https://github.com/microsoft/TypeScript-Website/blob/v2/docs/handbook/compiler-options-in-msbuild.html)
[tsconfig.json.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/project-config/tsconfig.json.md) -> [Compiler Options](https://github.com/microsoft/TypeScript-Website/blob/v2/tsconfig) / [TSConfig Reference](https://github.com/microsoft/TypeScript-Website/blob/v2/tsconfig)
[Everyday Types.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/handbook-v2/Everyday%20Types.md) -> [noImplicitAny](https://github.com/microsoft/TypeScript-Website/blob/v2/tsconfig#noImplicitAny) / [_may_ appear in error messages](https://github.com/microsoft/TypeScript-Website/blob/v2/play?#code/PTAEGEHsFsAcEsA2BTATqNrLusgzngIYDm+oA7koqIYuYQJ56gCueyoAUCKAC4AWHAHaFcoSADMaQ0PCG80EwgGNkALk6c5C1EtWgAsqOi1QAb06groEbjWg8vVHOKcAvpokshy3vEgyyMr8kEbQJogAFND2YREAlOaW1soBeJAoAHSIkMTRmbbI8e6aPMiZxJmgACqCGKhY6ABGyDnkFFQ0dIzMbBwCwqIccabcYLyQoKjIEmh8kwN8DLAc5PzwwbLMyAAeK77IACYaQSEjUWZWhfYAjABMAMwALA+gbsVjoADqgjKESytQPxCHghAByXigYgBfr8LAsYj8aQMUASbDQcRSExCeCwFiIQh+AKfAYyBiQFgOPyIaikSGLQo0Zj-aazaY+dSaXjLDgAGXgAC9CKhDqAALxJaw2Ib2RzOISuDycLw+ImBYKQflCkWRRD2LXCw6JCxS1JCdJZHJ5RAFIbFJU8ADKC3WzEcnVZaGYE1ABpFnFOmsFhsil2uoHuzwArO9SmAAEIsSFrZB-GgAjjA5gtVN8VCEc1o1C4Q4AGlR2AwO1EsBQoAAbvB-gJ4HhPgB5aDwem-Ph1TCV3AEEirTp4ELtRbTPD4vwKjOfAuioSQHuDXBcnmgACC+eCONFEs73YAPGGZVT5cRyyhiHh7AAON7lsG3vBggB8XGV3l8-nVISOgghxoLq9i7io-AHsayRWGaFrlFauq2rg9qaIGQHwCBqChtKdgRo8TxRjeyB3o+7xAA) / [in declaration merging, but interfaces can](https://github.com/microsoft/TypeScript-Website/blob/v2/play?#code/PTAEEEDtQS0gXApgJwGYEMDGjSfdAIx2UQFoB7AB0UkQBMAoEUfO0Wgd1ADd0AbAK6IAzizp16ALgYM4SNFhwBZdAFtV-UAG8GoPaADmNAcMmhh8ZHAMMAvjLkoM2UCvWad+0ARL0A-GYWVpA29gyY5JAWLJAwGnxmbvGgALzauvpGkCZmAEQAjABMAMwALLkANBl6zABi6DB8okR4Jjg+iPSgABboovDk3jjo5pbW1d6+dGb5djLwAJ7UoABKiJTwjThpnpnGpqPBoTLMAJrkArj4kOTwYmycPOhW6AR8IrDQ8N04wmo4HHQCwYi2Waw2W1S6S8HX8gTGITsQA) / [declare the shapes of object, not re-name primitives](https://github.com/microsoft/TypeScript-Website/blob/v2/play?#code/PTAEAkFMCdIcgM6gC4HcD2pIA8CGBbABwBtIl0AzUAKBFAFcEBLAOwHMUBPQs0XFgCahWyGBVwBjMrTDJMAshOhMARpD4tQ6FQCtIE5DWoixk9QEEWAeV37kARlABvaqDegAbrmL1IALlAEZGV2agBfampkbgtrWwMAJlAAXmdXdy8ff0Dg1jZwyLoAVWZ2Lh5QVHUJflAlSFxROsY5fFAWAmk6CnRoLGwmILzQQmV8JmQmDzI-SOiKgGV+CaYAL0gBBdyy1KCQ-Pn1AFFplgA5enw1PtSWS+vCsAAVAAtB4QQWOEMKBuYVUiVCYvYQsUTQcRSBDGMGmKSgAAa-VEgiQe2GLgKQA) / [_always_ appear in their original form](https://github.com/microsoft/TypeScript-Website/blob/v2/play?#code/PTAEGEHsFsAcEsA2BTATqNrLusgzngIYDm+oA7koqIYuYQJ56gCueyoAUCKAC4AWHAHaFcoSADMaQ0PCG80EwgGNkALk6c5C1EtWgAsqOi1QAb06groEbjWg8vVHOKcAvpokshy3vEgyyMr8kEbQJogAFND2YREAlOaW1soBeJAoAHSIkMTRmbbI8e6aPMiZxJmgACqCGKhY6ABGyDnkFFQ0dIzMbBwCwqIccabcYLyQoKjIEmh8kwN8DLAc5PzwwbLMyAAeK77IACYaQSEjUWY2Q-YAjABMAMwALA+gbsVjNXW8yxySoAADaAA0CCaZbPh1XYqXgOIY0ZgmcK0AA0nyaLFhhGY8F4AHJmEJILCWsgZId4NNfIgGFdcIcUTVfgBlZTOWC8T7kAJ42G4eT+GS42QyRaYbCgXAEEguTzeXyCjDBSAAQSE8Ai0Xsl0K9kcziExDeiQs1lAqSE6SyOTy0AKQ2KHk4p1V6s1OuuoHuzwArMagA)
[Module Resolution.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/reference/Module%20Resolution.md) -> [Modules](https://github.com/microsoft/TypeScript-Website/blob/v2/docs/handbook/modules.html)  /[ambient module declaration](https://github.com/microsoft/TypeScript-Website/blob/v2/docs/handbook/modules.html#ambient-modules) / [SystemJS documentation](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#paths)
[Modules.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/reference/Modules.md) -> [SystemJS](https://github.com/systemjs/systemjs/blob/master/docs/overview.md#plugin-syntax) / [Namespaces and Modules](https://github.com/microsoft/TypeScript-Website/blob/v2/docs/handbook/namespaces-and-modules.html)
[JSX.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/reference/JSX.md) -> [jsx in your tsconfig.json](https://github.com/microsoft/TypeScript-Website/blob/v2/tsconfig#jsx) / [jsxFactory](https://github.com/microsoft/TypeScript-Website/blob/v2/tsconfig/#jsxFactory) / [jsxFragmentFactory](https://github.com/microsoft/TypeScript-Website/blob/v2/tsconfig/#jsxFragmentFactory) / [jsxImportSource](https://github.com/microsoft/TypeScript-Website/blob/v2/tsconfig/#jsxImportSource)
[CONTRIBUTING.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/create-typescript-playground-plugin/template/CONTRIBUTING.md) -> [interface PlaygroundPlugin in ./src/vendor/playground.d.ts](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/create-typescript-playground-plugin/template/src/vendor/playground.d.ts)

**Issue:** : The documentation contains a dead link(404).

**Recommended Fix:** : Deadlink should be corrected to the correct link.

**Browser:** : Chrome

**Comment by orta** [comment]
I'm not really sure what to do with this issue, can you point out the actual dead links?

**Comment by seunghee114** [comment]
I modified the issue. sorry to confuse you. 😥 @orta
