### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by jamaicacat** [microsoft/TypeScript-Website#1403]
**Page URL:** https://www.typescriptlang.org/docs/handbook/interfaces.html#interfaces-extending-classes
### "Interfaces Extending Classes"
Text in last and pre-last paragraph

**Issue:** Why "member", but not "property"?
"In the above example, SelectableControl contains all of the members of Control, including the private state property. Since state is a private **member** ..."
I was struggling for a white to understand who these "members" are. I think, it would be more obvious if you replace "member" with "property".
Did I misunderstood anything? Waiting for your feedback!

**Recommended Fix:** replace "member" with "property" ?

**Comment by orta** [comment]
Thanks for the question. I agree it gets a bit confusing.

These are called members in the JavaScript spec, so we want to be using the same language as the official sources. You can see how MDN does the same in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

**Comment by jamaicacat** [comment]
As for me, 'members' there mean something like 'some part of the class' (something very general), not it's specific part. In result, I lost the main idea about interfaces being confused with 'members'. 😕 
I would recommend to add link to dictionary (where anyone can read that 'members are class/object method or property) or simply add onhover tip. What do you think?

And huge thanks for your answer!

**Comment by orta** [comment]
At some point I'd like to add a glossary to the docs but for now I think this is OK

**Comment by orta** [comment]
Going to close this, the glossary is a WIP #1523  but it'll take while to get there
