### ISSUE TITLE
## Website Navigation > 'New In 3.7'

### ISSUE THREAD

**Issue by peterblazejewicz** [microsoft/TypeScript-Website#141]
## Website Navigation 
Just 2c
👍 

![2019-12-02 14-10-48 2019-12-02 14_14_45](https://user-images.githubusercontent.com/49038/69988721-315c1600-1510-11ea-9de6-1051b18800b8.gif)

The current navigation cleanly splits exampels into JS/TS category, the '3.7' seems to be directly related to the 'TypeScript' category (though it is not). Can you consider naming this in a fashion like 'New in 3.7'? (this could refer to TS release notes > 'new in TS 3.7'/'New in 3.7'):
https://github.com/microsoft/TypeScript/wiki/What%27s-new-in-TypeScript

![image](https://user-images.githubusercontent.com/14539/70000590-a143be00-155b-11ea-8876-f1b72d09267e.png)

**Comment by orta** [comment]
Great point, yeah, I agree

**Comment by peterblazejewicz** [comment]
Closing, that was just to provide you a feedback, thanks!
