### ISSUE TITLE
Playground: default browser history behavior is still not sane

### ISSUE THREAD

**Issue by thw0rted** [microsoft/TypeScript-Website#1412]
There have been a few issues (#8, #190, #301) about how Playground pollutes your browser history.  If I read them correctly, the consensus is that because there's a setting to disable poking the history every time you type, the matter is resolved.  I don't think the current default behavior is reasonable.  I spent 10 minutes working up a short code example to link in a StackOverflow answer, and it added between 10-40 history entries per minute.

It should be pretty simple to limit the rate of changes while still leaving the "automatic save" option on by default.  Debounce the change detection on a pretty generous timeout -- I would say 10-30 seconds wouldn't be unreasonable -- and hook the document `unload` (or `beforeunload`) event to make sure unsaved changes aren't lost.  If you want to make sure that the user gets the exact current contents of the editor when they go to select the URL and copy it, you can hook the `blur` event on the editor and commit pending changes immediately.

**Comment by orta** [comment]
I was thinking about this when I built [this](https://whatsstoppingyou.dev/#map=3,0,0,0,3,3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,1,0,1,3,3,0,3,3,3,1,1,1,1,3,2,0,2,3,1,1,0,2,3,2,3,1,3,0,2,0,2,3,0,2,0,0,1,0,3,1,2,3,1,1,3,2,3,4,2,3,3,0,1,2,2,2,0,3,0,2,2,3,0,2,0,3,1,3,2,1,0,3,3,3,0,0,3,1,0,0,1,0,0,1,3,2,2,3,2,0,1,1,0,1,0,2,2,0,1,2,0,2,0,0,3,0,2,2,4,2,4,3,0,3,2,2,1,3,3,1,4,3,0,3,1,4,2,0,2,3,4,1,2,3,2,0,0,2,2,2,3,0,3,2,3,0,2,3,1,2,2,3,0,2,1,0,1,0,0,2,2,2,1,3,0,0,3,2,1,1,2,0,3,0,0,0,0,1,1,3,0,3,3,3,2,2,1,2,3,2,3,2,2,1,0,0,3,3,2,1,3,1,1,0,2,3,3,2,0,3,3,0,1,3,0,2,2,3,0,0,1,1,3,0,0,3,0,3,0,0,1,3,3,3,2,2,0,0,3,2,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,) a few months back and came up with a way which I think should do it without writing to the history most of the time, just haven't given it  shot. Basically if the change is just the hash, then set the location directly and only use history when a compiler flag has changed, should probably work. 

I've been open to someone making a PR to improve it, and have tried myself a few times - but I nor anyone else has came up with an answer which isn't un-ergonomic for me and the trade-offs we have today are sucky but reasonable IMO.

**Comment by orta** [comment]
Tried with https://github.com/microsoft/TypeScript-Website/commit/69d29bd841977e5818822affb04f29530690d061 and it didnt make a difference

**Comment by orta** [comment]
I gave this another shot a few weeks back, and I'd say it's good enough - at least I've not been annoyed by the changes 👍🏻
