### ISSUE TITLE
Docs: document of `this` is wrong? or I'm wrong about this?

### ISSUE THREAD

**Issue by sunderls** [microsoft/TypeScript-Website#1413]
**Page URL:** https://www.typescriptlang.org/docs/handbook/functions.html

**Issue:** 
quote

>We can fix this by making sure the function is bound to the correct this before we return the function to be used later. This way, regardless of how it’s later used, it will still be able to see the original deck object.

<img width="807" alt="Screen Shot 2020-12-11 at 21 24 33" src="https://user-images.githubusercontent.com/2394070/101903245-54c3a180-3bf7-11eb-94f9-7e38bbda4800.png">

Actually `this` for the arrow function is bound to the anonymous function outside, not to deck object, so it should still be `any`?

<img width="838" alt="Screen Shot 2020-12-11 at 21 15 38" src="https://user-images.githubusercontent.com/2394070/101902548-2f826380-3bf6-11eb-91a8-67e2ca9c14ac.png">

Currently TypeScript tells that type of `this` is fixed to deck, which seems not right to me. 

<img width="846" alt="Screen Shot 2020-12-11 at 21 17 58" src="https://user-images.githubusercontent.com/2394070/101902749-7ff9c100-3bf6-11eb-92e2-a30f32d183fe.png">

because `this` depends on how `createCardPicker` is used, like code below, `this` is now bound to deck2.

<img width="608" alt="Screen Shot 2020-12-11 at 21 22 21" src="https://user-images.githubusercontent.com/2394070/101903087-0f06d900-3bf7-11eb-9b60-ead46f2a877f.png">

**Recommended Fix:**

Not sure, maybe there is a problem about TS inferring `this`?

**Browser:**  Chrome

**Comment by orta** [comment]
If you run the code sample in the Playground with a console log on `this`, it logs the `deck` - which is what TypeScript says it is. It might be worth taking a second look to check yourself.

**Comment by sunderls** [comment]
Yeah, the sample code is right about `deck`,

I mean it should be `any` though ? 🤔 

## sample code  => deck

![スクリーンショット 2020-12-18 10 18 47](https://user-images.githubusercontent.com/2394070/102562461-74d4f280-411a-11eb-95c6-9277c175a659.jpg)


## another case => not deck
![スクリーンショット 2020-12-18 10 17 17](https://user-images.githubusercontent.com/2394070/102562365-422afa00-411a-11eb-852d-629eaed08668.jpg)



which means, it should still be `any`? 

maybe this is intentional from typescript, if that's the case I think maybe we better clarify it  in the document above. because `this` is not sure to be right bound, opposite to the document

> We can fix this by making sure the function is bound to the correct this before we return the function to be used later. This way, regardless of how it’s later used, it will still be able to see the original deck object.

**Comment by sunderls** [comment]
https://www.typescriptlang.org/docs/handbook/functions.html#this-parameters
oh the next sections explains it well though. I'll close it
