### ISSUE TITLE
Support formatter settings in the playground

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#142]
The playground used to use 2-4 spaces per tab, but now inserts actual tab characters which is terrible.

**Comment by orta** [comment]
I wonder if this is the auto formatting which is now applied - I assume I can configure TypeScript's formatter form the API somehow to do this

**Comment by rauschma** [comment]
For me, the Playground always indents 4 spaces, which messes up source code indented with 2 spaces. It’d be nice if indentation were a setting (with auto-detection being a welcome bonus).

**Comment by MicahZoltu** [comment]
Just used the new playground, now it appears to always insert 2 spaces when indenting.  I *wish* it inserted tabs.

**Comment by MicahZoltu** [comment]
It appears that indentation style is auto-detected on page load, but then refuses to change if the style changes.  This means that whatever contents are visible on the page when you first load it is what decides the indentation style.  If the page contains no indentation on load then it will default to 4-space indentation.

The immediate problem is that the default page contents are:
```typescript
// Welcome to the TypeScript Playground, this is a website
  // which gives you a chance to write, share and learn TypeScript.
  
  // You could think of it in three ways:
  //
  //  - A place to learn TypeScript in a place where nothing can break
  //  - A place to experiment with TypeScript syntax, and share the URLs with others
  //  - A sandbox to experiment with different compiler features of TypeScript
  
  const anExampleVariable = "Hello World"
  console.log(anExampleVariable)
  
  // To learn more about the language, click above in "Examples" or "What's New".
  // Otherwise, get started by removing these comments and the world is your playground.
```
Which (erroneously I believe) contain 2 spaces at the start of every line but the first.  This means Monaco detects the indentation style to be 2-spaces and even if you paste in text that doesn't use 2-space indent you are now stuck with it.

**Comment by MicahZoltu** [comment]
FWIW, I went to try to submit a PR to add indentation style as a configuration option, but was unable to figure out in 5 minutes of looking where `monaco.editor.create(element, config)` is called, which I *think* is where the indentation style would need to be set.

**Comment by orta** [comment]
Good catch on the indentation! 

This should only happen the first time you open the playground, because after that you'll always have the last code in localstorage which could have the indentation you want

I'm open to this being configurable - I had wondered about the Options sidebar basically having a sub-nav with `Plugins | Formatting | Behavior` which could let you be real specific about the setup

**Comment by MicahZoltu** [comment]
A section in "Config" (top nav) for "Editor" was my initial thoughts on where the best place for an option would be.  As a user, it is unclear to me why there are two configuration sections (Config and Options) and I often hide the right side-bar, so it is easy to forget that one even exists.

**Comment by orta** [comment]
Aye, well - one is for the typescript config which you might change often and the other is playground options which you should rarely need and likely only set once. Forgetting about the options is fine.

**Comment by orta** [comment]
It's now called 'TS Config' in the nav, I think that's better.

**Comment by orta** [comment]
And I separated "Plugins" from "Settings" too last weekend, now settings lives on the same top line as TS Confg / Examples / What's new - which fits better as it's a conceptual edit of the tool - not a part of the tool itself.

This does free up some visual space for formatting settings

![image](https://user-images.githubusercontent.com/49038/79495829-30291280-7ff3-11ea-9699-b5d79f23cad2.png)
