### ISSUE TITLE
Docs: const assertions

### ISSUE THREAD

**Issue by pstepniewskiconfigit** [microsoft/TypeScript-Website#1428]
**Page URL:** 
https://www.typescriptlang.org/docs

**Issue:** 
Missing information about `const assertions`

**Recommended Fix:** 
Only place I can find info about this feature is [this release note](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions). Const assertions are very useful feature and it deserves to be better documented.

**Browser:** 
n/a

**Comment by orta** [comment]
This is covered in the v2 handbook 👍🏻
