### ISSUE TITLE
Docs: Some content not visible in Utility Types -> Intrinsic String Manipulation Types

### ISSUE THREAD

**Issue by bsivanov** [microsoft/TypeScript-Website#1429]
**Page URL:** https://www.typescriptlang.org/docs/handbook/utility-types.html#intrinsic-string-manipulation-types

**Issue:** The content of the last section is trimmed.

**Recommended Fix:** Not sure, probably something to do with [this commit](https://github.com/microsoft/TypeScript-Website/commit/4ffd2bbd37b5fa3bd74a57bb96c374e9f0f900ce#diff-49db1bc6726d5385406141129898150ae14cb79f893564dd914422f702bc2eb3R146). 

**Browser:** Chrome on Windows, latest (Version 87.0.4280.88 (Official Build) (64-bit)).

**Comment by orta** [comment]
The suspense is over, https://github.com/microsoft/TypeScript-Website/commit/7211c5cc806749c340ef2bd891b81a8606d49a00 fixes this
