### ISSUE TITLE
Broken link for React Starter Kits on docs homepage

### ISSUE THREAD

**Issue by shumailxyz** [microsoft/TypeScript-Website#143]
Clicking on "Starter Kits" under "React Projects" section on docs homepage, leads to a `404` error.

Relevant code line: 

https://github.com/microsoft/TypeScript-Website/blob/26f2723da172df6acc7c3aa4eaec5a77f75c648f/src/_docs/home.html#L184

**Comment by orta** [comment]
interesting, guess they much have deleted that page

**Comment by shumailxyz** [comment]
Yes, I tried to find new link but couldn't find anything.
