### ISSUE TITLE
Doc for `utility-types.html#intrinsic-string-manipulation-types` ends abruptly with incomplete sentence

### ISSUE THREAD

**Issue by SimplGy** [microsoft/TypeScript-Website#1441]
Seems to be a commit error or accident. See the bottom of this page:

https://www.typescriptlang.org/docs/handbook/utility-types.html#intrinsic-string-manipulation-types

**Comment by codyaverett** [comment]
In the meantime here is some information on the typescript devblog
https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#template-literal-types

There are also some string literal type manipulation examples in the typescript 4.1 playground
https://www.typescriptlang.org/play?ts=4.1.0-dev.20201028&q=89#example/string-manipulation-with-template-literals

**Comment by orta** [comment]
Thanks for issue. 

The suspense is over, https://github.com/microsoft/TypeScript-Website/commit/7211c5cc806749c340ef2bd891b81a8606d49a00
