### ISSUE TITLE
Playground: Change 'Report GitHub issue on Typescript' to 'Report Typescript issue on GitHub'.

### ISSUE THREAD

**Issue by RReactJSX** [microsoft/TypeScript-Website#1444]
![Capture+_2020-12-24-12-52-58.png](https://user-images.githubusercontent.com/52389664/103106118-b0266400-45e7-11eb-9c7d-e4df0c6a453f.png)

**Comment by orta** [comment]
I'm not too sure I agree, can you explain why?

**Comment by RReactJSX** [comment]
Using _'Report GitHub issue on TypeScript'_ sounds like you are referring to TypeScript as a service and GitHub as something that Microsoft is providing. 

_'If you are reporting a TypeScript issue, then please visit GitHub.'_ is the same as saying _'Report TypeScript issue on GitHub.'_

If you are trying to report a GitHub issue then the current phrase used makes sense but since you are trying to report a TypeScript issue then the phrase I introduced makes much more sense to use.
