### ISSUE TITLE
Docs: "Iterators and Generators" in "Handbook References" contains no content for generator.

### ISSUE THREAD

**Issue by coolgod** [microsoft/TypeScript-Website#1462]
**Page URL:** https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html

**Issue:** The page title mentioned "Generator" but the content does not contain generator.

**Recommended Fix:** TBD

**Browser:** Chrome

![image](https://user-images.githubusercontent.com/6824327/103606479-5cf7bf80-4ecb-11eb-9c25-2c16e247b88a.png)

**Comment by simonjduff** [comment]
There's a [What's New for 3.6](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html) document, which contains some detail, but a formal API specification for generators would be very useful, especially regarding the generic type parameters.
