### ISSUE TITLE
Docs: Confusions about contextual typing

### ISSUE THREAD

**Issue by icyfish** [microsoft/TypeScript-Website#1463]
**Page URL:**  https://www.typescriptlang.org/docs/handbook/type-inference.html#contextual-typing

**Issue:**  

This is the example to illustrate contextual typing in docs. 
However, I don't get desired result in TS playground with this version of code.

```ts
window.onmousedown = function (mouseEvent) { // Parameter 'mouseEvent' implicitly has an 'any' type.(7006)
  console.log(mouseEvent.button);  
  console.log(mouseEvent.kangaroo);  
};
```

When I change the code above to version below, I get desired result like doc's. 

```ts
window.addEventListener('mousedown', function(mouseEvent) {
	console.log(mouseEvent.button); //<- OK
  console.log(mouseEvent.kangaroo); //<- Error!
})
```

I am confused about this. Can someone gives an explanation? 
Thanks so much!

**Comment by orta** [comment]
Interesting, this changed somewhere between 3.5 and 3.6:

[works in 3.5.1](https://www.typescriptlang.org/play?ts=3.5.1#code/O4SwdgJg9sB0CGEIFEBuBTMAXAMiAzlpugE4AUA5ALZQCu+60wYFANAAQBmtYAxliChgyNeujSYsASnYBvAFABIXkPxQANuljqoAcxF0GE7LABGtLFiFSA3OwD09gDwBadgHkA0vPbsVYNU1tPQMxYyxYAGt4MF14EigoWwdnN2QSBJIAQnkAXyl5eVBIGFghUQYmMHYAXnYyeBkagD45JX9ArR19eDMLKzBkx1cPb18OjS6Q+E0SCOjY+MSh1PZ0zJzcoA) but doesn't in [3.6.3](https://www.typescriptlang.org/play?ts=3.6.3#code/O4SwdgJg9sB0CGEIFEBuBTMAXAMiAzlpugE4AUA5ALZQCu+60wYFANAAQBmtYAxliChgyNeujSYsASnYBvAFABIXkPxQANuljqoAcxF0GE7LABGtLFiFSA3OwD09gDwBadgHkA0vPbsVYNU1tPQMxYyxYAGt4MF14EigoWwdnN2QSBJIAQnkAXyl5eVBIGFghUQYmMHYAXnYyeBkagD45JX9ArR19eDMLKzBkx1cPb18OjS6Q+E0SCOjY+MSh1PZ0zJzcoA)

Perhaps that's a side-effect of [global function merging?](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html#ambient-classes-and-functions-can-merge)  - the definition went from:

```
// 3.5.1
(property) GlobalEventHandlers.onmousedown: ((this: GlobalEventHandlers, ev: MouseEvent) => any) | null

// 3.6.3
(property) onmousedown: (((this: GlobalEventHandlers, ev: MouseEvent) => any) & ((this: Window, ev: MouseEvent) => any)) | null
```

**Comment by orta** [comment]
I think https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/972 fixes this
