### ISSUE TITLE
Docs: bug with right menu "On this page"

### ISSUE THREAD

**Issue by KostyaTretyak** [microsoft/TypeScript-Website#1468]
**Page URL:** https://www.typescriptlang.org/docs/handbook/decorators.html

**Issue:**

1. After loaded this page, in console I see:
  > GET https://www.typescriptlang.org/page-data/docs/home/page-data.json net::ERR_ABORTED 404 (Not Found) prefetch.js:37
2. Then, after click any item from right menu "On this page", I see:
> 
![image](https://user-images.githubusercontent.com/2286306/103684690-a95b0200-4f94-11eb-84b0-ddbd4d856202.png)

**Browser:**

Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by KostyaTretyak** [comment]
Fixed in https://github.com/microsoft/TypeScript-Website/commit/684d302

**Comment by orta** [comment]
Thanks, yeah! Took a bit of time to get deployed - something was up with the JS from application insights
