### ISSUE TITLE
Playground: CORS error for https://typescript.azureedge.net/cdn/4.1.3/monaco/min/vs/editor/editor.main.js in Firefox

### ISSUE THREAD

**Issue by huonw** [microsoft/TypeScript-Website#1475]
I visited https://www.typescriptlang.org/play and got stuck on the "Downloading Typescript" screen due to CORS errors.

![image](https://user-images.githubusercontent.com/1203825/103964141-dd117400-51ae-11eb-9da3-98f076105a44.png)

**Repro:** visit the playground https://www.typescriptlang.org/play using:

- Firefox: 84.0.1
- OS: macOS 10.15.7 (19H2)

**Code** N/A

**Expected behavior:** the playground should load, as it does in Chrome and Safari.

**Actual behavior:** nothing loads, and the console shows:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://typescript.azureedge.net/cdn/4.1.3/monaco/min/vs/editor/editor.main.js. (Reason: CORS request did not succeed).
```

**Comment by orta** [comment]
Could this be specific to your local  setup? It works fine on FF 84 on Mac OS 10.15 for me and this is a server-side setting which is consistent to all CDN files like this

**Comment by huonw** [comment]
Ah, that does seem to be the case: my (default/non-customized) uBlock Origin filters block `azureedge.net` requests by default. My apologies.
