### ISSUE TITLE
Docs: wrong example code in JSX chapter of Handbook Reference

### ISSUE THREAD

**Issue by zcfan** [microsoft/TypeScript-Website#1476]
**Page URL:** https://www.typescriptlang.org/docs/handbook/jsx.html#function-component

**Issue:** 
The overloads code example is wrong, overload signature is not compatible with implementation:

```
interface ClickableProps {
  children: JSX.Element[] | JSX.Element
}

interface HomeProps extends ClickableProps {
  home: JSX.Element;
}

interface SideProps extends ClickableProps {
  side: JSX.Element | string;
}

// HERE: HomeProps is not compatible with SideProps, this overload example is wrong.
function MainButton(prop: HomeProps): JSX.Element;
function MainButton(prop: SideProps): JSX.Element {
  ...
}
```

**Recommended Fix:** Having `HomeProps` and `SideProps` both overloads, then provide implementation with `HomeProps | SideProps` type.

**Browser:** independence

**Comment by orta** [comment]
Htm, yeah, it is a bit of a weird one - I've submitted a fix in https://github.com/microsoft/TypeScript-Website/commit/94867a81d37d897af212b06d0eede1afbaa10bb9 will go live next week
