### ISSUE TITLE
v2 Layout issue in Firefox, causing horizontal scroll

### ISSUE THREAD

**Issue by jamiebuilds** [microsoft/TypeScript-Website#148]
This element is going off the page and causing horizontal scrolling on Firefox 71.0
 
<img width="1440" alt="Screen Shot 2019-12-06 at 10 41 12 AM" src="https://user-images.githubusercontent.com/952783/70347521-8f8d3f80-1815-11ea-8103-96861501f946.png">

**Comment by orta** [comment]
oops - forgot to come and close this. It's working now on master :D
