### ISSUE TITLE
TypeScript Website Localization plans 2021

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#1480]
TS Website Localizers - **TDLR** from February I'd like new localization PRs to go to [microsoft/TypeScript-Website-Localizations](https://github.com/microsoft/TypeScript-Website-Localizations) instead which will be imported into this repo automatically. 

/cc @sasurau4 @Quramy @Naturalclar @khaosdoctor @danilofuchs @KingDarBoja @Kingwl @Bumkeyy @jefrydco @nusendra @mazipan @mandaputtra @AMashoshyna @msieroslawska @TomWebwalker 

Hi folks - congrats on your work so far you're translated a **whopping 1057 files** of translated TypeScript documentation since we started last January https://github.com/microsoft/TypeScript-Website/pull/180. Honestly, _that's pretty stunning_. It's also bit more traffic on the TypeScript Website repo than I expected and I'd like to calm it down a bit so that others can watch the repo.
 
Over the last month, I've been taking all of the infrastructure which maintains the localization side of the TypeScript website and made it work for any repo. You can see all of that in https://github.com/OSS-Docs-Tools - this means any big markdown-based website can re-use all this tech too. 

We'll have all the same CI checks and more focused documentation to help new folks get started on this repo. The new repo is much simpler, it is just a docs dir with each section in it:

```
❯ tree . -L 2 -I node_modules
.
├── CODE_OF_CONDUCT.md
├── LICENSE
├── LICENSE-CODE
├── README.md
├── SECURITY.md
├── docs
│   ├── documentation
│   ├── playground
│   ├── tsconfig
│   └── typescriptlang
├── localize.json
├── package.json
└── yarn.lock

5 directories, 8 files
```

I've ported the current translated docs via [@oss-docs/sync](https://www.npmjs.com/package/@oss-docs/sync) yesterday, but will re-run the command on Feb 1 bringing any existing PRs to this repo over.

Given that this change will break [existing localization PRs](https://github.com/microsoft/TypeScript-Website/pulls?q=is%3Aopen+is%3Apr+label%3Atranslation), I'm giving all of January to get those PRs sorted and if some don't make it - that's OK, we can figure out edge cases closer to the time. 

I'll slowly be updating all the docs and issues in here over the next month. You don't _have_ to do anything, it will all just switch over with time and I'll close any PRs which are still alive in Feb 1 👍🏻

**Comment by khaosdoctor** [comment]
Awesome! I'll update #233 to include this topic and I'll close it afterwards, directing everyone to the new repo and starting the process again! I'll try to finish reviewing all the PRs until the end of the month and avoid new PRs to be created so we can have a better transition.

**Comment by khaosdoctor** [comment]
@orta created https://github.com/microsoft/TypeScript-Website-Localizations/issues/1 to continue the updates over there
