### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by jablko** [microsoft/TypeScript-Website#1498]
Has there been any discussion about migrating from `gatsby-transformer-remark` to `gatsby-plugin-mdx`?

I used GitHub emojis in #1490 and they don't show up on [the TypeScript website](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#any-unknown-object-void-undefined-null-and-never-assignability). Whoopsie! :grimacing:

I think the simplest fix would be to edit the Markdown files and replace the :shortcodes: with Unicode characters, however there is also [remark-emoji](https://github.com/rhysd/remark-emoji) for this.

I looked at adding `remark-emoji` to `gatsby-config.js` and discovered there are two types of remark plugins: remark plugins and *Gatsby* remark plugins:
- https://www.gatsbyjs.com/docs/how-to/routing/mdx-plugins/#remark-plugins
- https://github.com/kevin940726/to-gatsby-remark-plugin#why

`gatsby-plugin-mdx` supports both directly, `gatsby-transformer-remark` only supports Gatsby remark plugins (I gather?).

So, curious if there's already been any discussion about `gatsby-plugin-mdx`? I looked through the commit log and the issues but haven't found anything relevant. Migrating to `gatsby-plugin-mdx` seems nontrivial and involves changes to your content: https://www.gatsbyjs.com/docs/how-to/routing/migrate-remark-to-mdx/

Finally there are multiple Gatsby remark plugins: https://www.gatsbyjs.com/plugins/?=emoji

So, edit the Markdown files? `remark-emoji`? Gatsby remark plugin? Something I haven't considered? and I'm curious about `gatsby-plugin-mdx`.

**Comment by orta** [comment]
I've been slowly looking at supporting MDX https://github.com/microsoft/TypeScript-Website/pull/1278 - it's not been trivial though (and the remark plugins specifically have been a problem) - Yesterday I shipped a new version of twoslash which specifically checks against mdx https://github.com/microsoft/TypeScript-Website/pull/1495 which might make that more possible.

**Comment by orta** [comment]
I opted out of MDX in #1278 and I'm too wild on adding a new dependency just for one table of emojii, so I switched it around to inline the HTML table and links to the original markdown in a html comment. It all looks pretty now.
