### ISSUE TITLE
GFM table alignment

### ISSUE THREAD

**Issue by jablko** [microsoft/TypeScript-Website#1499]
### Issue

#1222 left-aligned tables https://github.com/microsoft/TypeScript-Website/issues/1221#issuecomment-705625661, which looks good but overrides [GFM table alignment](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/organizing-information-with-tables#formatting-content-within-your-table:~:text=You%20can%20align%20text%20to%20the,%7C%20Left).

e.g. in #1490 I centered some of the columns https://github.com/microsoft/TypeScript-Website/pull/1490/files#diff-5df78592bbddd75ac689061920fbaee892b7755b8d637d160150981fdfce22aaR299

The rendered `td` and `th` elements do have `align="center"` attributes https://www.typescriptlang.org/docs/handbook/type-compatibility.html#any-unknown-object-void-undefined-null-and-never-assignability

but the `.markdown table td` rule is more specific:
![Screenshot from 2021-01-14 17-11-42](https://user-images.githubusercontent.com/78493/104664098-a6929800-568b-11eb-82f0-a60b64e2f903.png)

### Recommended Fix

Maybe `:not([align])` to `markdown.scss`?
```CSS
td:not([align]),
th:not([align]) {
  text-align: left;
}
```
-> https://github.com/microsoft/TypeScript-Website/blob/fccf7bcaf62199aae9ed902c33fbb72b3c17506e/packages/typescriptlang-org/src/templates/markdown.scss#L51-L53

**Comment by orta** [comment]
I fixed this by not using a markdown table, where I could add a css class to the table /shrug

Not elegant, but all of the current tables across the docs look nice and I don't really want to make hyper specific CSS to try hit just one
