### ISSUE TITLE
Playground doesn't support async generators.

### ISSUE THREAD

**Issue by cakoose** [microsoft/TypeScript-Website#15]
I put the following code into https://www.typescriptlang.org/play/

```typescript
async function f(): Promise<number> {
    return 1;
}

async function* g(): AsyncIterator<number> {
    yield 1;
    await f();
    return 2;
}
```

The compiler reports two errors on the `async function *g()` line.
- Cannot find global type 'AsyncIterableIterator'
- Cannot find name 'AsyncIterator'

Is that expected?

**Comment by saarw** [comment]
Also getting 'Cannot find name "AsyncGenerator"'

**Comment by orta** [comment]
Setting the target to ESNext works with all these samples out of the box o the playground  👍🏻
