### ISSUE TITLE
Extra > in closing tag

### ISSUE THREAD

**Issue by lukaszprus** [microsoft/TypeScript-Website#150]
https://github.com/microsoft/TypeScript-Website/blob/e610048c737a1caff6f809cca40ddb3c756bd727/src/_layouts/docs.html#L49

![Screenshot from 2019-12-14 22:52:06](https://user-images.githubusercontent.com/2707997/70848740-dfc76a00-1ec5-11ea-891b-86ca0e1bf8c9.png)

**Comment by orta** [comment]
Thanks, updated with https://github.com/microsoft/TypeScript-Website/commit/b8a1c78b0101de4461223cfef8ad14031172e8c3
