### ISSUE TITLE
Playground: Ca not set JSX to None / disable

### ISSUE THREAD

**Issue by safareli** [microsoft/TypeScript-Website#1505]
**Actual behavior:**
If you go to the [playground](https://www.typescriptlang.org/play), and in TS config you try to set `JSX:` to `None`, the page reloads and JSX: still is set to React.  Tho setting JSX to ReactNative or Preserve works fine.

**Expected behavior:**
I'm expecting to be able to disable JSX in the playground so I can write :

```ts
const id = <A>(v:A):A => v
```

and not have to instead write 

```ts
function id <A>(v:A):A {return v}
```

**Comment by orta** [comment]
Oh yeah, that's a bug for sure

**Comment by grapevinegizmos** [comment]
Yep, you can't write `let x = <MyInterface>{}` either

**Comment by safareli** [comment]
@orta is that PR already deployed? I can still observe the issue being present on the website (did command+r as well as test in incognito)

**Comment by orta** [comment]
It is on staging, https://www.staging-typescript.org/play

Prod deploys are every monday
