### ISSUE TITLE
Playground doesn't work

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript-Website#1506]
The playground shows the normal loading animation, then it shows the playground, but without the normal panel on the right side, and all buttons (outside of the navigation bar) are unresponsive.

The site doesn't update when typing in the code text box, but IntelliSense and autocompletion still work.

The TS version seems to have not been set, it shows "Version..."

![](https://user-images.githubusercontent.com/65428781/104970828-a81cd280-59a1-11eb-8cae-388eda71519d.png)

**Comment by orta** [comment]
This was likely form a bad JS upload a few days ago which poisoned your JS cache, hitting refresh a few times should fix it. If this happens again, systematically I'll  add a cache busting feature to the playground 👍🏻

**Comment by ghost** [comment]
@otra Yeah, it seemed to have been fixed after I cleared my entire browser cache yesterday, good to know that's all it was.
