### ISSUE TITLE
v2 "on this page" is overwhelming and not useful on long pages

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript-Website#151]
See http://www.typescriptlang.org/v2/docs/handbook/release-notes/overview.html

Also, this page reveals that the scrolling animation feels really slow if scrolling a long way.

**Comment by orta** [comment]
haha - yeah, it definitely is. Maybe I can put a max of 15 and then just call it

**Comment by orta** [comment]
This was added - thanks!
