### ISSUE TITLE
TypeScript glossary TODO list

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#1512]
Hi folks, I'm exploring adding a glossary for TypeScript terms to the website. I've started a few already, and have some design ideas for how it could be approached (think a mix of the tsconfig website and @joshwcomeau's [operator lookup](https://www.joshwcomeau.com/operator-lookup?match=bitwise-not) - I'll update this issue with designs when they are a bit more solid.

What I'd love is comments on **what terms/jargon related to TypeScript have tripped you up/others at some point?** Then I can work through this big list.

I think in this section of the site we'll probably need to reach into covering JS more than normal to be comprehensive: E.g. "variable reassignment, "classes", "object literals" "hoisting" and "ternary operator" might be something we should cover, but "Math.min" or "if else statements" probably aren't.

**Comment by orta** [comment]
I have a rough list of a [few already](https://github.com/orta/typescript-notes/blob/master/GLOSSARY.md#type-stuff-which-can-be-see-outside-the-compilers).

- Indexed types
- Conditional types
- Narrowing
- Expanding
- Generics
- Unions
- Literal
- Intersections
- Callable
- Instantiable
- As const keyword
- Infer keyword
- Tuple
- Mapped Types
- Index Signatures
- Type Assertions
- Expressions
- Statements
- Type System
- "Shape" of an object
- declare keyword
- "JS runtime"
- Types vs Runtime
- Assertion Functions
- Discriminate 
- Optional Chain
- Spreads
- Script vs Module
- Defiinition File
- contravariant / covariant / bivariance
- namespace

**Comment by robpalme** [comment]
Ambient vs global
External Module vs Module

Thing that needs a term but does not have one as far as I know:  a word to distinguish a type (e.g. a class instance type) named "foo" vs typeof the value "foo" (e.g. the type of the constructor function)

**Comment by mheiber** [comment]
- [Homomorphic mapped typed](https://stackoverflow.com/questions/59790508/what-does-homomorphic-mapped-type-mean)

- [Naked type parameter](https://stackoverflow.com/questions/51651499/typescript-what-is-a-naked-type-parameter)

**Comment by RyanCavanaugh** [comment]
Distributive / Distributivity along with naked type parameter 👍

**Comment by lazytype** [comment]
- declaration merging / module augmentation
- soundness
- some builtin types
  - `Promise` vs `PromiseLike`
  - `Generator` vs `GeneratorFunction`
  - `Iterator` vs `Iterable`
- `readonly` keyword, `ReadOnly<T>`, `ReadonlyArray<T>`, etc. (e.g. some people don't intuitively understand why `Array<T>` is a subtype of `ReadonlyArray<T>` and not the other way around)
- call signatures (and how they are still bivariant even with --strictFunctionTypes)
- mixin class
- rest parameter
- type widening, e.g. wrt literal types

**Comment by mkantor** [comment]
- `*.d.ts`
- `abstract class`
- both kinds of private fields
- contextual return types/contextual argument types
- control flow based type analysis
- destructuring
- downlevel
- `enum`
- excess property checking
- exhaustiveness checking
- `globalThis`
- higher-order function
- indexed access
- interface
- key remapping
- mapped type modifiers
- module resolution
- `never`
- newable
- nullish coalescing
- path mapping
- polymorphic
- project references/`composite`
- source map
- static side/instance side of classes
- structural typing
- synthetic default import
- template literal type
- `this` parameters
- top type/bottom type
- triple-slash directives
- type compatibility/assignability
- type guard
- type inference
- type predicate (`x is Y` return type)
- `unique symbol`
- utility type/helper type
- variadic
- weak types

**Comment by orta** [comment]
- "Uppercase String and Boolean" - we mention this in places, but a deeper explanation is useful
 - TC39 ?
- top-level await

**Comment by ducin** [comment]
- explicit vs implicit (type inference)
- static vs dynamic
- structural vs nominal
- structural polymorphism
- derivative types
- parametrized function types vs generic functions

**Comment by orta** [comment]
Some notes: https://hackmd.io/-WCdTOv-TDirMFd90Rz7Yg

**Comment by timoxley** [comment]
@orta Would be great if this glossary also included all the TypeScript syntax & keywords.

e.g. where can I go to look up exactly what `keyof`, `is`, `as` or `of`  do and where they are valid? 

Unless I've missed something, currently there's no actual official reference documentation for the syntax, it just has to be loosely inferred by reading a combination of Handbook, Handbook Reference and What's New pages.
