### ISSUE TITLE
Typescript playground shows incorrect line with error

### ISSUE THREAD

**Issue by Zydnar** [microsoft/TypeScript-Website#152]
New lines at the end of document confuse sandbox:
![obraz](https://user-images.githubusercontent.com/20562545/70908283-1eb30800-200b-11ea-8424-25bb57dddb6f.png)
Now if I delete them:
![obraz](https://user-images.githubusercontent.com/20562545/70908366-5326c400-200b-11ea-81a3-f617700b8b5f.png)
So error throws at line 2 but sandbox count new lines as part of expression.

**Comment by orta** [comment]
Hrm, thanks,  I wonder if this would be fixed once #7  is in - doing this code sample in vscode shows it in lib.dom.ts and the playground needs to support these as separate files to show those results

<img width="675" alt="Screen Shot 2019-12-17 at 12 11 01 PM" src="https://user-images.githubusercontent.com/49038/70994529-5e8af580-20c6-11ea-842d-54cddf3837bd.png">

**Comment by orta** [comment]
The playground now shows the right files but you can't jump to them because the playground isn't multi-file aware, I think this is good enough to close

![Screen Shot 2021-03-10 at 10 54 24 AM](https://user-images.githubusercontent.com/49038/110618889-15bdd180-818f-11eb-9bfa-d92e0274fc6a.png)
