### ISSUE TITLE
Idea: Community page margins are off in Firefox

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#1540]
![image](https://user-images.githubusercontent.com/972891/106426986-6a955c00-641b-11eb-8bf9-b1d075f356e0.png)

This happens to be the case because of the `.community .callouts .callout a` selector which adds a `margin-right: 8px`. Unfortunately, it applies to the text link (not just the logo link), which pushes the description 8px out.

**Comment by orta** [comment]
Interesting, what browser? This doesn't repro on mine (Checked safari and edge) 

![Screen Shot 2021-02-01 at 9 50 19 AM](https://user-images.githubusercontent.com/49038/106442252-f38bb200-6472-11eb-9963-37844b701fdb.png)

**Comment by DanielRosenwasser** [comment]
Forgot to post the link: https://www.typescriptlang.org/community

Ah this was on Firefox. Indeed, it looks like it works in Edge.

**Comment by falinsky** [comment]
Also, there are unexpected spaces caused by the same margins:
![community-page-empty-spaces-what-are-we-living-for](https://user-images.githubusercontent.com/859638/106534221-465d7c00-64fc-11eb-8cec-c957f5e45614.png)
