### ISSUE TITLE
Docs: Playground plugin page should be responsive to smaller screen width

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#1552]
Right now https://www.typescriptlang.org/dev/playground-plugins/ allows the screenshot to take up way more space than the text itself, which is non-ideal.

![image](https://user-images.githubusercontent.com/972891/107134080-9ee99c00-68a3-11eb-82e4-090e5a6150b3.png)

**Comment by orta** [comment]
Cool, I've added some more compression steps in that layout
