### ISSUE TITLE
Playground: Plugin require error gets swallowed by error handling logic

### ISSUE THREAD

**Issue by kevinramharak** [microsoft/TypeScript-Website#1554]
Whenever a plugin throws an error during plugin initialisation by calling `require` it wil cause a null ref on https://github.com/microsoft/TypeScript-Website/blob/v2/packages/typescriptlang-org/src/templates/play.tsx#L120.
This makes it harder to figure out what the original error is.

![image](https://user-images.githubusercontent.com/14903712/107149578-a4a1b900-6959-11eb-9777-9472c99c39f3.png)

**Repro:**

**Expected behavior:**
Expect to be able to see the original exception.

**Actual behavior:**
Can only see the error caused by trying to access `innerText` of null.

** sugested fix **
Change the `document.getElementById("loading-message")!.innerText` to check if the element exists instead of using a type assertion.

**Comment by orta** [comment]
Thanks!
