### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by rich-newman** [microsoft/TypeScript-Website#1561]
**Page URL:** https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/reference/Advanced%20Types.md#distributive-conditional-types

**Issue:** 

The text says **'Similar to union and intersection types, conditional types are not permitted to reference themselves recursively'**

This confused me. Union and intersection types **are** permitted to reference themselves recursively aren't they?

For example on the same page in the [Type Aliases](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/reference/Advanced%20Types.md#type-aliases) section we define 

`type LinkedList<Type> = Type & { next: LinkedList<Type> };`

Which is an intersection type which references itself recursively.  We can change that `&` to a `|` to create a (not very useful) union type that references itself recursively.

So is the original statement wrong, or is there a sense I'm missing in which it's correct?

**Recommended Fix:**

If it's wrong we can just take out 'Similar to union and intersection types' from the sentence I think.

**Comment by orta** [comment]
Yeah, this line was created before that restriction was liften in 3.7 - it can be removed 👍🏻
