### ISSUE TITLE
Chinese translated Docs has been outdated for a long time

### ISSUE THREAD

**Issue by Germxu** [microsoft/TypeScript-Website#1562]
when I search for tuple ,  I found that Chinese doc was  wrong, but English is right

Accessing an element outside the set of known indices fails with an error: [中文版](https://www.tslang.cn/docs/handbook/basic-types.html)

**Comment by orta** [comment]
That's an unofficial fork, not this repo - you can find the Chinese docs at https://www.typescriptlang.org/zh/

**Comment by Germxu** [comment]
thanks a lot !
