### ISSUE TITLE
Docs: Change misleading example suggesting accessor decorators can access class instances via target argument

### ISSUE THREAD

**Issue by tru03** [microsoft/TypeScript-Website#1577]
**Page URL:** [https://www.typescriptlang.org/docs/handbook/decorators.html#metadata](https://www.typescriptlang.org/docs/handbook/decorators.html#metadata)

**Issue:**
```
import "reflect-metadata";

class Point {
  x: number;
  y: number;
}

class Line {
  private _p0: Point;
  private _p1: Point;

  @validate
  set p0(value: Point) {
    this._p0 = value;
  }
  get p0() {
    return this._p0;
  }

  @validate
  set p1(value: Point) {
    this._p1 = value;
  }
  get p1() {
    return this._p1;
  }
}

function validate<T>(
  target: any,
  propertyKey: string,
  descriptor: TypedPropertyDescriptor<T>
) {
  let set = descriptor.set;
  descriptor.set = function (value: T) {
    let type = Reflect.getMetadata("design:type", target, propertyKey);
    if (!(value instanceof type)) {
      throw new TypeError("Invalid type.");
    }
    set.call(target, value);
  };
}
```

This example is unfortunate because it suggests that the `target` argument is a class (`Line`) **instance**, but as the documentation states it's "the **prototype** of the class for an instance member". That's because it's most reasonable to expect `set.call(target, value);` to be called on an instance, so the setter would work just like without the decorator.

This code results the `p0` and `p1` setters setting `_p0` and `_p1` properties on the Line prototype, which makes the displayed solution unusable in case of multiple instances, see:
```
const lines = [new Line(), new Line(), new Line()];
let i = 0;
lines.forEach(line => {
  line.p0 = {x: i, y: i};
  i++;
});
console.log(this.lines.map(line => line.p0.x)); // [2, 2, 2]
```

The example made me believe accessing a class instance from within the accessors defined in the decorator is possible, which made me waste a bunch of time, and I'd like others to avoid the same mistake.

**Recommended Fix:** Find a better suiting example or add a note that this example only works as expected with a single instance of `Line`.

**Comment by orta** [comment]
Yeah, I definitely agree - I'm mid-way through a revamp of this doc and I'll figure something out
