### ISSUE TITLE
Playground: unable to import submodule from npm package

### ISSUE THREAD

**Issue by snebjorn** [microsoft/TypeScript-Website#1578]
I'm trying to import a submodule from a package imported from NPM.
But it doesn't seem to work.

The root module works just fine.

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgM2AGxgUynAviqCEOAcigA8ArAZwHoIxsBDGaakgbgCgg

![image](https://user-images.githubusercontent.com/1266245/108263120-1eaa1d00-7166-11eb-867c-24a2b0d8d9bc.png)

```ts
import { Observable } from 'rxjs';       // <-- this works
import { filter } from 'rxjs/operators'; // <-- this doesn't work
```
`rxjs/operators` is included in the rxjs npm package

**Expected behavior:**
Should be able to import from `'rxjs/operators'`

**Actual behavior:**
This error is shown
> Cannot find module 'rxjs/operators' or its corresponding type declarations.(2307)

**Comment by orta** [comment]
Cool, makes sense, open to PRs adding support for this 👍🏻
