### ISSUE TITLE
Unhandled case where the parameter is Symbol

### ISSUE THREAD

**Issue by 2234839** [microsoft/TypeScript-Website#1589]
https://github.com/microsoft/TypeScript-Website/blob/4490d98fe701d60e2e653a4d159d6df9ca8e0764/packages/playground/src/sidebar/runtime.ts#L127

It will cause an error `TypeError: can't convert symbol to string`

[The simplest repeat demo](https://www.typescriptlang.org/zh/play?#code/LAKAxg9gdgzhA2BTAdPCBzAFAZQJ4FsAjBTAcgENSBKKoA)

**Comment by orta** [comment]
Sure, open to PRs 👍🏻
