### ISSUE TITLE
Docs: This document has many non operable examples https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/reference/Advanced%20Types.md

### ISSUE THREAD

**Issue by xtianus79** [microsoft/TypeScript-Website#1592]
I am reporting this because the code examples are poor. They should be working code examples and comments in the code examples. 
 https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/reference/Advanced%20Types.md

https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/reference/Advanced%20Types.md

the type user-defined has no working code. 

**Recommended Fix:** 

**Browser:**

**Comment by orta** [comment]
That section has two subsections with code, and all of these examples are backed by the compiler - so they do work. Can you maybe elaborate on what you think might be a better alternative?

**Comment by orta** [comment]
Closing due to lack of a reply
