### ISSUE TITLE
Docs: Homepage link to 4.2 release is broken

### ISSUE THREAD

**Issue by colejohnson66** [microsoft/TypeScript-Website#1599]
**Page URL:** https://www.typescriptlang.org/ and https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-2.html

**Issue:** The linked URL is a 404

**Recommended Fix:** Fix the link (or create the missing page)

**Browser:** N/A

**Comment by colejohnson66** [comment]
The ["Docs" page](https://www.typescriptlang.org/docs/) as well has a link towards the bottom ("What's new in 4.2") that links to the missing URL as well

**Comment by orta** [comment]
Thanks this should be fixed o the next deploy today 👍🏻

**Comment by colejohnson66** [comment]
Yes, it’s fixed now :)
