### ISSUE TITLE
Redirect to code flow example from nullable types example leads to inconsistent behavior 

### ISSUE THREAD

**Issue by ocBruno** [microsoft/TypeScript-Website#1608]
# Bug Report

### 🔎 Search Terms

code flow example documentation 
### 🕗 Version & Regression Information

- This is the behavior in every version I tried, and I reviewed the FAQ for entries about "code flow link documentation"

### ⏯ Playground Link

[This is the link](https://www.typescriptlang.org/play?strictNullChecks=false&ts=4.2.2#example/code-flow) of examples section in typescript documentation where the issue is happening and [this link to the same page](https://www.typescriptlang.org/play?ts=4.2.2&ssl=4&ssc=69&pln=1&pc=1#example/code-flow) is where the issue is not occuring

### 💻 Code

Follow code flow example link at line 40 
```
// ( see more at example:code-flow )
```

Hover over jon on if and else statement at line 17 and see how the type does not change as expected

```
// If you hover your mouse over the three following uses of 'jon' below,
// you'll see how the types change depending on where the word is located:

if (jon) {
  jon;
} else {
  jon;
}
```

### 🙁 Actual behavior

The type did not change on hover

### 🙂 Expected behavior

I expected the type to change as is happening correctly when redirected from the [type guards page code flow example link](https://www.typescriptlang.org/play/?q=219#example/type-guards) on line 4 

```
// Type Guarding is the term where you influence the code
// flow analysis via code. TypeScript uses existing JavaScript
// behavior which validates your objects at runtime to influence
// the code flow. This example assumes you've read example:code-flow
```

Pardon any mistakes above but if there is anything I should fix or I can do to help let me know and thanks for the great tool!

**Comment by orta** [comment]
Yeah, interesting - I think the examples loader needs to make sure it sets all of the required params.

Re: length, the goal of each one is to describe a concept completely independently - I'm not wild on dropping the length of the comments because that probably relies on linking out, but I'm open to PRs which can keep the original goal with less comments 👍🏻
