### ISSUE TITLE
Options in JavaScript are all grayed out

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#161]
http://www.typescriptlang.org/play/index.html?alwaysStrict=false&ts=3.8.0-dev.20191221&ssl=12&ssc=1&pln=12&pc=2&useJavaScript=true#code/PTAEAEBcGcFoGMAWBTeBrAsAKG8AVHtqHqAGID25AdEYVsRAA4CGATswLagDeAqgEoAZAL6gxoAK6sANuPEAhNjXolwLdl27RIrAJYA7AOaip0qolbIAZqEUAvZQ3CXIU-T216jogIoSHtMDYVhL68JC65O5WlAAU3KAW1qDCAJQ8ROIubomWVgDc2MJAA

![image](https://user-images.githubusercontent.com/972891/71384603-1755a680-2597-11ea-9a46-ae64c7017f14.png)

**Comment by orta** [comment]
Yep, that's on purpose, I guess the implication here is that they all should still work then? 

Do we need different defaults for that? What is your use case for different config options in JS mode?

**Comment by orta** [comment]
Fixed in the v3 playground
