### ISSUE TITLE
Docs: Undocumented behavior relating to TS2318 errors caused by noLib

### ISSUE THREAD

**Issue by RA80533** [microsoft/TypeScript-Website#1612]
**Page URL:**
https://www.typescriptlang.org/tsconfig#noLib

**Issue:**
Running `tsc` with `--noLib` causes the compiler to produce a handful of errors relating globals:

```console
$ tsc --noLib
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.

Found 8 errors.
```

Clarification was provided in https://github.com/microsoft/TypeScript/issues/3930#issuecomment-122953275 that this is the intended behavior; however, the documentation available in the reference guide for the TSConfig file does not provide any hint towards this.

**Recommended Fix:**
Document the purpose behind this behavior.

**Comment by orta** [comment]
Yeah, this makes sense 👍🏻

**Comment by hahmadia** [comment]
@orta

Please close , Thanks.
