### ISSUE TITLE
Playground: Resize while TS Config is open breaks the UI.

### ISSUE THREAD

**Issue by WORMSS** [microsoft/TypeScript-Website#1614]
Resize while TS Config is open breaks the UI.

![image](https://user-images.githubusercontent.com/1384537/110111771-bf285000-7da8-11eb-9cbe-6be8e5e6f0a9.png)

# [🎥 Video 🎥 ](https://streamable.com/mwa6qe)

**Repro:**

1) Open `TS Config`
2) grab the resize bar, and drag it over the TS Config panel

**Expected behavior:**

Update the TS Config panel width to the new size

**Actual behavior:**

Size stays the same and becomes hidden by the Output panel

**Comment by orta** [comment]
Aye, shame. 

This is likely to get moved into a sidebar in an upcoming playground release, so I'd only look into this if it's something you're strongly interested in - https://twitter.com/orta/status/1367119200112832514

**Comment by WORMSS** [comment]
Not really super interested.
The simple work around is close/reopen the TS Config and it corrects the size.. So it doesn't stop me working..
I can wait for version 4... or will it be version 5?
I forget what we are on.
