### ISSUE TITLE
Idea: Add padding to the menu on mobile

### ISSUE THREAD

**Issue by j-f1** [microsoft/TypeScript-Website#1623]
**Improvement Idea:**

When the bottom bar in Safari is not visible, the handbook menu collides with the home indicator on iPhone. By adding padding using `env(safe-area-inset-bottom)`, this can be remedied without adding excess padding in cases where the viewport is rectangular. See [this WebKit blog post](https://webkit.org/blog/7929/designing-websites-for-iphone-x/) for more detail.

**Why:**

![image](https://user-images.githubusercontent.com/25517624/110228300-0825f480-7ece-11eb-9cf9-ffba60692281.png)

**Alternative ideas:**

Another option would be to move the menu to the top of the screen, since there is always some sort of top bar when using Safari.

**Comment by orta** [comment]
Interesting, I did take that into account https://github.com/microsoft/TypeScript-Website/issues/130#issuecomment-560546774 but something might have changed - do you know if it's always like this?

**Comment by j-f1** [comment]
I only just noticed the issue — I didn’t try any debugging steps.
