### ISSUE TITLE
.

### ISSUE THREAD

**Issue by lyne408** [microsoft/TypeScript-Website#1633]
.

**Comment by orta** [comment]
Can you please post the errors? 

The website is working fine (as you can see by all the green ticks on the main branch ) https://github.com/microsoft/TypeScript-Website/commits/v2

**Comment by lyne408** [comment]
`RELEASE` tutorial.
- network issues
- build issues

**Comment by lyne408** [comment]
> 
> 
> Can you please post the errors?
> 
> The website is working fine (as you can see by all the green ticks on the main branch ) https://github.com/microsoft/TypeScript-Website/commits/v2

I'd deleted "node_modules".
I've found those docs `.md`.
0:00 - 06:00, I can't connect to Internet.
