### ISSUE TITLE
Docs: The unknown type

### ISSUE THREAD

**Issue by thany** [microsoft/TypeScript-Website#1635]
**Page URL:** https://www.typescriptlang.org/docs/handbook/basic-types.html#unknown

**Issue:** The [suggested page](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html) by which this page has been deprecated, doesn't describe the `unknown` type at all. It merely mentions it a few times. It's missing the clear & complete description that's still on the deprecated page.

**Recommended Fix:** To the [Everyday types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html) page, add a section *The unknown type* or something. It could be (or at least start with) a copypaste of the [unknown section on that deprecated page](https://www.typescriptlang.org/docs/handbook/basic-types.html#unknown).

Another fix is to create a secondary "types" page, perhaps *The not-so-everyday types* where more uncommon types are explained, among which the `unknown` type.

**Comment by orta** [comment]
Yeah, good ideas, `unknown` is currently documented inside the context of functions ( as it's most common usage is a return type from funds) so I'll add a special case for re-directs never void and unknown
