### ISSUE TITLE
Deprecation notice on old handbook has horrible contrast in dark mode

### ISSUE THREAD

**Issue by kanyuga** [microsoft/TypeScript-Website#1638]
The text on deprecation notice at the top is white on a pale yellow background in dark mode e.g.: https://www.typescriptlang.org/docs/handbook/advanced-types.html
<img width="594" alt="image" src="https://user-images.githubusercontent.com/1700080/110472386-5a456080-80ee-11eb-9422-761df060b831.png">

I tested this on both Firefox and Chrome on Big Sur.

**Comment by orta** [comment]
Oof
