### ISSUE TITLE
Make `/// <reference lib="..." />` triple slash directives work

### ISSUE THREAD

**Issue by isiahmeadows** [microsoft/TypeScript-Website#164]
[This snippet works as expected, because the target is set to ES2015](https://www.typescriptlang.org/play/?target=2#code/PQg8CcFMDNKg7AxpABAGwJYCMC8AiAUQGUAmABgEYBWPFYAPgChEB7eAZwBcUAvOFyOxQ4U8SAHcUAQXDgAhgE8AFBTIBKAHTQMaNEvUBuIA), but [this doesn't, because the directive isn't interpreted and handled correctly](https://www.typescriptlang.org/play/?target=1#code/PQg8CcFMDNKg7AxpABAGwJYCMC8AiAUQGUAmABgEYBWPFYAPgChEB7eAZwBcUAvOFyOxQ4U8SAHcUAQXDgAhgE8AFBTIBKAHTQMaNEvUBuIA). I'd like it to work for both.

Related to #136.

**Comment by orta** [comment]
This was fixed when we started using the TS resolving setup for lib d.ts files 👍🏻
