### ISSUE TITLE
Docs: Object Types / Tuple Types / Optional tuple elements snippet error (handbook v2)

### ISSUE THREAD

**Issue by masonlouchart** [microsoft/TypeScript-Website#1640]
**Page URL:** https://www.typescriptlang.org/docs/handbook/2/objects.html#tuple-types

**Issue:**

<img width="1372" alt="Capture d’écran 2021-03-09 à 21 13 14" src="https://user-images.githubusercontent.com/2325091/110532205-d3f44300-811c-11eb-89ac-57766564bb46.png">

**Comment by hahmadia** [comment]
I've created https://github.com/microsoft/TypeScript-Website/pull/1642 which attempts to fix this problem.
