### ISSUE TITLE
Docs: Epub doesn't upload to google play books

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#1644]
**Context URL:** https://twitter.com/AdamRackis/status/1369668474503630851

**Issue:** The epub doesn't upload, perhaps their's something off in how it's build (it did behave weirdly occasionally on my Mac too)

**Comment by cduran** [comment]
I have the same issue, the upload works but fails to process the file. 
Screeshot of google books website
<img width="167" alt="Screen Shot 2021-03-10 at 6 13 29 PM" src="https://user-images.githubusercontent.com/164527/110716268-6e5f8f80-81cc-11eb-8742-e7aaba8a199d.png">

_Note: In my Mac, the Books app seems to be handling it ok. Book app version 1.19 (1645)_

**Comment by cduran** [comment]
Doing further research using this tool:
[http://validator.idpf.org/](http://validator.idpf.org/)
 [https://github.com/w3c/epubcheck](https://github.com/w3c/epubcheck)
Gave me tons of errors.

**The result was:**
_Check finished with errors
Messages: 0 fatals / 2393 errors / 19 warnings / 1 info
EPUBCheck completed_

**On 2375 of those 2393 errors, the output message was this:**
_Error while parsing file: element "div" not allowed here; expected the element end-tag, text or element "a", "abbr", "area", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "command", "datalist", "del", "dfn", "em", "embed", "i", "iframe", "img", "input", "ins", "kbd", "keygen", "label", "link", "map", "mark", "meta", "meter", "ns1:switch", "ns2:math", "ns3:svg", "object", "output", "progress", "q", "ruby", "s", "samp", "script", "select", "small", "span", "strong", "sub", "sup", "textarea", "time", "u", "var", "video" or "wbr" (with xmlns:ns1="http://www.idpf.org/2007/ops" xmlns:ns2="http://www.w3.org/1998/Math/MathML" xmlns:ns3="http://www.w3.org/2000/svg")_

**Comment by orta** [comment]
Great, perfect, thanks @cduran - yeah it was the preview app
