### ISSUE TITLE
Playground: Export > Markdown Issue has invalid jsx and moduleResolution

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript-Website#1646]
The copy & paste output from Export > Copy as Markdown Issue includes:

```json
      ...
      "moduleResolution": 2,
      "target": "ES2015",
      "jsx": "React",
      "module": "ESNext"
      ...
```

The `"jsx"` and `"moduleResolution"` values don't pass TypeScript's native config file parsing:
* `moduleResolution` should be a string
* `jsx` should be lowercase

**Repro:**

https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCkFNoG8BQ0PQEbQLzQEYBuVAX1VVEhgBEEAnASwDcEATaBADwBcEA7NjHgQkaTNhIS2ALmj8ArgFssDPNB4ALRhAB0WItAD0RzlwAOCYHw4N6Ae3rR7-aAHIsbgDTQwIEM5aamD0SMx+jGwUEsAuEDz0CtaOABQAlCjoEpgQCpb06VLZGFo6+uoATEUY5KRAA

**Expected behavior:**

```json
      ...
      "moduleResolution": "node",
      "target": "ES2015",
      "jsx": "react",
      "module": "ESNext"
      ...
```

**Actual behavior:**

See above.

**Comment by hahmadia** [comment]
@orta 
Should we close this? I believe this was resolved in a recent PR merge.

**Comment by hahmadia** [comment]
https://github.com/microsoft/TypeScript-Website/pull/1652 resolves this
