### ISSUE TITLE
Playground: poor Chrome scrolling performance in Copy as Markdown Issue modal

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript-Website#1651]
The `backdrop-filter: blur(6px);` on the playground's export modal slows down my browser's scroll FPS.

With the CSS backdrop blur filter:

https://user-images.githubusercontent.com/3335181/110698150-474c9200-81bb-11eb-851e-2f1dca109aa9.mov

Without the filter:

https://user-images.githubusercontent.com/3335181/110698301-78c55d80-81bb-11eb-9427-2d09094194aa.mov

**Repro:**

1. Open the playground
2. Click Export > Copy as Markdown Issue
3. Scroll up or down in the modal's textarea

Brave Version 1.20.110 Chromium: 88.0.4324.192 (Official Build) (x86_64)

**Comment by orta** [comment]
Wild, maybe this is one of those "fast on the Mac" things, I'm open to dropping it and darkening the BG more

**Comment by JoshuaKGoldberg** [comment]
But Orta... I'm on a Mac! 😭

Not an M1 though, maybe that's it...

**Comment by orta** [comment]
Sounds like it's time for an upgrade ;)
