### ISSUE TITLE
Docs: Wikipedia-like preview popups

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#1656]
**Page URL:** Any documentation page

**Issue:** A link is context-less, can we provide useful context information on a mouse hover for a link which might be enough for someone to not need to click through?

![Screen Shot 2021-03-11 at 7 15 02 AM](https://user-images.githubusercontent.com/49038/110749837-87525a00-8239-11eb-85f1-dfdfa5e7179b.png)

We don't have images for pretty much all concepts we'd want to showcase, so it's closer to:

![Screen Shot 2021-03-11 at 7 16 13 AM](https://user-images.githubusercontent.com/49038/110749956-afda5400-8239-11eb-84c2-40ff8b357b06.png)

Something like this:

![Screen Shot 2021-03-11 at 7 31 29 AM](https://user-images.githubusercontent.com/49038/110751489-d39e9980-823b-11eb-8af2-2bbc75203368.png)

**Recommended Fix:** 

Take the metaphors used on wikipedia and reuse those.

Today, I can think of three different sources of information I think we could/should pull:

 - TSConfig settings info
 - Documentation pages
 - MDN Links

I think TSConfig info is probably the easiest to get started with, as it already is a well formed json dump in the codebase: `packages/tsconfig-reference/output/en-summary.json`.

**Implementation Notes:** 

For the TSConfig data. This data needs to be looked up at runtime, so we probably need to have the JSON dump  exposed in some format as a faux API (aka a JSON file, or a [JSONP](https://stackoverflow.com/questions/2067472/what-is-jsonp-and-why-was-it-created) script file. 

Then in `documentation.tsx` we need to register hovers on `a` links in an side effect which checks if the link is to /tsconfig/#flag - it pulls out the flag, checks if that's in the API, if so, wait to be sure the mouse is still hovering on the same element after ~0.5s then show the popover

I don't think we _need_ the hover when you tab through anchors, but it's probably a nice to have.

**Comment by orta** [comment]
### MDN implementation ideas

I think we'll need a build step in the `documentation` workspace, which first extracts a list of all developer.mozilla.org URLs which the markdown documentation references. From that list, we use a cloned copy of the https://github.com/mdn/data/ repo and look up each file by their url (it's in their yml)

E.g. [packages/documentation/copy/en/handbook-v2/Classes.md](https://github.com/microsoft/TypeScript-website/blob/1825553716443b481eb8dec3014e133041ddd299/packages/documentation/copy/en/handbook-v2/Classes.md#L123):

```
<blockquote class='bg-reading'>
   <p>Background Reading:<br />
   <a href='https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor'>Constructor (MDN)</a><br/>
   </p>
</blockquote>
```

Would pull out `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor` which we can find as [`content/files/en-us/web/javascript/reference/classes/constructor/index.md`](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/classes/constructor/index.md) because it has:

```
---
title: constructor
slug: Web/JavaScript/Reference/Classes/constructor
tags:
  - Classes
  - ECMAScript 2015
  - JavaScript
  - Language feature
browser-compat: javascript.classes.constructor
---
```

which matches the `slug`. 

### Markdown Summary

This is chunky, IMO it could be its own npm library. I could not find something like this already, so it's new grounds.

I had a think about an ideal summary looks like for a markdown document earlier. I think a good mix to have a character count of say 280 chars and an AST aware markdown trimmer. Look at this AST: https://astexplorer.net/#/gist/99935ecab8d55c6df79240583c7a2e62/f6a3aa27b9ec1a4993076a7bdd1e860b9d5fec0a

It would count the characters in each AST node ( first Heading, Paragraph, Break, Code, List ) until it either hit 280 characters or 5 root AST nodes, and anything after that would be dropped from the markdown document and that is then rendered.

So,

```md
### A longish title

It would count the characters in each AST node ( first Heading, Paragraph, Break, Code, List ) until it either hit 280 characters or 5 root AST nodes, and anything after that would be dropped from the markdown document and that is then rendered. (lets call this like 300 chars)

some more
```

would only render the first 2 nodes because the character limit Is hit. I think we should keep the full node (maybe unless it hits 450 chars at which point we add '...'?)

```md
### A title


   some code


Sure

OK

Yep

Not this though
```

Would render everything but `Not this though` (because that's 6 AST nodes) 

(For the MDN docs we'd need to drop all `{{ }}` ahead of time too)

**Comment by jarlin8** [comment]
https://myst.tools/docs/mystjs/syntax-overview 

this site achieved ,![](https://testingcf.jsdelivr.net/gh/jarlin8/OSS@main/backup/1673248360457Snipaste_2023-01-09_15-12-00.jpg)
