### ISSUE TITLE
Docs: Type Manipulation / Mapped Types / Further Exploration / Twoslash not enabled (handbook v2)

### ISSUE THREAD

**Issue by masonlouchart** [microsoft/TypeScript-Website#1661]
**Page URL:** https://www.typescriptlang.org/docs/handbook/2/mapped-types.html#further-exploration

**Issue:**

On the last paragraph the code sample is not interactive. I guess the "Twoslash" thing is not enabled.

![TypeScript_Docs_Mapped_types_further-exploration](https://user-images.githubusercontent.com/2325091/110771382-b88f5200-825a-11eb-841e-dfe82027b0fe.gif)

**Recommended Fix:**

Enable Twoslash for the code sample.

**Comment by orta** [comment]
You're right! Thanks

**Comment by masonlouchart** [comment]
Oh, so easy?!
I was going to take a look at it tonight 😄

**Comment by orta** [comment]
Hah, yeah, sorry!
