### ISSUE TITLE
Docs: Classes / Constructors / Reading recommendations hidden by codeblocks (handbook v2)

### ISSUE THREAD

**Issue by masonlouchart** [microsoft/TypeScript-Website#1663]
**Page URL:** https://www.typescriptlang.org/docs/handbook/2/classes.html#constructors

**Issue:**

<img width="1363" alt="Capture d’écran 2021-03-11 à 17 29 36" src="https://user-images.githubusercontent.com/2325091/110820882-cf03d080-828f-11eb-9356-983d69166189.png">

**Comment by masonlouchart** [comment]
Lot of reading recommendations are hidden by code blocks on this page. Might be the same on other pages.

**Comment by orta** [comment]
That's a shame, I think the answer might be to either move the background reading div to align with the body text, or to add something like a `clear: right` to the `pre`s
