### ISSUE TITLE
Docs: href to 'Compiler Options' in project-config/tsconfig.json.md

### ISSUE THREAD

**Issue by jihoon-seo** [microsoft/TypeScript-Website#1666]
**Page URL:** 
- https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/project-config/tsconfig.json.md#details
- https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Issue:** 
href to 'Compiler Options' is `/tsconfig`. (`[Compiler Options](/tsconfig)`)

**Recommended Fix:** 
`[Compiler Options](/docs/handbook/compiler-options.html)`

**Comment by orta** [comment]
Good spot, but that link is correct /tsconfig is a better reference than `https://www.typescriptlang.org/docs/handbook/compiler-options.html` - I didn't want to break URLs to that page though, if you look it's very focused on the CLI experience and not on the config options

**Comment by jihoon-seo** [comment]
Okay, I see!

P.S.
Then, my another suggestion is:
`[Compiler Options](/tsconfig#compiler-options)`
(Which will lead to https://www.typescriptlang.org/tsconfig#compiler-options)
