### ISSUE TITLE
Anchor symbol is too high relative to header

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript-Website#1670]
**Improvement Idea:** 

![image](https://user-images.githubusercontent.com/6685088/111007153-067f8500-8343-11eb-994d-8e8353ba54b5.png)

**Why:** It looks weird when it's too high

**Alternative ideas:** 🤷‍♂️

**Comment by hahmadia** [comment]
Hi! I've addressed this issue in my PR. Feel free to take a look and give feedback. Thanks!
