### ISSUE TITLE
Docs: Special Type : any

### ISSUE THREAD

**Issue by huseyn** [microsoft/TypeScript-Website#1683]
```
let obj: any = { x: 0 };
// None of these lines of code are errors
obj.foo();
obj();
obj.bar = 100;
obj = "hello";
const n: number = obj;
```

In above example was mentioned that 'None of these lines of code are errors' but obj.foo() and obj() throw an error. 

Page url: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html

**Comment by orta** [comment]
Maybe we need to be more explicit in this code sample, not raising compiler errors here is the feature we're talking about
