### ISSUE TITLE
Playground: Improve SEO when searching for `tsplayground`

### ISSUE THREAD

**Issue by andreiho** [microsoft/TypeScript-Website#1689]
![Screenshot 2021-03-18 at 09 28 20](https://user-images.githubusercontent.com/9000674/111598153-327d8900-87cf-11eb-8a74-8d2ed2e7361f.png)

**Repro:**

Just google `tsplayground`

**Expected behavior:**

TS Playground on top 🚀 

**Actual behavior:**

Well... let's just say my wife wasn't impressed when I blindly clicked on the first result.

**Comment by hahmadia** [comment]
This made me LOL literally 🤣

**Comment by orta** [comment]
I changed this earlier to be "TS Playground"  https://github.com/microsoft/TypeScript-Website/commit/4037de6655c2cd2dd158a6c8cefeaf68ef4d6829 to do some work to this

I don't want to change it any further (TSPlayground would get counted as one word and not two) and the Playground is not called _tsplayground_ the website tsplayground _is_ though so it really should show up in your unsafe results as the first link I'm afraid. 

I'm open to SEO improvements which don't rename the playground but I'm not sure there's much can be done

**Comment by andreiho** [comment]
@orta Would it make sense to change the URL to https://typescriptlang.org/tsplayground or https://typescriptlang.org/ts-playground?

If that's how people refer to it, then why not add it to the URL? That's ought to improve SEO. Some of the kinky search results above yours seem to match because it's part of the URL. Can't argue with the first result though, it's their domain.

**Comment by orta** [comment]
I'd be OK with a page there that exists only to redirect to the real URL of `/play`, I'm not sure if it'd get above the other site given that that is their domain and site-name but that wouldn't break URLs nor be a maintainance burden for the site

**Comment by maddie927** [comment]
Yeah, TypeScript is by far a minority user of the TS abbreviation and will never be the top result for `TS-[any word that isn't explicitly programming, but _especially_ playground]`. It should really just get renamed..

- typescript.org/play with "Try TypeScript"
- typescript.org/try with "Try TypeScript"
- /live maybe?
- /editor ?
- etc
