### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by huheng233** [microsoft/TypeScript-Website#1691]
**Page URL:** 
https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#properties-are-inferred-from-assignments-in-class-bodies
**Issue:** 
function Outer() {
  this.y = 2;
}

Outer.Inner = function () {
  this.yy = 2;
};

Outer.innter();
**Recommended Fix:** 
Outer.innter();   --should be-->   Outer.Inner();

**Comment by hahmadia** [comment]
Nice catch! I've created https://github.com/microsoft/TypeScript-Website/pull/1692 to fix this. Thanks!
