### ISSUE TITLE
Playground: Suggestion: Strip top-level export keywords when emitting JS

### ISSUE THREAD

**Issue by ada-waffles** [microsoft/TypeScript-Website#1693]
Stripping top-level `export` keywords from emitted JS in the Playground would make it easier to paste and work with code from a real file (which likely has one or more exports).

![image](https://user-images.githubusercontent.com/7603251/111658292-95c4e680-87e2-11eb-901f-5fe2a8143289.png)

![image](https://user-images.githubusercontent.com/7603251/111658330-a07f7b80-87e2-11eb-80b7-abddb49b24e9.png)

![image](https://user-images.githubusercontent.com/7603251/111658355-a83f2000-87e2-11eb-96dd-53ee935681a3.png)

**Repro:**

Type any code into the Playground that `export`s anything from the top level (not within a `namespace`) and click Run

**Expected behavior:**

The code should run ignoring the `export`s

**Actual behavior:**

The code chokes on the `export`s and will not run until they are removed

**Comment by ada-waffles** [comment]
Just going to add here: In discussion it's also been noted that this can be solved by wrapping all the playground code in a `namespace`

**Comment by hahmadia** [comment]
Hey! I've created the above mentioned PR which solves this issue. Will be awaiting review. Thanks
