### ISSUE TITLE
Docs: Index Signatures Self-Links

### ISSUE THREAD

**Issue by wffurr** [microsoft/TypeScript-Website#1695]
**Page URL:**

https://www.typescriptlang.org/docs/handbook/2/classes.html#index-signatures

**Issue:** 

The link in the phrase "these work the same as [Index Signatures](https://www.typescriptlang.org/docs/handbook/2/classes.html#index-signatures) for other object types" just links back to this same section.  It implies there's more documentation on index signatures to be found elsewhere, but I can't find it anywhere else in the handbook.  Perhaps there's a missing section in the "[Object Types](https://www.typescriptlang.org/docs/handbook/2/objects.html)" page for object types with index signatures?

**Recommended Fix:**

Remove the link and expand the documentation on index signatures on the class page or add a section to the object types page with expanded documentation on index signatures and link to that.

I would submit a fix myself, but I'm not sure what the right fix is here.

**Comment by wffurr** [comment]
Ah, I see there's a whole section in the "Object Types" page that's commented out, presumably to-be-written:

```
<!-- ## Other Kinds of Object Members

Most of the declarations in object types:

### Method Syntax

### Call Signatures

### Construct Signatures

### Index Signatures -->
```

which is where the class index signatures page would presumably link.

**Comment by adjenks** [comment]
When I go to the docs here: https://www.typescriptlang.org/docs/handbook/advanced-types.html#index-types-and-index-signatures
it says the page is depreciated and tells me to go to here:
typescriptlang.org/docs/handbook/2/indexed-access-types.html and the new page does not use the term "index signature" anywhere.
When I search the docs from the search menu I cannot find a page about index signatures.

I suppose this is a similar but unrelated issue...

**Comment by adjenks** [comment]
Oh, so based on your comment above, it's just not done yet, so I should just refer to the old docs.... I guess it just shouldn't tell me to go to the new page if there's no new version to look at.
