### ISSUE TITLE
Listing of community-contributed starter/boilerplate projects?

### ISSUE THREAD

**Issue by bitjson** [microsoft/TypeScript-Website#17]
After struggling to configure a Typescript project which exports both a CommonJS and ES6 module (for tree-shaking with Rollup), I spent some time putting together a [typescript-starter](https://github.com/bitjson/typescript-starter) project with source-mapped test coverage, typedoc documentation generation, a performant watch task, etc.

Looking around, there are dozens of outdated and neglected starters/boilerplates available, but none seem to have gained enough traction to continue being updated when newer versions of Typescript or improved tooling becomes available. (E.g. many are still using [`tsd`](https://github.com/DefinitelyTyped/tsd), which has been deprecated.)

Electron does really well (IMO) with promoting [community-maintained tools and projects](http://electron.atom.io/community/#boilerplates) – have you all considered providing something similar on the Typescript website or `README.md`? It might really help the ecosystem to coalesce around and maintain a few strong options.

**Comment by orta** [comment]
This is in 👍
