### ISSUE TITLE
Smart indentation not configured in nightly playgrounds

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#170]
```ts
class C {/**/
}
```

`/**/` is the cursor - hit enter

**Expected**:

```ts
class C {
    /**/
}
```

**Actual**:

```ts
class C {
/**/
}
```

**Comment by DanielRosenwasser** [comment]
Note specifically this is an issue with the nightlies, not the stable published version.

**Comment by orta** [comment]
This is fixed, it was due to how the playground's text got set up on launch
