### ISSUE TITLE
Call Signature Codeexample

### ISSUE THREAD

**Issue by AlteredStorm** [microsoft/TypeScript-Website#1706]
```
type DescribableFunction = {
  description: string;
  (someArg: number): boolean;
};
function doSomething(fn: DescribableFunction) {
  console.log(fn.description + " returned " + fn(6));
}
```

I would like to have an example to declare a variable on this topic. The current specification is very confusing.

**Comment by orta** [comment]
Can you explain your issue further? The type acts like a type does anywhere, making it callable doesn't change whether you can use it as a variable like `const a:DescribableFunction = ...`

**Comment by gitmibrahim** [comment]
> Can you explain your issue further? The type acts like a type does anywhere, making it callable doesn't change whether you can use it as a variable like `const a:DescribableFunction = ...`

I have the same issue, could anyone replace those `const a:DescribableFunction = ...` with a full example of a variable declaration?
