### ISSUE TITLE
Docs: More on functions - Declaring this in a Function - misleading example

### ISSUE THREAD

**Issue by sashaaKr** [microsoft/TypeScript-Website#1709]
**Page URL:** https://www.typescriptlang.org/docs/handbook/2/functions.html#declaring-this-in-a-function

**Issue:** 
In example there is `isAdmin` property that used in callback function, but `user` does not have `isAdmin` property - it called `admin`.

**Recommended Fix:**
Change `admin` to `isAdmin` in user declaration:
```js
const user = {
  id: 123,

  isAdmin: false,
  becomeAdmin: function () {
    this.isAdmin = true;
  },
};
```

If it is valid issue, I will more than happy to fix it, let me know.

**Comment by orta** [comment]
Great catch, that sample is just wrong I think want this:

```
interface User {
  id: number;
  admin: boolean;
}
declare const getDB: () => DB;
interface DB {
  filterUsers(filter: (this: User) => boolean): User[];
}

// ---cut---
const db = getDB();
const admins = db.filterUsers(function() {
  return this.admin
});
```

**Comment by sashaaKr** [comment]
@orta `declare` was not explained in handbook up till this point, so maybe it will be better to use syntax that is more familiar for newcomers?

**Comment by sashaaKr** [comment]
@orta WDYS?

**Comment by orta** [comment]
Declare isn't in the code sample because it is cut - so it's totally fine to be in there

**Comment by orta** [comment]
I've pushed a commit to an on-going PR fixing this

**Comment by rizalalfandi123** [comment]
@orta thank you. your description is very helpful
