### ISSUE TITLE
Docs: i8n vs. i18n

### ISSUE THREAD

**Issue by jihoon-seo** [microsoft/TypeScript-Website#1714]
**Page URL:** 
- https://github.com/microsoft/TypeScript-Website#docs
- https://github.com/microsoft/TypeScript-Website/blob/v2/docs/How%20i8n%20Works%20For%20Site%20Copy.md

**Issue:** 
The pages say "i8n", but it seems that "i18n" is right.

**Recommended Fix:** 
Find & replace "i8n" with "i18n" repo-wide.

**Comment by orta** [comment]
Makes sense 👍🏻
