### ISSUE TITLE
Docs: Reference to `mixins` page leads to nowhere

### ISSUE THREAD

**Issue by navneetkarnani** [microsoft/TypeScript-Website#1716]
**Page URL:** https://www.typescriptlang.org/docs/handbook/2/generics.html

**Issue:** Reference to `mixins` at the bottom of this page, refers to a url that is not published, or was moved.

**Recommended Fix:** Either publish the page on mixins (preferred), or remove the reference to it.

**Comment by orta** [comment]
Ah it's just a bad url, needs the `/2/` removing 👍🏻

**Comment by jihoon-seo** [comment]
This issue seems okay to close, since #1713 resolves this issue.

**Comment by orta** [comment]
Thanks @jihoon-seo
