### ISSUE TITLE
Docs:  tsconfig#exclude question

### ISSUE THREAD

**Issue by barinbritva** [microsoft/TypeScript-Website#1717]
Hi there!

**Page URL:** https://www.typescriptlang.org/tsconfig#exclude

**Issue:** It says exclude affects only files specified in include. But also it says by default it contains ["node_modules", "bower_components", "jspm_packages"] and outDir. It seems that is not a part of exclude option, but a part of TS logic? I saw a lot of config files with something like: exclude: ["node_modules", "something-else"]. Is it correct? I mean, if "node_modules" really specified in exclude by default, we need to restore default value when add our own value. But if exclude really affects only include directive, it's totally wrong to specify node_modules inside exclude option.

**Recommended Fix:** It would be great to make clear if node_modules and other package managers roots related with exclude option or not.

**Comment by orta** [comment]
These are just defensive defaults as a protection against people being overly aggressive with their `include` - I don't think there's any special casing in the compiler here, people are likely just copying and pasting without looking at what it does (or they are including node_modules in their `includes`). 

I'm open to ideas on wording changes though

**Comment by barinbritva** [comment]
I'll be back with my thoughts
