### ISSUE TITLE
compiler-options.html cuts off text

### ISSUE THREAD

**Issue by activescott** [microsoft/TypeScript-Website#172]
The right edge of http://www.typescriptlang.org/v2/docs/handbook/compiler-options.html is cut off. Annotated screenshot:
<img width="1030" alt="Screen Shot 2020-01-04 at 1 44 37 PM" src="https://user-images.githubusercontent.com/213716/71772006-7f41b080-2ef8-11ea-91a9-7b3166fa44a0.png">

**Comment by edzis** [comment]
Same here:
<img width="1552" alt="Screenshot 2020-03-07 at 14 40 24" src="https://user-images.githubusercontent.com/163636/76153521-eb1fd100-6081-11ea-914b-6755345eb043.png">

**Comment by brrusselburg** [comment]
Is this page gone/changed? `The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`
