### ISSUE TITLE
Docs: No previous/next links at the bottom of 'types from types' section

### ISSUE THREAD

**Issue by mfulton26** [microsoft/TypeScript-Website#1723]
**Page URL:** 
https://www.typescriptlang.org/docs/handbook/2/types-from-types.html

**Issue:** 
No previous/next links at the bottom of the page unlike https://www.typescriptlang.org/docs/handbook/2/objects.html which correctly links to the above URL for its next link. The first page I see after this URL with a next link in it in the Handbook is https://www.typescriptlang.org/docs/handbook/2/classes.html and it doesn't link to its previous page either.

**Recommended Fix:** 
I see navigation data in the codebase for this but I'm guessing it is either declared wrong or not being used fully to build these previous/next links for pages in the handbook that are grouped under a folder.

https://github.com/microsoft/TypeScript-Website/blob/25d856fd80d853734f6f076a37f94d23e0ade094/packages/typescriptlang-org/src/lib/documentationNavigation.ts

**Comment by orta** [comment]
Yeah, likely these two functions aren't accounting for jumping in and out of the types from types section

https://github.com/microsoft/TypeScript-Website/blob/25d856fd80d853734f6f076a37f94d23e0ade094/packages/typescriptlang-org/src/lib/documentationNavigation.ts#L4947

**Comment by mfulton26** [comment]
#1762 certainly improved things but there are still some issues. Should we reopen this issue or create one or multiple new issues for the following?

1. [Creating Types from Types](https://www.typescriptlang.org/docs/handbook/2/types-from-types.html) is missing a "Previous" link to [Object Types](https://www.typescriptlang.org/docs/handbook/2/objects.html).
2. [Template Literal Types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) is missing a "Next" link to [Classes](https://www.typescriptlang.org/docs/handbook/2/classes.html).
3. The ".d.ts Templates" pages ([Modules .d.ts](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html) through [Global: Modifying Module](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html)) are missing both "Previous" and "Next" links.
4. [Library Structures](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html) correctly links "Next" to [Modules .d.ts](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html) but [Do's and Don'ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html) is missing a "Previous" link to [Global: Modifying Module](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html).

**Comment by mfulton26** [comment]
I've created a separate issue for each one.
