### ISSUE TITLE
Twoslash: don't crash when an imported file is missing

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript-Website#1732]
Instead, let TS error as it would in a real environment. I was hoping to demonstrate what error message you get when trying to import from somewhere that has no declaration file, but it won’t let me get that far: https://www.typescriptlang.org/dev/bug-workbench/?isolatedModules=false#code/PTAEAEGcAsHsHcCiBbAlgFwFynQJwK4CmAUCBAIYA2lCAUpNgGZWQmljiOqWEB25yQtl6wAJoQD6yMfh6RgjWLGCpe4gB4A6UZvSRi4gMaVyuQqEOxekdKEWxs5XgE8A3MULqADrFy2AvHZK7uwQXDz8gsJiktKisoTy9sCw6NCEuJoAVvpxCZqePn6QoIEA3gC+IWSc3HwCQqCqGrr6qMhFtpV2uLDIoABEyanpuAPuQA

**Comment by orta** [comment]
Interesting, yeah, this makes sense 👍🏻
