### ISSUE TITLE
noImplicitOverride missing in playground tsconfig options

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript-Website#1733]
when v4.3.0-dev.20210401 is selected, the new flag is not available in tsconfig

sorry if this is the wrong spot to raise playground issues

![image](https://user-images.githubusercontent.com/57028336/113387816-644a3e80-93d0-11eb-991e-947f9cecd185.png)

**Comment by DetachHead** [comment]
@andrewbranch thanks. is that functionality specific to the playground? i tried changing a compiler flag using a comment like that in one of my projects but it didn't work

**Comment by andrewbranch** [comment]
Yes, sorry, that's just for the playground.

**Comment by orta** [comment]
The next deploy will have the dropdown auto-generated from the version of TypeScript, so a beta build will include beta flags - see https://github.com/microsoft/TypeScript-Website/pull/1735

**Comment by orta** [comment]
This shipped
