### ISSUE TITLE
[Playground] Allow to set moduleResolution

### ISSUE THREAD

**Issue by FredyC** [microsoft/TypeScript-Website#174]
The `moduleResolution` is set to `classic` by default if ES2015+ is being targetted. Most of the code using modules expect `node` resolution.

Trying to reproduce the issue that depends on imports causes a different outcome, basically acts like importing untyped code.

So it's either about allowing to set this configuration or better way as suggested by @DanielRosenwasser at https://github.com/microsoft/TypeScript/issues/35876#issuecomment-572475810 to assume that most people will use `node`.

Related #21, https://github.com/microsoft/TypeScript/issues/11434

**Comment by orta** [comment]
Good points! This will be in the v2 playground now with https://github.com/microsoft/TypeScript-Website/pull/176/commits/a0dee6656a340284ca0d659430e22bdf09980dee on the next v2 deploy when #176  is merged (if you want to try porting it to the current playground [change this file](https://github.com/orta/typescript-play/blob/master/public/main-3.js))

**Comment by orta** [comment]
This is in 
![Screen Shot 2020-02-14 at 9 09 44 AM](https://user-images.githubusercontent.com/49038/74538232-c1074300-4f09-11ea-8da3-3779f2b90331.png)

**Comment by tjx666** [comment]
@orta module option is not equals to moduleResolution

I can use module: ESNext, but moduleResolution: nodenext:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/41773861/231576693-623aeb9c-1b8d-4805-8cbe-d6c7f9b00c58.png">
