### ISSUE TITLE
Playground: Failed to load plugin(s)

### ISSUE THREAD

**Issue by Quramy** [microsoft/TypeScript-Website#1749]
Playground fails to load plugins

![スクリーンショット 2021-04-09 20 22 15](https://user-images.githubusercontent.com/1262998/114172977-5d43a300-9971-11eb-9fe6-d63920bb4b79.png)

**Repro:**

- Open Playground and select "Plugins" tab.
- Check some plugin and reload browser.

It seems that Playground creates invalid URL for `unpkg.com` :

- invalid: `https://unpkg.com//ts-playground-plugin-prettier@latest/dist/index.js`
- valid: `https://unpkg.com/ts-playground-plugin-prettier@latest/dist/index.js`

**Expected behavior:**

**Actual behavior:**

**Comment by orta** [comment]
Good digging, they must have tightened the routing on unpkg 👍🏻

**Comment by Quramy** [comment]
Thanks!
