### ISSUE TITLE
Playground: staging website with prerelease TypeScript breaks ctrl+arrow keys on Firefox

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#1763]
If I try going to

https://www.staging-typescript.org/play?ts=4.3.0-pr-43526-11&ssl=14&ssc=1&pln=15&pc=1#code/JYOwLgpgTgZghgYwgAgGIHt3IN4FgBQyRyAnnACblwBcyAzmFKAOYDcBxyARhVbSAFcAtl2jtCxANoBlEiPQAbAHTBIUOGHRQAugAoAlLQCSauFwUQAPAyYhmAPgIBfAgRgCQCMMHQhkMTEsAFWQIAA9IEHI6NEx7AxxXfBd8AlA1eCRkACE4KGDQiIgomIx0e0TU5KSLMGQw2lz87FJeGnpGFmQnZAAyHG42-mFRKAAabnVKdsERaAmZOS5FFVNNHQNaOBASbvsgA

and either use that build, or a beta, or a nightly, <kbd>Ctrl</kbd>+<kbd>⬅</kbd> and <kbd>Ctrl</kbd>+<kbd>➡</kbd>. Using <kbd>Ctrl</kbd>+<kbd>⬆</kbd> and <kbd>Ctrl</kbd>+<kbd>⬇</kbd> only scrolls the buffer.

**Comment by DanielRosenwasser** [comment]
(Could this potentially be an issue with upstream monaco?)

**Comment by orta** [comment]
It's likely an upstream issue, we don't try to touch any of Monaco's keyboard handling - is there an older build of TS where this _does_ work?

**Comment by Gerrit0** [comment]
This has now shipped... If I set the TS version to 2.4.3 I get semi-reasonable results. CTRL + Arrow still does really weird things, but it's what it used to do.

**Comment by orta** [comment]
I don't see any issues in [monaco-editor](https://github.com/microsoft/monaco-editor/issues?q=is%3Aissue+is%3Aopen+ctrl+) on the topic, could be the Mac shortcuts accidentally got applied to windows (ctrl + arrows are NOOPs on Mac)

**Comment by Juraj-Masiar** [comment]
I use Windows 10 and none of my Firefox browsers (including ESR) can now use "Ctrl + left/right" to move cursor in the editor. This includes "Ctrl + Shift + left/right" to select text.
It works in Chrome.

**Comment by DetachHead** [comment]
this seems to have been fixed upstream (or it was never an upstream issue), as it does not occur on the monaco demo website: https://microsoft.github.io/monaco-editor/index.html

**Comment by DanKaplanSES** [comment]
> this seems to have been fixed upstream (or it was never an upstream issue), as it does not occur on the monaco demo website: https://microsoft.github.io/monaco-editor/index.html

That link doesn't exist anymore. An embedded demo can be found here: https://microsoft.github.io/monaco-editor/ On that demo, `ctrl+left/right` works the way the OP (and myself) want. I'm not sure if the fix requires getting the latest monaco version or a directly changing something in this project. 

As of today, https://www.staging-typescript.org/play and https://www.typescriptlang.org/play have this issue.
