### ISSUE TITLE
Playground: Highlighting text changes width

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript-Website#1766]
![image](https://user-images.githubusercontent.com/19329837/115637714-0d989c00-a2ce-11eb-8f48-3160005a51dc.png)

**Repro:**

Type code in playground, highlight code

**Expected behavior:**

Width before highlighting is the same

**Actual behavior:**

Spaces are slightly smaller, resulting in narrower lines

**Comment by orta** [comment]
Interesting, I wonder if this came in during the custom fonts
