### ISSUE TITLE
Playground doesn't load async iterable definitions

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript-Website#177]
Playground says `Cannot find global type 'AsyncIterableIterator'.(2318)` with ESNext.

http://www.typescriptlang.org/play/index.html?target=99&ts=3.8.0-dev.20200109#code/IYZwngdgxgBAZgV2gFwJYHsICp4AoCUMA3gFAC+QA

**Comment by orta** [comment]
Probably relates to #7 - I built a bunch of the infra for this to be able to happen in the new playground

**Comment by bradzacher** [comment]
Duplicate of #15?

**Comment by orta** [comment]
Fixed in modern playground builds:

https://www.typescriptlang.org/play?target=99&ts=4.2.3#code/IYZwngdgxgBAZgV2gFwJYHsICp4AoCUMA3gFAzkwkC+QA
