### ISSUE TITLE
Docs: Confusing header ordering on TSConfig reference

### ISSUE THREAD

**Issue by davenquinn** [microsoft/TypeScript-Website#1778]
**Page URL:** https://www.typescriptlang.org/tsconfig
**Issue:**
As a (relative) newcomer to Typescript development and project setup, I often find myself referring to the `tsconfig.json` documentation. The documentation is complete and reasonably laid out, with one exception: it is difficult to quickly tell which options go in the "root" section of the JSON vs. `compilerOptions`.

The second paragraph discusses the distinction between these two types of options, but the index directly below this makes no reference to the distinction, making it difficult to quickly discern which section things should go in (although the narrative text mentions that most options fall into the `compilerOptions` category).

Scrolling past this section and reading through the file makes it apparent that the "root fields" consist entirely of the "File inclusion" set of fields, and many other options fall into the `compilerOptions` category. I haven't even read through far enough to figure out which ones are `watchOptions`. Moreover, if you use the index to skip directly to a specific option, you completely miss this section.

The current layout "buries the lede" a bit, and prioritizes interaction by people reading the file as a narrative object, rather than the more common targeted search mode of interaction. It is also somewhat unfriendly to newcomers.

**Recommended Fix:** 
The clearest fix would be to make the Index headers for option categories into second-tier headers, within the **Root options**, **Compiler options**, and **Watch options** sections. This would make it immediately obvious which section each option falls into for casual browsing.

In parallel, it would also be helpful to invert the header hierarchy in the main text somewhat: Root options, Compiler options, and Watch options should become top-level headers, and the individual categories beneath them should take on second-level header status.

It's possible that the "File inclusion" header should be removed entirely and replaced with a statement to the effect of, "TSConfig root-level options deal primarily with the inclusion and exclusion of files". This is a bit more helpful in describing why things are categorized the way they are.

Based on my mild confusion over several visits to the page, I think this fix would help significantly with accessibility and onboarding.

**Comment by orta** [comment]
This has a WIP branch, I've just not had time to wrap it up https://github.com/microsoft/TypeScript-Website/tree/full_tsconfig as  I've been on definitely typed duty

**Comment by orta** [comment]
This has just shipped, I'm not 100% I covered everything - so I'll leave this open and I'm happy to take some more feedback. https://www.typescriptlang.org/tsconfig

**Comment by davenquinn** [comment]
This is much improved! I like the new layout of the index. Very clear.

I'll add a few small suggestions, just for kicks:

<img width="218" alt="image" src="https://user-images.githubusercontent.com/1537910/117090037-d50caf80-ad1c-11eb-938c-5efcb8b8a972.png">

The index repeats the "Compiler options" header twice, which is a bit confusing. I think that the top level header should read **Options index** or similar. "Top level" -> "Top level options" would maintain parallelism. Also, I like the something similar to the layout of the headers below better than just having the monospaced text:
<img width="155" alt="image" src="https://user-images.githubusercontent.com/1537910/117090128-21f08600-ad1d-11eb-830e-9c6ae1d9106c.png">

With the changes and clarified index, you might be able to wholly remove or significantly shoroten the initially hidden invocation text.

Lastly, I'd consider wrapping the index in a white box like the rest of the sections.
