### ISSUE TITLE
Idea: Images are not shown in `/community` page

### ISSUE THREAD

**Issue by jihoon-seo** [microsoft/TypeScript-Website#1779]
**Improvement Idea:**

Fix images that are not shown in `/community` page.
https://www.typescriptlang.org/community
![image](https://user-images.githubusercontent.com/46767780/116185780-3fda4b80-a75d-11eb-9223-db0d0dc28ed9.png)

**Why:**

Because images are not shown in `/community` page

**Alternative ideas:**

**Comment by jihoon-seo** [comment]
When you view the page source code of https://www.typescriptlang.org/community ,
you can see that

```HTML
<img src="[object Module]" class="icon img-square" alt="logo of Hamburg TypeScript"/>
```

whose `src` is not proper.

**Comment by orta** [comment]
Ah, perfect, thanks
