### ISSUE TITLE
V2 tsconfig docs not showing default for `useDefineForClassFields`

### ISSUE THREAD

**Issue by tchetwin** [microsoft/TypeScript-Website#179]
Most of the boolean flags I'm looking at have a default value specified. (I haven't gone through exhaustively!)

The old compiler options lists it as `false` [here](https://www.typescriptlang.org/docs/handbook/compiler-options.html)

I don't see it in the new docs [here](http://www.typescriptlang.org/v2/en/tsconfig#useDefineForClassFields)

I suspect this may be where that section comes from:
https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/useDefineForClassFields.md

**Comment by orta** [comment]
Ah yeah! I probably wasn't using 3.7 when I started the list - I'm about to look into updating this site to the 3.8 beta and will make some automation to note what flags are missing! 

Thanks (and yeah, I've not documented it yet)
