### ISSUE TITLE
Replacement page for old `Advanced Types` makes no mention of of `in` operator usage

### ISSUE THREAD

**Issue by msbit** [microsoft/TypeScript-Website#1797]
**Page URL:**

https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-the-in-operator
 =>
https://www.typescriptlang.org/docs/handbook/2/types-from-types.html

**Issue:**

This URL:

https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-the-in-operator

indicates deprecation, and:

https://www.typescriptlang.org/docs/handbook/2/types-from-types.html

is referred to as the new page.

However, it doesn't mention use of the `in` operator for type narrowing.

It seems like:

https://www.typescriptlang.org/docs/handbook/2/narrowing.html

might be the better page to indicate as a replacement, but this doesn't mention it either.

**Recommended Fix:**

* Determine which page should have the information (one of the above or maybe one entirely separate)
* Include the content in that page
* Update the mentioned replacement page on the deprecated page (if needed)

**Comment by orta** [comment]
This should probably live in the narrowing section, I agree
