### ISSUE TITLE
Docs: Handbook: More on Functions doesn't show "this" used as a parameter

### ISSUE THREAD

**Issue by panathea** [microsoft/TypeScript-Website#1804]
**Page URL:** https://www.typescriptlang.org/docs/handbook/2/functions.html#declaring-this-in-a-function

**Issue:**

It seems like the preamble implies that we're about to see `this` used as a parameter in TypeScript to define its type, but then the code example doesn't do so.

I was initially confused by it, until I found out that you can dig in and get an explanation by:

1. Clicking "Try it" and getting the full code example (with the Interface that defines the type)
2. Hovering over the function to see the type definition:
     ![image](https://user-images.githubusercontent.com/5840970/117058981-4d5b7c80-aced-11eb-86de-1b89e40130af.png)

**Recommended Fix:**

Maybe expand to code example to provide the Interface definition, or provide an inline `(this: User)`.

**Comment by orta** [comment]
Great point, fixed in staging and will be deployed by next week at the latest 👍🏻
