### ISSUE TITLE
Docs: Wrong flex layout in titles with code elements

### ISSUE THREAD

**Issue by springuper** [microsoft/TypeScript-Website#1810]
**Page URL:** 
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop

**Issue:** 
It's pretty clear: the long title having code elements is broken into serveral columns because the `.markdown h1, .markdown h2, .markdown h3` uses flex layout:
<img width="933" alt="Screen Shot 2021-05-06 at 1 01 00 PM" src="https://user-images.githubusercontent.com/687412/117244234-42c6f180-ae6b-11eb-86aa-9029141a9825.png">

**Recommended Fix:** 
Change the default gatsby global css.

**Comment by sohamsshah** [comment]
Hey I would like to work on this issue!
I am quite new in TS but I truly believe in TS Supremacy 🚀 
Excited to contribute to the org!
