### ISSUE TITLE
Idea: Author avatars should use `title` instead of (or in addition to) `alt`

### ISSUE THREAD

**Issue by craigkovatch** [microsoft/TypeScript-Website#1818]
**Improvement Idea:** Add the `title` attribute on the author bubbles in the "Contributors to this page" section, instead of (or in addition to) the current `alt` attribute.

**Why:** Currently only `alt` is present, which is available to someone using a screen reader or someone nosy like me inspecting the DOM, but not to someone mousing-over an avatar curious to know the authors' names.

![image](https://user-images.githubusercontent.com/10970257/117897806-637eb500-b278-11eb-86db-d1303b8b26ca.png)
^ no tooltips!

![image](https://user-images.githubusercontent.com/10970257/117897822-6b3e5980-b278-11eb-8809-5e2093f98af0.png)
How else would I know to thank @orta ? 😁

**Comment by orta** [comment]
hah, yeah, makes sense

**Comment by craigkovatch** [comment]
@orta friendly bump, does this need assignment? Hoping it would be a pretty simple code change somewhere

**Comment by orta** [comment]
Sure, it's OSS, you're welcome to do it

**Comment by craigkovatch** [comment]
Happy to! Could you point me at the right file(s)?

-Craig (mobile)
________________________________

**Comment by orta** [comment]
I'd recommend cloning the codebase and searching for "contributors to this page"
