### ISSUE TITLE
Idea: Persist cookie choices across pages

### ISSUE THREAD

**Issue by eps1lon** [microsoft/TypeScript-Website#1826]
**Improvement Idea:** Cookie choices should be persisted

**Why:** This is the only page I know of that constantly asks me about cookie choices. 
I don't think this is good UX. It seems like the page just does not want to accept that I deactive non-essential cookies. It wouldn't be a problem if "reject all" would be as streamlined as "accept all". But  right now it's another implementation of "we really don't want you to reject our cookies".

https://user-images.githubusercontent.com/12292047/118351252-2dcd1b00-b55b-11eb-95d0-497fd02bb61f.mp4

**Alternative ideas:**

Display a "reject all" next to "accept all". Though that would be a nice addition regardless of this issue.

**Comment by orta** [comment]
This might be the default behavior for the MS cookie stuff which we have to use, maybe it's setup wrong somehow

**Comment by eps1lon** [comment]
There's no longer any cookie consent dialog so this is no longer relevant.
