### ISSUE TITLE
Playground: Menu bar says v3.6.2, but menu says 3.6.3

### ISSUE THREAD

**Issue by taymonbeal** [microsoft/TypeScript-Website#1832]
![https://www.typescriptlang.org/play?ts=3.6.3](https://user-images.githubusercontent.com/1991427/118519552-39f5db80-b707-11eb-971f-09d5c5489d9b.png)

**Repro:**
https://www.typescriptlang.org/play?ts=3.6.3

**Expected behavior:**
Version number in the menu and in the menu bar should match.

**Actual behavior:**
They don't.

**Comment by orta** [comment]
Thanks for the issue - I took a look at this yesterday and left details in https://github.com/microsoft/TypeScript-Website/issues/1867#issuecomment-851562060
