### ISSUE TITLE
Docs: html examples in PDF and EPUB are not rendered correctly

### ISSUE THREAD

**Issue by elwin1234** [microsoft/TypeScript-Website#1845]
**Page URL:** https://www.typescriptlang.org/assets/typescript-handbook.pdf and https://www.typescriptlang.org/assets/typescript-handbook.epub

**Issue:** Current production `pdf` _and_ `epub` variants of documentation do not render the html examples correctly. See screenshot:

![html_examples_error_in_pdf](https://user-images.githubusercontent.com/3977962/119356307-92e4e700-bca6-11eb-9c98-dbd751e47706.png)

**Comment by csp-stu** [comment]
There's a copy of the handbook source here if anyone wants to try reading it in the meantime. I don't know how to build it into an epub or pdf though: 

Markdown source: https://github.com/microsoft/TypeScript-Website/tree/v2/packages/documentation/copy/en/handbook-v2

Build scripts: https://github.com/microsoft/TypeScript-Website/tree/v2/packages/handbook-epub

**Comment by orta** [comment]
Thanks! 

This is likely a side-effect of some of the consolidation of the compiler syntax highlighting changes last week

**Comment by csp-stu** [comment]
Until it's fixed I built a quick and dirty epub file using [pandoc](https://pandoc.org/). Download the source markdown files (link above) and replace all ts twoslash formatted code blocks to plain code blocks. Then run the command: 

```
pandoc -M title="TypeScript Handbook V2" -M author="https://github.com/microsoft/TypeScript-Website/issues/1845" -M language="en-us" --table-of-contents -o typescript-handbook.epub \
The\ Handbook.md \
Basics.md \
Everyday\ Types.md \
Narrowing.md \
More\ on\ Functions.md \
Object\ Types.md \
Type\ Manipulation/_Creating\ Types\ from\ Types.md \
Type\ Manipulation/Generics.md \
Type\ Manipulation/Typeof\ Type\ Operator.md \
Type\ Manipulation/Keyof\ Type\ Operator.md \
Type\ Manipulation/Indexed\ Access\ Types.md \
Type\ Manipulation/Conditional\ Types.md \
Type\ Manipulation/Mapped\ Types.md \
Type\ Manipulation/Template\ Literal\ Types.md \
Classes.md \
Modules.md \
Type\ Declarations.md \
Understanding\ Errors.md 
```

**Comment by orta** [comment]
There's a PR with the fix coming out, it'll probably be deployed within ~2 hours
