### ISSUE TITLE
Document how to override broken node_module types

### ISSUE THREAD

**Issue by richardscarrott** [microsoft/TypeScript-Website#1851]
Sometimes you need to override the types defined by third party packages because:

a) You're waiting for the third party to merge and publish your type fix PR
b) The type fix is a breaking change, meaning you will only get the fix in newer versions of the package. This is particularly painful if you're already a number of major versions behind as it's not realistic (or necessary) to upgrade / refactor your codebase just to get it to compile.

These types can either be dedicated types packages in `@types/*` or types shipped alongside the package itself.

SO / Google comes up with a few options:

1. `declare module 'foo' {}`
   - This *augments* instead of *overrides* if the module isn't 'ambient' which is quite subtle and confusing
   - This therefore, requires you to rewrite the original node_modules types if they have `import` / `export`, otherwise it won't be an 'ambient' module.
2. Remap the paths in tsconfig
   - This is good as it allows you to just copy and paste then fix the types straight from node_modules
3. Copy paste the entire module (types + *code*) and install as `file://` with npm / yarn
    - This is fine for @types/* modules but is a pretty silly for modules which ship their own types as you'd miss security updates etc.

It would be great if there was a recommended, documented solution to this common problem.

**Comment by richardscarrott** [comment]
I've created a SO post which, if answered well, might be useful to incorporate into the docs https://stackoverflow.com/questions/67701504/best-way-to-override-third-party-typescript-types-in-node-modules

**Comment by orta** [comment]
I'm not sure that this is really a TypeScript specific problem, and something _we_ should document. As this is the case for any module on npm. There's some docs in DefinitelyTyped https://github.com/definitelytyped/definitelytyped/#testing on it, but for most folks we've been recommending `skipLibCheck` because they don't do much about it.

**Comment by richardscarrott** [comment]
@orta I see what you're saying so I'm trying to figure out why I think types should be treated differently to runtime code in this respect however I'm struggling a little...

I guess it's because types aren't always treated as first class component of a package so have bugs / incompatibilities between one another more often than the runtime code. Additionally, TS does have ways (as described above) to override the types, however they're all a little clumsy / under documented for this use case.

Some people have suggested the use of https://www.npmjs.com/package/patch-package which aligns with your thinking however so I'll give that a go 👍
