### ISSUE TITLE
Playground: Index signature code example won't work

### ISSUE THREAD

**Issue by Tzahile** [microsoft/TypeScript-Website#1863]
### Current behaviour:
'Index-signature' code example takes you to the ts playground, but the 'run button' leads to a compilation error
### Expected behaviour:
Examples provided by the ts docs should work in order to explain the subject
### Steps to reproduce:
Go to the subject [index-signatures](https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures), and press the 'Try' button in the code box
![image](https://user-images.githubusercontent.com/13683050/120155992-21eb8500-c1fa-11eb-94f2-865fca5f4310.png)
After being redirected to the playground, press the 'Run' button

**Comment by orta** [comment]
TypeScript code samples don't need to run to explain the types, it's not a goal of the code samples to always be runnable JavaScript - the goal is to show how _types works in a focused manner_, you can read more in https://github.com/microsoft/TypeScript-Website/issues/1769#issuecomment-827434203 - I'm going to close this as a duplicate. 

However, I'm always open to improvements in this code sample which don't detract from teaching the types and make it runnable too.
