### ISSUE TITLE
Docs: links to 4.3beta even after release

### ISSUE THREAD

**Issue by HolgerJeromin** [microsoft/TypeScript-Website#1864]
https://www.typescriptlang.org/download

**Issue:** 

> For project types which don't support Nuget. You can use the TypeScript Visual Studio extension.

Links to 
https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-43beta

**Recommended Fix:** 
Should link to 
https://marketplace.visualstudio.com/items?itemName=TypeScriptTeam.typescript-43

Or is this solved with #1860 ?

**Comment by orta** [comment]
Just needed some time I think, likely that VS release came out between the last deploy and the new automatic deploy this morning. It's all fixed now 👍🏻 .
