### ISSUE TITLE
Docs: v2 handbook doesn't document Excess Property Checks

### ISSUE THREAD

**Issue by jcalz** [microsoft/TypeScript-Website#1875]
**Page URL:** https://www.typescriptlang.org/docs/handbook/2/objects.html

**Issue:** The [documentation about excess property checks](https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks) in the deprecated v1 of the handbook doesn't seem to have any analog in v2.  If you click the "go to the new page" link in the deprecation dialog, it brings you to the "Object Types" page which doesn't mention excess property checks at all.

**Recommended Fix:** Add a section on excess property checks to v2 of the handbook, probably on the "Object Types" page.  I was first thinking maybe I could just copy the section from the old handbook, but it refers to different examples, and I'm not even sure where on the new page it should go.  Seems like a bigger rewrite than I'd be comfortable just dropping a PR on, although if someone can outline how it should be done, I'd be happy to do it.

**Comment by jzxchiang1** [comment]
Yes, this is actually quite important.

Excess property checks are a somewhat unexpected feature of TS, given that TS also supports structural subtyping. It's not obvious at all to a beginner.

See https://stackoverflow.com/questions/70360922/typescript-structural-typing-with-exception. There is confusion out there...
