### ISSUE TITLE
Playground: Output different from console (and node.js).

### ISSUE THREAD

**Issue by rentruewang** [microsoft/TypeScript-Website#1880]
## Summary

There is an issue with handling the output the output of `console.log`. The printing is different from browser console and `node.js`. See screenshot below. Playground link in repor section.

## Screenshots

![image](https://user-images.githubusercontent.com/32859905/121492519-86cc8980-ca09-11eb-915f-140a6fc99ac8.png)

![image](https://user-images.githubusercontent.com/32859905/121492737-b4b1ce00-ca09-11eb-9c30-0cafbf0e3342.png)

## Repro

Please see this playground [link](https://www.typescriptlang.org/play?&fbclid=IwAR26Uaq4_EfpwaFZsxo3vK_WV5ZsEiiCK-P5J7Tbv6cNtQQqYnJj3rLOB34#code/MYewdgzgLgBAJgUwA4LIswCeAuGBvAKBmJgG0ArEAI12gCcBLMAcwF1c6EBDOcAG0wx6TZqVYAaAgF8YAXnxESAIkpUAjEtxjJJGCuoAmTWX3qlExcVMBmY6VMbxe1UYu7TAFjsOlT00b9VWwsZLggYUEgoAG4CAihMFCEoOno5BV0KaloUkXYYAGUEKAAeYRYAPkkpeMSEZMYwWHlCTNUcxrZcMABXAFsqBDppOMjoeGQAfT4GaA60lpqx2EQkSd6+jqZm-BqCADMejCgGcBhmYsnVgAp2hpEASlwi0vLmCoySBn2Ya9Xp2ZQLJUVgwACE8iOiH2TAQcAen10xE4UB6dDAEzWM2gwNYYNiuj2umWmPC8lWqHQWFxBJIfGKMC4fD4V2QZJgYAQAHdCsUyrlKn82Q9acR9iA6L96SsYCAfqsIAjWkjiBcoKykH8HgA6cV0ACiXGAAAtrtcEPS+g9ZBVLCqSEyWQrtTw4ObLQ87bpPYS7f9sUDVKD5I6NRBRTAUWiMaGFbE9nqpQzVjAmJjKagsEq7dKOek1RqhUgRSMDhKk7BSABrJwAN1BcpgAHkqOQEMAoNrULkEBAiwDoA9s7p-htq8GYLXtRAGAAvBDxuIEMYgenavggZj9gMlldrjdb0f9XfgCCrhDrzfbwH2VReVgioA).

## Expected behavior

The printed set should not be empty.

## Actual behavior

Is empty.

**Comment by orta** [comment]
Yeah, sounds like a good feature request - you're welcome to give it a shot

**Comment by rentruewang** [comment]
Will do. Thanks for the reply!
