### ISSUE TITLE
"TypeScript for JavaScript Programmers": Unclear guidance regarding interfaces vs types

### ISSUE THREAD

**Issue by Chealer** [microsoft/TypeScript-Website#1899]
**Page URL:** https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

**Issue:** [The _Defining Types_ section](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html#defining-types) of the _TypeScript for JavaScript Programmers_ page contains:

> You’ll see that there are two syntaxes for building types: Interfaces and Types. You should prefer interface. Use type when you need specific features.

This report is not about the terminological confusion, but about the 2 last sentences, which seem contradictory, or at best unclear. As a veteran developer, this leaves me wondering which features are being mentioned, and whether we should use interfaces or "types".

**Recommended Fix:** To avoid confusion, this is not a bug report. That being said, being new to TypeScript, I can't recommend a precise solution. But types being a fundamental concept, I imagine there should be a page treating the choice between both approaches (if there isn't one already), and since the TS for JS programmers page intends to be brief, I imagine it would be best to defer such guidance to that dedicated page, perhaps simply indicating that one approach is generally preferred, and linking to that page.

**Comment by orta** [comment]
We do have a pretty [big section on this](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces) in the handbook, but I didn't really want to be sending people far into handbook only to have to go all the way back to carry on with what they were learning

**Comment by Chealer** [comment]
Thanks @orta

A few points for consideration:

Linking to the handbook doesn't force readers to interrupt their reading. In fact, I read the whole section and did not follow most of its 3 links - neither during my read, nor after.

There is already a link in the paragraph (which I guess should be removed/replaced).

The main issue reported is not the lack of detail, but the apparent contradiction between the 2 last sentences. Rephrasing these would suffice to solve most of this. Assuming my understanding that interfaces and types both have purpose is correct, it would be enough to change...
> You should prefer interface.

...to...
> You should prefer interface in most cases.
