### ISSUE TITLE
Ability to search in TypeScript documentation

### ISSUE THREAD

**Issue by danielsedlacek** [microsoft/TypeScript-Website#19]
## Search Terms
documentation, search

## Suggestion
Add the ability to search in [TypeScrip documentation](https://www.typescriptlang.org/docs/home.html)

## Use Cases
When reading TypeScript 3.0 release notes I stumbled into "Rest parameters with tuple types". As a JS developer I don't know what tuple types are. I don't know when tuple types were added to TS and there is no way to search the documentation.

## Examples
Search bar at the tof of the page. 

## Checklist

My suggestion meets these guidelines:
* [x] This wouldn't be a breaking change in existing TypeScript / JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. new expression-level syntax)

**Comment by orta** [comment]
This is in for both sites 👍
