### ISSUE TITLE
Docs: On-page search for error messages shows duplicate instances in the docs

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#1904]
If you go to the docs and <kbd>Ctrl</kbd>-<kbd>F</kbd> / <kbd>Cmd</kbd>-<kbd>F</kbd> to search the page for error message text, you'll see a "ghost" occurrence. For example

https://www.typescriptlang.org/docs/handbook/2/objects.html

![image](https://user-images.githubusercontent.com/972891/123580644-1b1b4800-d78f-11eb-9388-4a63cbf0cb6c.png)

I'm not sure whether there's an easy way to prevent that.

**Comment by orta** [comment]
Yeah, interesting, I wonder if text can be marked as decoration somehow via CSS

**Comment by mikeesto** [comment]
I take it the fake copy of the error is necessary to stop the layout breaking. Does it have any impact on the style? I tried setting visibility to hidden and couldn't see a noticeable difference, while also also fixing the duplicate find entry

**Comment by DanielRosenwasser** [comment]
It may be worth playing around with`data-` attributes, [`attr`](https://developer.mozilla.org/en-US/docs/Web/CSS/attr()), and the `before`/`after pseudo-selectors. I don't know enough here honestly.

**Comment by orta** [comment]
Yeah, I think @mikeesto's answer will do it 👍🏻

**Comment by orta** [comment]
It doesn't fix it with safari at least - but I added it in #1913 - I already have the behind marked as `user-select: none;` which you'd think would be a good indicator, but maybe there's more.

**Comment by mikeesto** [comment]
Interesting... I'm only seeing one match in Safari?

<img width="1244" alt="Screen Shot 2021-07-01 at 2 58 39 pm" src="https://user-images.githubusercontent.com/21051488/124066983-ef44de80-da7c-11eb-9d25-5bbc6fd105af.png">
