### ISSUE TITLE
typeRoots配置无效

### ISSUE THREAD

**Issue by Justonice2019** [microsoft/TypeScript-Website#1914]
1. 为什么我按照官方文档这样配置无效呢?
![image](https://user-images.githubusercontent.com/52747596/124053252-7af54580-da52-11eb-9f38-e2183f89b540.png)
![image](https://user-images.githubusercontent.com/52747596/124053264-7f216300-da52-11eb-8fbb-eea05ffa5dce.png)
![image](https://user-images.githubusercontent.com/52747596/124053274-834d8080-da52-11eb-89f6-0bca3cb4f294.png)
2. 如果我将mylib文件夹移动到./node_modules/@types文件夹就有效呢? shgenzi甚至typeRoots不变, mylib的声明还依旧能指向./node_module/@types/mylib呢?
![image](https://user-images.githubusercontent.com/52747596/124053439-d58ea180-da52-11eb-8d9d-da4ee6ada45d.png)
![image](https://user-images.githubusercontent.com/52747596/124053456-dde6dc80-da52-11eb-8c93-e9cce3b30467.png)
![image](https://user-images.githubusercontent.com/52747596/124053464-e0e1cd00-da52-11eb-8cc4-781b4b394e6d.png)
3. 使用的typescript版本如下, 我该如何正确配置呢?
![image](https://user-images.githubusercontent.com/52747596/124053538-07a00380-da53-11eb-8026-7a1c2cd5e5d5.png)

**Comment by orta** [comment]
Hi, I'd recommend looking for a Chinese community of TypeScript users to ask your question - this is for the website of the language TypeScript
