### ISSUE TITLE
Docs: ReleaseNotes on a feature are generally are more detailed than the Documentation

### ISSUE THREAD

**Issue by htho** [microsoft/TypeScript-Website#1918]
**Page URL:** https://www.typescriptlang.org/tsconfig#noUnusedLocals **(EXAMPLE)**

**Issue:**
The documentation does not tell the whole story. The Release Notes do (prefix an unused local with an underscore). https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#flag-unused-declarations-with---nounusedparameters-and---nounusedlocals

I've observed this before: There is much more detailed information and background in the ReleaseNotes than in the documentation.

**Recommended Fix:** (1) Either include a link to the **section** of the ReleaseNotes where details and background are explained (Make sure to name that link in a way that that suggests there is more to learn there).
(2) Or include all details and information in the documentation.

Approach (1) is simpler and requires less writing/editing. On the other hand information from the ReleaseNotes might become outdated. And the there is still the question if users will click that link. Some documentation will have the same or more information than the ReleaseNotes than the link would be useless and confusing.

Approach (2) requires more work but will in the end result in a better documentation.

**Comment by orta** [comment]
Sure, those are some good examples to look at - open to PRs improving the docs 👍🏻
