### ISSUE TITLE
Playground: `strict=true` in urls doesn't work

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript-Website#1919]
![image](https://user-images.githubusercontent.com/57028336/124347305-5b634600-dc27-11eb-83ec-a4b29701ae99.png)
![image](https://user-images.githubusercontent.com/57028336/124347315-68803500-dc27-11eb-8384-12b3d6399733.png)

**Repro:** https://www.typescriptlang.org/play?strict=true&ts=4.4.0-dev.20210702#code/C4JwngBA3gsAUPAvhAxgQ2CgFgCgKYCU08EpqA9gHYDOwEAltQMqj2UDmEAvBMGAA55yAMwh5uXHgHJaINuykky9UTkYs5HIrDhk9YgHTByAVX6CQAYTTU8OIgHoHEAPIAjAFZ4UdRhBG8AuJSAK6UANaU5ADulIq6ZIhKpCoQOHyCAeKS0rLyUtrJ+nhGpuZ4VjZ2js5RYiAg5CBFSXCIQA

**Expected behavior:**
`strict` flag is enabled when it's in the url
**Actual behavior:**
`strict` flag is not enabled

**Comment by orta** [comment]
strict is default in the playground, this could be a UI bug

**Comment by orta** [comment]
probably related #1922
