### ISSUE TITLE
Give the handbook a proper start page?

### ISSUE THREAD

**Issue by rauschma** [microsoft/TypeScript-Website#192]
* At the moment, this URL doesn’t work: https://www.typescriptlang.org/v2/docs/handbook/
* I think it would be useful if it did – for linking to the handbook.
* This page could, e.g., show a table of contents.
  * Other useful content: How to give feedback, who wrote the handbook, etc.

**Comment by orta** [comment]
Looks like there isn't really anything to compare to in https://www.typescriptlang.org/docs/handbook/ either, this is a solid idea

**Comment by orta** [comment]
I did this in v2! http://www.typescriptlang.org/v2/docs/handbook/

Though the feedback/handbook isn't in there

**Comment by orta** [comment]
I did an even better version of this
