### ISSUE TITLE
Docs: Footer on tsconfig reference is unreachable on mobile 

### ISSUE THREAD

**Issue by dstaley** [microsoft/TypeScript-Website#1920]
**Page URL:** https://www.typescriptlang.org/tsconfig

**Issue:** When viewing the tsconfig reference in Chrome on my Galaxy S21, the footer is unreachable. It animates into the viewport on scroll, but immediately animates out afterwards.

https://user-images.githubusercontent.com/88163/124348734-abe39080-dba0-11eb-9d59-364a3fb7882f.mp4

**Recommended Fix:** The footer works fine on the homepage, so I'm not sure what exactly about the tsconfig reference is causing this issue.

**Comment by orta** [comment]
It shouldn't really be showing the nav when you scroll down at all, strangely this doesn't reproduce on a iPhone  but does an an android with edge.
