### ISSUE TITLE
Playground: Bug: TS Config settings are not shared

### ISSUE THREAD

**Issue by Asaf-S** [microsoft/TypeScript-Website#1922]
TS Config settings are not shared

**Repro:**

1. Open this link: [link](https://www.typescriptlang.org/play?noFallthroughCasesInSwitch=true#code/GYVwdgxgLglg9mABAcwKZQEoEMwBM4C2AkmFABQFYAeAXImCAQEaoBOAlIgN4BQiirdCFZIAsligALAHTAANnDisy4qdNY58BMpwBUiSlXYBuHgF8ePCAgDOUeoxasAjIgC8KdNjyES5AMwmljYA7jBQEJJkDMxszpy8-AD0+sBYcnI2iFKscCDIkoi6SXyIKYgAYgCCADI1ACoAEhgA8gCqAOKNRSX8EFg2qIjOdOVpGVk5eQU9ZfrVdU2tnd3FpX22cHKo0grIZPGm-Mmp6ZnZkrn5hWvHc5W1Dc3tXT2l-YOIAEw064jWYBsWx2ezIXyCdyYgiwAGtTGYgA).
2. Click "TS Config" -> Tick the "noFallthroughCasesInSwitch" option so it will be turned on.
3. See that an error is listed.
4. Click the "Share" button, and paste it into a new tab.

**Expected behavior:**
1. The "noFallthroughCasesInSwitch" option under the "TS Config" option should be turned on.
2. The error is listed in the example, so others can see it.

**Actual behavior:**
1. The "noFallthroughCasesInSwitch" option under the "TS Config" option is turned off.
2. The error is NOT listed in the example, and I must request others to manually turn it on to see the error.

**Comment by orta** [comment]
Yeah, it's definitely not setting the compiler value in the console from the URL here 👍🏻

**Comment by orta** [comment]
I think this will be fixed by #1940
