### ISSUE TITLE
Playground: type discovery broken for certain re-export patterns

### ISSUE THREAD

**Issue by hayes** [microsoft/TypeScript-Website#1926]
In some cases when doing `export * from ./some-folder` type discovery looks for files in the wrong directory.

Simple playground example: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwIIF84DMoRHA5ACwEMBPA

The module being loaded has 4 files.  Each index file just does a `export * from` for the next file in the list, with the final file exporting a single type `A`.  

* index.ts
* types/index.ts: 
* types/utils/index.ts
* types/utils/a.ts

When the playground is discovering types for this module, it looks for the utils file in  at https://www.unpkg.com/hayes-type-discovery-bug@1.0.1/lib/util.d.ts and /hayes-type-discovery-bug@1.0.1/lib/util/index.d.ts instead of looking in the types directory.  I think this example has 1 more level of nesting than is required to show the issue, but is still a fairly simple reproduction.

Full code for the test package is here: https://github.com/hayes/type-discovery-bug

Files in the imported module:
<img width="1539" alt="Screen Shot 2021-07-09 at 10 41 19 PM" src="https://user-images.githubusercontent.com/816527/125153176-ce2c5f80-e106-11eb-838e-bd0a6e1fa14b.png">
playground loading utils file from the wrong directory:
<img width="1257" alt="Screen Shot 2021-07-09 at 10 39 59 PM" src="https://user-images.githubusercontent.com/816527/125153150-a210de80-e106-11eb-9c6d-82943a6eb7cd.png">

**Repro:**

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwIIF84DMoRHA5ACwEMBPA

**Expected behavior:**

type discovery should look for /lib/types/util/index.d.ts instead of /lib/util/index.d.ts
**Actual behavior:**

playground attempts to load /lib/util/index.d.ts

**Comment by orta** [comment]
Nice report, looks reasonable to me 👍🏻
