### ISSUE TITLE
Docs: Is Symbol() a function ?

### ISSUE THREAD

**Issue by alamenai** [microsoft/TypeScript-Website#1928]
**Page URL:**[less common primitives]( https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#less-common-primitives)

**Issue:** 

You've mentioned :

> There is a primitive in JavaScript used to create a globally unique reference via the function Symbol().

While [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) mentioned:

> Symbol is a built-in object whose constructor returns a symbol primitive — also called a Symbol value or just a Symbol — that’s guaranteed to be unique. Symbols are often used to add unique property keys to an object that won’t collide with keys any other code might add to the object, and which are hidden from any mechanisms other code will typically use to access the object. That enables a form of weak encapsulation, or a weak form of information hiding.

I just confused if `Symbol` is a built-in object with a constructor or a function!

**Comment by orta** [comment]
Thanks for the issue. It's not a constructor, but this is a JavaScript usage question and we don't call it a constructor anywhere in the docs (so I don't think the docs need changing.)

![Screen Shot 2021-07-19 at 9 49 05 AM](https://user-images.githubusercontent.com/49038/126131691-af6d9ff3-2f40-4896-a762-fdc7c15a90f8.png)
