### ISSUE TITLE
V2 handbook single-line code blocks are scrollable

### ISSUE THREAD

**Issue by ggoodman** [microsoft/TypeScript-Website#193]
It appears that single-line code blocks have a mismatch between the container's height and the contained code display's height. When these blocks _are_ scrolled, you can produce a tooltip-hover-flash. This seems to be because the tooltip causes the inner container to resize, moving the tooltip trigger above the cursor, which hides the tooltip, which causes the tooltip trigger to trigger again, etc...

Loving the work put into this! ❤️

**Comment by orta** [comment]
Thanks! Yeah, also the scrollbar shows up in windows too, which is a big meh

Right now the popovers are show inside the code-sample, but I think I'm going to have to just call it and move the popover out of the `<code>` and have it as a new top level element which sets its x/y positions. It means people without JS won't get it, but I've not been able to figure this one out elegantly with all its current constraints.
