### ISSUE TITLE
Feature: Open code snippet in new tab

### ISSUE THREAD

**Issue by alamenai** [microsoft/TypeScript-Website#1930]
**Improvement Idea:**

When I read the documentation and click `try` button in the snippet's example, it opens the editor in the same page ( Redirection in the same tab ). However, this annoys me because I click the `back` button of the browser each time when I want to come back to the documentation page.

**Why:**

1. Bad readability experience.
2. Use the browser's `context menu` each time.
3. Want to switching try several examples without going back in the documentation each time.

**Alternative ideas:**

Open the snippet code in a new `tab` by adding the `target` attribute in the link:

#### Example:

```html
<!DOCTYPE html>

<html>
<body>

<h1>The a target attribute</h1>

<a class='playgound-link' href='https://www.typescriptlang.org/play/#code/C4TwDgpgBA4gThCwBiBXAdgY2ASwPbpQC8UAFAIYBcUAzsHDugOYCUxAfFAG544AmAbgBQAMwzZ8hJgiQQ4pEemrxEKcbgJsA3kKhQA9PqgA6U0IC+QA' target="_blank">
Try</a>
</body>
</html>
```

#### Demo

<a href='https://www.typescriptlang.org/play/#code/C4TwDgpgBA4gThCwBiBXAdgY2ASwPbpQC8UAFAIYBcUAzsHDugOYCUxAfFAG544AmAbgBQAMwzZ8hJgiQQ4pEemrxEKcbgJsA3kKhQA9PqgA6U0IC+QA' target="_blank">
Try
</a>

**Comment by orta** [comment]
I'm not generally a fan of forcing pages into a new tab. I can generally see the value when it's 'leaving your site', but the playground is still the TS docs. Today you can choose to have it open in a separate tab etc by using your browsers features (like cmd/ctrl clicking) but you don't have to if you don't want to. If we switch to forcing a new tab then it's taking that choice from folks
