### ISSUE TITLE
Docs: Handbook v2: Classes: Inheriting Built-in Types - irrelevant information

### ISSUE THREAD

**Issue by Alexsey** [microsoft/TypeScript-Website#1938]
**Page URL:** https://www.typescriptlang.org/docs/handbook/2/classes.html#inheriting-built-in-types

**Issue:** The information in the section is intricate and irrelevant

**Recommended Fix:** If the actual version of TypeScript really has some issues with inheriting built-in types - they should be described in this section. If the actual version of TypeScript doesn't have any issues with inheriting build-in types - the section should be removed

The section is proposing this code snippet as problematic
```
class MsgError extends Error {
  constructor(m: string) {
    super(m);
  }
  sayHello() {
    return "hello " + this.message;
  }
}
```

According to the doc, this code should have two problems:
1. methods may be undefined on objects returned by constructing these subclasses, so calling sayHello will result in an error
2. instanceof will be broken between instances of the subclass and their instances, so (new MsgError()) instanceof MsgError will return false

But attempts to reproduce both of these issues failed:
```
const msgError = new MsgError('test-msg')
console.log(msgError.sayHello()) // "hello test-msg", just as it should be
console.log(msgError instanceof MsgError) // true, just as it should be
```

**Comment by orta** [comment]
I think you skipped the sentence saying how down leveling to ES5 has those issues: 

> however, there is no way to ensure a value for new.target when invoking a constructor in ECMAScript 5

E.g: https://www.typescriptlang.org/play?target=1#code/MYGwhgzhAECyEHMCiAnFB7F0CmAPALtgHYAmMqGWA3gFDTTDpET4oCuw+mAFALYBc0FigCWRBAEpotevQhsADthR8JAbjrQAvpohgAngAlsIEOm5SZslNnxsURaACIAFibPPoAamj4XIiAA6XmwoMARsDXodHRpGZnxoXkQKTGgAXmgibAB3OBS0HgByQhYAWmSEIok4pgh0EGxAswQ+AspAvSN3cwkpAHp+5zdTdF9Q-ArEJwAaaAArNhZoSGgRRIgXdDYQEmgAI2xa5gamlrbkQqwxFjAiYGx0ADN8y8oBodY2bDnF5dX1kItjs9ocaEA

> [ERR]: msgError.sayHello is not a function. (In 'msgError.sayHello()', 'msgError.sayHello' is undefined) 

I think as long as ES5 is the default in TS, we probably want this in (basically forever). Perhaps we could do a better job of highlighting the ES5-ness of it though.

**Comment by Alexsey** [comment]
@orta thank you for the answer! Yes, you are correct - I have skipped the section of down leveling to ES5 as something completely irrelevant :) I would make a PR with a comment to **Inheriting Built-in Types** section that this is not an issue for the modern compilation target

**Comment by Alexsey** [comment]
https://github.com/microsoft/TypeScript-Website/pull/1941

Also, I have noticed that in the [documentation for compiler options](https://www.typescriptlang.org/docs/handbook/compiler-options.html) is saying that the default `--target` is `ES3`. Should it also be updated to `ES5`?

**Comment by orta** [comment]
Nah, that's just me getting it wrong - we're so far away from ES3/5 that they both feel the same at this point. Thanks for the PR!
