### ISSUE TITLE
Docs: Doc already in English, but the overlay suggests to move to the page in English, but it leads me to the Korean. page

### ISSUE THREAD

**Issue by leochoo** [microsoft/TypeScript-Website#1943]
Doc already in English, but the overlay suggests to move to the page in English, but it leads me to Korean.

**Page URL:** 
https://www.typescriptlang.org/docs/handbook/2/basic-types.html

**Issue:** 
Doc already in English, but the overlay suggest to move to the page in English, but it leads me to Korean.

**Recommended Fix:** 

Obviously, it should not ask me to lead to an English page when I'm already in one,
and not lead me to Korean page when it says it will take me to an English page.

**Comment by orta** [comment]
Oh, I guess the overlay for 'go the Korean page'  isn't localized, because the Korean page seems fine 👍🏻

**Comment by orta** [comment]
This got localized 👍🏻

**Comment by leochoo** [comment]
Thank you!
