### ISSUE TITLE
Playground: JavaScript Error Triggers on Import Declarations Regardless of Placement at Top Level

### ISSUE THREAD

**Issue by ElTipejoLoco** [microsoft/TypeScript-Website#1949]
Attempting to run code with imports yields a JavaScript syntax error in the logs, preempting and preventing execution as a result.

![image](https://user-images.githubusercontent.com/22507424/126673501-cdf52857-d475-43a5-a426-8aed53473ecf.png)

**Repro:**
Attempting to run the [Function Chaining example](https://www.typescriptlang.org/play/?esModuleInterop=true&q=341#example/function-chaining) will yield the same error (using Firefox 90.0.1 64-bit).

**Expected behavior:**
JavaScript syntax error should only trigger if an import function exists outside of allowed area (top level of module).
**Actual behavior:**
JavaScript syntax error acts as if its import functions are not at the top of the code space.

**Comment by orta** [comment]
The playground only gets the types for imports, and doesn't handle the bundling of libraries for web - so you cannot run the javascript. For these cases I recommend using the export to code sandbox or stackblitz feature too get  full sandbox
