### ISSUE TITLE
Playground: ctrl+left/ctrl+right to move the caret between words doesn't work in firefox

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript-Website#1950]
same with ctrl+shift+left and ctrl+shift+right

**Comment by orta** [comment]
This is an upstream monaco issue I believe - https://microsoft.github.io/monaco-editor/index.html

**Comment by Gerrit0** [comment]
Duplicate of https://github.com/microsoft/TypeScript-Website/issues/1763
