### ISSUE TITLE
Publish `typeAcquisition` as a package

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript-Website#1955]
**Improvement Idea:**

Make a package out of the [`typeAcquisition`](https://github.com/microsoft/TypeScript-Website/blob/23cd21aec8ef8284d3cb89fad6607e839c2f97e8/packages/sandbox/src/typeAcquisition.ts).

PS. `@typescript/sandbox` could also be published - there would be probably users wanting to use that in their projects as well.

**Why:**

It's a good feature for online playgrounds and I could make use of this being a package 😉 I could also help to set this up if I would only get a green light for this.

**Comment by orta** [comment]
Ah, I missed this, yeah I think maybe making `@typescript/web-typeacquisition` can make sense. 

WRT the sandbox as a standalone, I'm less sure, I don't really want to support the many permutations of bundling setups people have (especially as the TS website doesn't use them and is just AMD) - I've seen the number of reports over at monaco and keeping on top of that is _work_

**Comment by Andarist** [comment]
I'm mostly interested in the type acquisition part - so that's OK with me 😅 

I could prepare a PR introducing setup for the `@typescript/web-typeacquisition` package (based on what you have there for `@typescript/vfs`). Would you like me to give this a spin? 

One thing that I'm not sure about... is [this Algolia endpoint](https://github.com/microsoft/TypeScript-Website/blob/23cd21aec8ef8284d3cb89fad6607e839c2f97e8/packages/sandbox/src/typeAcquisition.ts#L17) considered to be public? or should this be provided by the consumer of a package?

**Comment by orta** [comment]
I think it's probably a good idea to have that as a string you pass, @haroenv will probably have the definitive opinion on that

**Comment by Haroenv** [comment]
The endpoint is not meant to be used as-is, since it doesn't retry, I'd prefer if you use the algolia (lite) client

```ts
import algoliasearch from 'algoliasearch/lite';

const client = algoliasearch('OFCNCOG2CU', 'f54e21fa3a2a0160595bb058179bfb1e');

const object = await client.initIndex('npm-search').getObject(name);
```

I understand that the typescript website didn't want to add dependencies, but adding the retry strategy will drastically improve response time and resilience (also makes sure to do Simple Requests, to avoid CORS).

If you're planning to make a bigger project than something small as a side @andarist, I'd love to hear more about what you're making and give a dedicated api key.

For avoiding to change too many technicalities about this, it's probably all right for now to just pass appId, apiKey and indexName as arguments (with defaults possibly)

**Comment by Andarist** [comment]
> If you're planning to make a bigger project than something small as a side @Andarist, I'd love to hear more about what you're making and give a dedicated api key.

The use case is rather small at the moment - I'm working on the XState visualizer at the moment ( https://stately.ai/viz ) and, at the moment, I only need to fetch types for the `xstate` package itself. Once we start relying on static analysis instead of code evaluation in realms it would be cool to enable type acquisition for everything - just like it works on the TS playground itself. For now, I'm just filtering out requests for non-xstate packages.

> The endpoint is not meant to be used as-is, since it doesn't retry, I'd prefer if you use the algolia (lite) client

This would require us to set up our own algolia's npm-search index/server, right?

---

I've just seen this: https://github.com/microsoft/vscode/issues/172887 and I wonder if this just won't implement what I want "natively" in the TS server. Would that assessment be right?

**Comment by Haroenv** [comment]
No, you can use the code I put in the previous example instead of the fetch that happens now, or just the same appId/apiKey/indexName combo as used in this repo if you don't want to modify the typescript code.

**Comment by Andarist** [comment]
Oh, cool! I wasn't sure if I'm supposed to use those app ids etc or if they are considered to be "private". I don't expect for us to flood that with requests but I wouldn't like to use private-like resources without permission.

**Comment by Andarist** [comment]
According to [this tweet](https://twitter.com/orta/status/1448275924252774404) this has actually been released as a package. Thank you! I will be able to remove my dirty hacks from the codebase 🎉
