### ISSUE TITLE
Migrating to Static Web Apps plan

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#1966]
### Why Migrate?

Today, the TypeScript website is pseudo static. We treat it as a static website (and have been using azure blob storage for the staging website for the last year) but in reality its an AppService app (configured by [`Web.config`](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/typescriptlang-org/static/Web.config)) emulating a static website.

The mismatch from the pseudo static hosting has been the root cause of most downtime for the site, and I don't really want anyone else to have to learn the details there. 

### To Static Web App (SWA)

The TS site is exactly what Static web apps is built for. We've been deploying to SWA on every staging build, and I recently added a fancy alias https://static.staging-typescript.org/ which I've been using as my main website for dev etc. SWAs have been out of beta for a while now and it's time to migrate prod.

### Proposal

Everything is up and ready, we just need to migrate DNS to point to the SWA on prod. We can migrate in a two-step process to de-risk, because SWA just got access to be able to create apex domains, so we can handle #14 #23 and in the process _not_ initially migrate `www.`. 

1. We migrate `https://typescriptlang.org` to use the SWA - this domain _does not work_ today, it never has. We use that to be sure everything is working.
2. Then we migrate `www.` over to the SWA

Then we turn off the AppService.

**Comment by brillout** [comment]
I can see you guys liking [vite-plugin-ssr](https://vite-plugin-ssr.com/) (I'm its author). It has first-class support for static websites. (Static Websites are essentially like SSR (Server-side Rendering) but the HTML is rendered at bulid-time instead of request-time.) Feel free to let me know if you have questions.
