### ISSUE TITLE
TypeScript Website Home Page v2

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#1969]
**New Design:** [Figma link](https://www.figma.com/file/x8FJrNqj6oupqWn1s3uMg4/TypeScript-Website-Design?node-id=3723%3A1)
**Live Link:** https://typescriptlang.org/

Last August, we shipped a re-design of the homepage with the constraints of mixing the old homepage's colors, style and content with some of the more modern design language from the VS Code site and the Microsoft [fluent design](https://www.microsoft.com/design/fluent/#/) system.

Now the site is stable, we've come back to the index with fresh eyes, new user tests and gone through 4 iterations of ideas:
 - [Simplifying the homepage content and text](https://www.figma.com/file/x8FJrNqj6oupqWn1s3uMg4/TypeScript-Website-Design?node-id=2032%3A882)
 - [Minimalist tailwind-y aesthetics](https://www.figma.com/file/x8FJrNqj6oupqWn1s3uMg4/TypeScript-Website-Design?node-id=3087%3A6) to closer match GitHub's product pages
 - [A re-focus on user-feedback from contrasting the two designs](https://www.figma.com/file/x8FJrNqj6oupqWn1s3uMg4/TypeScript-Website-Design?node-id=3087%3A6) based on user-testing of the minimalist with the current site
 - [A constrained palette version of the re-focused design](https://www.figma.com/file/x8FJrNqj6oupqWn1s3uMg4/TypeScript-Website-Design?node-id=3723%3A1)  

The goals of the homepage are to introduce TypeScript, explain the value proposition of the language with a focus on the developer experience gains from migrating incrementally. We can use it to show JavaScript developers that it's not a 'cross the chasm to TypeScript' for getting better tooling, and can be a much slower / thoughtful process if they want.

You can preview the WIP implementation of the TypeScript re-design at https://static.staging-typescript.org/index4 - if you have ideas and suggestions for the design, you're welcome to leave feedback here.

**Comment by helloankit** [comment]
I loved the code examples in **Get Started** section of the new design, which is showcasing the thin line of difference between JS and TS.

On the current site, there is too much textual content. We can add some cool infographics, which can convey the message merely at a glance. Also, action items such as links to the documentation can be moved upwards.

**Comment by Messiahhh** [comment]
Good Job

**Comment by orta** [comment]
This is shipped 👍🏻
