### ISSUE TITLE
V2 playground editor doesn't respect change in dark mode preference

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#197]
If you switch between dark/light mode on the system, then the monaco instance on the playground stays its original color.

This can be fixed with a media query listener

* Older, more supported API https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener
* Newer, less supported API https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/onchange

**Comment by orta** [comment]
👍 - this happened to me during a demo last night actually
