### ISSUE TITLE
Docs: Invalid placeholder iD or element

### ISSUE THREAD

**Issue by crystalfp** [microsoft/TypeScript-Website#1975]
**Page URL:** Every documentation page, for example: https://www.typescriptlang.org/docs/handbook/project-references.html

**Issue:** When you enter this or any documentation page, the following popout appears:

![image](https://user-images.githubusercontent.com/865866/128605052-77eb6f55-21b7-44e4-8f63-f8e0a59fa561.png)

When you dismiss it, everything seems normal on the page.
I'm using Chrome 92.0.4515.131 on Windows 10.

**Recommended Fix:** Find who generate the popup and solve the root cause.

**Comment by crystalfp** [comment]
On page https://www.typescriptlang.org/docs/handbook/project-references.html hover the link that read: `using disableSourceOfProjectReferenceRedirect option.` in the https://www.typescriptlang.org/docs/handbook/project-references.html#caveats-for-project-references section. Multiple popups appears. Really annoying.

**Comment by orta** [comment]
Interesting, do you see any useful console logs? or maybe you have some sort of security extensions set up? The popup works for me on latest safari/chrome.

**Comment by orta** [comment]
That error message isn't in the TypeScript website codebase either, could that also be coming from an extension?

**Comment by crystalfp** [comment]
The problem does not appear on Firefox.
In the log on Chrome I have various "null" printed from an extension to kill cookies banners.
So thanks for your ideas @orta ! I will investigate with the extension author. Closing the issue. Thanks!
