### ISSUE TITLE
blog: please amend my name in the language changelog

### ISSUE THREAD

**Issue by KiaraGrouwstra** [microsoft/TypeScript-Website#1979]
hi, i made a few TS [PRs](https://github.com/Microsoft/TypeScript/pulls?q=is%3Apr+author%3AKiaraGrouwstra) a few years ago, a bit of which got in yielding a [changelog](https://devblogs.microsoft.com/typescript/announcing-typescript-2-7/) mention (2.7 + RC).
since then i have altered my legal name (as well as github username) however.
if it's not too much trouble, i hope this could be reflected in the changelog mention as well.

**Comment by orta** [comment]
No worries, we've changed the changelogs on the product blog and updated the site too - thanks for letting us know 👍🏻
