### ISSUE TITLE
Playground no scroll

### ISSUE THREAD

**Issue by WORMSS** [microsoft/TypeScript-Website#2]
In the https://www.typescriptlang.org/play if you have a lot of text (or a small amount of text on a small window) you cannot scroll to see the bottom. It just carries on and you lose the ability to read what you are typing.

**Comment by WORMSS** [comment]
@orta thank you. I didn't realise there was a typescript-website repo.. now that I know, I will post them there. (or here, since I just noticed the issue has been transferred).

**Comment by orta** [comment]
This is fixed now 👍
