### ISSUE TITLE
Website redirection issue

### ISSUE THREAD

**Issue by kenhowardpdx** [microsoft/TypeScript-Website#20]
This isn't a TS issue, but an issue with the website [www.typescriptlang.org](http://www.typescriptlang.org).

When entering `typescriptlang.org/play` in the browser's address bar you are redirected to the homepage `www.typescriptlang.org`.

Close this if it's not in the right place.

**Comment by orta** [comment]
related: we should force https for http urls ([source](https://twitter.com/orta/status/1178747610003378185))

**Comment by kenhowardpdx** [comment]
This is still occurring. I assume there's a DNS forward happening and it isn't capturing the path on forward.
