### ISSUE TITLE
Docs: Default value for `useDefineForClassFields` is misleading / wrong

### ISSUE THREAD

**Issue by MartinJohns** [microsoft/TypeScript-Website#2000]
**Page URL:** 
https://www.typescriptlang.org/tsconfig/#useDefineForClassFields  
https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Issue:** 
On both sites the default value is shown as `false`, when it actually depends on the target version.

**Recommended Fix:** 
Add the same documentation that is/will be added as part of microsoft/TypeScript#45503.

**Comment by orta** [comment]
This should happen as a part of upgrading the TS site to 4.4 release when it comes out 👍🏻

**Comment by orta** [comment]
This is in with the 4.4 update 👍🏻
