### ISSUE TITLE
Errors are not appearing in JS mode anymore

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#201]
I added it with https://github.com/microsoft/monaco-typescript/pull/40

Is it possible that this got undone somehow since then?

**Comment by IllusionMH** [comment]
This one seems resolved as per https://github.com/microsoft/TypeScript/issues/38113#issuecomment-655740591

Or this one is more broad?

**Comment by orta** [comment]
Ah nope that one is more broad - thanks
