### ISSUE TITLE
Docs: --sourceMap is not defaulting to false 

### ISSUE THREAD

**Issue by jcollum** [microsoft/TypeScript-Website#2015]
**Page URL:** https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Issue:** I think  --sourceMap is not defaulting to false. Can someone check my math before I PR and look dumb? I had to explicitly set `--sourceMap false` to not have source maps. 

**Recommended Fix:** I will PR.

**Comment by orta** [comment]
Yeah, it is definitely defaulting to false - `tsc --init` also keeps it as false. Maybe you had something like webpack generating them?
