### ISSUE TITLE
Idea: Clean up the HTML/Markdown of the Compiler Options page

### ISSUE THREAD

**Issue by oboukli** [microsoft/TypeScript-Website#2018]
**Improvement Idea:**

The _Compiler Options_ page has a malformed, probably autogenerated, HTML table.

Suggestions:

- Replace the with a proper standard HTML/markdown. (Fix the HTML generator)
- Remove the HTML attributes and use external CSS for styling the table

Page URL:
https://www.typescriptlang.org/docs/handbook/compiler-options.html

Markdown source:

```packages/documentation/copy/en/project-config/Compiler Options.md```

**Why:**

Documentation page is malformed.

**Alternative ideas:**

Do without HTML. Use markdown table.

**Comment by orta** [comment]
This was fixed, thanks!
