### ISSUE TITLE
Mixin: Type "{}" used in example but eslint fails with an error

### ISSUE THREAD

**Issue by HeikoStudt** [microsoft/TypeScript-Website#2019]
On the handbook page on Mixins (https://www.typescriptlang.org/docs/handbook/mixins.html) you have the following typescript code as an example:

```typescript
      type Constructor = new (...args: any[]) => {};
```

According to Default-Rules of eslint, this is an ERROR: Don't use `{}` as a type. `{}` actually means "any non-nullish value". In my view, eslint is right - the mixin will return an object and never something like a number.
(https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md)

It should probably be rewritten like this:

```typescript
      type Constructor = new (...args: any[]) => Record<string,any>; 
```

MFG (kind regards)

**Comment by orta** [comment]
Yeah, I pretty much agree with you (and eslint) here - funny that we don't have any cases in the compiler where it's not either `{}` or `any`

![Screen Shot 2021-09-13 at 2 28 37 PM](https://user-images.githubusercontent.com/49038/133092743-f9f89307-af3d-443d-81e0-5d290330aac4.png)
