### ISSUE TITLE
Docs: landing page v2 code snippets are truncated on mobile

### ISSUE THREAD

**Issue by amitport** [microsoft/TypeScript-Website#2020]
**Page URL:** 
Landing page v2

**Issue:** 
When trying to read code snippets on mobile Firefox or chrome the end of some lines is cut off and there is no ability to scroll horizontally.

**Recommended Fix:** 
Play with the css a bit :)

Thank you

**Comment by sbwp** [comment]
I'm seeing this issue on desktop as well. I'm seeing it in both the Interfaces and JSX tabs. I tested in a few different browsers/platforms:
- Firefox on Windows - Only saw the issue when the screen was small enough to squish the box with the snippets but large enough not to stack vertically like in mobile view
- Chrome on macOS - Occurs to varying degrees at all sizes when horizontally stacked and most sizes when the window is small enough to be vertically stacked
- Safari on macOS - Same as Chrome
- Safari on iOS (iPhone 13 Pro Max) - Occurs in both portrait and landscape
