### ISSUE TITLE
Docs: playground example breaks the back button

### ISSUE THREAD

**Issue by thany** [microsoft/TypeScript-Website#2022]
**Page URL:** https://www.typescriptlang.org/play/4-0/new-ts-features/unknown-in-catch.ts.html

**Issue:** When going to the above url, it breaks the back button. Because it does a client-side redirect to another url, the back button goes back to the above url, which in turn does the redirect again.

**Recommended Fix:**
Either:
1. Don't do a client redirect, but a server redirect.
2. Don't redirect at all, but load the playground right then and there.
3. Use a `history.replace` kind of trick

**Comment by orta** [comment]
I'm open to a PR adding the `history.replace` sort of trick, though I'm not sure it would work how you like (given how tricky that has turned out to be in the playground with the URL) - it's likely that this is probably just a limitation of the static deploys.

**Comment by thany** [comment]
I never said `history.replace` has got to be *the* solution. It's just an idea. It might also be possible to inline the playground right then & there.

**Comment by thany** [comment]
Please don't close, unless the problem is fixed.
