### ISSUE TITLE
Docs: Consistent and clear recommendation for if types should be included in DefinitelyTyped or in packages

### ISSUE THREAD

**Issue by cinderblock** [microsoft/TypeScript-Website#2032]
## Page URL
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

> Otherwise, we recommend submitting the types to DefinitelyTyped, which will publish them to the @types organization on npm.

## Issue

The documentation suggests that package maintainers should endeavor to keep their types published in DefinitelyTyped.

However the official guidance from Definitely Typed is to put the types in each package directly, if possible.

https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

> If you are the library author and your package is written in TypeScript, bundle the autogenerated declaration files in your package instead of publishing to Definitely Typed.

> When a package bundles its own types, types should be removed from Definitely Typed to avoid confusion.

This jives with how I think of Definitely Typed's intent; to provide types for packages that:
- refuse or can't be bothered to include types
- want to keep the published package size as small as possible

However, I think the "and your package is written in TypeScript" phrase is particularly misleading as well. It is perfectly valid to add & publish TypeScript types for a package written in JavaScript (heck, or even , for example, CoffeeScript).

## Recommended Fix

Clarify and make recommendation consistent across projects.

I, personally, feel **strongly** that the official recommendation should be that packages should publish their own types.  
I shouldn't need to `npm i package && npm i -D @types/package` to install a single package.
`@types/`DefinitelyTyped is a crutch for packages that don't include types.

Even if a developer isn't using TypeScript directly, the type information usually improves the developer experience.

**Comment by orta** [comment]
I've re-read this issue a few times now, and I think I'm just struggling to see how they don't collaborate. Can you give me some actionable ideas/PRs? Our mental model for where types should live is: 

 - If you generate the types from your source code, ship it with the npm package
 - If you don't, you probably want to use DT but obviously you can use still bundle some `index.d.ts` files if you like

**Comment by cinderblock** [comment]
I've come across a project recently (and I think another previously) that was considering incorporating the declaration files currently on DT into their sources for publishing on Npm. It seemed to be there was, and maybe still is, some confusion about when DT should be used.

While I don't think DT is going anywhere, it's better to include type declarations directly in the packages, no?

I think the specificity of the "generating" of types from "TypeScript and JavaScript projects" is suggesting that there are cases where it's prefered to keep the types in DT, when I'm pretty sure there basically aren't any.

**Comment by orta** [comment]
It's not always better - if the module maintainers don't use or understand typescript then how can they reliably maintain the .d.ts files? DT offers a way to easily test, deploy and maintain those types outside of that. There's no absolute rule for how anyone should deploy it, which is why we give those heuristics and offer options which I think are pretty reasonable

**Comment by cinderblock** [comment]
There are maintainers that are willing to incorporate type declarations into their sources who then see the wording on these pages and think that TS would rather the types be in DT when, if possible, it's better to incorporate the types into the package directly.

**Comment by orta** [comment]
Right, and they _may_ be better suited to not doing that - randos add types to peoples packages all the time in drive-by PRs and then they get out of date or are unmaintained because they're not actively used. We get PRs un-undeprecating  DT modules occasionally. If someone is deterred by that messaging, that can be OK.

The point is that this isn't always a net win for the maintainers and users, to switch from a nuanced statement to one that assumes it's all great isn't good activism for adding types to projects overall.

**Comment by cinderblock** [comment]
The statement, as is, isn't nuanced. It's confusing.

It suggests that it's only valid to include types in published package for types *generated* from sources (TS or JS). However manually *created* types are just as valid.

----

Maybe an alternative solution to the confusion here is spelling out the differences in the options, in particular as far as the consumer and maintainers are concerned. Specifically, that a user has to install two packages instead of one or that maintainers need to keep their types in sync with sources.
