### ISSUE TITLE
Docs: "Height" is spelled "heigth" in multiple places.

### ISSUE THREAD

**Issue by shreemaan-abhishek** [microsoft/TypeScript-Website#2036]
**Page URL:** 
https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html

**Issue:** 
"Height" is spelled "heigth"

**Recommended Fix:** 
We should fix it :D

**Comment by orta** [comment]
Thanks, but this was an intentional typo to show how TypeScript catches those
