### ISSUE TITLE
Playground: Nightlies stuck on 4.5.0-dev.20210910

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#2040]
If you check out https://www.typescriptlang.org/play?ts=next, you'll get a version that's about 2 weeks old. Not sure what's happening there.

**Comment by orta** [comment]
Looks like this button needs to be pressed: https://github.com/microsoft/TypeScript-Make-Monaco-Builds/actions/workflows/nightly.yml

![Screen Shot 2021-09-25 at 7 57 51 AM](https://user-images.githubusercontent.com/49038/134762088-93b97941-ca3b-4587-820f-a2138ebb02a0.png)
