### ISSUE TITLE
missing text in pdf handbook

### ISSUE THREAD

**Issue by alithecodeguy** [microsoft/TypeScript-Website#2042]
There was a missing text in pdf handbook on page 14, "Erased Types" section in code box
missing text : **"!" );**

**Comment by orta** [comment]
Looks like we need a hard line limit of maybe 68 chars in these code samples or the PDF won't show the rest

![Screen Shot 2021-09-27 at 9 21 30 AM](https://user-images.githubusercontent.com/49038/134871304-2ca8b9e3-88e2-4525-ab88-024e70cdc789.png)
