### ISSUE TITLE
Docs: Seemingly-incorrect statement about ESM

### ISSUE THREAD

**Issue by tjcrowder** [microsoft/TypeScript-Website#2047]
**Page URL:**

https://www.typescriptlang.org/docs/handbook/2/modules.html#commonjs-and-es-modules-interop

**Issue:**

It says:

> There is a mis-match in features between CommonJS and ES Module because ES Modules only support having the default export as an object, and never as a function.

That seems to be saying ESM doesn't allow exporting a function as the default, but [it does](https://codesandbox.io/s/function-default-export-fv7md):

```js
// export.js
export default function() {
    console.log("Hi there");
}
// import.js
import fn from "./export.js";
fn();
```

I suspect it's trying to say something else, not that you can't use a function as the default export. But I'm not sure what it *is* trying to say, so I can only flag up the problem, I can't solve it (without help).

**Recommended Fix:**

We should correct or clarify the sentence, but I'm not sure how because it's not clear to me what it's trying to say.

**Comment by orta** [comment]
It's about `import * as x` - from the linked tsconfig reference:

> the ES6 modules spec states that a namespace import (`import * as x`) can only be an object, by having TypeScript treating it the same as `= require("x")` then TypeScript allowed for the import to be treated as a function and be callable. This breaks the spec’s recommendations.

This should either mention it's about the namespace, or just be a more vague hint to read up on the tsconfig reference where the full explanation it

**Comment by tjcrowder** [comment]
@orta Ah, yes, it's the distinction between default import and module namespace import. Not just functions although that's the common way it's done, in CommonJS you can do `module.exports = 42` and `const x = require("x")` will give you a number.

How about:

> There is a mis-match in features between CommonJS and ES Modules because ES Modules distinguish between a default import (`import x from "x"`) and a module namespace object import (`import * as x from "x"`). In CommonJS, `const x = require("x")` could be either depending on how the module you're importing defined its exports. TypeScript has a compiler flag to reduce the friction between the two different sets of constraints with [`esModuleInterop`](https://www.typescriptlang.org/tsconfig#esModuleInterop).

or

> There is a mis-match in features between CommonJS and ES Modules regarding the distinction between a default import and a module namespace object import. TypeScript has a compiler flag to reduce the friction between the two different sets of constraints with [`esModuleInterop`](https://www.typescriptlang.org/tsconfig#esModuleInterop).

?

**Comment by orta** [comment]
The second works really well for me - thanks!
