### ISSUE TITLE
Blog Link Broken

### ISSUE THREAD

**Issue by dragomirtitian** [microsoft/TypeScript-Website#205]
The link to the blog on the [connect](https://www.typescriptlang.org/community/index.html) section of the site is broken, it leads to [archived blogs](https://docs.microsoft.com/en-us/archive/blogs/) instead of the actual [blog](https://devblogs.microsoft.com/typescript/)

**Comment by orta** [comment]
oh yeah

**Comment by orta** [comment]
fixed on next deploy
