### ISSUE TITLE
path imports of packages not supported

### ISSUE THREAD

**Issue by eps1lon** [microsoft/TypeScript-Website#206]
Repro: http://www.typescriptlang.org/play/#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQokscA3gL5xEnmV4wC0AExIB6VFigA3CWQbho8FnThwRIuDAAWWOLhKQAdlgMx0ATwgBXOJfGC6HLqTIABEMhgTgyADb9LwCJ6lCIAKmaQAOZQyGCaZiLABoJYAB6ydASWBvjAEAZwACJYIBAAFACUrMqq6gCaVlC6ECkOQA

Currently imports such as `react-dom/server` or `@material-ui/core/Typography` are not supported. It seems like it tries to fetch them by appending `.d.ts` (which is only part of the usual resolution algorithm). But even by leveraging that knowledge and using e.g. `import Typography from '@material-ui/core/Typography/index'` (where `import Typography from '@material-ui/core/Typography/index.d.ts'` does exits) is not in a found module.

Technically it should consider `import Typography from '@material-ui/core/Typography/index.d.ts'` in `import Typography from '@material-ui/core/Typography'` as well. In a perfect world it would also check the `types` field in `import Typography from '@material-ui/core/Typography/package.json'`.

**Comment by orta** [comment]
This is still valid, the key is that the fallback of the path might need to resolve over to definitely types too

```ts
import * as React from 'react';
import {} from 'react-dom/server'

function Demo() {
  // Your code
}
```

Looks at: `https://www.unpkg.com/react-dom@17.0.1/server.d.ts` which would work if they bundled

But it also needs to look at: `https://www.unpkg.com/@types/react@17.0.3/server.d.ts`
