### ISSUE TITLE
Idea: Output `<link rel=canonical>` in HTML, pointing to typescriptlang.org

### ISSUE THREAD

**Issue by jakub-g** [microsoft/TypeScript-Website#2069]
**Improvement Idea:** Output `<link rel=canonical>` in HTML, pointing to typescriptlang.org

**Why:** It seems that TS website is also served under `staging-typescript.org`, and that website too gets indexed by search engines. For some queries, it's even higher than `typescriptlang.org`. This duplication is not really good, can lead to messy bookmarks etc.

Example with DuckDuckGo:
![image](https://user-images.githubusercontent.com/1437027/136550948-6f489a75-cace-4ff8-9f37-7449152884a8.png)

[`<link rel=canonical>`](https://yoast.com/rel-canonical/) is a _canonical_ solution to this problem, to help the bots deduplicate content.

For example, https://www.staging-typescript.org/docs/handbook/declaration-files/dts-from-js.html should have `<link rel="canonical" href="https://www.typsescriptlang.org/docs/handbook/declaration-files/dts-from-js.html">` in `<head>`.

**Alternative ideas:**

Create valid https://www.staging-typescript.org/robots.txt which prevents crawling the staging page.

**Comment by orta** [comment]
Staging URLs get this set, which should do that:

![Screen Shot 2021-10-08 at 1 14 01 PM](https://user-images.githubusercontent.com/49038/136554987-9234d4ce-efb6-45be-b9f5-58dac37b36a0.png)

But I'm open to adding a canonical ref in there too 👍🏻
