### ISSUE TITLE
Docs: Typescript 1.1 blog post link forbidden

### ISSUE THREAD

**Issue by jHabjanMXP** [microsoft/TypeScript-Website#2075]
**Page URL:**  https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-1.html

**Issue:** 
Blog post for some impressive charts link doesn't resolve (403 forbidden)
http://blogs.msdn.com/b/typescript/archive/2014/10/06/announcing-typescript-1-1-ctp.aspx
![image](https://user-images.githubusercontent.com/60509445/136656057-30fb4eae-25de-4b8f-9899-c39430a8724c.png)

**Comment by orta** [comment]
It's probably this, but it doesn't seem to have any graphs: https://devblogs.microsoft.com/typescript/announcing-typescript-1-1-ctp/

**Comment by orta** [comment]
Looks like InfoQ has them: https://www.infoq.com/news/2014/10/typescript-11-ctp-available/

**Comment by jHabjanMXP** [comment]
@orta any updates?

**Comment by orta** [comment]
You're welcome to update the site 👍🏻
