### ISSUE TITLE
Idea: Estimate time to complete Handbook

### ISSUE THREAD

**Issue by siddtheone** [microsoft/TypeScript-Website#2077]
**Why:**

On [typescript from start](https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html) page, in end it's mentioned that handbook can be completed in 30 minutes.
This doesn't seem practical and discourage people if they can't do so. Currently its 183 pages.

**Alternative ideas:**

We should change 30 minutes to something practical value.

**Comment by orta** [comment]
Yeah, maybe we should just drop it all together
