### ISSUE TITLE
Playground: Arrays with length more than 1 have html strings attached to its elements

### ISSUE THREAD

**Issue by marcincichocki** [microsoft/TypeScript-Website#2080]
When logging array with at least 2 elements, html strings are concatenated to its elements: `<span class='comma'>` and `</span>`. This is pure visual issue, as array elements are not modified.

![image](https://user-images.githubusercontent.com/10232391/136793966-0cd145af-9627-4fff-a0c0-3f307fb2f9fb.png)

**Repro:**
https://www.typescriptlang.org/play?ts=4.4.3#code/MYewdgziA2CmB0w4EMBOAKAlAbgLAChRIYFoQBzdAbQEYAaAAgCZGBmAXRwKKjnjMpUALE07YgA

**Expected behavior:**
No HTML strings in arrays.

**Actual behavior:**
UI code is leaking through playground's console.

edit: same applies for other objects: `Set`, `Map` even `undefined`
edit2: Looks like this function is causing it: https://github.com/microsoft/TypeScript-Website/blob/0574037ab672e12eb93109bee3a94bb9a9b1b287/packages/playground/src/sidebar/runtime.ts#L241-L243

`<` and `>` are escaped and so are not treated as html, therefore leaking to console ui.

**Comment by orta** [comment]
Thanks, this should be fixed in prod now 👍🏻
