### ISSUE TITLE
Docs: The displayed name for some TSConfig options is in camel rather than title case

### ISSUE THREAD

**Issue by devuxer** [microsoft/TypeScript-Website#2089]
**Page URL:** https://www.typescriptlang.org/tsconfig

**Issue:** 

The human-readable displayed name for the following TSConfig options is in camel rather than title case:

- exactOptionalPropertyTypes
- noImplicitOverride
- noPropertyAccessFromIndexSignature
- noUncheckedIndexedAccess
- useUnknownInCatchVariables
- preserveValueImports
- jsxFragmentFactory
- jsxImportSource
- explainFiles
- disableReferencedProjectLoad
- watchFile
- watchDirectory
- fallbackPolling
- synchronousWatchDirectory
- excludeDirectories
- excludeFiles
- enable
- disableFilenameBasedTypeAcquisition

The display name for all other options is title case.

**Recommended Fix:** Make the display name in the frontmatter table for all of the above options title case.

**Comment by orta** [comment]
👍🏻 yep, sounds good
