### ISSUE TITLE
ATA: support parallel downloading of types

### ISSUE THREAD

**Issue by YousefED** [microsoft/TypeScript-Website#2100]
In this code, everytime the `ata("code")` function is called, the download counts are reset. I think it would be useful to be able to call the `ata` function in parallel (e.g.: for multiple code snippets).

See: https://github.com/microsoft/TypeScript-Website/blob/b728a42ae4bbce647f41ef68ef4971509f8490c5/packages/ata/src/index.ts#L53

The overall design should work well for this right? I think we'd need to look at the following:
- don't reset download counters
- Add a check for `estimatedToDownload === 0` before calling `finished`

**Comment by orta** [comment]
I thought it was downloading parallel all the .d.ts files in a single module, which is usually enough to be hitting the limits of a browser's parallel download limit ( which I think is like 5ish) but I could be wrong. This library is definitely built in mind of having a singleton doing all the work against one code sample, so it might require some clever work to undo that choice.

**Comment by YousefED** [comment]
> I thought it was downloading parallel all the .d.ts files in a single module, which is usually enough to be hitting the limits of a browser's parallel download limit ( which I think is like 5ish) but I could be wrong.

Yes, I think it's downloading in parallel (that's not my issue indeed)

> This library is definitely built in mind of having a singleton doing all the work against one code sample, so it might require some clever work to undo that choice.

Yep, this is my issue (I have multiple editors & code samples). What other changes do you think it would require besides what I suggest above? I can give a go at it with some guidance

**Comment by orta** [comment]
Unsure, I guess maybe there'd need to be something which links each call of `ata` to their corresponding download trees and then only pass back the consolidated summary of all the possible calls to the single delegate
