### ISSUE TITLE
ATA: Package incorrectly identifies itself as ESM but is actually CJS

### ISSUE THREAD

**Issue by JakobJingleheimer** [microsoft/TypeScript-Website#2101]
**Improvement Idea:**

ATA's package.json specifies the package `type` as `"module"`, meaning it is entirely ESM. However, only the source code is ESM and the distribution is CJS.

In order to avoid a breaking change, I propose adjusting the build to output both the current CJS and ESM, and then use package.json `exports` to identify which consumers should use. Also in order to avoid most scenarios of a breaking change, the distributed CJS must use the `.cjs` file extension to override package.json's `"type": "module"`; the `.cjs` file extension is not _fully_ backwards compatible, but Node [v12.16](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#2020-04-08-version-12162-erbium-lts-codebytere)+ supports it.

**Alternative ideas:**

* (Possible internal breaking change) Remove the (currently) erroneous `"type": "module"` from package.json

---

I can submit a PR for this, but wanted to discuss the proposal before doing the work in case there are any concerns or objections.

**Comment by orta** [comment]
I'm pretty open to anything realistically. The Playground doesn't consume the library via the npm module and so I've not gone through the ropes of actually using it that way. I think I added "type: module" to test some TS 4.5 features.

Perhaps its best that we ship as ESM only and have esbuild create a esm output and just stick with that?

**Comment by JakobJingleheimer** [comment]
Sure! If CJS doesn't matter, that's even easier!

PR incoming 🙂
