### ISSUE TITLE
Idea: Color scheme in AST panel is not dark mode compatible

### ISSUE THREAD

**Issue by marvinhagemeister** [microsoft/TypeScript-Website#2108]
**Improvement Idea:**

Update color scheme in AST panel for dark mode

**Why:**

It's hard to read, see

<img width="619" alt="Screenshot 2021-10-24 at 22 33 08" src="https://user-images.githubusercontent.com/1062408/138611844-1b059f56-be69-4796-8f24-4cae08e5bf58.png">

**Alternative ideas:**
n/a

**Comment by orta** [comment]
Agree 👍🏻
