### ISSUE TITLE
Playground: error in worker cloning when code has error

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#2122]
```ts
class C {
    method(): UnresolvedType {
    }
}
```

[Playground Link](https://www.typescriptlang.org/play?ts=4.5.0-dev.20211101#code/MYGwhgzhAEDC0G8CwAoa7oFsCmAXAFgPYAmAFAJQBc0AqgHYBO2EhIAbtsQCoCeADtkSoM0AL6pRQA)

Right now, `.js` emit just fails in the playground with this code, and you get the following error in the console:

```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': function (start, end) { return text.substring(start, end); } could not be cloned.
    at https://typescript.azureedge.net/cdn/4.5.0-dev.20211101/monaco/dev/vs/base/worker/workerMain.js:11571:30
    at Object.sendMessage (https://typescript.azureedge.net/cdn/4.5.0-dev.20211101/monaco/dev/vs/base/worker/workerMain.js:8170:21)
    at SimpleWorkerProtocol._send (https://typescript.azureedge.net/cdn/4.5.0-dev.20211101/monaco/dev/vs/base/worker/workerMain.js:8077:27)
    at https://typescript.azureedge.net/cdn/4.5.0-dev.20211101/monaco/dev/vs/base/worker/workerMain.js:8042:22
```

Looks like some type is not getting normalized in Monaco TypeScript?

**Comment by DanielRosenwasser** [comment]
It looks like the server might be sending scriptsnapshots across the workers?

https://github.com/microsoft/monaco-typescript/blob/6b6fc00cc12b7eb9597632c20201daa6b80a142f/src/tsWorker.ts#L119-L130

**Comment by orta** [comment]
Yeah, that feels right (and wrong)
