### ISSUE TITLE
tsWorker.js loaded from new playground is too heavy

### ISSUE THREAD

**Issue by Quramy** [microsoft/TypeScript-Website#213]
Why new tsWoker's bundle size is 5 times larger than one of v1 ? 🤔 
For now, loading v2 tsWorker takes over 10 secs and it makes bad experience.

#### v1

http://www.typescriptlang.org/play/?ts=3.8-Beta

<img width="935" alt="スクリーンショット 2020-02-05 18 37 10" src="https://user-images.githubusercontent.com/1262998/73829755-d7950680-4846-11ea-9297-c078e8a85769.png">

#### v2

https://www.typescriptlang.org/v2/en/play?ts=3.8.0-beta

<img width="1164" alt="スクリーンショット 2020-02-05 18 38 21" src="https://user-images.githubusercontent.com/1262998/73829789-e54a8c00-4846-11ea-9237-739913ca4299.png">

**Comment by Quramy** [comment]
Is this problem of Content-Encoding ? It seems that v1 's .js file is encoded with `br` but v2 file is not.

**Comment by orta** [comment]
Hrm, yeah, the new one comes from azure blob storage and the old one is unpkg. I wonder if they have a way to do gzip etc

**Comment by orta** [comment]
I think I've turned on a CDN for the files:

- old https://tswebinfra.blob.core.windows.net/indexes/releases.json
- new https://typescript.azureedge.net/indexes/releases.json

**Comment by Quramy** [comment]
Thanks for reply. 

Pls close this issue when the files are delivered from Azure CDN.

**Comment by Quramy** [comment]
I confirmed the new URL,  `https://typescript.azureedge.net/cdn/3.7.3/monaco/min/vs/language/typescript/tsWorker.js`, with latest v2 branch on my local machine 🎉 

Thanks for quick fix!
