### ISSUE TITLE
"callerNumber" instead of "calledNumber"

### ISSUE THREAD

**Issue by Deluvio** [microsoft/TypeScript-Website#2130]
https://github.com/microsoft/TypeScript-Website/blob/96eb5f58e58fcb7d8ba05ee6fcc9334feacf3103/packages/playground-examples/copy/en/TypeScript/Language/Type%20Guards.ts#L73
i think it should be `"callerNumber"` instead of `"calledNumber"`

**Comment by orta** [comment]
Agree!

**Comment by arghyab0** [comment]
Hey @orta, can I take this issue up ?

**Comment by orta** [comment]
Sure, it's a typo - feel free to fix it
