### ISSUE TITLE
Shareable links in playground broken for current and beta versions

### ISSUE THREAD

**Issue by WORMSS** [microsoft/TypeScript-Website#214]
Shareable links in playground broken for current and beta versions
Chrome 79, incognito mode.

### Reproduce current
* change content of playground,
* click + S
* Notice url is copied to clipboard notice, but the clipboard url is not shareable

### Reproduce beta
* change content of playground
* click + S
* Notice standard HTML save dialog is shown, no url in clipboard, url is shareable.

**Comment by orta** [comment]
Yeah, I still ned to add keyboard shortcuts to the new playground #194 

Maybe it's an incognito privacy feature on current? Works for me in safari just now

**Comment by WORMSS** [comment]
It used to work, as I use incognito as my "throwaway testing" as I like to keep my ongoing/utility types in the normal local storage. Only today has it started to faulter. And I havent updated chrome since yesterday. So presumed an update had gone out for the site, since I didn't remember seeing try beta button yesterday either

**Comment by WORMSS** [comment]
@orta 
New info
Chrome: 80.0.3987.87 (Official Build) (64-bit) (Incognito)

So, came back to the issue this morning.
Things I didn't notice.
### Current
* If you click Run, the URL bar is blanked, This must have been when I clicked "Ctrl+S" to save this current state, (now that I knew it was working).. So, bad timing I guess.
* If you open a new tab, you load in the local-storage data, but the URL is still blank, so pressing Ctrl+S at this point again becomes the blank URL.

#### Simple solution?
* Ctrl+S = "ensure the URL contains the latest shareable data, THEN do the copy"

#### Extended solution
* Run button = "ensure the URL contains the latest shareable data after running"
* Load local-storage = "ensure the URL contains the shareable data"

**Comment by orta** [comment]
This _seems_ to be fixed now, will leave it open to give you a chance to verify

**Comment by WORMSS** [comment]
Yep, confirmed. 
Though, I can't tell if "beta" playground is now the current playground, since this was a year old.
I went by the assumption it is..

**Comment by orta** [comment]
Hah, yeah it was, probably 👍🏻
