### ISSUE TITLE
A strange link in hankbook.

### ISSUE THREAD

**Issue by ruojianll** [microsoft/TypeScript-Website#2146]
`https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#support-for-umd-module-definitions`.

The link of `Isomorphic` redirected to a strange page in above section.

`http://isomorphic.net/`

**Comment by orta** [comment]
I guess the website must have gone away since then, perhaps wikipedia is now the best link: https://en.wikipedia.org/wiki/Isomorphic_JavaScript
