### ISSUE TITLE
Docs: "Non-null assertion operator" ' !. '  not documented anywhere except 2.0 release notes

### ISSUE THREAD

**Issue by peternann** [microsoft/TypeScript-Website#2151]
**Page URL:**  https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator

**Issue:**
As far as I can tell the "!." operator is only mentioned/documented in the 2.0 release notes. Nowhere else.
Surely it is not normal to require users to read all release notes to learn a language?
Release notes can even become incorrect, if breaking changes occur in the future, so they should not really be seen as a source for reference.

**Recommended Fix:**
It should be documented in the main language doco, somewhere.
An 'operators' summary page would be great.
If it is already in there somewhere, I do apologise, but I could not find it - Which could be another issue perhaps.

I hope you find this constructive, which is how it is intended.
I thought I knew all the operators in Typescript. Today I learned that I did not.
Cheers.

**Comment by fatcerberus** [comment]
https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#non-null-assertion-operator-postfix-
