### ISSUE TITLE
Idea: Make dark theme detection dynamic on handbook pages

### ISSUE THREAD

**Issue by jakub-g** [microsoft/TypeScript-Website#2155]
**Improvement Idea:** Make dark theme detection dynamic. 

**Why:** I set my OS to automatically switch to dark mode at 6PM.

Some pages (e.g. GitHub) automatically follow this and apply the dark mode correctly. On TS handbook pages though, I need to refresh the page to get dark mode.

**How**: 
From [quick search](https://stackoverflow.com/a/59621903/) it seems possible to listen to dark mode change with `addEventListener` on `matchMedia`:

```js
window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", e => {
   if (e.matches) {
        activateDarkMode()
   } else {
        activateLightMode() 
   }
}
```

From what I see the change should be applied here:
https://github.com/microsoft/TypeScript-Website/blob/8172b26caa47c2d0a49751bb60d5a48f175d0c60/packages/typescriptlang-org/gatsby-ssr.js#L23-L30

**Alternative ideas:**

The above is probably the only way

**Comment by orta** [comment]
TBH, we might want to just reload the page - I'm sure there'll be places where it won't just be based on CSS (like the playground )
