### ISSUE TITLE
Playground: 

### ISSUE THREAD

**Issue by akramnarejo** [microsoft/TypeScript-Website#2167]
**Repro:**

**Expected behavior:** Website should not reload upon re-selecting the running typescript version. 

**Actual behavior:** Website reloads upon re-selecting the running typescript version again.

**Comment by orta** [comment]
This is unlikely to change, the TypeScript version controls the monaco build and enables/disabled features inside the playground having all that change at runtime isn't really worth the complexity.

**Comment by akramnarejo** [comment]
> This is unlikely to change, the TypeScript version controls the monaco build and enables/disabled features inside the playground having all that change at runtime isn't really worth the complexity.

oh, it's alright then if it has others things also to be affected.
