### ISSUE TITLE
Default for generic parameters is not documented in the handbook

### ISSUE THREAD

**Issue by ArneBab** [microsoft/TypeScript-Website#2172]
The option to set a default for a generic parameter is noted in the [release notes for 2.3](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#generic-parameter-defaults), but not in the [generics section of the handbook](https://www.typescriptlang.org/docs/handbook/2/generics.html).

Is this intentional? Does this have implications on the stability of the syntax?

**Comment by orta** [comment]
Good spot, yeah, this is just an omission - TypeScript doesn't break old syntax, so it's always going to stick around

**Comment by jzxchiang1** [comment]
Yeah, this was confusing to me.
