### ISSUE TITLE
Docs: Awaited Type

### ISSUE THREAD

**Issue by holgergp** [microsoft/TypeScript-Website#2178]
**Page URL:** https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#the-awaited-type-and-promise-improvements

**Issue:** The docs for the newly introduced Awaited type could be improved. At least I have a hard time grasping the concept

**Recommended Fix:** 
I haven't grasped the concept fully, so the suggested changes/additions may worsen the docs altogether. But here we go:

Things I've been stumbling over this far:
- `Awaited` is _not_ the Return type of an async function. That was my first impression. That Return Type still is `Promise<T>`. 
- `Awaited` can be used in (maybe rare) occasions, where I want to explicitly type the returned value of an awaited call.
- `Awaited` then helps me to avoid maybe nested/recursive Promises: e.g `Promise<Promise<string>>`
  - As a sidenote: I even struggled to find an example where I can construct such nested Promise construct. Maybe a hint here may be helpful to others to.
- The second code example does not even mention the `Awaited` type. I would have find it easier to understand if it would have been explicitly stated. Maybe another example would help here.
Maybe something like this (if I have understood it correctly....)

<code>

const pipe = (f, g, h) => (input) => h(g(f(input)));

const thirdAsyncFn = async (): Promise`<string>` => {
    return '3';
};

const secondAsyncFn = async (): Promise`<string>`  => {
    return '2';
};

const firstAsyncFn = async (): Promise`<string>`  => {
    return '1';
};
const pipedFn = pipe(firstAsyncFn, secondAsyncFn, thirdAsyncFn);

const returnedValue1: Promise<Promise<Promise`<string>`>> = pipedFn(2);

const returnedValue2: Awaited<Promise`<string>`> = pipedFn(2);

</code>

**Comment by holgergp** [comment]
I can provide a PR, if I understood it correctly 😅 and this is something you find useful as well.

**Comment by orta** [comment]
Sure, give it a shot - I'll assign Ron if your changes are pretty drastic

**Comment by tipakA** [comment]
Is there any movement regarding adding the `Awaited<Type>` type to the [Utility Types](https://www.typescriptlang.org/docs/handbook/utility-types.html) page?
