### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by Joelmmm** [microsoft/TypeScript-Website#2186]
**Page URL:**  https://github.com/microsoft/TypeScript-Website/blob/214c43393439526191b824b4d578571bf20cd004/packages/documentation/copy/en/handbook-v2/More%20on%20Functions.md#optional-parameters

**Issue:**  The example talks about optional arguments and says the `toFixed` method of `number` takes an optional digit count. But in the code a function is declared with an optional parameter representing the number on which `toFixed` is called instead of the number that may be passed to the method as argument.

**Recommended Fix:** 
Instead of: 
```js
function f(n: number) {
  console.log(n.toFixed()); // 0 arguments
  console.log(n.toFixed(3)); // 1 argument
}
```
maybe it could be: 
```js
function f(n: number, x?: number) {
  console.log(n.toFixed()); // 0 arguments
  console.log(n.toFixed(x)); // 1 argument
}
```

**Comment by orta** [comment]
Agree 👍🏻
