### ISSUE TITLE
Docs: docs/handbook/compiler-options broken links 

### ISSUE THREAD

**Issue by mbelsky** [microsoft/TypeScript-Website#2191]
Hey,

**Page URL:** [docs/handbook/compiler-options](https://www.typescriptlang.org/docs/handbook/compiler-options.html)

**Issue:** this page contains some broken urls, like https://www.typescriptlang.org/docs/handbook/compiler-options.html#strict
<img width="1133" alt="Screenshot 2021-12-16 at 11 12 11" src="https://user-images.githubusercontent.com/3923527/146352253-cf8e38b0-8495-4cc2-8434-223417f48664.png">

**Recommended Fix:** I can't recommend any fix, but I have an idea how to fix that. These urls could be replaced with links to `tsconfig` page, like `/docs/handbook/compiler-options.html#strict`→`/tsconfig#strict` . If this is a correct fix, I can help with fixing that.

**Comment by orta** [comment]
I think we might need special string replacements on those links inside the generator in https://github.com/microsoft/TypeScript-Website/tree/v2/packages/tsconfig-reference/scripts/cli
