### ISSUE TITLE
Docs: Add short flags to tsc cli docs

### ISSUE THREAD

**Issue by KyleMit** [microsoft/TypeScript-Website#2205]
**Page URL:** https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Issue:** Missing short flags for CLI options

**Recommended Fix:** It looks like some of the docs may be generated (`<!-- Start of replacement  -->`) - so might not be trivial, but a lot of online guides use the short flags - i.e. "run `tsc -p`.  When browsing the documentation, it doesn't indicate what those flags are associated with.  Would it be possible to add the short flag aliases to the generated output as well

**Workaround**: This is included in the output from `tsc --help`

![example output with short flags from tsc help command](https://user-images.githubusercontent.com/4307307/147858972-27c30bee-7959-47cb-86ef-1ef294ae381d.png)

**Comment by orta** [comment]
Agree, sounds like a good first PR to the repo for someone 👍🏻

**Comment by KyleMit** [comment]
@orta, any idea wher to look?  It'd be easy enough to add them via updating the docs manually, but not sure where the `<!-- Start of replacement -->` is happening?

**Comment by orta** [comment]
The process for generating that CLI is in these two files: https://github.com/microsoft/TypeScript-Website/tree/v2/packages/tsconfig-reference/scripts/cli - I think you'll need to find out how typescript stores the single char alias in the options objects and make it add that to the name in the table

**Comment by FyiurAmron** [comment]
@KyleMit @orta any chance on having this restarted? AFAIU, this is still not present in the docs, even after all the years that have passed, and the short args are still mostly tribal knowledge (i.e. have to be deduced from actual run and not explicitly documented externally)?
