### ISSUE TITLE
TypeScript Playground Plugin ideas

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#221]
- An LSP-ish Playground where you can make see the response to specific calls
- An English explainer which explains a complex TS type
- Convert TS dts -> Flow interfaces(flowgen)
- Run tutorials in the playground against live code as a learning tool
- AST Viewer
- ts-query runner
- codemod runner
- Highlight TS vs JS (or type vs value) parts of some code code
- Show all used types in a file
- Show dts files in the current workspace
- Edit an ambient dts file

**Comment by Quramy** [comment]
Can Playground plugin API configure monaco editor’s key-bindings ? I want vim key-bindings.

**Comment by orta** [comment]
Yep, `sandbox.editor` gives you access to the current monaco - you might be able to just use the code from https://github.com/brijeshb42/monaco-vim directly via AMD

**Comment by orta** [comment]
[Sourcemap preview](https://sokra.github.io/source-map-visualization/#base64,InVzZSBzdHJpY3QiOw0KZnVuY3Rpb24gdGVzdChmKSB7DQogICAgZigpOw0KICAgIHJldHVybiB7IGE6ICJ0ZXN0IiB9Ow0KfQ0KdmFyIGIgPSB0ZXN0KGZ1bmN0aW9uICgpIHsNCiAgICBjb25zb2xlLmxvZygiZm9vMSIpOw0KICAgIGNvbnNvbGUubG9nKCJmb28yIik7DQp9KS5hOw0KdmFyIGRhdGEgPSB0ZXN0KGZ1bmN0aW9uICgpIHsNCiAgICBjb25zb2xlLmxvZygiZm9vMyIpOw0KICAgIGNvbnNvbGUubG9nKCJmb280Iik7DQp9KTsNCi8vIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LmpzLm1hcA==,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi9pbmRleC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQ0EsU0FBUyxJQUFJLENBQUMsQ0FBVztJQUNyQixDQUFDLEVBQUUsQ0FBQztJQUNKLE9BQU8sRUFBRSxDQUFDLEVBQUUsTUFBTSxFQUFFLENBQUM7QUFDekIsQ0FBQztBQUVPLElBQUE7OztJQUFJLENBR1Q7QUFFSCxJQUFNLElBQUksR0FBRyxJQUFJLENBQUM7SUFDZCxPQUFPLENBQUMsR0FBRyxDQUFDLE1BQU0sQ0FBQyxDQUFDO0lBQ3BCLE9BQU8sQ0FBQyxHQUFHLENBQUMsTUFBTSxDQUFDLENBQUM7QUFDeEIsQ0FBQyxDQUFDLENBQUMifQ==,DQpmdW5jdGlvbiB0ZXN0KGY6IEZ1bmN0aW9uKTogeyBhOiBzdHJpbmcgfSB7DQogICAgZigpOw0KICAgIHJldHVybiB7IGE6ICJ0ZXN0IiB9Ow0KfQ0KDQpjb25zdCB7IGE6IGIgfSA9IHRlc3QoKCkgPT4gew0KICAgIGNvbnNvbGUubG9nKCJmb28xIik7DQogICAgY29uc29sZS5sb2coImZvbzIiKTsNCn0pOw0KDQpjb25zdCBkYXRhID0gdGVzdCgoKSA9PiB7DQogICAgY29uc29sZS5sb2coImZvbzMiKTsNCiAgICBjb25zb2xlLmxvZygiZm9vNCIpOw0KfSk7DQo=)

**Comment by Quramy** [comment]
I made a plugin to apply Vim keybindings https://github.com/Quramy/ts-playground-plugin-vim 🎉

**Comment by orta** [comment]
Ace!

**Comment by orta** [comment]
#520 

also:

`sourceFile.locals` is a private variable that gives you a list of all the symbols at the local root of the 
source file, which can be a starting point for showing what types are defined in the current file
