### ISSUE TITLE
Outdated releases page

### ISSUE THREAD

**Issue by cefn** [microsoft/TypeScript-Website#2220]
I searched for `Typescript Next Release` on Google

It took me to...
https://www.typescriptlang.org/upcoming/

which states...

```Our next release is 4.4, which is planned for Aug 24```

This seems to be populated from the static data at https://github.com/microsoft/TypeScript-Website/blob/0de3ae9831231f31a0ee7f2cf885ad5acc9ad114/packages/typescriptlang-org/src/lib/release-plan.json

There's an automation approach for populating this indicated at https://github.com/microsoft/TypeScript-Website/commit/77e14ccc91263ff167dd371b2c910f95aa220093 to refresh it. 

I attempted to run this to raise a PR but calling...

```
node packages/typescriptlang-org/scripts/getTypeScriptNPMVersions.js
```

...failed with ...

```sh
TypeScript-Website % node packages/typescriptlang-org/scripts/getTypeScriptNPMVersions.js
(node:80410) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:80410) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:80410) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by orta** [comment]
Ah yeah, I forgot to remove that page during the homepage redesign - it was an internal page not linked anywhere so I assumed it would not turn up but I guess it must be in a sitemap

**Comment by orta** [comment]
This will ship on the next prod deploy - thanks!
