### ISSUE TITLE
Docs: 4 legged bees

### ISSUE THREAD

**Issue by VsevolodGolovanov** [microsoft/TypeScript-Website#2229]
**Page URL:** 
https://www.typescriptlang.org/docs/handbook/2/generics.html#using-class-types-in-generics

**Issue:** 
```
class Animal {
  numLegs: number = 4;
}
 
class Bee extends Animal {
  keeper: BeeKeeper = new BeeKeeper();
}
```
This example implies that bees have 4 legs. They have 6.

**Recommended Fix:** 
Change bees to cats.

**Comment by orta** [comment]
Oh yeah, I probably chose Bee because I wanted to have it be a different number of legs inside the class
