### ISSUE TITLE
Docs: Construct signatures for Date object is incorrect

### ISSUE THREAD

**Issue by jimmy-liao-gogoro** [microsoft/TypeScript-Website#2233]
**Links:**
- [Construct signatures](https://www.typescriptlang.org/docs/handbook/2/functions.html#construct-signatures)
- [Construct signatures TS Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMJwDYYPJVQexAGcwoBXBMZAbwFgAoZZECAd2QAoiAuZEqUAHMAlLwAicSAG4GTDiAD8vEGQC2AI2ijmazVBn0AvkA)

In `lib.es5.d.ts`, this is DateConstructor interface:
```ts
interface DateConstructor {
    (): string; // Please notice this constructor signature without new 
    new(): Date;
    new(value: number | string): Date;
    new(year: number, month: number, date?: number, hours?: number, minutes?: number, seconds?: number, ms?: number): Date;
    // skip rest of them
}
```

But in [Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMJwDYYPJVQexAGcwoBXBMZAbwFgAoZZECAd2QAoiAuZEqUAHMAlLwAicSAG4GTDiAD8vEGQC2AI2ijmazVBn0AvkA), this is CallOrConstruct interface:
```ts
interface CallOrConstruct {
  new (s: string): Date;
  (n?: number): number; // this is not matched with DateConstructor without new
}
```

**Repro:**
When document reader tries to create a function with CallOrConstruct parameter: `createDate(D: CallOrConstruct): void`.
They call `createDate(Date)` and see the type error.
```ts
const createDate = (D: CallOrConstruct) => {
  const d1 = new D('2021/01/21');
  const d2 = D();
  console.log('d1', d1);
  console.log('d2', d2);
}

createDate(Date);
// error message: Argument of type 'DateConstructor' is not assignable to parameter of type 'CallOrConstruct'.
// Type 'string' is not assignable to type 'number'.(2345)
```
[Link for this incorrect example](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMJwDYYPJVQexAGcwoBXBMZAbwFgAoZZECAd2QAoiAuZEqUAHMAlLwAicSAG4GTDiAD8vEGQC2AI2ijmazVBn0AvgwYJCJZAigRJECZGQBeTmN7osuAsVIUwwpwB8NLKW5lQAJgCMTsxsyGIcAOQATAAMyZEA9KlZGYnCBkxm3sjhyTEJBSHFRPgYEAB0GPiCSVGJADSlkVWMocR1jc2tiWWdpcm9xvSm1rb2EBwLvZmZyACCUIJqEODI+DDIYACeAA4oiQte-L74UInIwETM+FRwRETAgiBw6vVH+GQpzgUDgqggkCg+0OJ3OyES7hweDC5EoiQaDFWyAAKmcLvwhA8ni83h8vj8-igwIDYRcVBpoOiOMkAMwAFgArMIgA)

**Expected behavior:**
CallOrConstruct should be matched with DateConstructor.
And there is no error while `createDate(Date)` .

**Actual behavior:**
There is an error while `createDate(Date)` .
Because CallOrConstruct should be
```ts
interface CallOrConstruct {
  new (s: string): Date;
  (): string; // now this signature is matched with DateConstructor in `lib.es5.d.ts`
}
```
[Link for this modified example](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMJwDYYPJVQexAGcwoBXBMZAbwFgAoZZECAd2QAoiAuZEqUAHMAlLwAicSAG4GTDqL6khM+gF8GDBIRLIEUCJIgTIyALycxvdFlwFipCmGFmAfDVm7tVACYBGM8xsyGIcAOQATAAM4b4A9JFxMaHCKkxa9sje4QEhKR7pRPgYEAB0GPiCYX6hADSZvnmMnsRFpeWVoVm1meGN6vSa+obGEBwjKUA)

**Comment by LiaoJimmy** [comment]
@orta Hi, I'm @jimmy-liao-gogoro .
Can I fix this issue by myself?
I'd like to update this
```ts
// before
interface CallOrConstruct {
  (n?: number): number;
}
```
to this
```ts
// after
interface CallOrConstruct {
  (): string; 
}
```

**Comment by orta** [comment]
This issue wouldn't need to be talked about (and fixed)  in the main TypeScript repo, rather than here in the website. I'd recommend moving it to there 👍🏻

**Comment by jimmy-liao-gogoro** [comment]
> This issue wouldn't need to be talked about (and fixed) in the main TypeScript repo, rather than here in the website. I'd recommend moving it to there 👍🏻

Thank you for your kindly reply.
May I ask you where should I move this issue?
I think this is [documentation issue](https://github.com/microsoft/TypeScript-Website/blob/2814689e0b802259018b59ab4e989e3173c625c4/packages/documentation/copy/en/handbook-v2/More%20on%20Functions.md?plain=1#L84) in TS website.

**Comment by orta** [comment]
It seems to me that you want to change the version in es5.d.ts?

**Comment by LiaoJimmy** [comment]
No. I want to change in this repo:
[TypeScript-Website/packages/documentation/copy/en/handbook-v2/More on Functions.md, L84](https://github.com/microsoft/TypeScript-Website/blob/2814689e0b802259018b59ab4e989e3173c625c4/packages/documentation/copy/en/handbook-v2/More%20on%20Functions.md?plain=1#L84)

I think this line should be
```
  (): string; 
```
because there is no parameter in `Date()` and it return string.

**Comment by jimmy-liao-gogoro** [comment]
@orta sorry, I think this is documentation issue, not playground.
