### ISSUE TITLE
Playground: Multi-file feature is broken

### ISSUE THREAD

**Issue by DanielSWolf** [microsoft/TypeScript-Website#2237]
The `// @filename:` twoslash annotation doesn't seem to work. Note the following points in the screenshot below:

* At the very top, there is a blue line saying `// @filename: /input.tsx`. I'm assuming this line should coincide with my actual `@filename` annotations, but it doesn't.
* In line 5, the import says it can't find a file './sum', even though a `@filename` twoslash annotation with this name is right below.
* In line 7, the code has access to the `sum` function. This is *not*, however, because the import is working, but merely because the playground seems to be treating the entire source code as a single file, ignoring the `@filename` twoslash annotations.

![image](https://user-images.githubusercontent.com/5963162/150630192-9c83ede7-417a-4d35-951d-21f0e329b325.png)

**Repro:**

[Playground link](https://www.typescriptlang.org/play?ts=4.5.4&q=420#code/PTAEAEDMEsBsFMB2BDAtvAXKA5gJ3vAC7y4B0hAzgLABQt9N0qADgPa6GgDeoFArqlABfUJFytBAclLB+qSQG4GAY1aIKrBKVitsACgAGARlABqUCYC8oACRc5eowBoLASiEHXSujRCi4SGiYvALk1D7wAB5sHKJ8iMqE0GohqHrIWIgCAEYkLtmZOSSu3LSgoPiEfLiIoMhmoNneQrRAA)

**Expected behavior:**

The twoslash annotation `// @filename: some-file.ts` should begin a new logical file, as [documented here](https://www.typescriptlang.org/play?ts=4.5.4&q=420#handbook-16).

**Actual behavior:**

The twoslash annotation is ignored.

**Comment by orta** [comment]
Hrm, it looks like I turned off the multi-file unless you add the flag `?multifile=true` to the playground. I can't quite remember why, but I assume it was a quick fix because it fundamentally affects the non-multifile editor support when it was off. 

I think the best strategy is that I update the docs on this.

**Comment by DanielSWolf** [comment]
I added `multifile=true&...` to the URL, but the import still doesn't seem to work: [Playground link](https://www.typescriptlang.org/play?multifile=true&ts=4.5.4#code/PTAEAEDMEsBsFMB2BDAtvAXKA5gJ3vAC7y4B0hAzgLABQt0qADgPa6GgDeoFArqqAF9QkXM34ByUsF6pxAblq0Axs0QVmCUrGbYAFAAMAjKADUoYwF5QAEg4zdhgDTmAlAP0uFdGiGFwkaJjcfOTU3vAAHixswjyISoTQqsGoushYiHwARiTOWRnZJC6ctKCg+IQ8uIigyKagWV4CtEA)

**Comment by orta** [comment]
Ah, it's case sensitive `multiFile`, and seems to largely be broken after the move to handle monaco esm. I'm going to fully deprecate it and remove it from the docs. Thanks (I'd recommend using something like code sandbox to do multi-file repros)

**Comment by DanielSWolf** [comment]
I think that removing the feature would be a pity! It's so convenient for quickly sketching a multi-file setup. Can't it be fixed?

**Comment by orta** [comment]
Sure, you're welcome to take a look at it ( the code is in https://github.com/microsoft/TypeScript-Website/tree/v2/packages/playground-worker ) - but realistically I'm not sure if I'll find the time and I'd rather not be setting the wrong expectations for folks

**Comment by DanielSWolf** [comment]
Point taken. 😉
