### ISSUE TITLE
V2 tsconfig documentation errors

### ISSUE THREAD

**Issue by FletcherGoss** [microsoft/TypeScript-Website#224]
Location: <https://www.typescriptlang.org/v2/en/tsconfig#include>

It says:  `"include": ["src/**", "tests/**"]`

This throws an error: "File specification cannot end in a recursive directory wildcard ('**'):"

It should be: `"include": ["src/**/*". "tests/**/*"]`

---

Location: https://www.typescriptlang.org/v2/en/tsconfig#removeComments

The main bulk of text and the right-hand sidebar conflict. One says "Defaults to `true`". The other says "Default `false`". In practice, it's `false`.

---

Location: https://www.typescriptlang.org/v2/en/tsconfig#allowUnusedLabels | https://www.typescriptlang.org/v2/en/tsconfig#allowUnreachableCode

They say: "Set to false to disable warnings about"
They should be: "Set to true to disable warnings about"

---

importHelpers is included in both Project Options and Advanced. Is this intentional?

---

More than happy to submit a PR for these myself. Just wanted to double check it isn't a case of changes coming down the pipeline, and that the right place to edit these is `packages/tsconfig-reference/copy/en/options`.

**Comment by orta** [comment]
Yeah, all these sound like bugs - thanks!

I think the `importHelpers` one is tricky, I've not figured that out myself yet

**Comment by orta** [comment]
This is fixed ( thanks! )
