### ISSUE TITLE
Idea: Error pages per error code

### ISSUE THREAD

**Issue by mohsen1** [microsoft/TypeScript-Website#2244]
**Improvement Idea:**
Like hoe Rust has a URL in the error message per error code that takes you to a page explaining the error with more example 

Rust example: https://doc.rust-lang.org/error-index.html#E0308

BTW I don't like the super long page with fragment routing in Rust's website
**Why:**
Because some errors are really hard to make sense of. For example `ts(4026)` was hard for me to understand

**Alternative ideas:**
Make the error number a link to a google or something!

**Comment by orta** [comment]
Dupe of https://github.com/microsoft/TypeScript-Website/issues/298
