### ISSUE TITLE
[Playground] Twoslash highlights don't work with TS 4.6

### ISSUE THREAD

**Issue by Andarist** [microsoft/TypeScript-Website#2247]
**Repro:**

[repro playground](https://www.typescriptlang.org/play?ts=4.6.0-dev.20220116#code/C4TwDgpgBAsiCiA3CA7YBnKBeKBvKokAXFAOQBiA8paVAL5QA+eB4EJpAQgIIBKtdALAAoEQHoxUAIwjC0AJIoAJhAAenEABU2AHk1Q1wVEsz45JdMABOASxQBzegD5seEVCgBtANJQ7UTU9SOVIAXVCSeFVrAEMAY2A9ABoWcyhfOicAbhE6HNFhOShFFVUIJVcStQ1tSB04JFQMJ3FJKAA9AH4RVqgAJh7CtigAVRQbAHsUTQnFIyt0CATJlD0XHHcoAAp9Q2NMGJQQKE7t1RJNAEpsF0PjkhQIZCtrveVMTa3zvxQAMwgrFBeNcsLcjicgVAHk8AYMilV1Fo2H09AZovtUmwLNY7I5Mq4xisZnMAYtllNUW8TFA7hDeEsJlYlHpPAAiOSs0IpTQuaHPFoFCRQACu9gANsc5LJhgjyn1KspqkjICiGsg0OgBUKOt1BZIAMxw4YAYQmAFswMKjDpuGijO8aUd1iwfD8oABrCAgCa-KDcCJ+nyhehQABkIpQ7pQEwA7ih8tLIMVFYjahB9ZT0Q6zFioJZbA5nK5TRarRAdAiasi1gLesAABY2TBTaBWCAxCpm4VxetQABGEGA80TChT5X1CtKVcgGbVTU1vR1gyFABYjUnK8qICvM-bqTniHmcYX8ThcJtPPA3foYph4GyOeFIrkE0MN2OlCvJ0q0zu5xqtTaLogA)

**Expected behavior:**

It should work as it works for the current latest version of TS (4.5.x): [TS playground](https://www.typescriptlang.org/play?ts=4.5.4#code/C4TwDgpgBAsiCiA3CA7YBnKBeKBvKokAXFAOQBiA8paVAL5QA+eB4EJpAQgIIBKtdALAAoEQHoxUAIwjC0AJIoAJhAAenEABU2AHk1Q1wVEsz45JdMABOASxQBzegD5seEVCgBtANJQ7UTU9SOVIAXVCSeFVrAEMAY2A9ABoWcyhfOicAbhE6HNFhOShFFVUIJVcStQ1tSB04JFQMJ3FJKAA9AH4RVqgAJh7CtigAVRQbAHsUTQnFIyt0CATJlD0XHHcoAAp9Q2NMGJQQKE7t1RJNAEpsF0PjkhQIZCtrveVMTa3zvxQAMwgrFBeNcsLcjicgVAHk8AYMilV1Fo2H09AZovtUmwLNY7I5Mq4xisZnMAYtllNUW8TFA7hDeEsJlYlHpPAAiOSs0IpTQuaHPFoFCRQACu9gANsc5LJhgjyn1KspqkjICiGsg0OgBUKOt1BZIAMxw4YAYQmAFswMKjDpuGijO8aUd1iwfD8oABrCAgCa-KDcCJ+nyhehQABkIpQ7pQEwA7ih8tLIMVFYjahB9ZT0Q6zFioJZbA5nK5TRarRAdAiasi1gLesAABY2TBTaBWCAxCpm4VxetQABGEGA80TChT5X1CtKVcgGbVTU1vR1gyFABYjUnK8qICvM-bqTniHmcYX8ThcJtPPA3foYph4GyOeFIrkE0MN2OlCvJ0q0zu5xqtTaLogA)

**Actual behavior:**

It fails with this in the console:
> Uncaught Error: Cannot read properties of undefined (reading 'length')

**Comment by orta** [comment]
Noted in the upstream PR in monaco/vscode which broke it, you're welcome to either make a workaround in the playground or help get it resolved upstream

**Comment by Andarist** [comment]
I could work on implementing a workaround here. I'm not 100% sure how to handle this though. From what I understand, based on the response [here](https://github.com/microsoft/vscode/issues/129528#issuecomment-1031165744), we'd have to conditionally register the different shape of the inlay provider here:
https://github.com/microsoft/TypeScript-Website/blob/f189f5bcb676dcf6ff04966192593fa40942c62f/packages/playground/src/index.ts#L718

The question from my side would be - how to determine which shape should be registered? As far as I can tell this depends on the version of the Monaco that is being used and this is how the URL for that gets constructed:
https://github.com/microsoft/TypeScript-Website/blob/f189f5bcb676dcf6ff04966192593fa40942c62f/packages/typescriptlang-org/src/templates/play.tsx#L98

I'm not sure how the TS version relates to the Monaco version in this path. Can I safely assume that loading TS 4.6+ means that a new version of the inlay hints provider has to be created? From what I see the actual (semver~) version of Monaco is not exposed anywhere (I've checked `window.sandbox.monaco` in the playground).

**Comment by orta** [comment]
I've added a note that Monaco might want to have a version number so that this can be determined safely at runtime, ^

I think switching make-monaco-builds to stop using nightly Monaco and use an older commit for the while is probably the right call for the moment, a correct answer would probably need a change in ms/vscode which propagates down through monaco-editor-core

**Comment by Andarist** [comment]
So, in a sense - this ticket will get resolved for the time being once https://github.com/microsoft/TypeScript-Make-Monaco-Builds/pull/8 lands and gets redeployed?

**Comment by orta** [comment]
Yes, all the nightlies when it was broke will stay broke, but new nightlies (and releases) will get the static version of Monaco with newer TS

**Comment by orta** [comment]
I'm settling for a different answer after seeing https://github.com/microsoft/TypeScript-Website/pull/2267

I think we should update to use the new inlay format in the playground, and switch to only supporting the feature on 4.6+ when that comes out so we don't have to juggle two separate APIs with no obvious way to know which shape to give back to Monaco

**Comment by Andarist** [comment]
Damn, I love this feature! I guess though that once 4.6 gets released I won't have as many use cases for using this in pre-4.6 playgrounds 🤔 Whatever works I guess. 

It would be great though if we could push Monaco a little bit to include the version somewhere, cause I think this might be very useful in the future. The sooner we get access to it the easier it will be to overcome API incompatibilities in the feature without removing features from older playgrounds.

Do you have any good coordination plan for this release? I mean - I could create a PR to adjust how the API is used but that would have to sit unmerged until 4.6 release, right?

**Comment by orta** [comment]
Yeah, I have mentioned adding a version number in the runtime in https://github.com/microsoft/monaco-editor/issues/2948 - maybe we could bake it in via a script inside make-monaco-builds but I couldn't see an obvious place to add it from the outside

Yeah,  FWIW this is the first time a Monaco API has changed on the playground. And yeah, here's no 4.6 PR for the site yet, I was thinking of making one sometime this week as the 22nd is spec'd for the release day but you're welcome to take a look also: https://github.com/microsoft/TypeScript-Website/blob/v2/docs/New%20TypeScript%20Version.md is the guide

**Comment by orta** [comment]
Confirming that these are now working on production with 4.6 👍🏻 - issue can be closed, thanks @andarist
