### ISSUE TITLE
No 'watch' compiler option in V2 tsconfig documentation

### ISSUE THREAD

**Issue by FletcherGoss** [microsoft/TypeScript-Website#225]
I searched Issues to see if this had been mentioned previously, and found this quote in the "Update" issue:

> Having a data-dump is a good first start, but some of these flags are obviously CLI only, for example: `"help"` or `"watch"` and the graph of these options is quite complex but not represented in the TypeScript codebase.
> 
> To map these domains, there is a [file called `tsconfigRules.ts`](https://github.com/microsoft/TypeScript-website/blob/v2/packages/tsconfig-reference/scripts/tsconfigRules.ts) which strives to be the source of truth for how the config options connects and their additional metadata.
> 
> _Originally posted by @orta in https://github.com/microsoft/TypeScript-Website/issues/130#issuecomment-569932561_

However, `watch` is a valid option in tsconfig.json as part of the `compilerOptions`.

**Comment by orta** [comment]
Yeah, and it's changed a bunch in 3.8, I'd like to add them back in - yep 👍

**Comment by orta** [comment]
These are in now
