### ISSUE TITLE
Idea: open the try demo in a new tab 

### ISSUE THREAD

**Issue by xgqfrms** [microsoft/TypeScript-Website#2256]
**Improvement Idea:**

open the try demo in a new tab 

![image](https://user-images.githubusercontent.com/7291672/152767303-98c023d4-856c-43fe-b165-ccbbf8291a00.png)

https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/en/handbook-v2/Type%20Manipulation/Generics.md

**Why:**

better UX, as far as me.

**Alternative ideas:**

```diff
- <a class="playground-link" href="https://www.typescriptlang.org/play/#code/GYV...fIA">Try</a>

```

```diff
+ <a class="playground-link" target="_blank" href="https://www.typescriptlang.org/play/#code/GYV...fIA">Try</a>

```

**Comment by xgqfrms** [comment]
# my solution

```js

(() => {
  const tryLinks = document.querySelectorAll(`[class="playground-link"]`);
  for (let item of tryLinks) {
    item.target = "_blank";
  }
})();

```

**Comment by orta** [comment]
I've been cautious with this because it's trivial to open a new window by alt clicking, but much harder to go back the other way when you have code like this

**Comment by xgqfrms** [comment]
That's right, but not everyone knows that way.

I think if give some tips will be better.

![image](https://user-images.githubusercontent.com/7291672/152963177-83fbf53f-3c16-4bf4-8369-9eabdf5402e2.png)


```js
(() => {
  const tryLinks = document.querySelectorAll(`[class="playground-link"]`);
  for (let item of tryLinks) {
    item.title = "💡Press Alt key when click the left mouse button, will be open a link in new tab";
  }
})();
```

**Comment by orta** [comment]
I don't think we should be adding that sort of information in hovers etc, there's right click to do it and all sorts of other wats to control your browser
