### ISSUE TITLE
Playground: JSDoc example uses TypeScript, not JavaScript and is therefore not working properly

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript-Website#2261]
JSDoc example uses TypeScript, not JavaScript and is therefore not working properly. Types aren't picked up and show `any` or compiler errors.

![grafik](https://user-images.githubusercontent.com/17641229/153190895-c751522c-ac86-4833-828d-94a7d9c7d13d.png)

**Repro:** Visit https://www.typescriptlang.org/play#example/jsdoc-support

**Expected behavior:**
The tsconfig for this example should use Javascript, not TypeScript

**Actual behavior:**
see above.

**Comment by orta** [comment]
It depends on how you get there - inside the playground it always adds the `useJavaScript` - https://www.typescriptlang.org/play/?useJavaScript=trueq=45#example/jsdoc-support

Where did you find a link without it?

**Comment by AlCalzone** [comment]
> Where did you find a link without it?

Here, which seems to be this link: https://www.typescriptlang.org/play/javascript/modern-javascript/jsdoc-support.js.html

https://user-images.githubusercontent.com/17641229/153356286-c07dea99-10aa-4a96-b88c-6fd915ffcae8.mp4

**Comment by orta** [comment]
Cool, the code which handles the redirect inside that page would need to take into a playground examples custom args, code starts here: https://github.com/microsoft/TypeScript-Website/blob/v2/packages/typescriptlang-org/lib/bootup/ingestion/createPlaygroundExamplePages.ts
