### ISSUE TITLE
Docs: there is no parameter for msgbox()

### ISSUE THREAD

**Issue by jimmy-liao-gogoro** [microsoft/TypeScript-Website#2265]
**Page URL:** 
[Typeof Type Operator, Limitations](https://www.typescriptlang.org/docs/handbook/2/typeof-types.html#limitations)
[Typeof Type Operator.md](https://github.com/microsoft/TypeScript-Website/blob/8a19ee4dc8d26ac7d5536664788fe88064bf7825/packages/documentation/copy/en/handbook-v2/Type%20Manipulation/Typeof%20Type%20Operator.md?plain=1#L65)

**Issue:** 
There is no string parameter for `msgbox()` and it causes `msgbox("prompt text")` error
```ts
// @errors: 1005
declare const msgbox: () => boolean;
// type msgbox = any;
// ---cut---
// Meant to use = ReturnType<typeof msgbox>

// Expected 0 arguments, but got 1.(2554)
msgbox("Are you sure you want to continue?")

let shouldContinue: typeof msgbox("Are you sure you want to continue?");
```
[Playground](https://www.typescriptlang.org/play?#code/PTAEAEFMCdoe2gZwFygIwAYMFYBQATSAYwBsBDaSUIuAO0QBdQBbRAcwCM4APVACgCUoALwA+UFzglIZWgG5cIUAwCeAByqtOPEaFkqFSgLQmiAVwYmjisAFkZtJgzigziKsNAAlSAzPRaABV1SAAeVQ04ADMWdi5uUVwbUABRbg0iBkh8UAw9aDYzZkhHRAAaCQtQNjgmNAA6PgAmbGwAFgFcLXi+ACIAQUpQFTgzUER-KhGxgHdZJxcaRwBLWjNIAH5eztxpJkQAC1GSfABhOgZV9dQIyGjY7W4+wanR8cnht7nHZUWLq822zkQA)

**Recommended Fix:** 
Add string prompt parameter
```ts
declare const msgbox: (prompt: string) => boolean;
```
[Playground](https://www.typescriptlang.org/play?#code/PTAEAEFMCdoe2gZwFygIwAYMFYBQATSAYwBsBDaSUIuAO0QBdQBbRAcwCM4APVACgAO8ZgIapG0AJa02ASlABeAHygucEpDK0A3LhCgGATwFVWnHotBbDu-QFoHRAK4MHdvWACym2kwZxQJ0QqBVAAJUgGJ2haABVjSAAeIxM4ADMWdi5uJVxcM2y+ACIAQUpQQzgnUERoqkrqgHctPwCaX2knSAB+Itk8jSZEAAsqknwAYToGTshUFMh0zPNuYrL6qpq6is3m3wM26dne2W0gA)

**Comment by orta** [comment]
Yep, you're welcome to make that change 👍🏻
