### ISSUE TITLE
"Skip to content" link does not skip all navigation on some pages

### ISSUE THREAD

**Issue by quiteolly** [microsoft/TypeScript-Website#2270]
**Improvement Idea:**
On pages with sidebar navigation, "Skip to content" link should skip to actual content, and not to the end of top menu.

Currently, the skip link on typescriptlang.org is done with a `<div id="site-content"></div>` block inside the header component that references `href="#site-content"`. This does not skip all navigation on the page in Docs and Handbook sections: users wishing to skip to main content still have to skip through all `#sidebar` links, even on mobile where sidebar navigation is not displayed by default. This should be done differently in a way that would consistently skip to actual page content instead of another navigation block.

I can provide a PR if we agree on some solution here.

**Why:**
Keyboard users rely on skip links to get to the main content on the page. Currently, "Skip to content" link does not skip to the main content on Docs and Handbook pages, and users have to skip additional 10-15 links before getting to the actual page content.

**Alternative ideas:**

**Comment by orta** [comment]
Agree.

I think this can be solved by letting [`SiteNav`](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/typescriptlang-org/src/components/layout/TopNav.tsx) have an optional prop `skipToAnchor` which overrides `#site-content"`, then passing it in to the `<Layout` in the [documentation template page](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/typescriptlang-org/src/templates/documentation.tsx#L95) should propagate that though. I think `#handbook-content` should suffice looking at the DOM
