### ISSUE TITLE
Docs: Typo in Korean website

### ISSUE THREAD

**Issue by Han-Kyeol** [microsoft/TypeScript-Website#2276]
**Page URL:** https://www.typescriptlang.org/ko/docs/handbook/typescript-in-5-minutes.html

**Issue:** There is a typo under the 'Defining Types' chapter.

**Recommended Fix:** '몇 가지를 추기해 목록을 확장합니다' -> '몇 가지를 추가해 목록을 확장합니다'

**Comment by orta** [comment]
Ace, leave feedback (or a PR) over on https://github.com/microsoft/TypeScript-Website-localizations
