### ISSUE TITLE
Idea: Persisted search modal

### ISSUE THREAD

**Issue by Josh-Cena** [microsoft/TypeScript-Website#2278]
**Improvement Idea:** The search box should open up a persisted search modal when clicked, instead of showing results in a dropdown.

**Why:**

Not sure if it's my Internet or Algolia to blame, but the first query always seems to take forever. This means in the meantime of waiting for Algolia to return results, there's absolutely no feedback and I don't know what's going on. If I hit <kbd>Enter</kbd> before anything comes up, the entire input is erased but the page doesn't jump, which is even more confusing.

[Webpack](https://webpack.js.org/), [VuePress](https://v2.vuepress.vuejs.org/), [Docusaurus](https://docusaurus.io/), etc. would open up the search modal in a persisted dialog box instead of showing it in a dropdown. I don't know if the version of `docsearch` matters, and whether simply changing the "search box" to a toggle button would work, but I do believe it improves UX.

Reference: [how Docusaurus' `SearchBar` is implemented](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.tsx)

**Alternative ideas:**

🤔

**Comment by orta** [comment]
There's a PR for this https://github.com/microsoft/TypeScript-Website/pull/928 but I didn't get it in in time to handle the a11y audit which would eventually come with it. The last one took a very long time and iteration cycles to get right with the accessibility team at MS and it's not something I'd want to force on the current maintainers

**Comment by Josh-Cena** [comment]
Ah, so it _is_ a feature with DocSearch v3... Since there's already an open PR I would close this then.

**Comment by Josh-Cena** [comment]
Accessibility audits are certainly a pain to get right, I understand...
