### ISSUE TITLE
Playground: Type hint comment shows incorrect type in destructuring

### ISSUE THREAD

**Issue by tony19** [microsoft/TypeScript-Website#2287]
Using the type-hint comment (`// ^?`) pointing to a destructured property displays the wrong type: `any`. Interestingly, the problem sometimes only affects some of the type hints:

<img width="266" alt="Screen Shot 2022-02-28 at 11 08 35 PM" src="https://user-images.githubusercontent.com/26580/156108744-75f12ea7-1e74-4a22-aec9-7cd43f3c905d.png">

Sometimes both:
<img width="244" alt="Screen Shot 2022-02-28 at 11 15 30 PM" src="https://user-images.githubusercontent.com/26580/156109373-d795abe8-b72c-434f-839b-edcd2d32ccd0.png">

**Repro:**
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGELgQ5bwC+c6UBcA5AG4CuqNAUC6gB6SwoYCGDADbw0mHPkLEYACgQs4cMFTABnAFyJ5CuBw1zt2mAE8wqDQDkGIAEaooAGi0GoqAI4NgL5BphQm9uAB6QMBeDcAJHac4UkcDIz1IhWNTCytbBwS4F3dPVG84X38g0IiDaK0yhRVUGAYwaSUIVQBKTQNBasQdAKMouABeRWUVSOCDAD0AfkiAYyIVCHaAOkEIAHNpJNQIdB0mjIMDw+DJ8sdSJqA

**Expected behavior:**
All type hints show the correct type (not `any`).

**Actual behavior:**
Some of the type hints show `any` (sometimes).

**Comment by orta** [comment]
Might have been a cache issue while the types were being loaded? This worked on my computer after only clicking the link

![Screenshot from 2022-03-01 08 23 40](https://user-images.githubusercontent.com/49038/156132154-437d6860-4a48-48b7-b872-4b4688d4a2ea.png)
