### ISSUE TITLE
Playground: Nightly version stuck on 4.7.0-dev.20220215

### ISSUE THREAD

**Issue by MartinJohns** [microsoft/TypeScript-Website#2292]
The "Nightly" version of TypeScript seems to be stuck on 20220215, over two weeks old. Version 4.6.2, which contains changes done after the 15th February, is not selectable.

**Repro:**
Select "Nightly" in the playground.

![image](https://user-images.githubusercontent.com/5269069/156368241-a7329aa1-e428-4898-8cb1-6ed5005372f7.png)

**Expected behavior:**
The latest nightly is used (4.7.0-dev.20220302 as of today).

**Actual behavior:**
An old nightly is used (4.7.0-dev.20220215).

---

Related? #2040  
Possibly fixed by #2288?

**Comment by orta** [comment]
It's https://github.com/microsoft/TypeScript-Make-Monaco-Builds/issues/11 - tsc has a breaking change in the language service and Monaco needs updating for it
