### ISSUE TITLE
Docs: Missing documentation of assertion functions

### ISSUE THREAD

**Issue by j-ulrich** [microsoft/TypeScript-Website#2298]
**Page URL:** none yet

**Issue:** There is no mention of assertion functions in the handbook. The only official documentation of them is in the release notes of TypeScript 3.7: https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#assertion-functions

**Recommended Fix:** For the sake of completeness, there should be at least a short section explaining assertion functions somewhere in the handbook. For more detailed examples, it could link to the blog post.

**Comment by Pyrolistical** [comment]
Agreed! I love this feature and often look for it here: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates
...and then get confused on where it is documented

**Comment by Pyrolistical** [comment]
I wrote a blog post filling in this gap https://blog.battlefy.com/refactor-lying-typescript-type-assertions-into-real-assertions
