### ISSUE TITLE
Several loading errors on the non-HTTPS www.typescriptlang.org website

### ISSUE THREAD

**Issue by UweKeim** [microsoft/TypeScript-Website#23]
When navigating to the non-SSL version of [www.typescriptlang.org](http://www.typescriptlang.org), there are several errors shown in the Google Chrome console:

> www.typescriptlang.org/:1 Access to Font at 'http://i.s-microsoft.com/fonts/segoe-ui/west-european/normal/latest.woff' from origin 'http://www.typescriptlang.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.typescriptlang.org' is therefore not allowed access.
> www.typescriptlang.org/:1 Access to Font at 'http://i.s-microsoft.com/fonts/segoe-ui/west-european/semilight/latest.woff' from origin 'http://www.typescriptlang.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.typescriptlang.org' is therefore not allowed access.
> www.typescriptlang.org/:1 Access to Font at 'http://i.s-microsoft.com/fonts/segoe-ui/west-european/semilight/latest.ttf' from origin 'http://www.typescriptlang.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.typescriptlang.org' is therefore not allowed access.
> glyphicons-halflings…ular.bc0cf52d.woff2 Failed to load resource: the server responded with a status of 404 (Not Found)

Since there seems to be no automatich non-HTTP to HTTPS redirect, I have to manually prefix "https" in my browser's address bar.

**My suggestion:**

Please add an automatic redirect to HTTPS.

**Comment by orta** [comment]
The site is now OSS (see the archived branch on this repo), so you're welcome to take a look - I can't reproduce this though:

<img width="1119" alt="Screen Shot 2019-07-10 at 3 23 03 PM" src="https://user-images.githubusercontent.com/49038/60998316-ac851b80-a326-11e9-96ee-093cc1ea26b7.png">

**Comment by orta** [comment]
I'm going to close, we self-host fonts now
