### ISSUE TITLE
Playground: ability to copy version

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript-Website#2308]
when raising issues on the typescript repo, it's tedious to have to manually type the version when using nightly

![image](https://user-images.githubusercontent.com/57028336/159215022-1489a205-f03e-4ad6-a94f-b715f042868b.png)

**Comment by orta** [comment]
The version is of the playground is hardcoded in the URL of the playground - you could grab it from there? I'd assume you were already including that link in the issue anyway though?

**Comment by DetachHead** [comment]
lol dunno why i never thought to do that. but yeah i agree it shouldn't be necessary, i only really do it because the issue template asks for it
