### ISSUE TITLE
Idea: Ability to select system fonts

### ISSUE THREAD

**Issue by intrnl** [microsoft/TypeScript-Website#2317]
**Improvement Idea:**

The website should allow for using system fonts, as defined in the browser's font settings.

![Screenshot_20220401_212823](https://user-images.githubusercontent.com/20620901/161283770-3fd254f7-c1e5-41dc-8ed8-3afd10368462.png)

**Why:**

People have their own ways of reading, and they might find some fonts to be easier to read. As for my case, I use JetBrains Mono but without ligatures because I find it harder to read the symbols that way.

**Alternative ideas:**

The current fonts list can be expanded, but I think it's much better to just provide the ability for users to use what they already have instead.

Yes, you can force apply your browser's font settings to sites, however this has the tendency of breaking some sites with broken iconography etc, so this really isn't the best option.

**Comment by orta** [comment]
Is this request specific to the playground? I think adding 'system default' to the dropdown is pretty reasonable

**Comment by intrnl** [comment]
Yeah it's related to playground as well, but I also saw the font selection on docs, does it not apply there?

**Comment by orta** [comment]
Yeah, the font in the documents code sample's would be respected by the choice from that dropdown - yeah, I think it'd be reasonable for it to be added 👍🏻
