### ISSUE TITLE
Docs: Anchor links broken on reload

### ISSUE THREAD

**Issue by LorenzHenk** [microsoft/TypeScript-Website#2318]
**Page URL:** 

In all tsconfig reference pages.

For example https://www.typescriptlang.org/tsconfig#target

**Issue:** 

When visiting the page, the link changes from https://www.typescriptlang.org/tsconfig#target to https://www.typescriptlang.org/tsconfig#target= (`=` is appended). Reloading the page jumps to the top, since the anchor is now invalid.

**Recommended Fix:** 

The link should not be postfixed with `=`.

**Comment by orta** [comment]
I can't reproduce this on edge nor safari, is there other javascript (extensions) which could be doing this which is specific to your computer?

**Comment by LorenzHenk** [comment]
You're right, this is a bug of https://github.com/ClearURLs/Addon.
Thanks and sorry for the noise :grin:
