### ISSUE TITLE
Idea: list names/versions of auto-imported packages in Playground

### ISSUE THREAD

**Issue by seansfkelley** [microsoft/TypeScript-Website#2328]
**Improvement Idea:** list somewhere (perhaps in the sidebar where the .d.ts and errors go?) what names and versions the playground has picked up for auto-imported libraries.

**Why:** I wasted about an hour trying to repro a typing issue in the playground that I was seeing locally, only to find that the playground was pulling a squatted package name instead of the right package (this exact issue: https://github.com/microsoft/TypeScript-Website/issues/2119).

**Alternative ideas:** n/a...?

**Comment by orta** [comment]
Given that this has been the only case for an edge case in ATA so far, it's probably worth adding a special case in the ATA resolver for express. Otherwise, I think a sidebar plugin which only shows when there there has been imported types seems pretty reasonable if it's concise.

**Comment by seansfkelley** [comment]
> I think a sidebar plugin which only shows when there there has been imported types seems pretty reasonable if it's concise.

Agreed. #2119 was the impetus for filing this in the first place, but it's not the first time I had wanted this feature, just the saddest time. My project is often major versions behind on libraries and their typings, and being told that right off the bat when I try to isolate typing issues would be a nice time-saver.
