### ISSUE TITLE
Playground: `out` keyword isn't blue

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript-Website#2329]
https://www.typescriptlang.org/play?ts=4.7.0-dev.20220408#code/JYOwLgpgTgZghgYwgAgGIHt0B5TPQVzGQBUA+ZAbwFgAoZe5ANzgBt8IAuE2gXyA

![image](https://user-images.githubusercontent.com/57028336/162555879-19ae0bda-64ec-4f07-b38f-ffeeab483e33.png)

**Comment by orta** [comment]
The monaco syntax highlighter for TS is significantly simpler than the one shipped for editors, but if you want to see if they'll accept `out` as a keyword it is here: https://github.com/microsoft/monaco-editor/blob/main/src/basic-languages/javascript/javascript.ts#L16

**Comment by DanielRosenwasser** [comment]
Should be fixed by https://github.com/microsoft/monaco-editor/pull/3066.
