### ISSUE TITLE
Playground: links always open with "ààà"

### ISSUE THREAD

**Issue by ImRodry** [microsoft/TypeScript-Website#2339]
Every playground link I open only has "ààà" as its input and I get redirected to https://www.typescriptlang.org/play?#code%2FAco=. I have tried emptying the website's cache and reloading with no success.

![image](https://user-images.githubusercontent.com/38259440/163652737-434842fb-16c8-44cd-b1f9-61e5cc9245b0.png)

**Repro:**
This is probably not reproducible this way but this seems to happen with every link I open and no one else has this issue so far

1. Open any playground link, can be one shared by yourself
2. Observe how the code should only contain "ààà" and nothing else

**Expected behavior:** The link should open properly and include the shared code

**Actual behavior:** The playground only contains 1 line with "ààà" written in it

**Comment by orta** [comment]
Perhaps an extension is messing with the URL?

**Comment by ImRodry** [comment]
How could I know which one?

**Comment by orta** [comment]
No idea, disable them all and see if that stops the additional URL params, then bisect and guess

**Comment by ImRodry** [comment]
After doing some digging it seems like the issue came from https://chrome.google.com/webstore/detail/clearurls/lckanjgmijmafbedllaakclkaicjfmnk so I'm not sure if you want to keep this open to make the website compatible with this extension or if I should try to report this issue to them

**Comment by orta** [comment]
Nah, I don't think we'll add special casing for random chrome extensions - no idea where to even start with something like this. I'd recommend getting the typescript site added to a list of exceptions.

**Comment by ImRodry** [comment]
Alright, I have reported this on their repo so I'll close this issue here. Thank you!
