### ISSUE TITLE
TypeScript: Documentation - Everyday Types Type Assertions sample code error

### ISSUE THREAD

**Issue by ts0818** [microsoft/TypeScript-Website#2341]
When I executed "TRY" with the following code on the following page, an error occurred.
I don't think I have enough information.
■page
https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions
■code
const myCanvas = &lt;HTMLCanvasElement&gt;document.getElementById("main_canvas");

■result
https://www.typescriptlang.org/play?#code/MYewdgzgLgBAtgTwMIEMwDcURgXhgHgAkAVAWQBlUMsBRAGwFM4GwoA+AExGAFdnWAdAHMGUekxZQAQggCSHABQAiOCgCWYAPrA0mCEoCUAbiA
Errors in code
Cannot find name 'React'.
JSX element 'HTMLCanvasElement' has no corresponding closing tag.
'</' expected.

**Comment by orta** [comment]
This code sample needs jsx being set to zero to run safely because of the collision with jsx syntax, open to PRs 👍🏻 

https://www.typescriptlang.org/play?jsx=0#code/MYewdgzgLgBAtgTwMIEMwDcURgXhgHgAkAVAWQBlUMsBRAGwFM4GwoA+AExGAFdnWAdAHMGUekxZQAQggCSHABQAiOCgCWYAPrA0mCEoCUAbiA

**Comment by ts0818** [comment]
Thank you for your quick reply.
What number of PRs(Pull Requests) are you published about this issue?
https://github.com/microsoft/TypeScript-Website/pulls

**Comment by orta** [comment]
Allow me to rephrase: you are welcome to submit a pull request which fixes it

**Comment by ts0818** [comment]
Sorry for the late reply. 
I'm new to TypeScript, so it's difficult to fix this issue and pull request.
