### ISSUE TITLE
Docs: Make the Handbook more readable and interesting

### ISSUE THREAD

**Issue by shoaibshebi** [microsoft/TypeScript-Website#2353]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary & Current scenario 😯

TS is getting hit now in the development and  a lot of companies and developers are getting benefit from it. Though, there are video resources to learn TS, but no forum can be the so accurate as official docs. I have gone through the docs and found really helpful but wasting so much time to consume this Typed Language as the docs are no so much mature like other languages docs.

### New and required behavior 🤔

As you know approximately 93% of effective communication is nonverbal & emotional, while spoken words account for only 7%. And also 1 picture = 1000 words. So to make the docs more interesting, catchy and fastly consumalbe I have updated the docs with emojies, which makes the coding world more joyful and fun, so that developers can learn and develop fast.

Note: 👉 Currently I've update first two articles "The TypeScript Handbook" & "The Basics" so that you can suggest the changes.

### Examples 🌈

[_Strapi_ ](https://docs.strapi.io/developer-docs/latest/getting-started/introduction.html#open-source-contribution)

**Comment by Josh-Cena** [comment]
> 1 picture = 1000 words

That's about _meaningful_ schematics. Changing "bug" to "bug 🐛" only adds extra noise.
