### ISSUE TITLE
Unable to follow Getting Started step

### ISSUE THREAD

**Issue by nithiwatter** [microsoft/TypeScript-Website#2355]
I have cloned the project but am unable to run `yarn install` - the installation process always fails for me. I have already looked at the issue **https://github.com/microsoft/TypeScript-Website/issues/1981#issue-965803800**

<img width="449" alt="image" src="https://user-images.githubusercontent.com/59894785/164975325-8d9427b0-7cb0-4b7c-b0c1-28470992a615.png">

![image](https://user-images.githubusercontent.com/59894785/164975310-4a2b482a-d2a5-4613-b811-c9a418d28257.png)

**Repro:**
```
git clone https://github.com/microsoft/TypeScript-website
cd TypeScript-website
yarn install
```

**Expected behavior:**
Successful installation.
**Actual behavior:**
Fail to install.

**Comment by orta** [comment]
What do the linked logs show for canvas?

**Comment by nithiwatter** [comment]
I figured it out - basically I use Node v16 and Windows 10, so canvas needs to be built during installation - I just followed the instructions in the following link https://github.com/Automattic/node-canvas/wiki/Installation:-Windows

**Comment by nithiwatter** [comment]
I am sorry, but there is now a new problem - `yarn install` now runs successfully after the above instructions; however, running `yarn bootstrap` now fails:

<img width="901" alt="image" src="https://user-images.githubusercontent.com/59894785/164979266-291c8c08-4b70-445e-b17a-445a157b57e5.png">

Thank you!

**Comment by orta** [comment]
This could be something specific to node 16 - I've never tested it (and we run 14 on CI I believe)

**Comment by orta** [comment]
Maybe look for an import of `tsconfigOpts.json` in the codebase and add the import meta?

**Comment by nithiwatter** [comment]
Just tested with node 14.19.1 - everything works. Seems like certain optional flags during build time cause problems with version 16!
