### ISSUE TITLE
Docs: Deployment issue on AppService

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#2373]
The site deploys by shipping the .html files to the [SITE-PRODUCTION branch](https://github.com/microsoft/TypeScript-Website/tree/SITE-PRODUCTION) which is then picked up automatically by the TypeScript App Service auto-re-deploy system in Azure. ( [logs](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/99160d5b-9289-4b66-8074-ed268e739e8e/resourceGroups/Default-Web-WestUS/providers/Microsoft.Web/sites/TypeScript-1ebb3390-2634-4956-a955-eab987b7bb25/vstscd) ) 

It looks like at least since early april the changes to the site haven't been picked up by the app service, as https://github.com/microsoft/TypeScript-Website/pull/2321 [creates the right file](https://github.com/microsoft/TypeScript-Website/blob/SITE-PRODUCTION/docs/handbook/release-notes/typescript-4-6.html) but isn't available on the web site https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-6.html see #2372

It's likely either some security changes in Azure, or something which can hopefully be seen in the deploy logs

**Comment by andrewbranch** [comment]
With an incredible amount of pain and an email thread expanding to 20+ people, we have successfully Turned It Off And Back On Again which seemed to do the trick.

**Comment by orta** [comment]
My sympathies

**Comment by orta** [comment]
That said, it doesn't seem to have worked reliably - the "4.7 as default" deploy from monday doesn't seem to have propagated to typescriptlang.org

<img width="1204" alt="Screen Shot 2022-06-01 at 2 53 24 PM" src="https://user-images.githubusercontent.com/49038/171421942-2302e5d4-fd15-4eca-b32e-4a7539dc5541.png">

**Comment by andrewbranch** [comment]
Hm, the first deploy I did manually, assuming the push trigger would work. I guess the push trigger isn’t working 😞

**Comment by andrewbranch** [comment]
Indeed, Deployment Center has no record of any deployment attempt after that manual one.

**Comment by andrewbranch** [comment]
It’s supposed to install a web hook on the repo when you set it up. Best guess is that it skipped that when it saw there was an existing web hook, but that web hook is defunct.

**Comment by orta** [comment]
Yeah, I could see that happening.

There's the [static web app set up](https://github.com/microsoft/TypeScript-Website/blob/v2/.github/workflows/deploy-prod.yml#L52-L61), but that's probably also a bunch of emails to get the DNS safely moved over from the appservice to the SWA
