### ISSUE TITLE
Playground: Cannot find name 'React'

### ISSUE THREAD

**Issue by vezaynk** [microsoft/TypeScript-Website#2398]
JSX is unusable with importing the React namespace, for which there appears to be no option.

![image](https://user-images.githubusercontent.com/10255546/170732549-976f1b77-9e28-46e5-80b6-e19bc25f34c4.png)

**Repro:** [playground](https://www.typescriptlang.org/play?ts=4.7.0-beta&filetype=ts#code/MYewdgzgLgBAhjAvDAPAEwJYDcB8KD0muQA)

**Expected behavior:**

Writing `<div></div>` is typesafe.

**Actual behavior:**
Writing `<div></div>` is not typesafe, because React's definitions are not found.

**Comment by orta** [comment]
You'd need to include React as an import in your playground to add the React types for JSX, this allows the playground to work with more than just React in JSX (and largely matches how it works in reality)
