### ISSUE TITLE
[Feature request] TypeScript Playground presentation ability

### ISSUE THREAD

**Issue by QuantumInformation** [microsoft/TypeScript-Website#24]
I was thinking it would be nice to store a bunch of code examples for the TypeScript Playground. 
I envision this allowing you to step through a list of code examples like a presentation.
This would be great when giving tutorials on how TypeScript compares with JavaScript.

ie
slide one:
![image](https://cloud.githubusercontent.com/assets/216566/23164356/8ded3c7a-f82e-11e6-9017-ff2ef8e273b0.png)

slide two:

![image](https://cloud.githubusercontent.com/assets/216566/23164431/de9b74f2-f82e-11e6-9960-9449c9b596c3.png)

**Comment by orta** [comment]
Linking to https://github.com/microsoft/TypeScript-Website/issues/36

**Comment by orta** [comment]
I built this as a plugin!

https://www.typescriptlang.org/v2/dev/playground-plugins/

**Comment by QuantumInformation** [comment]
thx
