### ISSUE TITLE
Docs: Dead links to "contribution guidelines" page

### ISSUE THREAD

**Issue by mmiller42** [microsoft/TypeScript-Website#2406]
**Page URL:**

* https://www.typescriptlang.org/docs/handbook/declaration-files/consumption.html#searching
* https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#publish-to-types

**Issue:** 

These two pages include links to this URL, which currently returns a 404 page: https://www.definitelytyped.org/guides/contributing.html

I was searching for a reference that showed how to create a `@types` package for a NPM module that already had an org (e.g. `@some-lib/button-component`). (Used the "Search for typed packages" to find out that it looks like it works as `@types/${orgName}__${packageName}`).

There are two pages that include links to the "Contribution Guidelines" page

https://github.com/microsoft/TypeScript-Website/blob/d4f04091f8d4386f6927b20906667e847d9d3471/packages/documentation/copy/en/declaration-files/Publishing.md?plain=1#L182

https://github.com/microsoft/TypeScript-Website/blob/d4f04091f8d4386f6927b20906667e847d9d3471/packages/documentation/copy/en/declaration-files/Consumption.md?plain=1#L44

**Recommended Fix:** 

I'm not sure, did the page just get moved and links need updating? Or was it removed altogether and these sections should be deleted?

**Comment by orta** [comment]
Looks like that domain expired and got taken over, we should drop all references to it.

**Comment by mmiller42** [comment]
Is there any existing page that documents the `@types` npm namespace?

**Comment by orta** [comment]
The definitely typed readme is probably a good enough  link I think
