### ISSUE TITLE
Docs: Not updated for new module node16/nodenext released in 4.7

### ISSUE THREAD

**Issue by segevfiner** [microsoft/TypeScript-Website#2420]
**Page URL:** https://www.typescriptlang.org/tsconfig

**Issue:** The docs don't seem to be updated about node16/nodenext released in TypeScript 4.7. This include both the tsconfig reference and modules handbook and reference pages.

**Recommended Fix:** Update the docs with new information about the new node16/nodenext module mode.

**Comment by orta** [comment]
Will be fixed by https://github.com/microsoft/TypeScript-Website/pull/2380

**Comment by q42jaap** [comment]
The PR is merged but the docs aren't updated yet.

**Comment by orta** [comment]
It's deployed to staging, either the team makes a prod deploy ahead of time or it happens on the scheduled monday timer
