### ISSUE TITLE
Docs: moduleSuffixes is undocumented

### ISSUE THREAD

**Issue by MartinJohns** [microsoft/TypeScript-Website#2423]
**Page URL:** 
https://www.typescriptlang.org/tsconfig  
https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Issue:** 
The compiler option `moduleSuffixes` is not documented anywhere.

**Recommended Fix:** 
Add documentation for `moduleSuffixes`.

**Comment by orta** [comment]
The team haven't merged my 4.7 PR yet I'm afraid, https://github.com/microsoft/TypeScript-Website/pull/2380
