### ISSUE TITLE
Module(@typescript/vfs): lib files from cdn are broken

### ISSUE THREAD

**Issue by okikio** [microsoft/TypeScript-Website#2424]
**Improvement Idea:**

Lib types fetched from `@typescript/vfs`' CDN are broken, they return 404 errors. 
e.g. https://typescript.azureedge.net/cdn/4.7.4/typescript/lib/lib.es2020.full.d.ts
- ![image](https://user-images.githubusercontent.com/17222836/174426223-d109ca69-38eb-4286-987d-4cc77bb5bc98.png)
- ![image](https://user-images.githubusercontent.com/17222836/174426237-215b5d4c-d63a-440a-8c5e-f6689cc0ed50.png)

**Why:**

I'm not sure why it's broken but as there is no easy way to switch CDN's it's makes it very difficult to fetch `lib.d.ts` in WebWorkers.

**Alternative ideas:**

- Allow the user to easily switch CDN's 
- Make the typescript CDN more reliable

**Comment by orta** [comment]
Looking fine here?

<img width="1026" alt="Screen Shot 2022-06-19 at 4 10 33 PM" src="https://user-images.githubusercontent.com/49038/174487841-8d655e29-4c5b-4869-bc02-0c021e0284b3.png">

If the playground can load a specific version of typescript, then the files have to be in the CDN
