### ISSUE TITLE
Playground should call `monaco.editor.remeasureFonts()` after font loads and changes

### ISSUE THREAD

**Issue by graphemecluster** [microsoft/TypeScript-Website#2427]
I can see a slight change of space width while highlighting the text. I wonder if anyone ever reported this before.
Calling `monaco.editor.remeasureFonts()` manually in the console solves the issues.
(This API was introduced by https://github.com/microsoft/monaco-editor/issues/392)
That is all.

**Comment by orta** [comment]
Thanks! PR submitted
