### ISSUE TITLE
Request on documentation about the tests and development guide

### ISSUE THREAD

**Issue by aghArdeshir** [microsoft/TypeScript-Website#2428]
Hi. I've been trying to contribute to TypeScript for the last month (This is the problem I want to resolve just for reference: https://github.com/microsoft/TypeScript/issues/49149)

The setup, install, VSCode containers, documentation to run tests was all fine. I even got to run the tests and seeing them all pass.

But constantly I am being lost in the way the whole thing generally work.

My change is as simple as this:
![image](https://user-images.githubusercontent.com/5755214/175543928-bdf9c904-4b8f-40b6-9bdb-93daae4310c5.png)

But when I run tests, I get failing tests in too many files that does not seem related to my eye. I believe I will need to understand the whole thing more to be able to make any change in this code base.

I understand that the whole TypeScript thing is not an easy thing to understand and develop; like it is not a normal application; rather it is a whole language and type system.

But still, what I request is a public documentation on how the tests work work. Like, specifically how to read these files:

https://github.com/microsoft/TypeScript/blob/v4.7.4/tests/baselines/reference/abstractPropertyInitializer.types

https://github.com/microsoft/TypeScript/blob/v4.7.4/tests/baselines/reference/YieldExpression5_es6.errors.txt

https://github.com/microsoft/TypeScript/blob/v4.7.4/tests/baselines/reference/YieldExpression4_es6.symbols

I tried reading some merged PRs. But, still, they were too hard to understand.

**Comment by orta** [comment]
I'm afraid the TS website repo isn't really the place for that sort of docs, but there is https://github.com/microsoft/TypeScript-Compiler-Notes which does keep notes on the typescript compiler repo. It might be good to either write some of your own notes up from reading the codebase there, or look through the existing notes and see if you find an answer.

**Comment by aghArdeshir** [comment]
Thank you so much @orta . I didn't know such a repo exists.

I believe that answers my need for now and is a very very very good starting point.
