### ISSUE TITLE
ATA not working for any `@ember` modules

### ISSUE THREAD

**Issue by chriskrycho** [microsoft/TypeScript-Website#243]
Automatic type acquisition is awesome! …but I work on Ember, and it doesn't work there. Minimal reproduction:

```
import EmberObject from '@ember/object';

```

[Playground Link](https://www.typescriptlang.org/v2/en/play?useDefineForClassFields=true&target=99#code/JYWwDg9gTgLgBAURAIwKZQPLIFaoMbwBmUEIcA5AAKoroD0EO+M5A3AFBA)

Maybe related:

- #53
- #92
- #6

**Comment by orta** [comment]
This isn't showing up on the yarn search: https://yarnpkg.com/?q=%40ember%2Fobject&p=1  - which is why the TypeScript Playground

( It's neither showing up in npm search either, so it might not be in the unpkg CDN also )

Where does it come form?

**Comment by chriskrycho** [comment]
Ahhhh, that's why. `ember-source` provides these packages. This is a historical quirk, basically, that is sloooowly being ironed out—and it's technically compliant with the ES module spec, but is super surprising as a user/consumer.

**Comment by orta** [comment]
Cool - I have this for node: https://github.com/microsoft/TypeScript-website/blob/5a39caafdec9efa6d149413a83f77bcb75530ce4/packages/sandbox/src/typeAcquisition.ts#L60-L61

It might be able to work for ember in the same sense?

**Comment by chriskrycho** [comment]
Something like that might work, yeah – I'd have to dig into how ATA is working to be sure.

One of the challenges is that the types on DT do accurately represent the imports used by Ember apps, but the relevant packages *don't* (yet) actually exist on disk in a meaningful way, so *nothing* that uses Node's package resolution approach will "just work" here. I'm happy to help dig into this and get it working, though!

**Comment by orta** [comment]
Yeah, this implementation tries to re-create the resolution strategy for getting the d.ts files but makes fake modules in memory - it might just work as-is with a few modules resolving to ember-source

**Comment by orta** [comment]
Took a quick re-look at this during some issue triage, things have improved on the ATA side, but it does look like there's gonna have to be some hard-coding in the playground to know which to ignore looking:

```ts
import 'ember';
import EmberObject from '@ember/object';
```

Creates:

![Screen Shot 2021-03-10 at 9 39 32 AM](https://user-images.githubusercontent.com/49038/110608874-8dd2ca00-8184-11eb-9548-26efb4b08715.png)
![Screen Shot 2021-03-10 at 9 39 36 AM](https://user-images.githubusercontent.com/49038/110608881-90cdba80-8184-11eb-8bd1-b306f1556344.png)

Looks like a bunch of strange paths from bad internal resolves and some nulls from failed lookups to `@types`

**Comment by chriskrycho** [comment]
Thank you for following up here! FWIW, I'm currently working on a path which *should* see us publishing our own types in the next 6-ish months, but if we can unblock this in a day of work or something I will absolutely make time for that.
