### ISSUE TITLE
Missing end of line semicolons - "Differences Between Type Aliases and Interfaces"

### ISSUE THREAD

**Issue by MaxRigby** [microsoft/TypeScript-Website#2440]
Under "Differences Between Type Aliases and Interfaces" > "Interface" > "Extending an interface", the last three lines are missing semicolons.

I'm not yet super technically proficient - and it seems semicolons are [optional more than I expected](https://dev.to/b3ns44d/the-semicolon-in-javascript-typescript-pros-and-cons-8cl#:~:text=The%20use%20of%20semicolons%20in,to%20an%20unexpected%20runtime%20error.). But I'd imagine the 'extending an interface' on the left should have a parallel structure to the 'Extending a type via intersections' on the right in all ways not relevant to the point that's being made. I initially wondered if it was trying to make some comment about semicolon use for interfaces.

Thanks!

**Comment by orta** [comment]
There's a PR for this: https://github.com/microsoft/TypeScript-Website/pull/2435

Semis are optional in types, but we use prettier on all code samples to make them consistent
