### ISSUE TITLE
Width is not enough

### ISSUE THREAD

**Issue by vitaly-zdanevich** [microsoft/TypeScript-Website#2452]
See [here](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html):

![image](https://user-images.githubusercontent.com/3514015/178553077-a90978cb-4e93-4fc8-a2f5-3a2f6f33d1ed.png)

**Comment by orta** [comment]
This has an open PR: https://github.com/microsoft/TypeScript-Website/pull/2410
