### ISSUE TITLE
declare a JavaScript object with `: TypeName` is confusing

### ISSUE THREAD

**Issue by awxiaoxian2020** [microsoft/TypeScript-Website#2457]
> You can then declare that a JavaScript object conforms to the shape of your new `interface` by using syntax like `: TypeName`

https://github.com/microsoft/TypeScript-Website/blob/b062487cdb4f64b88079c163abb59eb2be3084cc/packages/documentation/copy/en/get-started/TS%20for%20JS%20Programmers.md?plain=1#L53-L66

We use `: TypeName` grammar in interface, not creating the object, the declaration of interface have been written before these text.

So should we use `: value` instead?

**Comment by orta** [comment]
I'm not quite sure what you're talking about to be honest, (I think your point may be lost in translation) but the code sample is correct and what we'd like it to be 👍🏻

**Comment by awxiaoxian2020** [comment]
> I'm not quite sure what you're talking about to be honest, (I think your point may be lost in translation) but the code sample is correct and what we'd like it to be 👍🏻

What I said was:
> You can then declare that a JavaScript object conforms to the shape of your new interface by using syntax like ` : TypeName`

should be:
> You can then declare that a JavaScript object conforms to the shape of your new interface by using syntax like ` : value`

**Comment by orta** [comment]
Thanks - this sentence is still correct  then - you don't write`: value` in TypeScript because that's not a type: 

```ts
 const user: User = { 
   name: "Hayes", 
   id: 0, 
 }; 
```

is not:

```
 const user: user = { 
   name: "Hayes", 
   id: 0, 
 }; 
```

for example (you'd need to use `typeof user`, and even then it make no sense to write that)

**Comment by awxiaoxian2020** [comment]
> Thanks - this sentence is still correct then - you don't write`: value` in TypeScript because that's not a type:
> 
> ```ts
>  const user: User = { 
>    name: "Hayes", 
>    id: 0, 
>  }; 
> ```
> 
> is not:
> 
> ```
>  const user: user = { 
>    name: "Hayes", 
>    id: 0, 
>  }; 
> ```
> 
> for example (you'd need to use `typeof user`, and even then it make no sense to write that)

I misunderstand the position, Thanks very much indeed!
