### ISSUE TITLE
Docs: Describe the difference between "module": "ES2020" & "module": "ES2022"

### ISSUE THREAD

**Issue by segevfiner** [microsoft/TypeScript-Website#2492]
**Page URL:** https://www.typescriptlang.org/tsconfig#module

**Issue:** The docs do not describe the difference between `"module": "ES2020"` & `"module": "ES2022"`, it's not obvious what is different between them

**Recommended Fix:** Document the difference between them, the same as the difference between `ES2015` and `ES2020` is documented.

**Comment by orta** [comment]
I imagine these are aliases for backwards compatability ( /cc @weswigham ? ) if so. I can add it

**Comment by LinusU** [comment]
Seems like top-level await is one of the differences: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#module-es2022

Found in this discussion: https://stackoverflow.com/a/67371788/148072#comment130044780_67371788

**Comment by agilgur5** [comment]
Looks like this was documented in https://github.com/microsoft/TypeScript-Website/pull/2662
