### ISSUE TITLE
Update Playground Examples

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript-Website#25]
The TypeScript Playground examples are... not great. We deserve a new set.

General principles
 * Don't lean on classes
 * Show off type inference where possible - minimal annotations
 * Emphasize working with JavaScript
 * Show both error-finding and good intellisense

# Please Suggest More!

-------------

# Basic Types & Inference
```ts
const array = ["red", "green", "blue", "yellow"];
array.forEach(color => {
  // TypeScript knows 'color' is a string and warns on the incorrect method name
  console.log(color.toUppercase());

  // Try typing 'color.' on this line to see members of string
  color
});

// TypeScript knows s has one of two string values.
// This can detect some different errors
const s = Math.random() > 0.5 ? "aaa" : "bbb";
// ... like the spelling error here
if (s === "aa") {
 // oops
}
// ... and the logic error here!
if (s === "aaa" && s === "bbb") {
  // oops
}
```

# Functions
```ts
function check(s: string) {
  return s.length > 3;
}

// TypeScript warns if we get the argument count wrong
check();
// Or if the argument type is wrong
check(10);

// The return type of the function is inferred,
// so errors like this are automatically detected
if (check("hi") === "world") {
  // Never true because 'world' isn't a boolean
}
```

# Union Types
```ts
// TypeScript can work with objects of mixed types
const items = ["red", 10, 15, "blue"];
for (const i of items) {
  if (typeof i === "string") {
    // TypeScript knows 'i' is 'string' here
    console.log(i.toUpperCase());
  } else {
    // 'i' is of type 'number' here
    console.log(i * 2);
  }
}



```

# Generics

# ES6 Classes

# What else?

**Comment by orta** [comment]
Blast from the past on this issue - but I've moved it to the TS website now, I've tried to think of the examples from quite far back - helping folks look for simpler JS use cases (if you're new) all the way you to advanced TS things like conditional types. What do folks think of this general progression?

<img width="707" alt="Screen Shot 2019-07-11 at 6 49 46 PM" src="https://user-images.githubusercontent.com/49038/61090472-ca2cb080-a40c-11e9-9782-977841c37681.png">

( To do it I'd have to add JS support, and type acquisition to the playground - but that's achievable )

**Comment by orta** [comment]
There isn't done for showing how to work with the DOM! Added

**Comment by orta** [comment]
OK... well, on 2nd round when trying to think about the advanced types much harder. I ended up coming up with "a lot" but also TS things which weren't quite "advanced" - so:

![Screen Shot 2019-07-12 at 8 01 37 PM](https://user-images.githubusercontent.com/49038/61164032-e0f00780-a4df-11e9-90c0-070916112eec.png)

then for things which are really _typescript_ and not just day-to-day JS

![Screen Shot 2019-07-12 at 8 01 55 PM](https://user-images.githubusercontent.com/49038/61164036-ea796f80-a4df-11e9-8604-242bb1070d1c.png)


... ideally there'd be one more. Maybe that could be example apps or something which when you run it would be cool, sorta like the [current retracer](https://www.typescriptlang.org/play/#example/building-a-raytracer)

**Comment by orta** [comment]
This is shipped!
