### ISSUE TITLE
Make Onboarding/Cross-Platform Development Smoother

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#2500]
When @RyanCavanaugh and I spoke to @navya9singh recently about the onboarding process for the site, there were a few issues when building on other platforms, and even once she got things working with a codespace, the repo was having a few build issues based on newly constructed artifacts.

So some things that we should think about:

* how do we ensure the site doesn't have too many environment-specific expectations to build?
* the contents of the site update dynamically based on external data sources - how do we differentiate between an *intentional* update of the site vs. an automated update? How much manual intervention should we expect from these things? How do we avoid forgetting steps?

**Comment by orta** [comment]
The site validates that you can [bootstrap and build on Windows on CI](https://github.com/microsoft/TypeScript-Website/blob/v2/.github/workflows/CI.yml#L51-L74) with every commit - open to looking at specific cases where things aren't working, but this has been pretty useful with external contributors who use Window before

WRT assets on release updates, that's a good question - I wanted to always know exactly what changed when I was actively working on this but I think there's probably a few files which can be put into the gitignore. The full docs for upgrading the version are here: https://github.com/microsoft/TypeScript-Website/blob/v2/docs/New%20TypeScript%20Version.md

**Comment by redradist** [comment]
Please, also consider adding official support for deno.
Deno currently supports npm packages and it should be very easy to do
