### ISSUE TITLE
Docs: is there a problem with your conditional type example ?

### ISSUE THREAD

**Issue by cedric-demongivert** [microsoft/TypeScript-Website#2511]
**Page URL:** https://www.typescriptlang.org/docs/handbook/2/conditional-types.html

**Issue:**

I may have missed something, but with your example located in the conditional type documentation that states that this snippet of code : 

```ts
interface IdLabel {
  id: number /* some fields */;
}
interface NameLabel {
  name: string /* other fields */;
}
 
function createLabel(id: number): IdLabel;
function createLabel(name: string): NameLabel;
function createLabel(nameOrId: string | number): IdLabel | NameLabel;
function createLabel(nameOrId: string | number): IdLabel | NameLabel {
  throw "unimplemented";
}
```

Is equivalent to this one : 

```ts
interface IdLabel {
  id: number /* some fields */;
}
interface NameLabel {
  name: string /* other fields */;
}
type NameOrId<T extends number | string> = T extends number
  ? IdLabel
  : NameLabel;
// ---cut---
function createLabel<T extends number | string>(idOrName: T): NameOrId<T> {
  throw "unimplemented";
}

let a = createLabel("typescript");
//  ^?

let b = createLabel(2.8);
//  ^?

let c = createLabel(Math.random() ? "hello" : 42);
//  ^?
```

It seems that when you implement it like that : 

```ts
function createLabel(id: number): IdLabel;
function createLabel(name: string): NameLabel;
function createLabel(nameOrId: string | number): IdLabel | NameLabel;
function createLabel(nameOrId: string | number): IdLabel | NameLabel
{
  if (typeof nameOrId === 'number') {
    return { id: nameOrId }
  } else {
    return { name: nameOrId }
  }
}
```

The code works in the playground, but the same one with your conditional type : 

```ts
function createLabel<T extends number | string>(idOrName: T): NameOrId<T>
{
  if (typeof idOrName === 'number') {
    return { id: idOrName }
  } else {
    return { name: idOrName }
  }
}
```

Lead to two compilation errors : 
 - Type '{ id: number; }' is not assignable to type 'NameOrId<T>'.
 - Type '{ name: string; }' is not assignable to type 'NameOrId<T>'.

As if the compiler does not downgrade NameOrId<T> in accordance with the assertion over the idOrName parameter.

**Recommended Fix:**

Do I missed something here ? If not, maybe a better example (that works also with an implementation of the method) may lead to less confusion.

Best regards,
Cédric Demongivert

**Comment by ikesau** [comment]
I'm also wondering about this. It's strange that the documentation explains the feature and then its own demonstration states that the feature is unimplemented.
