### ISSUE TITLE
Including documentation for Map/HashMap on website

### ISSUE THREAD

**Issue by MisterEggnog** [microsoft/TypeScript-Website#2514]
**Improvement Idea:**
Document Map/HashMap type.

**Why:**

This seems to be the main website for looking at typescript documentation & reference, it currently does not mention Map/Hashmap at all, merely referring to "Mapped Types."

Map is a valid class in Typescript, therefore this seems like the logical place to document it.

**Alternative ideas:**

**Comment by orta** [comment]
Thanks for trying to improve the TypeScript docs, we want to be documenting the difference between what JavaScript and TypeScript is, leaving extensive docs on JavaScript objects to properties like MDN (which do it really well)- as there's nothing TypeScript specific in how Map/HashMap are used, they aren't included in the TypeScript documentation.

**Comment by MisterEggnog** [comment]
Oh, I did not know that was part of JavaScript. Thank you for the information.
