### ISSUE TITLE
Playground: no 4.8 release

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript-Website#2519]
typescript 4.8 was released 10 days ago but it's not on the playground yet https://github.com/microsoft/TypeScript/releases/tag/v4.8.2

![image](https://user-images.githubusercontent.com/57028336/188372701-9a28af23-7d2c-4428-bd20-98508a7a0885.png)

**Comment by andrewbranch** [comment]
Fixed. 4.8 release notes coming soon too.
