### ISSUE TITLE
Playground: `suppressImplicitAnyIndexErrors` layout is confusing

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript-Website#2527]
it looks like the checkbox is for `noImplicitAny` and with the wrong description

# actual
![image](https://user-images.githubusercontent.com/57028336/189041484-b5fa55b8-6bcd-44cf-9aa5-f6ddcdef1296.png)

# expected
![image](https://user-images.githubusercontent.com/57028336/189041761-711b863e-3256-4149-8bb8-d3abf5bf713b.png)

**Comment by orta** [comment]
Looks like a CSS bug, should be a pretty easy fix for someone interested in contributing
