### ISSUE TITLE
where‘s zh？How to Contributing?

### ISSUE THREAD

**Issue by hexiaokang** [microsoft/TypeScript-Website#2528]
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/16911432/189259408-9f4ec50c-5795-4f6b-abed-6512b068ea61.png">

**Comment by orta** [comment]
You can find all that info in https://github.com/microsoft/TypeScript-Website-Localizations/

**Comment by hexiaokang** [comment]
Thanks!

**Comment by MarsIncarnate** [comment]
谢谢
