### ISSUE TITLE
V2: Flash of content, then content removed from DOM if CDN is blocked by content blockers

### ISSUE THREAD

**Issue by jsynowiec** [microsoft/TypeScript-Website#253]
**What happens:**
On release notes pages like [this one](https://www.typescriptlang.org/v2/docs/handbook/release-notes/typescript-3-7.html) a flash of content before everything is removed can be observed if loading of `https://az416426.vo.msecnd.net/scripts/b/ai.2.min.js` fails.

**Why it matters:**
`az416426.vo.msecnd.net` domain is classified as `Tracking/Misc` by AdGuard Simplified Domain Names filter list, and this list seems to be one of the default filters enabled on most AdGuard products (their DNS and content blockers).

**What should happen:**
Static content shouldn't break or be removed from DOM if some JavaScript fails to load from CDN.

**Comment by orta** [comment]
This page is just broke ( #178 ) - I'm pretty sure I'm running a bunch of anti-trackers, I'll double check but I don't think this is the case

**Comment by orta** [comment]
Can you check now?

**Comment by jsynowiec** [comment]
Sorry for the false positive then. Looked related because it occurred right after failing to load that script.

Now it displays just fine!
