### ISSUE TITLE
Docs: Significantly outdated with regards to Typescript Runtime availability

### ISSUE THREAD

**Issue by thegaryroberts** [microsoft/TypeScript-Website#2540]
**Page URL:** [Handbook - Page 2 - Erased Types](https://www.typescriptlang.org/docs/handbook/2/basic-types.html#erased-types)

**Issue:** It needs updated to point out there **are now** "runtimes that can just run TypeScript unmodified"

**Recommended Fix:** Acknowledge Deno (and others, if: any).

Seems wise to direct learners at newer, simpler options for working with Typescript around this point (or at least not deny their existence).

Docs in general could do with an overhaul to get learners working with and loving the language, before covering the transpilation/emit to JS stuff later, should they still need it (I weep for them).

**Comment by orta** [comment]
I think Deno is established and stable enough that this section could get a few tweaks. 👍🏻 

Can't pretend that th point is to be erasable and it is generally the users responsibility to do that though. Could also mention the types as comments proposal too.
