### ISSUE TITLE
Playground: Add ability to stop a running script

### ISSUE THREAD

**Issue by JLCarveth** [microsoft/TypeScript-Website#2541]
When running some code in the playground, there is no way to stop the execution of a running program (a la Ctrl+C in the terminal). This can lead to some weird behaviour. For example, set an interval to log `A` to the console periodically and run the code. Changing the output to `B` causes `A` and `B` to both be output to the console.

![image](https://user-images.githubusercontent.com/23156861/191822678-b15e9449-f941-49d2-bcd2-f918f1fb286a.png)

**Repro:**
1. Simply run the following line of code in the playground, and run the code.
```
let interval = setInterval(() => { console.log('A') }, 1000);
```
2. Modify the code, and 'run' again:
```
let interval = setInterval(() => { console.log('B') }, 1000);
```

**Expected behavior:**
I expect only 'B' to be printed.
**Actual behavior:**
'B' and 'A' are being printed.

**Comment by orta** [comment]
This is kind of the halting problem, but I dont think there's a way in the JS runtime to eval your code and be able to stop all side-effects like your setInterval from being ran. This is not really feasible without [shadowrealms](https://github.com/tc39/proposal-shadowrealm) I expect and that brings with it a whole host of other issues which make this not really doable.
