### ISSUE TITLE
Playground: Can run playground scripts on Chrome

### ISSUE THREAD

**Issue by JeanMeche** [microsoft/TypeScript-Website#2545]
My Chrome won't run the scripts on my current session. 

The console logs this error : 

```
createElements.ts:223 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at activatePlugin (createElements.ts:223:52)
    at runButton.onclick (index.ts:448:21)
```

I'm currently on Chrome M105, I disabled all my extensions. Also tried with `open --new -a "Google Chrome" --args --disable-extensions`

But this does not happen with in private navigation or when using a new profile.

**Comment by orta** [comment]
You probably installed a playground plugin which is crashing on launch (/early bootup), probably best to reset your local storage on the typescript website. I thought we had try catches around all the plugin launch code, so it could be crashing after that which is why it's fully bailing.

**Comment by JeanMeche** [comment]
Yup, 

On `index.ts`, 
```
const runPlugin = plugins.find(p => p.id === "logs")!
```
is returning `undefined`. 

Non-null assertion operator are baaaaaad 😊

Edit: Run JavaScript in Browser was disabled on my side. 

That was it.
