### ISSUE TITLE
PLEASE document "declare module" and the rules for declarations.d.ts

### ISSUE THREAD

**Issue by qwertie** [microsoft/TypeScript-Website#255]
As far as I can tell there is just [one page](https://www.typescriptlang.org/docs/handbook/modules.html) intended specifically to document "declare module" (though see also [this](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html)).

Over [here](https://github.com/microsoft/TypeScript/issues/2709), QuantumInformation is, like myself, puzzled why this error happens and what the heck an "augmentation" is:

    declare module "mirage-server";
    // Invalid module name in augmentation, module 'mirage-server' cannot be found.

    import MirageServer, { Factory } from 'mirage-server';

We just want to be able to import an untyped JS module.

In my company's codebase there are hundreds of folders full of (mostly JS) source code. One of these folders happens to contain a eni_defs.d.ts file full of `declare module` statements, which, unlike the one above, actually work. But _why_ does it work? I don't see _any_ references to eni_defs.d.ts, _anywhere_. It appears that TypeScript has an undocumented rule to scan files called `*.d.ts`, but _where_ does it look for them? I tried putting a new declarations.d.ts file in a different folder, a place that seemed reasonable to me, but for some reason TypeScript didn't see that one.

So please explain the following in the documentation:

1. How TypeScript decides which folders it will scan for d.ts files that contain "declare module" statements.
2. (a) that "declare module" only works work in files that DO NOT use import/export (unless there is already a "declare module" or set of type definitions for the module already) and (b) WHY "declare module" only works work in files that do not use import/export.
3. Also, the `declare module "*!text"` example doesn't work in our codebase. This is because TypeScript emits code that refers to `ModuleName.default` but it must be simply `ModuleName` without `default` in our code. I think the documentation should explain the fact that different systems set up their text imports in different ways and that TypeScript only supports one of these ways. (By the way, this seems vaguely related to [this issue](https://stackoverflow.com/questions/50661510/why-doesnt-fs-work-when-imported-as-an-es6-module) I had earlier... is there a page of documentation about confusing import issues like this one?)

**Comment by orta** [comment]
1 - DTS files don't have a unique lookup, they respect [`include`](https://www.typescriptlang.org/v2/en/tsconfig#include) or [`files`](https://www.typescriptlang.org/v2/en/tsconfig#files) in your tsconfig

2 - it only works in [ambient modules](https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules), which are effectively only interface files (like header files in C++) 

Honestly, I'm not sure myself why it only works in them, but I've not been around got too long

3 - I'm not really sure I get what you are implying? The declare module example should show how to describe the what you'd see at runtime - perhaps you've not set up the right interface for those types of modules?
