### ISSUE TITLE
Playground: Two spaces are merged into one

### ISSUE THREAD

**Issue by nopeless** [microsoft/TypeScript-Website#2554]
![image](https://user-images.githubusercontent.com/38830903/193212727-fa468f8d-7fc4-481e-a864-e72c79e70e8c.png)

I can't believe this bug hasn't been reported

**Comment by orta** [comment]
This is likely a side-effect of trying to reduce the amount of whitespace in a type to make it show within the tiny space available in the insets. It might be solvable, but it'd be tricky I bet.

https://github.com/microsoft/TypeScript-Website/blob/v2/packages/playground/src/twoslashInlays.ts#L35-L36

**Comment by nopeless** [comment]
Bump

**Comment by orta** [comment]
You're welcome to try and fix the issue by making a smarter minifier (or maybe checking the length of the type ahead of time), but there's very reasonable reasons (character limit on inline attachments) for why it is how it is

**Comment by nopeless** [comment]
@orta Does the solution have to be efficient? If not, I can implement a simple regex that checks for opening and closing quotes. Problem is this is likely going to lead to performance issues if called a lot

**Comment by orta** [comment]
Yeah, I'm afraid it does, I think these get updated per keystroke
