### ISSUE TITLE
Docs: No explanation for meaning of Type> in warning

### ISSUE THREAD

**Issue by gisborne** [microsoft/TypeScript-Website#2561]
**Page URL:** 

Information is missing. No particular page.

**Issue:** 

Intellij is showing me a warning "Type 'QueryObjectResult  >' is not assignable to type 'QueryObjectResult '"

I can find no explanation after some time searching this website of what _Type_ > means.

Note that the explanation should probably go in several places, as ">" is impossible to just search for. Or maybe have a "Symbols" page.

(It's conceivable this is some IntelliJ specific issue, in which case I apologize. Although this seems unlikely, as all this is presumably coming from the language server.

**Recommended Fix:** 

Add a symbols page explaining this and other symbols, and also probably putting a brief explanation of this in a few other suitable places.

**Comment by orta** [comment]
I'm not sure what the '>' you're referring to - it has no specific usage in TypeScript, but in JavaScript it's the greater than operator. It is used to close a generic type though, so maybe you have typoes in your code?


That saidm the handbook goes into quite a lot of details about what a type is, https://www.typescriptlang.org/docs/handbook/2/basic-types.html if you're just getting started and include sections on generics too
