### ISSUE TITLE
Docs: Incorrectly positioned error messages in the TSConfig Reference

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript-Website#2568]
**Page URL:** https://www.typescriptlang.org/tsconfig#resolveJsonModule

**Issue:**

In this section, there are two error messages in the source code. Both are incorrectly placed.

1. The import error appears in the imported file, but should be in the importing file (just after `import settings from "./settings.json";`).
2. The comparison error appears in the imported file, but should be in the importing file, just after the comparison in question (`settings.dry === 2;`).

I'd have fixed the issue, but I couldn't find the error messages in the [corresponding Markdown file](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/resolveJsonModule.md).

**Recommended Fix:** 

<img width="729" alt="Screen Shot 2022-10-16 at 10 24 54" src="https://user-images.githubusercontent.com/106395723/196026228-5455b537-f34d-4897-8318-c73b82e7b8ef.png">

**Comment by orta** [comment]
The errors come from the compiler, and are attached wherever the compiler attaches them - they are not hardcoded! You might have to make the changes in the compiler then they will get fixed here.
