### ISSUE TITLE
Playground: mutiple file not working

### ISSUE THREAD

**Issue by Mister-Hope** [microsoft/TypeScript-Website#2573]
`// @filename: xxx` not working as expected

![image](https://user-images.githubusercontent.com/33315834/196862737-507d809e-faa6-4b15-b2fa-10321e2a3482.png)

**Repro:**

https://www.typescriptlang.org/play?#code/PTAEEsFsAcBtwMbgC6gGbgE4GdUdgKagAU4AdtAK7IB0y2w9AHsAFYPtMCUAUAgPZlcoAIagAvKACMPEKAAC+AmRGQCALlDAlAJjrZZYAML9IasqnKjQ2AgLIATdOEJ9BwsZKk7DCpSrVNJQBmfV8TM2VLMmtkAAssJyU3IVRPaR1goA

See: 

https://github.com/microsoft/TypeScript-Website/blob/v2/packages/playground-handbook/copy/en/Multi-File%20Playgrounds.md

**Comment by orta** [comment]
I removed the feature as it wasn't very reliable, I don't think there's any public-facing mention of this support - only the un-used docs inside the codebase

**Comment by Mister-Hope** [comment]
Yes, I saw that from the link, so if this is not supported maybe we should remove it?

**Comment by cebamps** [comment]
> I removed the feature as it wasn't very reliable, I don't think there's any public-facing mention of this support - only the un-used docs inside the codebase

Hello @orta. The linked handbook page is actually available through the Playground's built-in help, and is currently located here: https://www.typescriptlang.org/play?#handbook-15
