### ISSUE TITLE
Playground: `importsNotUsedAsValues` tsconfig option is missing

### ISSUE THREAD

**Issue by DetachHead** [microsoft/TypeScript-Website#2574]
![image](https://user-images.githubusercontent.com/57028336/196872685-d755a92b-d88b-4280-8b67-980fb064dfc2.png)

**Comment by orta** [comment]
Yeah, I'd 👍🏻 a PR adding it to the 'interop constraints' section - if you'd like to set it manually you can use the twoslash comments system, which you can read about in the playground help section

**Comment by DetachHead** [comment]
happy to give it a go, would you be able to show me where these options are in the repo? i'm having trouble finding it

**Comment by yukinotech** [comment]
> happy to give it a go, would you be able to show me where these options are in the repo? i'm having trouble finding it

I encountered the same problem, the help documentation is as follows:

https://www.typescriptlang.org/play?target=99&jsx=4&module=6&ts=4.8.4#handbook-11 , 

Or you can directly look at the example below:
https://www.typescriptlang.org/play?strictPropertyInitialization=false&importsNotUsedAsValues=1#code/PTAEAEEsFsAcHsBOAXAzgOXsgqqgpgCYCCqAagIYA2ArnqgFyyJ16IBueAsAFAwIqgA3qACyoAL6gAZonjRQAcgB0wZHWQKePPAA9+yUAGN4AO1QGi9UaAC8oAIw9jZ+JTxLK8AOYAKQwEogA
