### ISSUE TITLE
Docs: Open try in new tab.

### ISSUE THREAD

**Issue by VibhorJaiswal** [microsoft/TypeScript-Website#2576]
Open try demo in new tab because it is little difficult to everytime do a right click and select open in new tab.

![image](https://user-images.githubusercontent.com/69683278/197344902-547dea1d-598c-45c6-9993-1414b70693aa.png)

I saw a same issue here #2256 but I don't know why it was closed. Maybe because his approach is little complex (to press alt and click).
My solution is simple that just open it in new tab everytime.

If you think this should be done than I will be happy to contribute this feature.

**Comment by orta** [comment]
Prior discussion: https://github.com/microsoft/TypeScript-Website/issues/1930

**Comment by VibhorJaiswal** [comment]
@orta  After seeing multiple issues for the same feature, other documentations opening a new tab for their editor, and my personal experience, I still think it would be better to open it in a new tab. But since you want to give both choice to the user(to open in same tab as well as new tab) I am closing this issue.
