### ISSUE TITLE
Docs: zh document contributes link error, not updated to the new repo address

### ISSUE THREAD

**Issue by xgqfrms** [microsoft/TypeScript-Website#2578]
**Page URL:** 

https://www.typescriptlang.org/zh/docs/handbook/2/conditional-types.html

`sending a Pull Request`

![image](https://user-images.githubusercontent.com/7291672/197398942-ba5f5b0c-e9b3-434c-93e9-242fcbb4bcea.png)

**Issue:** 

After clicking the link, got a `404` error

```md
The 'microsoft/TypeScript-Website' repository doesn't contain the 'packages/documentation/copy/zh/handbook-v2/Type Manipulation/Conditional Types.md' path in 'v2'.  
```

![image](https://user-images.githubusercontent.com/7291672/197399135-d19bc950-cd67-4676-9cd9-d1ec3ff7bb83.png)

**Recommended Fix:** 

```diff
The TypeScript docs are an open source project. 
- Help us improve these pages [by sending a Pull Request](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/documentation/copy/zh/handbook-v2/Type%20Manipulation/Conditional%20Types.md) ❤

The TypeScript docs are an open source project. 
+ Help us improve these pages [by sending a Pull Request](https://github.com/microsoft/TypeScript-Website-Localizations/edit/main/docs/documentation/zh/handbook-v2/Type%20Manipulation/Conditional%20Types.md) ❤

```

old repo:

~~https://github.com/microsoft/TypeScript-Website/~~

new repo:

https://github.com/microsoft/TypeScript-Website-Localizations/

`zh/handbook-v2`

https://github.com/microsoft/TypeScript-Website-Localizations/tree/main/docs/documentation/zh/handbook-v2

**Comment by hexiaokang** [comment]
https://github.com/microsoft/TypeScript-Website/issues/2528

**Comment by xgqfrms** [comment]
Seems like there are no plans to fix it?
