### ISSUE TITLE
Playground: Type hints not re-evaluating when config changes

### ISSUE THREAD

**Issue by MartinJohns** [microsoft/TypeScript-Website#2581]
The type hints enabled with `// ^?` are not being re-evaluated when the tsconfig changes. A very minor, not very important thing, but I just noticed it and wanted to report.

![image](https://user-images.githubusercontent.com/5269069/197625190-d506a726-b6ac-41c8-93be-1b7f31a88ca3.png)

**Repro:**

Open playground with this code:
```typescript
const val = Math.random() > 0.5 ? 123 : undefined
//    ^?
```

Disable `strictNullChecks`.

[Playground link](https://www.typescriptlang.org/play?strictNullChecks=false#code/MYewdgzgLgBAbgQwDYwLwwLIKgCwHQBOCYAJiALYAUAlDAHwwAMeArDAPwwCMATAMwwAXDACupAKYAzAJZhxJAFAB6JTDUwAeuwVA)

**Expected behavior:**
The type hint will change to `123`.

**Actual behavior:**
The type hint remains `123 | undefined`.

**Comment by orta** [comment]
I'd imagine there's some kind of Monaco API to invalidate any existing inline inline markers which we could trigger in the sandbox on config changes
