### ISSUE TITLE
Remove `stripInternal` from the Playground UI

### ISSUE THREAD

**Issue by RyanCavanaugh** [microsoft/TypeScript-Website#2586]
It shouldn't be possible to turn on an unsupported flag!

**Comment by cristobal** [comment]
Should this be removed from the tsconfig options as well?

**Comment by orta** [comment]
Adding it to this list will remove it: https://github.com/microsoft/TypeScript-Website/blob/f9c407d6dfd15d99cef781b60216f79373578464/packages/playground/src/createConfigDropdown.ts#L24-L51
