### ISSUE TITLE
Docs: The error message is wrongly placed in the "Additional Import Syntax" of the Modules part 

### ISSUE THREAD

**Issue by olawalethefirst** [microsoft/TypeScript-Website#2591]
**Page URL:**  https://www.typescriptlang.org/docs/handbook/2/modules.html 

**Issue:**  The position of typescript's error message, illustrated with the caption `'createCatName' cannot be used as a value because it was imported using 'import type'.` is misleading as it does not accurately show the line of code that causes the exception. 

**Recommended Fix:**  The error message should be repositioned after the `const name = createCatName();` line of the code extract.

![git](https://user-images.githubusercontent.com/66824020/199441059-6e74b6db-1573-41fe-85e7-3ad7265c7fac.png)

**Comment by orta** [comment]
Perhaps a twoslash bug as this error should live in `app.ts`?

**Comment by olawalethefirst** [comment]
yes, I tried forking to propose a fix but couldn't find the error included in the repo.

**Comment by orta** [comment]
You'd need to copy & paste the code sample into the twoslash packages' errors to see what's up there 👍🏻

**Comment by agilgur5** [comment]
Same as #2568 I think
