### ISSUE TITLE
TS Playground font size options

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript-Website#2594]
I need to always scroll to see the logs when the view is zoomed
Could you fix that issue. Or add option to increase font size

**Comment by orta** [comment]
Hi, could you maybe provide some context with a screenshot? The logs show up at the top of the sidebar, and so they should be visible even at pretty high zoom levels: ( e.g. 200% )

![image](https://user-images.githubusercontent.com/49038/199846025-220b1cbf-bda1-4878-8724-2ae010b01adc.png)

**Comment by ghost** [comment]
Problems start when you have like 1000 logs. Also cleaning is hard. Maybe console footer should be sticky or something

https://user-images.githubusercontent.com/77569421/200142939-e71ac225-4767-469a-a7d3-7a53360423a5.mp4

**Comment by a7993n** [comment]
Same Issue here using Chrome Version 105.0.5195.102 (Official Build) (x86_64)

**Comment by orta** [comment]
Yeah, I guess it could be reasonable to have the app look at how big the viewport is and how much there could be for the logs panel and shrink the sidebar to fit 

It'd be quite a lot of work to get right though, and you're probably better off using the dev webtools inspector at that point which is still getting the logs as normal
