### ISSUE TITLE
Feature request: per-page TOC for website's documentation

### ISSUE THREAD

**Issue by lonix1** [microsoft/TypeScript-Website#26]
## Search Terms
handbook, typescriptlang, website

## Suggestion

The documentation on the website ([example](https://www.typescriptlang.org/docs/handbook/basic-types.html)) if not user friendly at all.

There is a TOC on the left for all the pages. But there is no TOC per-page.

Scroll down that example I linked to - see how hard it is to find any info? There needs to be a TOC at the top of the page, and even better, a scrolling TOC on the right that shows where you are right now.

The documentation is of a high quality, but accessing it is a chore.

**Comment by RyanCavanaugh** [comment]
New handbook has auto-generated TOCs with permalinks
