### ISSUE TITLE
Idea:  Editor font zoom In/Out

### ISSUE THREAD

**Issue by a7993n** [microsoft/TypeScript-Website#2600]
**Improvement Idea:**
I checked two browsers now with the problem on the log output zoom In - Out, I recommend using a field with custom font size.

Browsers used:
 - Chrome Version 105.0.5195.102 (Official Build) (x86_64)
 - Brave v1.45.118 (Nov 2nd, 2022)
 
**Why:**

**Alternative ideas:**

**Comment by orta** [comment]
Hi, can you provide some screenshots or a richer explanation - I'm not sure what you're asking for? The logs get larger with the rest of the site as you use the browsers zoom controls
