### ISSUE TITLE
Outdated tsup link

### ISSUE THREAD

**Issue by bradmk-1** [microsoft/TypeScript-Website#2601]
https://www.typescriptlang.org/docs/bootstrap

On the above page, the tsup URL points to **https://tsup.egoist.sh/**, where it should be **https://tsup.egoist.dev/**

**Comment by orta** [comment]
Assuming the deploy infra is fine, this should be coming up on the next deploy on monday - https://github.com/microsoft/TypeScript-Website/pull/2468

**Comment by bradmk-1** [comment]
Perfect didn't realise this was already addressed, will close.

**Comment by Knorrke** [comment]
> Assuming the deploy infra is fine, this should be coming up on the next deploy on monday - #2468

@orta The link is still not updated unfortunately.
