### ISSUE TITLE
Docs: Main Page—Version Bar

### ISSUE THREAD

**Issue by mbelsky** [microsoft/TypeScript-Website#2611]
Hi team,

There is a small issue with version bar on the main page:

**Page URL:** https://www.typescriptlang.org/
**Issue:** Version bar displays Typescript 4.8 as current version instead of 4.9

<img width="1113" alt="Screenshot 2022-11-23 at 14 33 18" src="https://user-images.githubusercontent.com/3923527/203560004-41cda590-4bee-4d9c-ab9d-aa95ae3ec0da.png">

**Comment by andrewbranch** [comment]
Deployed an update yesterday.
