### ISSUE TITLE
Website: incorrect wording for `available version...` text

### ISSUE THREAD

**Issue by sidoruk-sv** [microsoft/TypeScript-Website#2612]
**Bug on a Website:**

**URL:**
https://www.typescriptlang.org/

**Issue:**
> [TypeScript 4.8](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/) is now available, 4.9 has a release candidate to try.

Mention that:
- `TypeScript 4.8` leads to 4.9 Announcement page.
- there is no new RC for the next version and 4.9 is the latest available version (so wording about RC is outdated and misleading);

![image](https://user-images.githubusercontent.com/439289/204041323-789ecd5d-457f-4042-9c1d-9c9d56e77804.png)

### Expected result:

> [TypeScript 4.9](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/) is now available.

```diff
<p>
-  <a href="https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/">TypeScript <!-- -->4.8</a>
+  <a href="https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/">TypeScript <!-- -->4.9</a>
-  <!-- -->is now available<span>, 
+ <!-- -->is now available.
-  <a href="https://devblogs.microsoft.com/typescript/announcing-typescript-4-9-beta/">4.9</a>
-  <!-- -->has a release candidate to try.</span>
</p>
```

**Comment by jcalz** [comment]
https://github.com/microsoft/TypeScript-Website/actions/runs/3514225645/jobs/5887977290
```
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 110
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly
```

Looks like this failed and needs someone to tend to it.

**Comment by andrewbranch** [comment]
Done.
