### ISSUE TITLE
Docs sidebar cache issues?

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/TypeScript-Website#2621]
Something I’ve observed many times is that we add a page, like #2615, and it doesn’t show up in the sidebar until you enter the URL directly into your browser once. It’s as if the sidebar content is being aggressively cached in the browser. No amount of refreshes will fix it, but clearing website data or using a private window will. @orta any idea what’s going on here or where to begin looking?

**Comment by orta** [comment]
Off hand, no, I'm not sure I've seen that behavior during dev.

There's no additional caching WRT the sidebar, it gets rendered directly into the HTML (e.g. is visible on CURL)  which should always be grabbed by a browser for the main route

![image](https://user-images.githubusercontent.com/49038/204791211-8b1cc2df-2924-4586-b3d0-f6912cf80f35.png)

My best guess is either:

 - Gatsby PWA shenanigans (we're two major semvers away, so I was thinking of trying top update over the winter break) - I tried to not let any PWA stuff happen on the site (I dont see a service worker when I open it now, so this is very unlikely
 
 - Deployment shenanigans? Perhaps we need some sort of caching headers on the HTML files when says when the file's content has changed via the `Last-Modified` header?  The app service side of the site is all the defaults which may not account for that
