### ISSUE TITLE
Docs: Where is docs for JS types in TS?

### ISSUE THREAD

**Issue by Worldwidebrine** [microsoft/TypeScript-Website#2630]
**Issue:**
I don't see TS docs for JS types. Did I miss something?

**Recommended Fix:**
I found this:
https://microsoft.github.io/PowerBI-JavaScript/index.html
Why isn't there any link to this page?

**Comment by orta** [comment]
Do you mean the compiler API when you use `require("typescript")`? - there isn't strictly a docs section for that but https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API is the main starting point

**Comment by Worldwidebrine** [comment]
> Do you mean the compiler API when you use `require("typescript")`? - there isn't strictly a docs section for that but https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API is the main starting point

@orta No.
I mean Promise,Iterator,Generator,Awaited,Map,Set,...

**Comment by orta** [comment]
TypeScript aims to only add a type system, and so the docs don't try to compete with better (and more resourced) projects describing the JS runtime

Those are best documented in MDN in my opinion: https://developer.mozilla.org/en-US/docs/Web

**Comment by Worldwidebrine** [comment]
> TypeScript aims to only add a type system, and so the docs don't try to compete with better (and more resourced) projects describing the JS runtime
> 
> Those are best documented in MDN in my opinion: https://developer.mozilla.org/en-US/docs/Web

@orta I'm not talking about docs for JS.
When I'm using TS, tsc **automatically** uses **built-in types** that is "describing the JS runtime".
https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_es2015_iterable_d_.iterator.html
Without editor type hint, how can I know how to use `Iterator`? How can I know it has 3 arguments?
It's fine that the docs are not better than other JS projects because it is not only docs for JS but also docs for TS.

**Comment by orta** [comment]
Yeah, makes sense, Iterator probably want to be included on the utility types page: https://www.typescriptlang.org/docs/handbook/utility-types.html

But Set / Map, Promise, probably not - perhaps those could have a home in the everyday types handbook page, but it's ready pretty long and to teach generics there is too early in the handbook

**Comment by Worldwidebrine** [comment]
Description is not needed.
I just think that there should be a link to https://microsoft.github.io/PowerBI-JavaScript/index.html
