### ISSUE TITLE
Docs:  Strange code example for converting TS to JS

### ISSUE THREAD

**Issue by ASDFGamer** [microsoft/TypeScript-Website#2634]
**Page URL:** https://www.typescriptlang.org/

**Issue:** 
In the section "TypeScript becomes JavaScript via the delete key." are 3 different code examples. The first two are the same as far as I can see. I think that the second onw with the caption "Types are removed." is the problem.

**Recommended Fix:** 
You could remove the second example or show some way between the full TS file and the full JS file as is indicated by the Caption "Types are removed."

**Comment by orta** [comment]
Looks like the highlight colour in the CSS was changed to be the same colour as the background, making it look like it is the same code sample twice, nice spot

Target:
<img width="1127" alt="Screenshot 2022-12-23 at 10 54 43" src="https://user-images.githubusercontent.com/49038/209323771-3250fcdb-8f74-4476-810e-cdcf8b39ef08.png">

**Comment by orta** [comment]
Thanks - I've fixed this in #2473

**Comment by ASDFGamer** [comment]
Looks good.
I closed the issue, because i think, that the problem is fixed, but i have no problem If it is reopened because, it is the wrong procedure for this repo or the problem isn't fully fixed
