### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by emilmuller** [microsoft/TypeScript-Website#2644]
**Page URL:** https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Issue:**

I'm looking for options for tsc --init. Specifically how to generate a tsconfig with a custom file name, or whether it is possible at all. The only documentation for this command is "Initializes a TypeScript project and creates a tsconfig.json file.". It does not mention that you can in fact add e.g. compiler options that will become part of the tsconfig file.

The fact that that is not mentioned makes me doubt if there are other things not mentioned, e.g. to define a custom file name.

If possible, please document tsc --init completely.

Kind regards, Emil

**Comment by Amarjeetdev012** [comment]
We use 'tsc --init' to generate a tsconfig file, just like how we use 'npm init' to create a package.json file when creating an npm package.
