### ISSUE TITLE
Docs: TSConfig "exclude" default value has display cut off (and inconsistent formatting)

### ISSUE THREAD

**Issue by Andrew-Mackay** [microsoft/TypeScript-Website#2653]
**Page URL:** https://www.typescriptlang.org/tsconfig#exclude

**Issue:** The default value for the "exclude" TSConfig documentation is cut off (and lacks the same "code" formatting as the other default options)

The following screenshot shows what it currently looks like (using Google Chrome Version 107.0.5304.110):
![Screenshot from 2022-12-23 09-36-17](https://user-images.githubusercontent.com/22844315/209313032-40f22d2d-77d4-40ed-8eb1-eaac9f908d7d.png)

And this screenshot highlights that the actual HTML has the full value (as well as a link to https://www.typescriptlang.org/tsconfig#outDir?):
![Screenshot from 2022-12-23 09-44-37](https://user-images.githubusercontent.com/22844315/209313186-1de1de9b-8255-4b89-a35b-7a5445fea68e.png)

**Recommended Fix:** This looks like it might be the first default value that is too wide to fit on one line. I believe it should wrap onto the next line and use the `<code></code>` tags for consistent formatting with the other default values. I also believe the link to https://www.typescriptlang.org/tsconfig#outDir should maybe be removed?

**Comment by orta** [comment]
Looks like it's missing spaces between the commas, that should fix it up at least
