### ISSUE TITLE
Playground: Object property type inferred as unknown when using Identity type

### ISSUE THREAD

**Issue by robertojnior** [microsoft/TypeScript-Website#2660]
I was following [this Twitter thread](https://twitter.com/kentcdodds/status/1608187990215655424) (very insightful by the way) from Kent C Dodds, seeing the solutions, and trying to build my own, to have a better understanding of Generics.

In this process I was comparing these two:

- [separated type definition for the identity function](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgJhAdsAlqAPAFQHxQLxQDeAUFFANoDSUKiUA1hCAPYBmUmAugFxQAUiAIYBbCL0oBKfLgBuzFHGIBfANzFirAK6IAxqmZ0FSVBhx9gveMbQgs2KSTIAnCME1O6wZep0GAzsBQzABGAFb4NAjINnyOUIICIhAOpGRQAPTpUAB6APypZL6IfswANhAAdKXMAOaJohKpSgA0qcH1yUQFGVl53UUl5VW1HY1kSsoSKkA);
- [in-line type definition in the identity function](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDAJgUzLKBPAPAFQD4AKKALkQG9EBtAaWSQGs1s5hF8BdC4sAQwC2aCnQCUiALyFEANzipEAXwmUAUIkQAnNFBBakUNUrVqICAM5REcAEYArKcnSYYOYus38+QtKo2aiAD0QYgAegD8AZrmYBZwADZoAHQJcADmPsJiAUoANAG2WX5U0cGhkWWx8UmpGcU5miYqANxAA);

In the [separated type definition for the identity function](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgJhAdsAlqAPAFQHxQLxQDeAUFFANoDSUKiUA1hCAPYBmUmAugFxQAUiAIYBbCL0oBKfLgBuzFHGIBfANzFirAK6IAxqmZ0FSVBhx9gveMbQgs2KSTIAnCME1O6wZep0GAzsBQzABGAFb4NAjINnyOUIICIhAOpGRQAPTpUAB6APypZL6IfswANhAAdKXMAOaJohKpSgA0qcH1yUQFGVl53UUl5VW1HY1kSsoSKkA) the `obj` is typed as:
```typescript
const obj: Identity<{
  a: unknown;
  b: unknown;
}>
```

Where in the [in-line type definition in the identity function](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDAJgUzLKBPAPAFQD4AKKALkQG9EBtAaWSQGs1s5hF8BdC4sAQwC2aCnQCUiALyFEANzipEAXwmUAUIkQAnNFBBakUNUrVqICAM5REcAEYArKcnSYYOYus38+QtKo2aiAD0QYgAegD8AZrmYBZwADZoAHQJcADmPsJiAUoANAG2WX5U0cGhkWWx8UmpGcU5miYqANxAA) the `obj` is properly typed as:
```typescript
const obj: {
  a: (name: "a") => void;
  b: (name: "b") => void;
}
```

And if in the first solution we do:
```typescript
type X = typeof obj
```
it returns the type correctly:

<img width="338" alt="Screenshot 2022-12-29 at 5 17 30 PM" src="https://user-images.githubusercontent.com/10870576/210007232-a5ba6181-69d1-4025-8c4f-6b7ad19fa5a6.png">

**Repro:**

Use this TS playground: [separated type definition for the identity function](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgJhAdsAlqAPAFQHxQLxQDeAUFFANoDSUKiUA1hCAPYBmUmAugFxQAUiAIYBbCL0oBKfLgBuzFHGIBfANzFirAK6IAxqmZ0FSVBhx9gveMbQgs2KSTIAnCME1O6wZep0GAzsBQzABGAFb4NAjINnyOUIICIhAOpGRQAPTpUAB6APypZL6IfswANhAAdKXMAOaJohKpSgA0qcH1yUQFGVl53UUl5VW1HY1kSsoSKkA)

**Expected behavior:**

When hovering the `obj` variable it returns the correct type:
```typescript
const obj: {
  a: (name: "a") => void;
  b: (name: "b") => void;
}
```

**Actual behavior:**
Its returning the object property with `unknown` type:
```typescript
const obj: Identity<{
  a: unknown;
  b: unknown;
}>
```

**Comment by orta** [comment]
I think you might have posted in the wrong place, this is the repo for the TypeScript website - I think you want to be posting this on the TypeScript repo instead as it doesn't seem to be a problem with the site or the playground?

**Comment by robertojnior** [comment]
> I think you might have posted in the wrong place, this is the repo for the TypeScript website - I think you want to be posting this on the TypeScript repo instead as it doesn't seem to be a problem with the site or the playground?

@orta you're 100% correct, my bad, thanks!
