### ISSUE TITLE
Playground: Automatic type aquisition broken

### ISSUE THREAD

**Issue by eps1lon** [microsoft/TypeScript-Website#2696]
**Repro:**

```tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom'
```

[Playground Link](https://www.typescriptlang.org/play?ssl=2&ssc=38&pln=2&pc=36#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQoksiK62eMAIgPICycREuUocAtABMSZIA)

**Expected behavior:**

Types are aquired

**Actual behavior:**

```
Cannot find module 'react' or its corresponding type declarations.
Cannot find module 'react-dom' or its corresponding type declarations.
```

Possibly caused by

```
Access to fetch at 'https://data.jsdelivr.com/v1/package/resolve/npm/@types/react@latest' from origin 'https://www.typescriptlang.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
apis.ts:55          GET https://data.jsdelivr.com/v1/package/resolve/npm/@types/react@latest net::ERR_FAILED 301
```

**Comment by orta** [comment]
Looks temporary: 
![image](https://user-images.githubusercontent.com/49038/215582454-2e3ab493-8f73-4372-b428-0f83e787cc3e.png)

**Comment by eps1lon** [comment]
Still seeing this: ![Screenshot from 2023-01-31 05-42-08](https://user-images.githubusercontent.com/12292047/215667314-c2300d19-fc46-49af-a6f7-10666c4109ed.png)

 Does it also work for you with cache turned off?

**Comment by orta** [comment]
Yep, 
![image](https://user-images.githubusercontent.com/49038/215689907-6cd3d72f-67d6-42b4-9ea9-82ae63b70a54.png)

I'd recommend asking on the jsdelivr repo, https://github.com/jsdelivr/jsdelivr
