### ISSUE TITLE
Playground: Unable to view AST in nightly builds (5.0.0-dev.20230129)

### ISSUE THREAD

**Issue by liuxingbaoyu** [microsoft/TypeScript-Website#2699]
Unable to view AST in nightly build (5.0.0-dev.20230129)

![image](https://user-images.githubusercontent.com/30521560/215393874-ddc222b7-41e3-485a-9dd0-bb65cc3ae50c.png)

**Repro:**
https://www.typescriptlang.org/play?noImplicitAny=false&declaration=false&ts=5.0.0-dev.20230129#code/GYVwdgxgLglg9mABMMBxOcAmAKAhgJwHMBnASgG8BYAKETsRoF8g

Note: AST Viewer may need to be manually enabled in settings

**Expected behavior:**

Display normally, as in the stable version.

**Actual behavior:**

Display Error.

**Comment by orta** [comment]
This _looks_ like a crash in TypeScript rather then in the playground, I'd recommend writing an isssue on their repo
