### ISSUE TITLE
www.typescriptlang.org doc style problem

### ISSUE THREAD

**Issue by magicdawn** [microsoft/TypeScript-Website#27]
http://www.typescriptlang.org/docs/tutorial.html

It looks like this on 
- macOS sierra
- RMBP 15 inch(2880 x 1800)
- Chrome 53
  ![image](https://cloud.githubusercontent.com/assets/4067115/19076550/d64f45a6-8a7b-11e6-9780-e614411a958b.png)

By guessing the class name you use `col-md-2` & `col-md-10`, I believe it should look like
![image](https://cloud.githubusercontent.com/assets/4067115/19076649/4318522c-8a7c-11e6-9ab4-a1ae9488ef84.png)

and safari is ok
![image](https://cloud.githubusercontent.com/assets/4067115/19077228/535b8ff8-8a7e-11e6-8cff-ba9f02649379.png)

I can not find a repo for the website, so I report this problem here.

**Comment by orta** [comment]
Going to close this, as it won't be an issue with v2 - it will have it's own suite of bugs instead
