### ISSUE TITLE
Front page of v2 Site Doesn't Convey Input/Output well enough

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#270]
I don't think that the current image gives the idea of what the input code will look like compared to the output.

![image](https://user-images.githubusercontent.com/972891/74890644-7cc8d800-5339-11ea-8c99-6ff2212299e7.png)

I think switching it to left-is-input, right-is-output (just like the playground) would be better. Maybe even a label would help.

![image](https://user-images.githubusercontent.com/972891/74890759-df21d880-5339-11ea-82d3-9c27801924e1.png)

**Comment by orta** [comment]
I was going for more of a:

- Here is your editor without TypeScript
- Here is your editor with TypeScript 

vibe.

In part because code is always left aligned - so if I order it [TS] - [JS] then the JS _may_ not fit (or at least can't be cropped) 

I think I can do something like your labels, and then they fade on the first "next" clicked too

Will give it a try

**Comment by DanielRosenwasser** [comment]
Yeah, I think we have to consider what we're trying to convey. Either:

> It's just JavaScript with erased types!

or

> Look at what this experience gives you!

And they're kinda intermingled which makes it harder!

**Comment by DanielRosenwasser** [comment]
I think the labels would be a good minimum if the space is hard to play around with.

**Comment by orta** [comment]
We already have space for a label, do you think this makes it clearer?

![Screen Shot 2020-02-20 at 4 09 28 PM](https://user-images.githubusercontent.com/49038/74978824-6a16d780-53fb-11ea-994f-96fde962ba23.png)

**Comment by orta** [comment]
Also possible, really downplaying older versions (will have to do a bit of work to make that a11y though) 

![Screen Shot 2020-02-20 at 4 19 23 PM](https://user-images.githubusercontent.com/49038/74979562-d9d99200-53fc-11ea-9e1d-57a00a51bd2a.png)

**Comment by orta** [comment]
This design angle was dropped
