### ISSUE TITLE
Playground: Cannot handle multi-file imports in a single code sample in the Playground

### ISSUE THREAD

**Issue by liby** [microsoft/TypeScript-Website#2701]
## Summary

TypeScript Twoslash says it can “[Handle multi-file imports in a single code sample](https://www.typescriptlang.org/dev/twoslash/#:~:text=or%20.map%20files-,Handle%20multi%2Dfile%20imports%20in%20a%20single%20code%20sample,-Creating%20a%20playground)”

https://github.com/microsoft/TypeScript-Website/blob/v2/packages/ts-twoslasher/test/fixtures/importsModules.ts
```
// @filename: Component.tsx
import React from "react"

export function Hello() {
  return (
    <div>
      <h1>Hello World</h1>
    </div>
  )
}

// @filename: index.ts
import { Hello } from "./Component"
console.log(Hello)
```
Try it in the playground and find it doesn't work.

## Screenshot

<img width="877" alt="image" src="https://user-images.githubusercontent.com/38807139/215556272-58ba2dfb-9b10-43ce-b2df-5e6aa210d89d.png">

**Repro:** https://www.typescriptlang.org/play/#code/PTAEAEDMEsBsFMB2BDAtvAXKAwge1QA66JIAuAdKQM4AeAUNIbgE6mgBK8yAxm5M-lAAiZl15C6deDSKtQkAK6Je0YqAAS8WLFwAKAJSgA3nVChRpBc0Shdps6AA8AE2gA3AHz2HTgBYBGD01tXFAAdRZYZ0dgAK8fGNdPe306AF9JEAgYBBR0LGhEZ2lKKgYmOSMNLR1QNPkBVGFyYDwmEkRSCW5iKlwEch0Ac11gnVSgA

**Expected behavior:** It works normally.

**Actual behavior:**  Can't work.

**Comment by orta** [comment]
Twoslash isn't actually running in the playground, there's just some specific features like `// ^?` which were replicated within the playground (I did get multi-file running, but it wasn't stable enough to warrant shipping permanently )

**Comment by liby** [comment]
> I did get multi-file running, but it wasn't stable enough to warrant shipping permanently 

Hope it arrives soon, this issue can be closed (or kept open until it works).
