### ISSUE TITLE
Docs: 5.0 beta announcement blog post has invalid config syntax

### ISSUE THREAD

**Issue by dominikg** [microsoft/TypeScript-Website#2710]
**Page URL:** 
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#supporting-multiple-configuration-files-in-extends

**Issue:** 

examples have `extends` nested inside `compilerOptions` multiple times in the section about multi extends. e.g.
```ts
// packages/front-end/src/tsconfig.json
{
    "compilerOptions": {
        "extends": "../../../tsconfig.base.json",

        "outDir": "../lib",
        // ...
    }
}
```

**Recommended Fix:** 

move extends to top level.

cc @DanielRosenwasser

**Comment by dominikg** [comment]
Improved in the RC announcement but some examples for other features still use extends nested inside CompilerOptions.
eg. https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#satisfies-support-in-jsdoc

**Comment by agilgur5** [comment]
I think these all got fixed? [Beta](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#supporting-multiple-configuration-files-in-extends), [RC](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#satisfies-support-in-jsdoc)
