### ISSUE TITLE
Near-Term Website Simplications (March 2023)

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#2728]
The primary use-case for the website is to learn how to use TypeScript. We think there are some opportunities to simplify our pages to avoid overwhelming newcomers. Additionally, we have a lot of UI whose surface area translates to testing costs that often need to be repeated.

After discussing among @RyanCavanaugh, @navya9singh, and others, we came to a list of near-term improvements we'd like to make. So in the next month or two, we'd like to make the following simplifications:

* [ ] Remove "Popular Documentation Pages" from the footer
* [ ] Remove duplicate "Get Started" sections on the landing page
* [ ] Remove header link to Handbook (prefer Docs), possible rename to "Documentation"
* [ ] Make [Docs](https://www.typescriptlang.org/docs/) a special page within the same docs view that the handbook, references pages, etc. live
* [ ] Investigate whether the [build tool integration page](https://www.typescriptlang.org/docs/handbook/integrating-with-build-tools.html) can link out to external resources
* [ ] Move [Branding](https://www.typescriptlang.org/branding) page to a GitHub repo
* [ ] Move [Cheat Sheets](https://www.typescriptlang.org/cheatsheets) to a docs page or GitHub repo
* [ ] Delist [Tools](https://www.typescriptlang.org/tools) from the header
* [ ] Remove "Errors" view and "Plugins" view from the [TypeScript Playground](https://www.typescriptlang.org/play?)

**Comment by homomorphist** [comment]
> Remove "Errors" view and "Plugins" view from the [TypeScript Playground](https://www.typescriptlang.org/play?)

Does that imply removal of these tabs altogether? Or is it just making the tabs invisible to a newcomer by changing the settings defaults?

**Comment by DanielRosenwasser** [comment]
I've heard a few people ask about the `Errors` tab - I think we'd be open to keeping that around.

Plugins though, we're more skeptical of, and we wonder if using something like `https://vscode.dev` is a better mechanism for these use-cases. Out of curiosity, what are some plugins you currently use @Agapurnis?

**Comment by homomorphist** [comment]
I'd definitely be a fan of keeping the `Errors` tab around.

>  Out of curiosity, what are some plugins you currently use @Agapurnis?

I don't seem to often find myself using them. A lot of the plugins seem to have too-niche of a purpose for me, or are tools to make the editor more on-par with a larger IDE. If I ever need the latter, I'll usually end up switching to something like StackBlitz.

**Comment by tjjfvi** [comment]
I personally find the plugins to be an extremely useful part of the playground, and extensively use the link shortener, vim, and prettier plugins. `vscode.dev` is a great tool, but (afaik) there's no way to share links with it – especially in the context of the TS Discord, where the playground is the go-to way to share code.
