### ISSUE TITLE
Add Greek to inYourLanguage.ts

### ISSUE THREAD

**Issue by Petrosdevri** [microsoft/TypeScript-Website#2747]
I would like to translate this TypeScript guide into Greek, as I have seen there is no individual who has submitted any issue. Because this procedure is large and complicated, I would like to learn more about what I can translate therefore it would be appreciated if I began with the inYourLanguage.ts file.

**Comment by orta** [comment]
Localization work is documented over here: https://github.com/microsoft/TypeScript-Website-Localizations#typescript-website-localizations

That said, I wouldn't recommend putting much time into it until you see either of these repos getting PRs merged
