### ISSUE TITLE
Docs: Awaited section release version hyper link redirect to 404 page.

### ISSUE THREAD

**Issue by JeevanMahesha** [microsoft/TypeScript-Website#2758]
**Page URL:**  https://www.typescriptlang.org/docs/handbook/utility-types.html

**Issue:**  
Awaited<Type> section release version hyper link redirect to 404 page.

step 1:- Navigate to Utility Types 
step 2:- Awaited Type section there is an hyper like for release version when we click it redirect for 
release doc.

The URL added for the release number is wrong. we have to change it.

**Recommended Fix:** 

Existing URL :- https://www.typescriptlang.org/docs/handbook/docs/handbook/release-notes/typescript-4-5.html#the-awaited-type-and-promise-improvements

Expected URL :- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#the-awaited-type-and-promise-improvements

In the existing your there is docs/handbook path twice if we remove it it will work as expected.

**Comment by Sruthi12032001** [comment]
Yes, I too faced this issue.

**Comment by agilgur5** [comment]
Looks like this was fixed by OP in https://github.com/microsoft/TypeScript-Website/pull/2763

**Comment by JeevanMahesha** [comment]
> Looks like this was fixed by OP in #2763

yes it's closed @agilgur5
