### ISSUE TITLE
typescript-vfs still accesses local storage even when storer is provided

### ISSUE THREAD

**Issue by arteme** [microsoft/TypeScript-Website#2762]
Typescript-vfs module caches data is the local storage or the provided storer. This should -in theory- make typescript-vfs compatible with environments without local storage access, like the web workers. However, even when a storer is provided, the code accesses `localStorage` instead of `storelike` here, which is clearly a bug:
https://github.com/microsoft/TypeScript-Website/commit/920a54021725d2412f7963f93ec39fe4daeb37f1#diff-221727bfd6227563593353939e5f0944f6d1465c0f207a55a4a248990e821171L293

**Comment by orta** [comment]
Makes sense to me, you're welcome to send a PR and bump the version number in the package.json 👍🏻
