### ISSUE TITLE
Docs: "Try it yourself" example of d.ts declaration usage doesn't work.

### ISSUE THREAD

**Issue by LeonardoDaLuz** [microsoft/TypeScript-Website#2764]
"Try it yourself" example of d.ts declaration usage doesn't work.

https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html

![image](https://user-images.githubusercontent.com/80224694/228413231-02ab658f-3eab-458b-bdc4-32d9353071bc.png)

I don't know how to fix it as I'm trying to learn but the docs aren't clear. It doesn't work for me, and the example running on the site doesn't either.

**Comment by orta** [comment]
The example is to show how the .d.ts file works - if you click on ".d.ts" tab in the sidebar, you can see how it works.

If you'd like to add a type to the `arr`, that'd be a good PR to send
