### ISSUE TITLE
Playground: Add a way to copy the share URL from the UI

### ISSUE THREAD

**Issue by DanKaplanSES** [microsoft/TypeScript-Website#2788]
The first time I used the site I was very confused about how to share my playground with others. I figured it out when somebody told me the keyboard shortcut to copy the url is `ctrl+s` (at least on Windows).

I think they should also be added to the UI, perhaps as a menu item. 

**Repro:**

1. Create a new playground
2. Attempt to share the playground by copying the URL into your clipboard

**Expected behavior:**
There is UI somewhere that provides this functionality

**Actual behavior:**
New users have to learn that `ctrl+s` achieves this.

**Note:**
Maybe there is some way of doing this on the UI that I haven't found. Perhaps simply copying the address bar achieves the same effect. In my experience, this isn't expected, as a a lot of similar sites address bar links to the page owner's version, not the public version. 

Regardless, I think this functionality should be easier to find on the UI.

**Comment by orta** [comment]
There is a big "Share" button on the toolbar which does this which you missed:

![image](https://user-images.githubusercontent.com/49038/232041183-07c14a4b-0c9f-432e-8838-20422c7d9a50.png)

**Comment by DanKaplanSES** [comment]
Oops. Well that's embarrassing. Not sure how I missed that. ~~I'm going to close this and create a similar issue.~~ Actually, I'm having a lot of fleeting thoughts so I think I'll just write an additional comment:

**Comment by DanKaplanSES** [comment]
Here's my brain dump of various UX changes. Apologies if anything I say comes out rude or assertive; these are weakly held, half-baked opinions I'm sharing to give food for thought, and I'm the furthest thing from a designer. 

Some ideas are incompatible with others.

- [ ] Some export menu items are related to exporting, but others are related to sharing. Consider:
    - [ ] Merge export and share into a single drop down menu named "Share".
    - [ ] Turn share into a drop down menu like export and move the relevant menu items into it
- [ ] This is purely anecdotal, but I can't recall the last time I interacted with the Run button, nor can I recall the last time somebody wrote a playground that required using it; consider changing the order of the menu from most used to least used. For me, that would be: Share, Export, Run, v5.0.4. (If these are going to be a rearranged, IMHO, it should be ordered based on the frequency of all the users, not just me.)
- [ ] I don't understand why TS Config and v5.0.4 are on separate rows. At a high level, both are related to configuring the current playground. 
    - [ ] re: the TS Config row: The TS Config menu is for configuring the current playground. The next two menus are help resources. Settings is on the far right, which seems to be related to configuring the current playground. 
    - [ ] I think you could consolidate all the TS Config and the v5.0.4 content into the Settings menu, and that's where I would expect to find it. 
- [ ] For UI consistency, consider giving the settings button the up/down triangle that exists on the right-hand side of the other menus like TS Config, Examples, Help, etc.
    - [ ] Also consider giving it a "close" button in the upper right hand corner like the others

If any of these are worthy of consideration, let me know and I will create a separate ticket. Otherwise, feel free to close this issue on my behalf as the original was made in error. Thanks!
