### ISSUE TITLE
missing `deleteFile` function in VirtualTypeScriptEnvironment

### ISSUE THREAD

**Issue by flurrux** [microsoft/TypeScript-Website#2799]
the VirtualTypeScriptEnvironment interface has two file-related functions `createFile` and `updateFile`, but seemingly no `deleteFile`.

https://github.com/microsoft/TypeScript-Website/blob/b89d197063b6849bbfc2edfb033f6082be950636/packages/typescript-vfs/src/index.ts#L22-L23

is this intended?
i've tried using the `VirtualTypeScriptEnvironment.sys.deleteFile` function, but it is undefined.  

my current workaround is to set the file contents to a single-space string (completely empty strings currently throw errors as reported here: #2713).  
it's not too big an issue for me right now since my virtual files are not directly visible and their names are auto-incremented, but i figured this would be worth posting here.

**Comment by orta** [comment]
I never needed one for the Playground, / twoslash so I never thought to add it - I think it makes sense to send a PR adding it 👍🏻

**Comment by marklundin** [comment]
Just following up on this. Is there a reason `deleteFile` is no included?  I could take a look at a PR, but wanted to make sure the omission is not by design
