### ISSUE TITLE
CRITICAL: Dead link.

### ISSUE THREAD

**Issue by MicahZoltu** [microsoft/TypeScript-Website#2806]
**Page URL:**
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html

**Issue:**
This link is dead, and I'm not sure what to link to instead.
https://github.com/microsoft/TypeScript-Website/blob/62f87a80f571762ff252eb38b53b890f9f864acb/packages/documentation/copy/en/release-notes/TypeScript%202.6.md?plain=1#L15

**Comment by MicahZoltu** [comment]
Hmm, I just checked the GitHub repository and this still appears to be a broken link.  Is the fix perhaps in a branch or something?

**Comment by jakebailey** [comment]
In the template you filled out:

> For errors, typos, etc in documentation or other website copy, please send a PR

A link to the web archive would be fine. But this isn't a critical issue as defined by the issue template.
