### ISSUE TITLE
`object` type in v2 docs

### ISSUE THREAD

**Issue by quangv** [microsoft/TypeScript-Website#2813]
Hi I was looking for a type for an "any" object literal.

I saw the type `object` in [depreciated basic types page.](https://www.typescriptlang.org/docs/handbook/basic-types.html#object), but no mention of it in [replacement "Everyday Types" page](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html).

Is the `object` type out of favor? I've also tried `{ [x: string]: unknown }`.

**Comment by andrewbranch** [comment]
When you clicked "Create New Issue", the issue form was pre-populated with a “critical issue” template. Unfortunately, we don’t have the bandwidth to triage questions and other issues that don’t track broken website functionality. For questions and discussion, we suggest joining the [TypeScript community Discord](https://discord.gg/typescript). We are also accepting well-scoped pull requests to improve the documentation; see #2804 for more details. Thank you for understanding!
