### ISSUE TITLE
Docs: "types" and "typings" are synonymous in Module Resolution.md

### ISSUE THREAD

**Issue by HamdaanAliQuatil** [microsoft/TypeScript-Website#2863]
**Page URL:** https://www.typescriptlang.org/docs/handbook/module-resolution.html#how-typescript-resolves-modules

**Issue:** `package.json` can contain any of the two fields `types` and `typings`. When TypeScript resolves a module it may look for either of the two fields. It would be beneficial from a clarity and documentation standpoint if the `Module Resolution.md` mentioned that the `typings` field can be used interchangeably with the `types` field.

**Recommended fix:** Rewrite for clarity in Module Resolution.md under the following section:
1. Add a note under "How TypeScript resolves modules" mentioning `typings` is also permissible in `package.json`
2. Under relative import pt. 4, mention `typings` within parenthesis.
3. Under non-relative import pt. 4, 12, and 20, mention `typings` within parenthesis.
4. Leave output under "Tracing module resolution" in the current state as it is not incorrect.
5. Add a note under "Things to look out for" pt 3, indicating that the output may contain a `typings` field.

**Comment by jakebailey** [comment]
Per #2804, we're not accepting non-critical issues. That being said, I think we already turned down this change as `typings` is not something we want anyone using even if it technically works.
