### ISSUE TITLE
Playground: ATA not working correctly for JS files

### ISSUE THREAD

**Issue by burtek** [microsoft/TypeScript-Website#2872]
**Page URL:** https://www.typescriptlang.org/play?filetype=js#code/PQKhAIAEGcEMBcCW0BmiCm1wG9EFsAHAewCd4AKAckwBtEA7eAWgBN0170mBjI+tAOaUAlADoAYjQQBRAMoAZBvADCfQQG0AugF9wIYAChe9aPHCxwAXnBaDQA

**Issue:** With ATA enabled, in playground set to JS type, types for packages are not acquired.

![image](https://github.com/microsoft/TypeScript-Website/assets/2940958/3ad6b9d5-859d-4293-9eb7-5ae0e886236c)

`import ('eslint-define-config')` works correctly in TS files

**Comment by orta** [comment]
I think the ATA code will only work with top level `import`s, instead of inline imports in comments as it uses the typescript compiler API to grab imports - additional code would be needed to grab imports referenced via import types. It should be fine in a JS playground using import though

**Comment by burtek** [comment]
By top level `import`s do you mean `import x from y`? Or anything that's not JSDoc?

The below [works fine](https://www.typescriptlang.org/play?filetype=ts#code/MYewdgzgLgBAhjAvDA2gXRhOUCWEBmOAphDDgLYAOIATlABQDkJANjmFALQAmRhYRTqDCEA5owCUAOgBiLbAFEAygBl2UAMLgx6ANwAoIA), so I'd expect jsdoc comment to also work... :thinking:

```ts
const a = [] satisfies import('eslint-define-config').FlatESLintConfig[];
```

**Comment by jakebailey** [comment]
You must have deleted the template; per #2804, we're not accepting issues that aren't critical (totally broken page, malicious links, accessiblity, etc). We'd accept a PR to fix this up, but at the moment we're not tracking issues besides critical ones.
