### ISSUE TITLE
Two pages named "Modules" in the handbook

### ISSUE THREAD

**Issue by not-my-profile** [microsoft/TypeScript-Website#2873]
There is the [Modules](https://www.typescriptlang.org/docs/handbook/modules.html) page and then there is the [Modules](https://www.typescriptlang.org/docs/handbook/2/modules.html) page (note the /2/ in the URL).

#1611 apparently didn't add a `deprecated_by` frontmatter field for the older page.

Most confusingly the new page still references the old same-named page:

> and you can find information about the other module patterns in the reference section under [Modules](https://www.typescriptlang.org/docs/handbook/modules.html).

If we don't deprecate the older page for the former then I think we should at least rename it (perhaps to `Modules (Legacy)`), update the backlinks accordingly and add a reference to the newer page to the intro of the older page.

**Comment by jakebailey** [comment]
You must have deleted the template. Per #2804, we're not accepting non-critical issues; we'd happily accept a PR which improves things if you have a concrete idea, but otherwise short of the page not actually rendering or being totally broken, I'm going to close this.

**Comment by not-my-profile** [comment]
No, I didn't delete anything. You still have blank issues enabled, see #2879.

**Comment by jakebailey** [comment]
Darn, well, I just assumed nobody would click that.
