### ISSUE TITLE
The community section of the website has broken links.

### ISSUE THREAD

**Issue by Sadeedpv** [microsoft/TypeScript-Website#2878]
In the meetup section of this [page](https://www.typescriptlang.org/community), there are broken links; it says that the meetup group you're looking for doesn't exist.

**Comment by jakebailey** [comment]
You must have missed the issue template; per #2804 we aren't accepting issues except absolutely critical ones. If one of the links goes somewhere really bad, then we definitely want to know about it, but otherwise we'd appreciate a PR which fixes the links or removes them.
