### ISSUE TITLE
Inheriting JSDoc comments declared on an interface in the implementation class

### ISSUE THREAD

**Issue by x11x** [microsoft/TypeScript-Website#2898]
Should it be documented somewhere (i.e. the "JSDoc Reference page"?) that you can write JSDoc comments on interfaces, and implementing classes automatically inherit them?
Maybe this is specific to the tooling and not to TypeScript itself, but `@inheritdoc` is mentioned in the TypeScript docs.

- `@inheritdoc` is listed under [Unsupported tags](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#unsupported-tags), which says there's an open issue for it ([#23215](https://github.com/Microsoft/TypeScript/issues/23215)). That issue is now closed, maybe docs should change to reflect this? It looks like `@inheritdoc` is now supported, but only for static class members? (I'm a bit unclear).
- However, I noticed that in tooling I use (VSCode) and also the TS Playground, that the expected thing automatically happens without the need for `@inheritdoc`. In fact, if you do try to use `@inheritdoc`, it overwrites the summary section with the string `{@inheritdoc ...}`, but if you omit it completely, it correctly inherits all relevant parts of the JSDoc from the interface.
- I'm not sure what happens with documentation site generation tools. Based on reading issue [#1498](https://github.com/TypeStrong/typedoc/issues/1498), it looks like TypeDoc aims to support this, but someone at the bottom mentioned it was still not working, also it is maybe less powerful or complete than VSCode (does not work for some more complex cases like `Omit`ting members).

[Playground link](https://www.typescriptlang.org/play?#code/PQKhCgAIUhBA7SBLeAXApgJwGYEMDG6kAJugM76ZIBGKA5pLpAO5LF3qoB0UMAAgAcArtQA2SfL2Dh0ADwEB7TKmRoseQpACSAdTYcVAbyiRQESBZgARTLmZlIqABZFW7TpAWJnRYkjICorgAnpBkQjgE6DwW0JAmcYK4tgC2kLKQALSOLpAAGpCKZEioSF6e2Dmu+pwJ-ALJuGmh2T6QAJqFCsWl5QqVbW4GdZB8mJwR8A5yTYHoddIWxLbMABSyAFyQ8EIp1FgANJDBWzt7WACUW9QKCqLouPAA3OAAvuDgZqPCYhLQ0nJFMpIPggmQHAAhISoVBeACMyBScxS6DQDl0NSMJh+4nwJBW61Ou32mCOJ22xMu11u90ekGMsUg41Qk0geFEZHQLws73enzA3xEuP+MnkShUoNw4MgUJhXgATIjkajUOi9O4sRYvnwUC4qKgrAo8SBFoUhX9lnZCRTzqTjkTbVdIDc7g9EAzYszWezOdzILyPtqcX8TaKgRKwZDobD4ABmJX3FFo7Tqgz0kxfQw6+B6kqGvEYjVcS3MV4iizBvEl61nElkh0kp0u2nuhJMiaYRA+rkmAOfYCQAASCgAblhPGPMJAAEQl6eOBRhdC+I27FW4XrwDbgVbwdDMGXR+EXYsrJ6mAf4JTjfCoHd7g+ymPyk8l8-AS-X9C3+-7w9yuNXzPC8wl2FJklCUcsGYfUMEQVhnHpbNcwNI1IC4DDXiAA)

**Comment by jakebailey** [comment]
If you want to send a PR to clarify something, we'd appreciate it, but per #2804, we aren't accepting issues that are not "critical", and it doesn't seem like you used the issue template.
