### ISSUE TITLE
Suggestion:It will be good to open multi language of document and let us to translate it.

### ISSUE THREAD

**Issue by wengrs** [microsoft/TypeScript-Website#29]
I want to translate some of the document to Chinese. But I cannot show it on the website.

**Comment by orta** [comment]
There's a whole translation process going on via https://github.com/microsoft/TypeScript-Website/issues/100 and the [TypeScript Community Discord](https://discord.gg/typescript). If you'd like to get started, now is the time!

We have a few Japanese pages now: https://www.typescriptlang.org/v2/ja/play
