### ISSUE TITLE
`bundler` and `node16` not mentioned in Module Resolution

### ISSUE THREAD

**Issue by shishkin** [microsoft/TypeScript-Website#2913]
Handbook [Module Resolution page](https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies) doesn't mention newly added `bundler` and `node16`/`nodenext` options. There are also implications that are not mentioned in [the config reference](https://www.typescriptlang.org/tsconfig#moduleResolution), but only in [the announcement blog](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler).

**Comment by andrewbranch** [comment]
This is in progress: https://github.com/microsoft/TypeScript/issues/52593
