### ISSUE TITLE
Playground: Unable to run code - TypeError: window.i is not a function

### ISSUE THREAD

**Issue by gsuuon** [microsoft/TypeScript-Website#2925]
**Page URL:** https://www.typescriptlang.org/play

**Issue:** Clicking 'Run' errors with

```
localizeWithFallback.ts:4 Uncaught TypeError: window.i is not a function
    at localize (localizeWithFallback.ts:4:26)
    at Object.willMount (runtime.ts:92:39)
    at activatePlugin (createElements.ts:250:32)
    at runButton.onclick (index.ts:449:21)
```

![Screenshot 2023-08-25 124857](https://github.com/microsoft/TypeScript-Website/assets/6422188/a9191399-25aa-4762-b1e8-aa0622a84973)

**Comment by jakebailey** [comment]
I can't reproduce: 
![image](https://github.com/microsoft/TypeScript-Website/assets/5341706/36a275b2-f45b-4a38-a517-375b5f51d15e)

**Comment by gsuuon** [comment]
Other user (in closed issue):
https://github.com/microsoft/TypeScript-Website/issues/411#issuecomment-1686621141
Also saw repro comments in Discord:
https://discord.com/channels/508357248330760243/1142137314924048395/1142137314924048395

**Comment by jakebailey** [comment]
Even in an incognito window, things work for me, but I can run `window.i` and it is indeed a string.

**Comment by jakebailey** [comment]
Finally did get it to crash, somehow. 
![image](https://github.com/microsoft/TypeScript-Website/assets/5341706/570ce6a1-be21-4a33-b4b3-062bc6193a24)

Seems like there's a race loading the localization code:

![image](https://github.com/microsoft/TypeScript-Website/assets/5341706/64fd54ad-e859-4d02-a7c0-1da7617237f1)

**Comment by orta** [comment]
Perhaps the ms cookie banner script is introducing it's own `window.i`? `__ms$mod__` is a strange identifier/string

The code booting up the playground has `window.i` setting up before it pretty unambiguously

https://github.com/microsoft/TypeScript-Website/blob/4f7eb6497e8f1e3cbaec8e2919950ae37d08ee3d/packages/typescriptlang-org/src/templates/play.tsx#L58-L183

**Comment by jakebailey** [comment]
Could be application insights? https://github.com/microsoft/ApplicationInsights-JS/blob/45b91f72c8e4b451ecf4c7e44a35f945b4371881/rollup.base.config.js#L76

**Comment by orta** [comment]
Yeah, I agree - that's probably it.

Could have the run button re-assign `window.i`

**Comment by tadashi-aikawa** [comment]
I encountered the same problem on Windows 11 and Google Chrome.

In the secret mode, it doesn't often occurs but almost always when devtools is open.

https://github.com/microsoft/TypeScript-Website/assets/9500018/1a512a52-941c-40c5-abb4-be6b2b5574e8

**Comment by jakebailey** [comment]
> Yeah, I agree - that's probably it.
> 
> Could have the run button re-assign `window.i`

Possibly, though that wouldn't help plugins or anyone trying to look it up without the Run button.

I was going to suggest changing the code to use another less-conflict-y name like `__tsLocalize` but we'd have to leave `window.i` behind for plugins, yet that will still be broken.

We could make the prop dynamic and have a setter just ignore writes, but...
