### ISSUE TITLE
twoslash doesn't support cutting and showing errors

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#293]
I wanted to include a code sample like this:

```
// @errors: 2322
interface User {
  name: string;
  id: number;
}
// ---cut---
const user: User = {
  name: "Hayes",
  iD:123
}
```

But could not

**Comment by hahmadia** [comment]
@orta

Is this still valid? Seems to be working now 
![image](https://user-images.githubusercontent.com/17804942/110747150-e600df00-820b-11eb-86de-d865b8a5c47c.png)

**Comment by orta** [comment]
Looks like it to me, yeah
