### ISSUE TITLE
Missing documentation of TypeScript 5.2 

### ISSUE THREAD

**Issue by liuliangsir** [microsoft/TypeScript-Website#2935]
Page URL: none yet

Issue: There is no mention of TypeScript 5.2 in What's New section inside the handbook. The only official documentation about them is [in the release notes of TypeScript 5.2](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/).

Recommended Fix: For the sake of completeness, there should be a release note about TypeScript 5.2 in What's New section inside the handbook.

**Comment by andrewbranch** [comment]
@navya9singh can you take a look? Thanks!

**Comment by 0xJaskeerat** [comment]
@andrewbranch @navya9singh I was too about to open a similar issue regarding this 

Anyways, since all the information is present in the release notes 
I would love to contribute to the What's New Section,  so @andrewbranch can you please assign this to me . 
I'll submitting a related PR for you guys to review

**Comment by andrewbranch** [comment]
Thank you for offering @0xJaskeerat, but we have a private repo with the markdown source of the release notes so it's easier for one of us to just paste it into here.

**Comment by 0xJaskeerat** [comment]
Hey @andrewbranch , can you tell me please what all repos are open for 
Open Source Contributions , so that I can play with those only. ?

**Comment by andrewbranch** [comment]
Contributions are accepted here, but that doesn’t mean we’ll always accept any PR for any issue. See https://github.com/microsoft/TypeScript-Website/issues/2804 and https://github.com/microsoft/TypeScript/blob/main/CONTRIBUTING.md
