### ISSUE TITLE
Update module-resolution page

### ISSUE THREAD

**Issue by ShuiRuTian** [microsoft/TypeScript-Website#2942]
**Page URL:** 
https://www.typescriptlang.org/docs/handbook/module-resolution.html#node

**Issue:** 
node introduces https://nodejs.org/api/packages.html#exports and [imports](https://nodejs.org/api/packages.html#imports), maybe we should update this part

**Comment by jakebailey** [comment]
See: https://github.com/microsoft/TypeScript/issues/52593
