### ISSUE TITLE
CRITICAL: 

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript-Website#2949]
the typescript playground is not opening in the new tab which makes it little bit unconvenient to use.

**Comment by jakebailey** [comment]
This most definitely isn't a critical issue, sorry.

Whether or not a link should open in a new tab or not is a hotly debated item, as some people _don't_ want to open a new tab and setting `target="_blank"` means _nobody_ can have that behavior; you can Ctrl+click or middle click to do that quickly.
