### ISSUE TITLE
Playground pollutes history with hundreds of entries/minute.

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/TypeScript-Website#301]
**Search Terms:**
playground history

It seems every keypress triggers a new history entry to be added. This quickly fills up my history with hundreds/thousands of playground entries. This is on Edge.

**Comment by orta** [comment]
Dupe of https://github.com/microsoft/TypeScript-Website/issues/190 - there's an option to turn this off in the  new history but I'm afraid the correct browser API do this even though they say it won't https://github.com/microsoft/TypeScript-Website/issues/8
