### ISSUE TITLE
performance page says to use --trace-ic but node says bad option

### ISSUE THREAD

**Issue by lukeapage** [microsoft/TypeScript-Website#3012]
On this page:
https://github.com/microsoft/TypeScript/wiki/Performance#performance-tracing

It says to do this:

```
node --trace-ic ./node_modules/typescript/lib/tsc.js --generateCpuProfile profile.cpuprofile -p tsconfig.json
```

but in node v18 I get:

```
C:\Program Files\nodejs\node.exe: bad option: --trace-ic
```

**Comment by jakebailey** [comment]
This is the wrong repo for this issue; that's the wiki of the main TypeScript repo.

**Comment by lukeapage** [comment]
Sorry :/ I will move this to the main repo.

**Comment by jakebailey** [comment]
I was about to do it for you, sorry! (Got distracted)

**Comment by lukeapage** [comment]
done it now: https://github.com/microsoft/TypeScript/issues/57016
