### ISSUE TITLE
Errors yarn installing on an M2 Macbook Pro

### ISSUE THREAD

**Issue by Stream-web** [microsoft/TypeScript-Website#3016]
The error reported in the environment of node 16.19.1 is as follows 
fsevents@patch:fsevents@npm%3A1.2.11#~builtin<compat/fsevents>::version=1.2.11&hash=18f3a7 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/bx/7hvpbzf15fx9wbqnr3_qfvq40000gn/T/xfs-a0498197/build.log)
➤ YN0009: │ bufferutil@npm:4.0.1 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/bx/7hvpbzf15fx9wbqnr3_qfvq40000gn/T/xfs-30edbd5b/build.log)
➤ YN0009: │ utf-8-validate@npm:5.0.2 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/bx/7hvpbzf15fx9wbqnr3_qfvq40000gn/T/xfs-0805469e/build.log)
➤ YN0009: │ sharp@npm:0.28.1 couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/bx/7hvpbzf15fx9wbqnr3_qfvq40000gn/T/xfs-3f5f5320/build.log)

**Comment by jakebailey** [comment]
This is certainly _not_ critical; you also have not provided those logs. Most likely, you're missing xcode or something.
