### ISSUE TITLE
Older versions of TypeScript (2.x) aren't working in the new playground 

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#305]

**Comment by orta** [comment]
Related: #347

**Comment by orta** [comment]
I re-uploaded them, but it seems to be API issues for a lot of them

**Comment by orta** [comment]
The tsWorker background thread isn't getting set up right (missing monaco global) which I'm not quite sure  - but I've shipped this https://github.com/microsoft/TypeScript-Website/commit/12f1bea680bf74171c84dd9c464065d1c0a38c8b#diff-f417bef08d6d6a088ed8d57da75acda0R171 to only show working TS versions

**Comment by kzaabox** [comment]
I was using this site by targeting ES3 with TS version v2.8.1 (this version is used by our project for legacy reasons). 
Please make the older TS versions to work with the new site and don't leave it like that. Thanks. :)

**Comment by orta** [comment]
This probably isn't going to happen now, it's enough work keeping support for the different possible runtimes for the 3.x branches that I'm OK with dropping support for older versions - sorry!
