### ISSUE TITLE
[Pdf] Pdf document not found in the provided url

### ISSUE THREAD

**Issue by itssenorito** [microsoft/TypeScript-Website#3094]
I googled pdf of typescript, and found something, but when I clicked, I didn't get the pdf or the page, instead I got 404 from GitHub pages: 
![Screenshot_20240510_202705_Chrome](https://github.com/microsoft/TypeScript-Website/assets/125188557/ba251229-8364-4d54-9593-8f5de3995f17)
Link: https://www.typescriptlang.org/assets/typescript-handbook.pdf

Browser: chrome, android.
Regards.

**Comment by jakebailey** [comment]
PDFs have been explicitly removed from the site: https://github.com/microsoft/TypeScript-Website/pull/2619#issuecomment-1331128079
