### ISSUE TITLE
Playground support compiler option --jsxFactory 

### ISSUE THREAD

**Issue by zheeeng** [microsoft/TypeScript-Website#31]
As title

**Comment by orta** [comment]
[Here's a working example](https://www.typescriptlang.org/play/index.html?jsx=2#code/PQKgsAUABCUAICsDOAPKBTFBDAtgBwBt1IZhJIAzAVwDsBjAFwEsB7GjbfIqACgDoBWAE4BzJAC4oWGgE8A2gF0AlJJpUcAI3RCoAbxJQh6BlSHsALACZIAX3IQAJujoFh6KNXrM2UAGpN0AHcePCEWPAk9KAZMBkkkBiEmGhEoGxUpWQBuezo2BKgHFhwoAF4oAB5-IOjY0oAiAAt0AgIWKECWIQIHeqhgAD4soA)

```ts
/*
 * @jsx example
 */

function example (...args: any[]): number {
  return 42
}

declare function View(props: { text: string }): any;

const dom = <View text="hello world" />;
```

**Comment by zheeeng** [comment]
Thx, @orta
