### ISSUE TITLE
bug in example of the tsconfig.json's guide: https://www.typescriptlang.org/tsconfig/#noImplicitAny

### ISSUE THREAD

**Issue by giangann** [microsoft/TypeScript-Website#3105]
instead of use **substr()** funtion, i think it have a wrong typo so now the function using is **subtr()**
it cause unexpected behavior when try to run example
![image](https://github.com/microsoft/TypeScript-Website/assets/70595717/5ac7143c-2693-4c0c-a3eb-85ecbacef171)

**Comment by jakebailey** [comment]
This is an intentionally broken example, as the lack of an annotation is hiding the fact that there's a typo.
