### ISSUE TITLE
TSX syntax highlighting

### ISSUE THREAD

**Issue by ceymard** [microsoft/TypeScript-Website#311]
It seems the tsx mode doesn't have syntax highlighting.

Is it something to do with monaco-typescript ?

I'm trying to get the playground working with a lib I'm building for online example checking, and the lack of tsx syntax highlighting makes it all look funky...

**Comment by orta** [comment]
Yeah, I think this is a monaco-editor issue, it has a unique setup for syntax highlighting called monarch (you can see the JS one here: https://microsoft.github.io/monaco-editor/monarch.html ) - that would need to be improved
