### ISSUE TITLE
Playground stuck at "Downloading TypeScript"

### ISSUE THREAD

**Issue by cshaa** [microsoft/TypeScript-Website#3110]
**Page URL:** https://www.typescriptlang.org/play/

**Issue:** Opening the playground only shows "Downloading TypeScript" and never loads. The console shows a timeout error. Tested in Brave and Firefox.

![image](https://github.com/microsoft/TypeScript-Website/assets/1671665/fd159a2c-f014-404c-9941-20d9ad99a64b)

![image](https://github.com/microsoft/TypeScript-Website/assets/1671665/82149a82-4caa-4155-9eb1-cf8b9feb9a03)

**Comment by cshaa** [comment]
Oh, it works again

**Comment by jakebailey** [comment]
I do see this happen sometimes and a refresh always fixes it. Thanks for noticing that it's some sort of timeout, though, though it's confusing why unrelated scripts would also time out?
