### ISSUE TITLE
CRITICAL: https://www.typescriptlang.org/assets/typescript-cheat-sheets.zip/

### ISSUE THREAD

**Issue by Mohitkumar6122** [microsoft/TypeScript-Website#3126]
**Page URL:** : [https://www.typescriptlang.org/assets/typescript-cheat-sheets.zip/](https://www.typescriptlang.org/assets/typescript-cheat-sheets.zip/)

**Issue:**  https://www.typescriptlang.org/assets/typescript-cheat-sheets.zip/

![image](https://github.com/microsoft/TypeScript-Website/assets/47894634/80c1548a-786d-447a-9b2e-d0fb014a0f10)

**Comment by orta** [comment]
You added an extra `/` -  https://www.typescriptlang.org/assets/typescript-cheat-sheets.zip

**Comment by jakebailey** [comment]
Unless there's a page on the site which links this wrong, this isn't something that's a problem here.

**Comment by Mohitkumar6122** [comment]
@orta , @jakebailey I clicked on the [Download PDFs and PNGs](https://www.typescriptlang.org/assets/typescript-cheat-sheets.zip/) link on the official doc

![image](https://github.com/microsoft/TypeScript-Website/assets/47894634/86667496-ba1f-4bc9-bee7-920602116436)

**Comment by Mohitkumar6122** [comment]
Here is the official doc link https://www.typescriptlang.org/docs/
You can check this by yourself.

**Comment by Mohitkumar6122** [comment]
> You added an extra `/` - https://www.typescriptlang.org/assets/typescript-cheat-sheets.zip

Thanks for the cheatsheet
