### ISSUE TITLE
Feature Request: Maintain playground plugin state between tabs

### ISSUE THREAD

**Issue by just214** [microsoft/TypeScript-Website#313]
It seems like it could be useful for the playground plugins to maintain state between sidebar tab selections. I imagine there could be scenarios where a user might want to see the JS, errors, or DTS without losing their place in a plugin they are using.  

I've been thinking about how this could be handled in templates and the only idea that comes to mind is to utilize localStorage, however, this would would have to be tied into the state model of any frameworks that might be utilized, meaning more abstractions for the user. 

I was thinking that perhaps this could beneficial to be changed at the API level. I've been reviewing the source to see what it would take to keep the plugin alive between tab selections. I  see how everything is getting generated but haven't quite traced down to where the contents of `div.playground-plugin-container ` is getting updated between tab selections. Definitely interesting diving into the playground source :) 

If this is something that seems like it could be useful, I am happy to continue to look into it and try to make the necessary changes.

**Comment by orta** [comment]
I added a `data` to the Plugin interface a while back - I think it's pretty reasonable for that to get persisted between tabs? So far I've been using local storage everywhere, but maybe it could be the playground's job to serialize and de-serialize that into localstorage

**Comment by gojutin** [comment]
I'll take a look at `data` and see how I might be able to utilize that with the templates. I might also expose a custom `useState` hook that ties into localStorage, although, I'd really like to avoid this abstraction if possible.

**Comment by gojutin** [comment]
Would it make sense or be feasible to only actually unmount the plugin if the user explicitly does so and not between sidebar tabs? If so, that seems like it would simplify extensibility the most.

**Comment by orta** [comment]
We could yep, there might need to changes to the Plugin API itself but I'm not offended by the change - so long as it's easy for a plugin to register for monaco changes only when its foremost
