### ISSUE TITLE
text not readable when chrome dark mode

### ISSUE THREAD

**Issue by bluelovers** [microsoft/TypeScript-Website#316]
when dark mode is enable, option text will not readable

![image](https://user-images.githubusercontent.com/167966/76072171-72157080-5fd2-11ea-8df4-6938a2ac6202.png)

**Comment by orta** [comment]
Cool, looks like when I brought in the right fonts - they brought some coloring with them! Fixing

**Comment by orta** [comment]
Fixed & deployed
