### ISSUE TITLE
Internal links don't work

### ISSUE THREAD

**Issue by pagdot** [microsoft/TypeScript-Website#317]
All internal links don't seem to work atm. External links work fine.

I get following error in the JavaScript console of my browser when clicking on an internal link:

```
Error: 404 page could not be found. Checkout https://www.gatsbyjs.org/docs/add-404-page/
```

**Comment by orta** [comment]
#290 - I think it's this and I have a guess that https://github.com/microsoft/TypeScript-Website/commit/d4916f4fad8f4b8913319023c1c53e0e5c89fd68 will fix it, if it doesn't then I'll be reverting the weekend test 👍

**Comment by mdchristians** [comment]
Noticing the same thing in Chrome and Firefox.  Opening in a new tab does work, however.

**Comment by orta** [comment]
Cool, this is fixed now 👍
