### ISSUE TITLE
Playground: code formmating broken with TS3.4+ readonly notation

### ISSUE THREAD

**Issue by jcalz** [microsoft/TypeScript-Website#32]
**Code**:
Looks like the [`readonly` modifier for arrays](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#improvements-for-readonlyarray-and-readonly-tuples) breaks code reformatting in the Playground.

```ts
// comment out to allow reformatting
const oops: readonly number[] = [1, 2, 3];
/*
SyntaxError: "',' expected. (2:22), parser-typescript.js
> 2 | const oops: readonly number[] = [1, 2, 3];
    |                      ^
*/

// Alt + Shift + F: IT DOES NOTHING!!!
const 
x 
= 
1;
```
**Expected behavior:**
Code reformats (so `const x = 1;` is moved to a single line)

**Actual behavior:**
Code does not reformat.  A console error indicates that the `readonly` modifier is not expected.

**Playground Link:**
[Playground Link](https://www.typescriptlang.org/play/index.html#code/PTAEGMHsFtoUwHYBdSQK4qZUBDANnpAO6gBOcAZpKdDkkgJYIDmAUFAgM4qSQAOnAFxk4OACaQEeAJ6gEaaACM4pANoBdUAF5QqgIwAaUACYjAZnUBuVsABUrAMrTkOAB4BRUqWrCARAHIDf1A4Vz44cCQ4MQA6UAAKY0FjYwBKIz4cUk4VAFokaXDOcFIGPiQYgCtOVgA+E1AAHwhJblR+IRFxSRk5BWU1TR19I1NQC2tQKabp2bn52YA9VltgVhswAEE8FABqUAcACwYKPdAAMWEASQAVUAARAHl3B1AAOUebgAkrt4BxACEQPYrRQrFcoFYOlYeksQA)

**Related Issues:**
microsoft/TypeScript#29435, introducing the `readonly` modifier for array types

**Comment by orta** [comment]
Weird, looks like the [prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEIAc1KYBOcAhgCbQA2AnplAK4C2ARnEQNoC6mAvJhwCMAGkwAmUQGYuAbgA6UEMJB4YAS3TJQpIkQgB3AAo6EaZCFIA3CGvJKQLIqTABrODADKuZ2qgBzZBgiBjhlAAsYJioAdTC1eDRvMDgPU3i1S3iaczA0M2VfNHYYQyc-JlJkADNSKiLlACs0AA8AISdXdw9SJjgAGV84atr6kCbmj18-KjgARQYIeGG60JBvIiKicxgaXDg0MCI1XBh7XCPYaNsYMOQADgAGZXOIIuinXHNz-fZLIeUAI4LeClPBmFCkNAAWigcDg5Hh9hIQLUJFKpHKlSQNRWyiKTDUgWCqzQUxm80WQ2xI1WMFILCu5BuyAkICCpDUVCmAGEIEwKuYoNB-iAGEUACr08E4ooAX1lQA) doesn't have this problem. 

The new playground will go back to the built-in TS formatter, so you're welcome to look at maybe updating the prettier for this playground in the meantime.

**Comment by orta** [comment]
Moving back to the TS formatter fixed this 👍

**Comment by jcalz** [comment]
[Playground link](https://www.typescriptlang.org/play/index.html#code/PTAEGMHsFtoUwHYBdSQK4qZUBDANnpAO6gBOcAZpKdDkkgJYIDmAUFAgM4qSQAOnAFxk4OACaQEeAJ6gEaaACM4pANoBdUAF5QqgIwAaUACYjAZnUBuVsABUrAMrTkOAB4BRUqWrCARAHIDf1A4Vz44cCQ4MQA6UAAKY0FjYwBKIz4cUk4VAFokaXDOcFIGPiQYgCtOVgA+E1AAHwhJblR+IRFxSRk5BWU1TR19I1NQC2tQKabp2bn52YA9VltgVhswAEE8FABqUAcACwYKPdAAMWEASQAVUAARAHl3B1AAOUebgAkrt4BxACEQPYrRQrFcoFYOlYeksQA) still looks bad to me; is there some website/playground release schedule or some other thing I'm missing?

**Comment by orta** [comment]
It's on this PR: https://github.com/microsoft/TypeScript-Website/pulls
