### ISSUE TITLE
Broken links in v2 website

### ISSUE THREAD

**Issue by BurtHarris** [microsoft/TypeScript-Website#320]
The site tells me that v2 is being tested over the weekend.  It seems to contain systematic problems in hyperlinks. 

On page https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html there are hyperlinks to other sections of the declaration-file chapter, e.g.  'Library Structures' links to a non-existant page https://www.typescriptlang.org/docs/handbook/declaration-files/Library%20Structures.md.   

The proper pages can be reached through the table-of-contents tree on the left, but only if the screen is wide enough to show it.   For the above example, the correct link seems to be to https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html

**Comment by orta** [comment]
Thanks, looks like the old site would handle re-writing markdown links between files!
