### ISSUE TITLE
Show compiler invocation instead of installation ...

### ISSUE THREAD

**Issue by InnanYuan** [microsoft/TypeScript-Website#321]
In the "Install TypeScript" section at the bottom of [TypeScript home](https://www.typescriptlang.org/), I think the command quoted under the "Then run the compiler via `tsc`" section should be something like "`tsc <your_program.ts>`" instead of current "`npm install -g typescript`". Maybe another harm of copy&paste? 🤒

![Screen Shot 2020-03-08 at 09 44 30](https://user-images.githubusercontent.com/59414428/76155065-c9762680-6121-11ea-9dc9-491eb252f453.png)

**Comment by orta** [comment]
Yeah, bad localization c&p - fixed in next deploy! Thank you!
