### ISSUE TITLE
[Minor] [v2] Deep-linking and a compliment

### ISSUE THREAD

**Issue by hossameldeen** [microsoft/TypeScript-Website#322]
### Deep-linking

Not sure if a bug or intentional design, but in this screenshot the first 3 boxes point to the same link, instead of, e.g., making "Understand the tooling" point to https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

![image](https://user-images.githubusercontent.com/6719916/76157397-143b7280-6111-11ea-90a4-ce926248e91f.png)

### A compliment

Whoever has the designed the screenshot above is a genius!  ... I indeed came for the tooling section, and the 2 or 3 other sections concisely compress my goals when accessing the site. Also, the release box is just 🚀 

So, yes, feel free to close if the 3 boxes linking to the same page is intentional.

**Comment by orta** [comment]
Thanks! 

Yeah, I spent some time having a think about what the best call to action could be once you've got a general sense of where you might want to go once you _might_ have been persuaded that TS is worth your time. 

It took 4 designs to get to that quarterly releases section, even now it's quite "representational" on timelines but I think it shows the idea well!
