### ISSUE TITLE
Wide tables get trimmed on v2 site version

### ISSUE THREAD

**Issue by Kefir100** [microsoft/TypeScript-Website#324]
Hey there! Some of the parts are getting trimmed.
Specifically, the Description column is half hidden and cannot be scrolled horizontally.

<img width="1440" alt="Снимок экрана 2020-03-08 в 13 44 55" src="https://user-images.githubusercontent.com/22402935/76161318-52ea2080-6143-11ea-8800-eca8d0bc8ba8.png">

**Comment by orta** [comment]
oof, yeah

**Comment by orta** [comment]
Well, it can scroll now  and the page overall is less bad (the sidebar is suppressed) 

I think once I get mdx support in the site then I'll make this codegen'd

**Comment by Kefir100** [comment]
Yeah, thanks! It works just fine for now
