### ISSUE TITLE
TS Playground-v2 automatic type acquisition: "Cannot find module 'react'."

### ISSUE THREAD

**Issue by ford04** [microsoft/TypeScript-Website#326]
There currently seems to be a problem with react types / automatic type acquisition in general (or I just don't have got the hang of the new Playgroundv2 yet):
```
import React, { useState } from "react"; // error
import ReactDOM from "react-dom"; // error
import {pipeable } from "fp-ts" // works

const App = () => {
    const [state, setState] = useState(42);
    return <div>test {state}</div>;
};

ReactDOM.render(<App />, document.getElementById("root"));
```
[Playground link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDecCuAzkgMowoxJwC+cAZlBCHAERSoYsDccA9L3CRRGUAFChIsRBxgARAPIBZeo2ZsZAWgAmTbnwFCR48NHg4wwMKgBGAGyq0GTVnTAaYhFvrgB3aAGtCUVE0CAA7QngAQTAwOABeOAAKAEoEgD5cUTgcuFCI+ABtSIokbGIYMlKAXQSCYirKJIAWACYUrmzc9hh8KDC4AB4tYAA3dMpI3BLKakHeEfHO6k7RZHQ5JQA6djCtISTBmLjedOwdNHwQJDCYLYBzJBgAUXtr24AhAE8ASS0ktgQCAwFgpDpAA)

Above code first resulted in "react" and "react-dom" not found errors, "fp-ts" was found. Adding custom npm modules didn't help either. ATA is enabled as seen down under, `esModuleInterop` and jsx option checked as well. Strangely enough, sometime it doesn't work with any library  (I cannot reproduce it consistently).

Is this an unhappy coincidence with the new site's testing weekend or a known issue?

![grafik](https://user-images.githubusercontent.com/16099458/76163393-fc321600-6145-11ea-8217-719e916f6695.png)

**Comment by orta** [comment]
Hrm, the ATA code in v2 hasn't changed since [Jan 2nd](https://github.com/microsoft/TypeScript-Website/commits/v2/packages/sandbox/src/typeAcquisition.ts) - will add some more debugging tools to the v2 code to see if something is up there

**Comment by orta** [comment]
hah, this is because we added React as an exposed variable to playground plugins
