### ISSUE TITLE
Compiler Options link is broken

### ISSUE THREAD

**Issue by sparebytes** [microsoft/TypeScript-Website#327]
The link to Compiler Options at the bottom of this page under "Details" doesn't work. 
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
it points to
https://www.typescriptlang.org/v2/tsconfig
instead of
https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by orta** [comment]
Thanks! Fixed in the next deploy
