### ISSUE TITLE
Documentation vanished

### ISSUE THREAD

**Issue by jbruni** [microsoft/TypeScript-Website#328]
Links at homepage, header, footer, _etc_, are pointing to https://www.typescriptlang.org/docs/index.html

It seems the new documentation home is at https://www.typescriptlang.org/docs/home

I am reporting this here due to the notification showing at the top of the website saying "_Note: we are testing out the new v2 site over the weekend, if we have missed something you rely on please file issues on microsoft/TypeScript-Website_"

Thank you.

**UPDATE**: see [screenshots below](https://github.com/microsoft/TypeScript-Website/issues/328#issuecomment-596217628)

**Comment by orta** [comment]
Thanks for the issue

I can't find any of these links? Any chance you can be more specific? I'll make a re-direct anyway, but I'd rather fox the root problems.

**Comment by jbruni** [comment]
Thanks, @orta 

Well... I just browsed https://www.typescriptlang.org/ 

- There is "Documentation" link, first at the header top navigation.
- There is "Documentation" button, call to action
- There is "Learn it fast" button, another call to action
- Near the bottom/footer, there is a "Docs" link, under "Learn"

I will post corresponding screenshots in next comment

**Comment by jbruni** [comment]
@orta - Screenshots of the links:

### Header top nav

![doc-link-1](https://user-images.githubusercontent.com/69181/76165733-17962480-6138-11ea-9fa9-9e284f772a27.png)

### CTA button

![doc-link-2](https://user-images.githubusercontent.com/69181/76165735-2b418b00-6138-11ea-8f30-939ec4e6448c.png)

### Other CTA button

![doc-link-3](https://user-images.githubusercontent.com/69181/76165738-32689900-6138-11ea-8388-f5078214a7f0.png)

### Bottom link

![doc-link-4](https://user-images.githubusercontent.com/69181/76165741-3d232e00-6138-11ea-8d88-8ce5b689ddcd.png)

----------------------

This is what I get by clicking on them:

### Missing page

![doc-404-1](https://user-images.githubusercontent.com/69181/76165745-4c09e080-6138-11ea-9d15-44237341ca10.png)

### Access denied

![doc-403-1](https://user-images.githubusercontent.com/69181/76165752-5af09300-6138-11ea-8479-d6c0eabd32b2.png)

**Comment by orta** [comment]
Interesting, this looks like a local overly agressive caching issue - over the weekend the site has [looked like this](https://twitter.com/orta/status/1236411190349312000) (I've also added + deployed the redirects, so it might fix itself on your next browse )

**Comment by jbruni** [comment]
Thanks, @orta 

Indeed! I'm surprised to acknowledge I was seeing the previous site version...

Anyway, The workaround was as simple as opening dev tools (configured to skip cache) and reload the page.
