### ISSUE TITLE
Safe area is not always respected in iOS SafariViewController

### ISSUE THREAD

**Issue by jineshshah36** [microsoft/TypeScript-Website#330]
To reproduce, open the app in in-app iOS SafariViewController, And scroll down then back up slowly

![9BF32D46-D7EA-4C9E-A38B-21596EC0EAA0](https://user-images.githubusercontent.com/6501089/76166120-81abcb00-6132-11ea-997b-b9cf94685c89.png)

**Comment by orta** [comment]
Hrm, the CSS definitely declares that it should respect the safe area - I wonder if embedded safariVCs keep the rules of their outer apps and it's not conforming right?

**Comment by jineshshah36** [comment]
Yeah it is weird, not sure if there's anything that can be done

**Comment by orta** [comment]
Not really much I can do here, I'm open to ideas if someone comes along and finds this in the future
