### ISSUE TITLE
ATA not working for @squill/squill

### ISSUE THREAD

**Issue by AnyhowStep** [microsoft/TypeScript-Website#333]
Code:
```ts
import * as sql from "@squill/squill";

sql.table("test");
```

Playground:
http://www.typescriptlang.org/v2/en/play?#code/JYWwDg9gTgLgBAKjgQwM51QRwDZwGZQQhwBEAAlgK7DbYD0VN2JA3AFAcdbYB0MyAI2wBTABQkYw1DBIBKFkA

Screenshots:
![image](https://user-images.githubusercontent.com/5655961/76270978-7a2d1480-624d-11ea-9154-6ddd1a2eadd7.png)
![image](https://user-images.githubusercontent.com/5655961/76270989-8022f580-624d-11ea-8989-f5a764d54a17.png)

Expected: `sql.table()` should be defined, it's a function exported by the package.
Actual: A bunch of errors

**Comment by AnyhowStep** [comment]
It seems to be looking for `dist/expr-column.d.ts` when it should be looking for `dist/expr-column/index.d.ts` (which, itself, will export from stuff from other files/directories)

**Comment by orta** [comment]
Cool, yeah, basically a dupe of #248 

I've not added all the nodejs routing to ATA

**Comment by AnyhowStep** [comment]
Ah. I'll close this, then. I did try to hack in support to fix it but I quickly realized I wasn't going very far =(

**Comment by AnyhowStep** [comment]
Anyway, I managed to make my own Playground that pulls in a list of hard-coded packages thanks to your well-written code <3

I didn't really need full node resolution, in the end (although it would have made life easier).
