### ISSUE TITLE
markdown for tsconfig "plugins" is not displayed

### ISSUE THREAD

**Issue by Quramy** [microsoft/TypeScript-Website#334]
I found https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/plugins.md , but this markdown is not listed in https://www.typescriptlang.org/v2/tsconfig .

And I found the entry for "plugins" gets the following, which is generated via gerenateJSON.ts :

```json
    {
      "name": "plugins",
      "type": "list",
      "isTSConfigOnly": true,
      "element": {
        "name": "plugin",
        "type": "object"
      },
      "description": {
        "code": 6181,
        "category": 3,
        "key": "List_of_language_service_plugins_6181",
        "message": "List of language service plugins."
      }
    }
```

This entry misses `categoryCode` key because  the original entry in ts.optionDeclarations has no `category` object (All ts.optionDeclarations items excluding `help` and `plugins` have `category` section).

How can I fix this?

**Comment by orta** [comment]
Let's manually set its category to Project Options in the generation script
