### ISSUE TITLE
Feature request: "on this page" should float as you scroll and highlight current section

### ISSUE THREAD

**Issue by ur92** [microsoft/TypeScript-Website#336]
Seems that if "on this page" will be always visible and highlight the current section, it will make navigation a lot easier. 
See [Jest docs](https://jestjs.io/docs/en/getting-started.html) for example 
![image](https://user-images.githubusercontent.com/6205315/76468552-e0a06700-63f4-11ea-95ba-9f4eeca20064.png)

**Comment by orta** [comment]
looks like there was already code for it, but it doesn't seem to be working

**Comment by pamtbaau** [comment]
I would like to expand on this by requesting to also scroll the left side menu.

**Comment by orta** [comment]
I tried that and went back on it, it didn't feel right and scrolling in it is awkward

**Comment by orta** [comment]
This is fixed
