### ISSUE TITLE
d.ts  Guide page is missing

### ISSUE THREAD

**Issue by RusinovAnton** [microsoft/TypeScript-Website#340]
I've tried to find docs about d.ts, so I searched for them and saw this search result:

![image](https://user-images.githubusercontent.com/13165540/76686444-124b4500-6624-11ea-9d5a-097edb43cd38.png)

clicking on the link in dropdown redirects me to the http://www.typescriptlang.org/docs/home.html#try-beta

which says: 
> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by orta** [comment]
Thanks - Fixed with #349
