### ISSUE TITLE
syntax typo in typescript docs

### ISSUE THREAD

**Issue by akulsr0** [microsoft/TypeScript-Website#341]
Hey there, I have found a syntax typo in typescript handbook documentation.

### Typo
In official doc, enum is defined as follows: 
``` typescript
enum Color 
  Red,
  Green,
  Blue
}
let c: Color = Color.Green;
```
*But, there is no opening curly-brace i.e. '{'*

``` typescript
enum Color {
  Red,
  Green,
  Blue
}
let c: Color = Color.Green;
```

[Link to typo](http://www.typescriptlang.org/docs/handbook/basic-types.html)

Kindly update the docs, and fix this typo.

**Comment by akulsr0** [comment]
Snapshot of typo: 
![Screenshot 2020-03-14 at 10 58 11 PM](https://user-images.githubusercontent.com/43666833/76687162-5d2a8400-6647-11ea-9235-916a39e27fe0.png)

**Comment by orta** [comment]
This looks like a twoslash bug, code in the markdown is correct

**Comment by orta** [comment]
This got fixed, thanks!
