### ISSUE TITLE
Suggestion: Dark Syntax Highlight when navigating docs

### ISSUE THREAD

**Issue by IagoLast** [microsoft/TypeScript-Website#342]
Hi there 👋  

Just found a banner asking for suggestions about the new page so here you got my 2 cents.

I got dark mode enabled and I think it would be nice having the code snippets on a dark scheme too.

<img width="1373" alt="Example of a snippet with the VSCODE theme" src="https://user-images.githubusercontent.com/2657897/76689364-64489680-6635-11ea-8359-2340ddc17686.png">

Regards

**Comment by orta** [comment]
One day, but the syntax highlighter gives raw color hex values, so it'd take some work to make that happen.

**Comment by Enteleform** [comment]
This.

Seriously.

Me, upon witnessing the supreme contrast of the redesign:
![dont. do. it.](https://media0.giphy.com/media/LRCxXWRljt4LYf6AK1/giphy.gif)

&nbsp;  
Go with a dark theme, or a light theme. Please don't do both 🙏 👁 ⚡️ 🙅‍♂  
&nbsp;  
(*unless you have a toggle that allows you to pick one or the other...*) 👈 💯 👌

**Comment by orta** [comment]
You're welcome to take a look at it, until then it's in the backlog 👍

**Comment by tjjfvi** [comment]
This is a code snippet I've used to dark mode things in the past. It attempts to keep the "color" of the color relatively unmodified, while swapping light/dark.

```ts
import Color from "color";

function darkModeColor(color: Color){
    const inversionAmount = Math.pow(1 - color.saturationv() / 100, 2);
    color = color.mix(color.negate(), inversionAmount);
    return color;
}
```

It would be great if someone could implement this or similar; the contrast is painful atm.

**Comment by orta** [comment]
This has been fixed 👍🏻
