### ISSUE TITLE
Rogue "0"

### ISSUE THREAD

**Issue by mrlovett** [microsoft/TypeScript-Website#344]
Reading the Declaration Files documentation and noticed that on the Templates pages there are random zeros next to the articles (see attached images). This can be found on the main Template page and all subsequent templates.

Rogue zeros are marked with red circles on the screenshots.

![typescript-templates-rogue-zero-1](https://user-images.githubusercontent.com/34556357/76692374-80f0c880-664d-11ea-8803-42529414c962.jpg)

![typescript-templates-rogue-zero-2](https://user-images.githubusercontent.com/34556357/76692378-85b57c80-664d-11ea-9ead-153a741b17ec.jpg)

**Comment by orta** [comment]
I bet this is the check for headers to show the sidebar
