### ISSUE TITLE
Playground: hard to see the code in Dark Mode

### ISSUE THREAD

**Issue by ValeriiVasin** [microsoft/TypeScript-Website#351]
Please add the ability to change the theme, or pick the theme, that is having more contrast.

It is hard to see the keywords here:
![image](https://user-images.githubusercontent.com/918065/76707759-573dad00-66f2-11ea-914f-ad235c9feff2.png)

Especially if you are working on a big screen.

**Comment by orta** [comment]
I feel like this is the default, but I'm open to changing the colors to be brighter

**Comment by seunghee114** [comment]
Could I try to work on this?

**Comment by R99bbit** [comment]
can i working on this issue?

**Comment by orta** [comment]
Yep

**Comment by orta** [comment]
This is fixed!
