### ISSUE TITLE
Unable to switch playground out of TSX mode

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript-Website#353]
The playground has a toggle for choosing what `--jsx` is passed to the compiler, but setting it to None still leaves the playground's input file as `input.tsx` resulting in compilation errors when trying to use generic arrow functions.

[Playground](http://www.typescriptlang.org/en/play?#code/MYewdgzgLgBAZgVzMGBeGAeAKgPgBQCGATkQFwxYCUaOMA3gFAMC+A3EA)
```ts
const func = <T>(arr: T) => {
};
```

This is a regression - the old site allowed the above code since it was not contained in a TSX file.

**Comment by jcalz** [comment]
@orta Is this back again?
