### ISSUE TITLE
I found a syntax error in the handbook.

### ISSUE THREAD

**Issue by leeyunhome** [microsoft/TypeScript-Website#354]
Hello, 

I found a syntax error in the handbook.
https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-oop.html

![image](https://user-images.githubusercontent.com/59910227/76713355-6741a500-6763-11ea-93a1-8eb71bc81fb8.png)

Thank you

**Comment by orta** [comment]
All likely the same thing as #350 and #341
