### ISSUE TITLE
Several images are missing from ASP.NET Core page

### ISSUE THREAD

**Issue by th91vi** [microsoft/TypeScript-Website#357]
10 images (perhaps screens) are missing from the cited page. Console errors below.

- asp-net-core.html:64 GET https://www.typescriptlang.org/assets/images/tutorials/aspnet/new-asp-project-empty-17.PNG 404 (Not Found)
- asp-net-core.html:62 GET https://www.typescriptlang.org/assets/images/tutorials/aspnet/new-asp-project-empty.png 404 (Not Found)
- asp-net-core.html:88 GET https://www.typescriptlang.org/assets/images/tutorials/aspnet/install-nuget-packages.png 404 (Not Found)
- asp-net-core.html:99 GET https://www.typescriptlang.org/assets/images/tutorials/aspnet/new-folder.png 404 (Not Found)
- asp-net-core.html:101 GET https://www.typescriptlang.org/assets/images/tutorials/aspnet/scripts-folder.png 404 (Not Found)
- asp-net-core.html:105 GET https://www.typescriptlang.org/assets/images/tutorials/aspnet/new-item.png 404 (Not Found)
- asp-net-core.html:178 GET https://www.typescriptlang.org/assets/images/tutorials/aspnet/task-runner-explorer.png 404 (Not Found)
- asp-net-core.html:120 GET https://www.typescriptlang.org/assets/images/tutorials/aspnet/new-tsconfig.png 404 (Not Found)
- asp-net-core.html:212 GET https://www.typescriptlang.org/assets/images/tutorials/aspnet/running-demo.png 404 (Not Found)
- asp-net-core.html:220 GET https://www.typescriptlang.org/assets/images/tutorials/aspnet/paused-demo.png 404 (Not Found)

![image](https://user-images.githubusercontent.com/42702980/76722951-6c333400-6724-11ea-958f-272aaa9ccd19.png)

**Comment by orta** [comment]
Thanks! Fixed on the next deploy
