### ISSUE TITLE
Missing overview of typescript utility types

### ISSUE THREAD

**Issue by ntziolis** [microsoft/TypeScript-Website#360]
First of great work. like the new more detailed documentation.  that said In the previous version there was a fantastic overview that should be included up top as this is what most people use as a reference they could always get back to for quick overview. if not on top we def need a direct link to such an overview. thx

**Comment by orta** [comment]
Hi, I think you just missed the page - it's still in the same URL and in the sidebar: https://www.typescriptlang.org/docs/handbook/utility-types.html

![Screen Shot 2020-03-16 at 8 35 41 AM](https://user-images.githubusercontent.com/49038/76758984-247ecd80-6761-11ea-96f5-0f29b3e14f6b.png)
