### ISSUE TITLE
--target and --module: ES2020 missing from the website

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript-Website#363]
`tsc --version` prints 3.8.3 and `tsc --help|grep target` prints:
>  -t VERSION, --target VERSION                       Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'.

https://www.typescriptlang.org/tsconfig#target under `Allowed` does not mention “ES2020”.

**Comment by dilyanpalauzov** [comment]
Likewise `tsc --help|grep module` prints:
>  -m KIND, --module KIND                             Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'.

and ES2020 is not under `Allowed` at https://www.typescriptlang.org/tsconfig#module

**Comment by orta** [comment]
Thanks! This is fixed in the next deploy
