### ISSUE TITLE
On playgorund, the link to typescript-playground-presentation-mode is wrong

### ISSUE THREAD

**Issue by j-oliveras** [microsoft/TypeScript-Website#365]
On playground in Presentation Mode, the link to typescript-playground-presentation-mode npm package is wrong: it goes to https://www.npmjs.com/packagetypescript-playground-presentation-mode instead of https://www.npmjs.com/package/typescript-playground-presentation-mode (slash after package).

**Comment by orta** [comment]
Thanks! Fixed in next deploy
