### ISSUE TITLE
Playground:'Log' on the right side of page miss delayed message when using 'Promise'

### ISSUE THREAD

**Issue by asurance** [microsoft/TypeScript-Website#367]
**Code**
```ts
main()
async function main() {
    console.log(1)
    Promise.resolve().then(() => {
        console.log(2)
    })
    console.log(3)
}

async function main2() {
    console.log(1)
    new Promise((resolve) => {
        console.log(2)
        resolve()
    })
    console.log(3)
}
```
**Logs**
```
1
3
```
We need to open browser debugging tools to get actual result.
```
1
3
2
```
It can be confusing or misleading for people who are not familiar with the 'Promise'

**Comment by orta** [comment]
Makes sense, you're welcome to take a look at this here: https://github.com/microsoft/TypeScript-Website/blob/v2/packages/playground/src/sidebar/runtime.ts

**Comment by asurance** [comment]
> Makes sense, you're welcome to take a look at this here: https://github.com/microsoft/TypeScript-Website/blob/v2/packages/playground/src/sidebar/runtime.ts.  

OK,I know why the problem will happen.Because the delay calls `console.log`, if you just change `console.log`, you really can't output the delayed message。I have a bold idea, but I'm not sure it's feasible and that is to use `namespace` or something like that.
```typescript
const another = console
//random name guarantee no conflicts
namespace a {
    // set context for this use
    const console = {
        log(...argv: any[]) {
            another.log(`under namespace a`)
            another.log(...argv)
        }
    }
    // user‘s first use
    console.log(1)
    Promise.resolve().then(() => {
        console.log(2)
    });
    // end
}
namespace b {
    const console = {
        log(...argv: any[]) {
            another.log(`under namespace b`)
            another.log(...argv)
        }
    }
    // user's second use
    console.log(3)
    // end
}
```
And the output:
```
under namespace a
1
under namespace b
3
under namespace a
2
```
So you can distinguish between the first and the second.

**Comment by Zlatkovsky** [comment]
@asurance , @orta , I just submitted a pull request to fix this issue, and verified that @asurance 's example now works correctly.

**Comment by Zlatkovsky** [comment]
Actually, looks like my fix is incomplete. See more discussion [here](https://github.com/microsoft/TypeScript-Website/pull/1376#issuecomment-734919002)
