### ISSUE TITLE
importHelpers documented twice

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript-Website#368]
https://www.typescriptlang.org/tsconfig documents twice importHelpers: once under “Project options” and once under “Advanced”.  All other options are documented only once.

**Comment by sasurau4** [comment]
@orta I confirmed ths issue fixed in latest https://www.typescriptlang.org/tsconfig.
I think this issue fixed by https://github.com/microsoft/TypeScript-Website/commit/b72ff9cdc6d3424edc91054485026606bd9da91d and could you close?
