### ISSUE TITLE
Bug reporting link to github does not work

### ISSUE THREAD

**Issue by erikaadvisser** [microsoft/TypeScript-Website#369]
Page: https://www.typescriptlang.org/community section: Github

I wanted to report a documentation improvement, but the link is currently:

https://www.typescriptlang.org/{{ site.data.urls.ts_github_issues }} 

The irony :)

**Comment by JulianG** [comment]
same for other links in he community page:
- StackOverflow
- Twitter
- Definitely Typed

**Comment by orta** [comment]
Thanks! Fixed
