### ISSUE TITLE
Hyperlink to next release 3.9 links to 3.8

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript-Website#370]
https://www.typescriptlang.org/ says:
“
Quarterly Releases

Our next release is *3.9*, which is planned for May 12
”

Behind 3.9 there is hyperlink to https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html .  So 3.9 links to 3.8 which is wrong

**Comment by orta** [comment]
Thanks! Fixed in next deploy
