### ISSUE TITLE
moduleResolution: for module:es2020 the default is Classic

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript-Website#371]
https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies says:
```
Module Resolution Strategies

There are two possible module resolution strategies: Node and Classic. You can use the --moduleResolution flag to specify the module resolution strategy. If not specified, the default is Classic for --module AMD | System | ES2015 or Node otherwise.

Classic

This used to be TypeScript’s default resolution strategy. Nowadays, this strategy is mainly present for backward compatibility.
```

I use module: es2020 and have to specify explictly moduleResolution: Node.  So Classic is applied also for es2020 and the documentation shall reflect this.

**Comment by dilyanpalauzov** [comment]
Also for module:: ESNext, the moduleResolution is Classic, for tsc for tsc 3.8.3.

**Comment by orta** [comment]
This has been updating for the new site 👍
