### ISSUE TITLE
tsconfig page is missing?

### ISSUE THREAD

**Issue by MarkoCen** [microsoft/TypeScript-Website#377]
The [tsconfig](https://www.typescriptlang.org/tsconfig) doc page is missing. not sure if it renamed or removed by accident

**Comment by anka-213** [comment]
It is linked to from amongst others this page: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

They should probably try running a spider on the website that checks for dead links automatically.

**Comment by MarkoCen** [comment]
> 
> 
> It is linked to from amongst others this page: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
> 
> They should probably try running a spider on the website that checks for dead links automatically.

Since a lot of external sites (like my company's github pages) still reference the old pages. I think a better way is to do a 301 redirect, from the old page to the renamed page,

**Comment by karlhepler** [comment]
Here's the Google cache for those in need: https://webcache.googleusercontent.com/search?q=cache:ni4Pqj9z5UkJ:https://www.typescriptlang.org/v2/tsconfig+&cd=1&hl=en&ct=clnk&gl=us

**Comment by orta** [comment]
Going to close this in favor of #378 - thanks peeps

Those two pages are different pages, and don't need re-directs 👍
