### ISSUE TITLE
TypeScript Site is experiencing 404s

### ISSUE THREAD

**Issue by mckennapsean** [microsoft/TypeScript-Website#378]
In production, I am seeing the v2 site (as noted on the [Documentation page](http://www.typescriptlang.org/docs/home/)) but other pages are not loading:

- [Downloads](http://www.typescriptlang.org/download): "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."
- [Tools](http://www.typescriptlang.org/tools): "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." 
- [Playground](http://www.typescriptlang.org/play/#): Stuck infinitely on "Downloading TypeScript...", console shows 404's for various resources

**Comment by TimMensch** [comment]
The whole reference site seems to be down.

* None of the handbook sidebar links at the "Handbook Reference" or below work.
* The search box does nothing.

And there are a ton of JavaScript files and a manifest that return 404. 

Everything is broken. 😭

**Comment by lynnic26** [comment]
online accident

**Comment by TimMensch** [comment]
So they're aware and it's being fixed?

**Comment by orta** [comment]
I am now, I've just deployed the v2 site to see if that fixes it ( https://github.com/microsoft/TypeScript-Website/actions/runs/57628789 )

**Comment by orta** [comment]
I've tried deploying https://github.com/microsoft/TypeScript-Website/commit/578726141df8c9bde76e38046a64d086fff9a7c4 an older build c3b67960b88a6c853945aef3ba71927f91fcf966 of the site in case it's something which has been added in the last few days

**Comment by nickzelei** [comment]
> I've tried deploying [5787261](https://github.com/microsoft/TypeScript-Website/commit/578726141df8c9bde76e38046a64d086fff9a7c4) an older build [c3b6796](https://github.com/microsoft/TypeScript-Website/commit/c3b67960b88a6c853945aef3ba71927f91fcf966) of the site in case it's something which has been added in the last few days

Has this been deployed? Just went to link someone to the playground and saw it was broken like described above. Getting a few errors in the console.

![image](https://user-images.githubusercontent.com/2420177/76889353-abf03d80-6842-11ea-91cc-a47102eacc35.png)

**Comment by orta** [comment]
It has, it just doesn't seem to have worked

I'm now trying to deploy an even older v1 without the v2 at all

**Comment by orta** [comment]
Still looking at this

**Comment by aleksandrlat** [comment]
Is it possible to access old version for now?

**Comment by orta** [comment]
Deploying the old site is having the same problems as deploying the new site I'm afraid.

**Comment by orta** [comment]
I've successfully got the current site up and running on our internal staging services: http://testsite-typescript-41eeb979-7eaa-4c74-9d47-9d182c7b61ab.azurewebsites.net/

With luck I can port that over

**Comment by Leko** [comment]
To me, it looks like your staging website is working.

**Comment by harold-b** [comment]
Note that I am also getting 404s in the Playground. It never stops "Downloading Typescript...":
![image](https://user-images.githubusercontent.com/11462418/76900556-917c8b00-6867-11ea-8c38-089c1870cb8e.png)

**Comment by orta** [comment]
Alright, I've figured out the underlaying cause and will do a post-mortem once I've got all the site wrapped up and working fine, shouldn't be long now.

**Comment by orta** [comment]
OK, that's it back up and running 🎉

**Comment by Bonlou** [comment]
Not sure of the usefulness of my comment, but I can't access https://www.typescriptlang.org/tsconfig.

![image](https://user-images.githubusercontent.com/29218400/76905360-0f5d8800-68a2-11ea-9f6f-9ae02c1412b1.png)

Keep the good work going ! :+1:

**Comment by orta** [comment]
That page is only available during the betas, you can get access to it at https://www.typescriptlang.org/v2/tsconfig

**Comment by mckennapsean** [comment]
Playground appears to be up & running. Other links I have were wrong but everything seems accessible off [the main site](https://www.typescriptlang.org/) now. Thanks for the fast replies & updates, @orta & team!

**Comment by orta** [comment]
I've created a post-mortem for the downtime: https://github.com/microsoft/TypeScript-Website/issues/385

**Comment by s001dxp** [comment]
Good work @orta! Thanks for your timely fixes.
