### ISSUE TITLE
404's for all resources on playground

### ISSUE THREAD

**Issue by bradzacher** [microsoft/TypeScript-Website#380]
When loading up https://www.typescriptlang.org/play/ right now, I get 404's for all the resources, which obv means that it doesn't work.

Probably just a bad deployment, because everything but the JS looks like it's loaded fine. I can click around elsewhere and it looks like it loads fine.

![image](https://user-images.githubusercontent.com/7462525/76876050-9c66f980-682e-11ea-9e03-ab42514811e3.png)

**Comment by TimMensch** [comment]
#378 #379 have the same underlying issue.

**Comment by bradzacher** [comment]
Ahh sorry, I had the issue page open for 30 mins before I got around to raising this issue, so I didn't see those get logged.
I'll close this in favour of those.
