### ISSUE TITLE
Link to tsconfig broken

### ISSUE THREAD

**Issue by rowild** [microsoft/TypeScript-Website#382]
Here
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
at the end of  the article it says to read more at "TSConfig Reference", but the link provided leads into nowhere.

**Comment by B3zo0** [comment]
So in all places where the links are https://www.typescriptlang.org/tsconfig not working. This link does https://www.typescriptlang.org/en/tsconfig

**Comment by orta** [comment]
This issue only occurs in v1, when in v2 `/tsconfig` should be working fine, I'm thinking of deploying v2 permanently soon, so this issue will resolve itself.

**Comment by orta** [comment]
The link is fixed, and things have all settled now post launch
