### ISSUE TITLE
Webpack 4, 5 examples

### ISSUE THREAD

**Issue by rowild** [microsoft/TypeScript-Website#383]
Here
https://www.typescriptlang.org/docs/handbook/integrating-with-build-tools.html

only examples for Webpack 1 and 2 integration are offered. I would like to suggest that the Typescript documentation should provide examples for Webpack 4 and 5 (maybe 3?), too.

**Comment by orta** [comment]
We should probably only do the latest 2 semvers, this file need re-examination entirely - I've never heard of Duo

**Comment by rowild** [comment]
@orta what does the "You Can Do This" label mean?

**Comment by orta** [comment]
I'd definitely accept a PR which makes these changes

**Comment by rowild** [comment]
@orta you mean from me? Well... I am not into Typescript, so there will be nothing comming rom me, sorry!

**Comment by orta** [comment]
Nope, I mean that anyone can fix it 👍 (or it'll eventually make its way into my backlog)

**Comment by rowild** [comment]
Ah, understood! Thank you for explaining!!
