### ISSUE TITLE
Tooling in 5 minutes link is broken

### ISSUE THREAD

**Issue by disk-edit** [microsoft/TypeScript-Website#384]
https://www.typescriptlang.org/docs/handbook/typescript-tooling-in-5-minutes.html

The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Comment by orta** [comment]
This page only exists in the v2 site, and was only around during the betas, for now you can use 
https://www.typescriptlang.org/v2/docs/handbook/typescript-tooling-in-5-minutes.html
