### ISSUE TITLE
Please optimize the mobile web

### ISSUE THREAD

**Issue by KumaCool** [microsoft/TypeScript-Website#386]
It has been updated frequently for the new version of web.
I always read the documents by my mobile before bedtime.
But my mobile can't  adapt the new version very well. 
And there is non of option to link to the old version.
Hope to optimize it.

**Comment by orta** [comment]
The v2 mobile pages are very optimized for web: https://github.com/microsoft/TypeScript-Website/issues/130#issuecomment-560546774
