### ISSUE TITLE
`checkJs` not working in new playground

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript-Website#389]
Here's an [example](https://www.typescriptlang.org/v2/en/play?strictNullChecks=true&noUnusedLocals=true&noUnusedParameters=true&target=5&useJavaScript=true#code/PTAEAEBcGcFoGMAWBTeBrAUBgZgVwHbyQCWA9vqAIIDuy0pAtsgLLEAex+AFAEICG0ZKAC8oeABsB0UAG9QAXwCUsjKDWgATski4NFCVKq16TUMjaRk+ACbT+gleqeg+xxsi7KZq57-jl6cWQAOnFSAHMuAHJXOncoxR9feSSFDBScAiIyCgBhUlJxVg5ueyFRA2hpOSVHdS0dPTFJKtB8wrMLK1sjOKZizl4BZC9Up39CzzrfcYDCkLDImLcmBLH1FKcUjMrpZgBPXJbpc0sbaRo+lnZB0ac+Bj4AL05Iu5noXAAHZA1g2JMHkSM1Anx+fwm4imIFAAB5YAjEYjQABlRCkXDiaygABGQj4FF+GlIGlS2ywQUgoAYIlA+GQ1FAByOUk8GAY-xWQNAQA).

Hover over the `cool` in `super.cool()` and it shows up as `any`, despite both `checkJs` being turned on and `// @ts-check` comment placed at the top of the file.

I am expecting it to be a type error.

**Comment by orta** [comment]
Could be related to #49

**Comment by orta** [comment]
Fixed in https://github.com/microsoft/TypeScript-Website/commit/8782d0dbfd72f19d46deb5123533dd7f6b623329
