### ISSUE TITLE
The close button on the annoying banner

### ISSUE THREAD

**Issue by sportshead** [microsoft/TypeScript-Website#391]
Add a close button on the banner please

It's extremely annoying

**Comment by orta** [comment]
Can you provide a screenshot? "annoying banner" is kinda vague

**Comment by sportshead** [comment]
The banner that leads me to this issue page

**Comment by orta** [comment]
The v2 banner? No, I'm not removing that until, or giving folks the option to remove it it's ready to ship. I get enough bug reports from people thinking links from v2 should work in v1 for example, this sets expectations right.
