### ISSUE TITLE
Expired SSL cert for www.typescriptlang.org

### ISSUE THREAD

**Issue by rbingham** [microsoft/TypeScript-Website#392]
It looks like the SSL certificate for www.typescriptlang.org has expired.
![expired_cert](https://user-images.githubusercontent.com/7032804/77032298-a04b6680-6969-11ea-93c8-ee3521235635.png)

**Comment by sportshead** [comment]
Please fix this ASAP!

**Comment by orta** [comment]
I don't know how microsoft handles certs - but we did have it scheduled for renewal (and it's looking fine for me)

![Screen Shot 2020-03-19 at 10 22 59 AM](https://user-images.githubusercontent.com/49038/77077499-aeca6a00-69cb-11ea-9bec-83087c2ef094.png)

**Comment by orta** [comment]
I heard this might have also been fixed another way, so it _should_ be double fine also

**Comment by rbingham** [comment]
It looks like it's working for me now. Thanks for looking into orta

**Comment by DanielRosenwasser** [comment]
Sorry, I fixed this last night. My apologies there. As we move off of older processes that are hard to manage, I believe things will become more reliable.
