### ISSUE TITLE
V2 Suggestion: Faster access to Popular Documentation Pages and Playground

### ISSUE THREAD

**Issue by rdhelms** [microsoft/TypeScript-Website#395]
As a long-time TypeScript user, 99% of my use of the TypeScript website is in the following area:

![image](https://user-images.githubusercontent.com/7010586/77164019-bbab9400-6a85-11ea-8bfb-69f5a206ba79.png)

But now this is a pretty long scroll down from the documentation home page, and I didn't even notice it the first few times I opened V2 since those used to all be so accessible in the top left.

Could we at least have an anchor tag for that section? At least that way we could have a more helpful bookmark.

**Comment by orta** [comment]
I wonder if a better option would be to have some sort of tab at the top which keeps track in loncalstorage, then it could always be at the top

**Comment by rdhelms** [comment]
Honestly another confusion point for me was that I completely glossed over the "Start Learning" section and didn't even notice that there was a Handbook link at the top where "Samples" used to be, and I also didn't process that "Examples" meant a link to the playground. Now that I know that, I'll probably just use those two links instead.

But internally, I'll be ignoring the phrase "Start Learning" and the label of "Examples". In my mind, that top section is more like:
"Start Learning" -> "Resources"
"Examples" -> "Playground" (maybe some subtext about examples could be good, but really the main important thing to me about that link is that it takes you to the playground, and once you're in the playground there are pretty obvious links to access examples)

![image](https://user-images.githubusercontent.com/7010586/77177928-b86fd280-6a9c-11ea-8aff-9409db220d73.png)

**Comment by ethanresnick** [comment]
I would _love, love, love_ to have the playground linked in the main top nav again. I think that's helpful for veteran + new users alike.

**Comment by orta** [comment]
I opened #417 to think about the sub navs

**Comment by orta** [comment]
This came up again internally - I'm gonna try do some navigation changes to make this less of an issue specifically:

 - Make a better handbook index (which is not a dense text page) which is an index for the different sections 
-  Add both playground and handbook to the nav when the screen size is big enough to fit (so maybe > 800px wide)

Take some of the wording changes into account form this thread 👍

**Comment by orta** [comment]
Got quite far on this

![Screen Shot 2020-04-20 at 7 28 42 PM](https://user-images.githubusercontent.com/49038/79808923-37c32100-833d-11ea-9e1c-17018ec62193.png)

**Comment by orta** [comment]
I think I might get some value from having symbols with links  - https://adaptivecards.io has a set which I can re-use

**Comment by orta** [comment]
I'm happy with where this is today, it'll get better when I start splitting some of these pages even further but this is good enough
