### ISSUE TITLE
Syntax Highlighting Missing on JSX page.

### ISSUE THREAD

**Issue by bjnst6** [microsoft/TypeScript-Website#396]
It appears as if the syntax highlighting/color-coding on the V2 JSX page is missing for the last code snippet under the "Attribute type checking" heading.

![JSX page](https://user-images.githubusercontent.com/1914742/77186441-42be3380-6aa9-11ea-8edb-02e5cb0ad21a.png)

**Comment by Bibliofile** [comment]
Fixed by #424, can be closed.

**Comment by orta** [comment]
Thanks
