### ISSUE TITLE
Playground no longer allows CTRL+Enter to run code

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript-Website#400]
The V2 playground has apparently dropped support for using CTRL+Enter to run the compiled JS immediately, now requiring that I *gasp* use my mouse to click the run button.

Also reported in Discord but it appears the message was missed:

> **elderapo** - <small>03/14/2020</small>
also ctrl + enter doesn't work anymore for running code

**Comment by orta** [comment]
Odd, there's definitely code for this:

https://github.com/microsoft/TypeScript-website/blob/e6524ebda91b200840460a3caa65c5da4e980ab7/packages/playground/src/index.ts#L235-L244

**Comment by Gerrit0** [comment]
Thanks! 400 issues down!
