### ISSUE TITLE
Feature: Add support for changing the colour of code blocks

### ISSUE THREAD

**Issue by PaulBags** [microsoft/TypeScript-Website#401]
Hi, the new colour scheme is unreadable. White on grey just blurs into a big blob for me, can you at least bring in a toggle to the old style so I could continue my studies?

**Comment by orta** [comment]
I'm reasonably sure all pages pass all the a11y standards for colour definitions at 4:3 - could have missed something though, can you provide some screenshots?

**Comment by PaulBags** [comment]
![20200323_075107](https://user-images.githubusercontent.com/19583196/77257827-94e69b00-6cdb-11ea-96b0-8306195f971d.jpg)
Tried to take a picture of how bad it is, as you can see the camera compensated and completely washed out the code block instead. From my perspective trying to read it as a human it's all washed out - though not quite as bad as that code block.

**Comment by orta** [comment]
![Screen Shot 2020-03-22 at 4 15 32 PM](https://user-images.githubusercontent.com/49038/77259523-5e1b7100-6c58-11ea-9b08-c9d44eaf2bb5.png)

Interesting, so this page the code is completely white for you? https://typescript-v2-405.now.sh/docs/handbook/functions.html

**Comment by rmbaad** [comment]
Please don't force dark theme in the documentation site and add a switcher light/dark theme. I'm also having problems with reading docs. I have a dark theme in OS, but it's not mean I need forcing dark theme in all websites without the possibility to switch it.
Thank you

**Comment by orta** [comment]
I'm open to a light/dark switch in the footer 👍

**Comment by orta** [comment]
@joshwcomeau has a good overview of what it takes to move to a non-flashing switcher for light/dark mode. https://joshwcomeau.com/gatsby/dark-mode/

I'm also open to that same switcher being two binary toggles which let you select light/dark for the code theme too like the new handbook draft pages: https://microsoft.github.io/TypeScript-New-Handbook/everything/

**Comment by dandelionadia** [comment]
Please, can you tell me where is written this logic of theme in your code? I've failed in trying to find it.

**Comment by orta** [comment]
@dandelionadia  - it's all done in CSS today (look for `prefers-color-scheme` in the code base)

You'd need to follow through with https://joshwcomeau.com/gatsby/dark-mode/  which occasionally is pretty deep gatsby stuff, so if you get stuck make a a WIP branch and ask

- This means switching some of those CSS colour scheme detectors to use CSS variables
- For the switch itself, just throw together a blank button or something, I can do some design work on it over the weekend
- Ignore coloring code samples for now, that's a separate but linked issue, that will build on this work anyway

**Comment by orta** [comment]
OK, this is done now (thanks @dandelionadia for the base to work from) - there's a theme switcher, I'm going to use #342 to be about switching the code samples
