### ISSUE TITLE
Sidedar Suggestion

### ISSUE THREAD

**Issue by cheng-github** [microsoft/TypeScript-Website#402]
Hi, glad to see ts's website changed to v2.
But, in v1, there is no sidebar within the content in a chapter.
I recently is learning your doc, but the changes in v2 show sidebar in every chaprter.

**Comment by cheng-github** [comment]
I wish there is a possibility the user can choose if showing sidebar in every chapter. Thanks a lot.

**Comment by orta** [comment]
The sidebar will show/hide depending on the screen size - you're welcome to resize your browser to hide/show it.
