### ISSUE TITLE
/docs not working

### ISSUE THREAD

**Issue by Abrax20** [microsoft/TypeScript-Website#404]
Your Typescript Team,
The Google index is not updated, thats the reason why https://www.typescriptlang.org/docs/ is the default link, but it does not work because the new link is https://www.typescriptlang.org/docs/home. Please add a redirect https://www.typescriptlang.org/docs/  to https://www.typescriptlang.org/docs/home to redirect the people :)

**Comment by orta** [comment]
looks like a bug in the redirect code
