### ISSUE TITLE
The font-size is too small in mobile website even change the Scaling

### ISSUE THREAD

**Issue by qiujinyuan** [microsoft/TypeScript-Website#407]
![image](https://user-images.githubusercontent.com/28440197/77269902-45a56800-6ce5-11ea-8e8c-c05c8fc60486.png)

maybe the ```font-size:16px``` declaration in ```<html>``` is not a good idea.

**Comment by orta** [comment]
16px is definitely a good size for mobile, I don't plan on making it bigger. Though if there's an accessibility option we're not conforming to, I'm open to changing this.

The site also allows zooming, so if you're really struggling either turn your phone sideways or zoom
