### ISSUE TITLE
Playground samples don't provide log output

### ISSUE THREAD

**Issue by joej164** [microsoft/TypeScript-Website#408]
When I try and run any of the examples in the Playground, nothing shows up in the Log.

https://www.typescriptlang.org/en/play?target=1

The Hello World Javascript file when run, I get no output, in the errors I get "Cannot find name 'console'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'."

I didn't see any option in the TS Config tab to enable the DOM.

Not sure if this is because of the V2 testing or if it's something on my side.  I'm running this in Chrome Version 80.0.3987.149 (Official Build) (64-bit) on Mac High Sierra latest version.

**Comment by rikrak** [comment]
I have the same issue when compiling to ES5 using v3.8.3 of TS.  If I increase the version of either, then the problem goes away

**Comment by rikrak** [comment]
Just noticed that using @ts-ignore works however:
  class Hello{
    private _name:string;

    constructor(name: string){
      this._name = name;
    }
    public get name():string{ return this._name;}
  }

  var x = new Hello("Smith");
  
  //@ts-ignore
  console.log(x);

**Comment by orta** [comment]
Ah yeah, this issue was because the DOM APIs weren't in the playground before ~3.9 ish and they are in newer versions - so I'm closing. This is a side-effect of how we support multiple typescript versions.
