### ISSUE TITLE
Promise.all weirdness in nightlies

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#409]
The playground seems to have a lot of weirdness [...] with `Promise.all`. Things like signature help don't even seem to work correctly. I'm not sure exactly what the problem is, but if you do try that code out locally with a nightly version of TypeScript, it should all work fine.

_Originally posted by @DanielRosenwasser in https://github.com/microsoft/TypeScript/issues/33752#issuecomment-602416759_

**Comment by DanielRosenwasser** [comment]
The code that we were trying out had some issues:

```ts
(async () => {
    const [num1, num2] = await Promise.all([Promise.resolve(1), Promise.resolve(null)]);
    num1.toString();
})
```

it had different error messages than locally, and it had problems with triggering signature help. Very strange.

**Comment by DanielRosenwasser** [comment]
(maybe because of `lib.d.ts` ordering?)

**Comment by orta** [comment]
I think all the filenames for the lib.d.ts are hardcoded, is there a chance that 3.9 adds a new file?

**Comment by DanielRosenwasser** [comment]
I don't think so, but @rbuckton would have more context here.

**Comment by DanielRosenwasser** [comment]
I think that https://github.com/microsoft/TypeScript/pull/37510 fixes this.

**Comment by DanielRosenwasser** [comment]
Verified that it does! The problem is that TypeScript internally has a list for ordering the `.d.ts` files, but it differs from the `/// <reference lib="..." />` directives which I believe the playground crawls to concatenate/build.

Sorry for the confusion on this end.

**Comment by orta** [comment]
👍 thanks!
