### ISSUE TITLE
Playground doesn't work

### ISSUE THREAD

**Issue by Skolotsky** [microsoft/TypeScript-Website#411]
![image](https://user-images.githubusercontent.com/6927091/77302696-c6269180-6d02-11ea-928a-304278cb69e7.png)

**Comment by seedbre4d** [comment]
I can confirm this is happening to me also.

**Comment by orta** [comment]
What browser and URLs? The playground has been working fine on mine all weekend?

**Comment by Skolotsky** [comment]
chrome 80.0.3987.122 64-bit macOS, https://www.typescriptlang.org/play/

**Comment by orta** [comment]
Intersting, I've shipped a potential fix but I'm struggling to repro

**Comment by orta** [comment]
Going to assume this is fixed now

**Comment by tomtheisen** [comment]
It's back. 

![image](https://github.com/microsoft/TypeScript-Website/assets/2049910/ff85984f-83d2-4e56-ad59-c619fa570a9a)

Also, out of scope, but <kbd>ctrl</kbd>-arrow text navigation stopped working in firefox.
