### ISSUE TITLE
Support subnavs for quick links on desktop 

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#417]
**Improvement Idea:** Add a subnav to the main navigation items on the website

Some ideas:

Re-use the footer idea

![Screen Shot 2020-03-24 at 4 08 22 PM](https://user-images.githubusercontent.com/49038/77472057-bb92f780-6de9-11ea-9f77-de89765988a5.png)

Tighter, but with less context

![Screen Shot 2020-03-24 at 4 08 46 PM](https://user-images.githubusercontent.com/49038/77472074-c188d880-6de9-11ea-9b5e-06e17860d2c7.png)

Should be handle with care because people assume that they can't click on the subnav item which triggers the dropdown.

Constraints:

- It should probably appear for the first time after you've slowed to a stop, so not instant on the hover
- [It'd need something like this](https://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown) to make it easy to use fast

**Why:** Allow faster navigation throughout the site by extending the reach of the navigation

**Alternative ideas:** There's search, which could probably use a hotkey which could also help

**Comment by ai** [comment]
Current website has a lot of horizontal space (screenshot from 13" laptop)

![20200324202037](https://user-images.githubusercontent.com/19343/77488918-040fdc80-6e0d-11ea-9585-b2891176e0db.png)

Maybe moving the menu vertically will work better in this case? You will have more space to put more elements on menu top level for better discoverability?

Here is an example from [Logux](logux.io)
![20200324202129](https://user-images.githubusercontent.com/19343/77488977-2f92c700-6e0d-11ea-9dc7-cf45bcb6b28f.png)

**Comment by OfficialMarinho** [comment]
I loved! The idea seems like marketplaces.

**Comment by orta** [comment]
Thanks @ai - that's a really good idea and exactly the kind of fresh thinking I was hoping for. 

I'm not sure if we can pull it off (there's _a lot_ of sections and documents in the site) but I'll take a stab at making a design to see if it can fit

**Comment by orta** [comment]
This came back up as a potential route to avoid nested subnavs on the playground, still exploring it
