### ISSUE TITLE
Docs: [] playground > Primitives > Any

### ISSUE THREAD

**Issue by leeyunhome** [microsoft/TypeScript-Website#419]
https://www.typescriptlang.org/play/index.html?e=152#example/any

**Issue:** 
function 'debug' lacks return-type annotation like below

![image](https://user-images.githubusercontent.com/59910227/77598446-2f95e280-6f45-11ea-903d-d9d82ea57f36.png)

**Recommended Fix:** 
![image](https://user-images.githubusercontent.com/59910227/77598673-c5ca0880-6f45-11ea-9fc4-3af24a2bb26f.png)

**Browser:** 
Chrome 80.0.3987.149

**Comment by orta** [comment]
Thanks! This is fixed in the v2 site now 👍
