### ISSUE TITLE
Docs: [] broken link

### ISSUE THREAD

**Issue by leeyunhome** [microsoft/TypeScript-Website#420]
**Page URL:** 
https://www.typescriptlang.org/play/index.html?e=15#example/union-and-intersection-types

**Issue:** 
broken link  
![image](https://user-images.githubusercontent.com/59910227/77600556-a6ce7500-6f4b-11ea-8211-b39c3d2ed75a.png)

**Recommended Fix:** 
![image](https://user-images.githubusercontent.com/59910227/77600608-c796ca80-6f4b-11ea-9a76-ce1fc273ba50.png)
to 
![image](https://user-images.githubusercontent.com/59910227/77600711-0167d100-6f4c-11ea-9598-fb7b8059be30.png)

**Browser:** 
chrome

**Comment by orta** [comment]
Thanks! Looks like that was in a lot of places, I've fixed all the references in the v2 site
