### ISSUE TITLE
Write down that "import './b.js'" does read b.ts

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript-Website#422]
Moved from https://github.com/microsoft/TypeScript/issues/37547.

• Document that `import ./b.js` reads the file b.ts

I use nodejs 13.11.0 with {"type": "module"} in package.json: all .js files are handles as ES6 modules.

I create a file module b.ts:
```javascript
var m = [1,2,3];
export default m;
and also a.ts:
```
and
```javascript
import x from "./b";
console.log(x);
```
Now, the file TypeScript has actually to import is b.ts. If I write in a.ts import ./b.ts,then the resulting javascript will contain import ./b.ts which does not work and in fact tsc does not allow import ./b.ts.

If I keep import "./b", then the resulting code in JavaScript is import "./b";. This does not work (in Node and in the browser), since the filename to be imported is b.js and the extension has to be specified. See also nodejs/node#32442.

Then the last resort is to write in TypeScript import "./b.js";. This is not logical, as at the time this is read, the b.js file probably does not exist yet and TypeScript has to read b.ts. In fact, TypeScript does exactly this, when I run the process behing strace: On import './b.js'; tsc 3.8.3 reads b.ts.

But this does match the documentation:

At https://www.typescriptlang.org/docs/handbook/modules.html all sample imports do not use file extensions. except in the discouraged examle at https://www.typescriptlang.org/docs/handbook/modules.html#import-a-module-for-side-effects-only .

The final code must contain import "./b.js"; otherwise Node does not find the file.

At https://www.typescriptlang.org/docs/handbook/module-resolution.html it is not described what shall the TS-input contain so that both:
• the result is import "/.b.js"; and
• TypeScript handles the imported file as TypeScript file-module

**Comment by orta** [comment]
I'm not sure I want to document this until we have proper support for node's ESM modules - it's still experimental, and our only support is because the classic module resolution happens to work in a some cases but breaks in many many others.

**Comment by dilyanpalauzov** [comment]
How shall one work with modules/import under Node 13 and TypeScript now, after reading the documentation?  I personally wrote this after I struggled a while.  Yes, the classic module search performed by TS is not the one that is documented, see  https://github.com/microsoft/TypeScript-Website/issues/373, https://github.com/microsoft/TypeScript-Website/issues/371.

Having a team for deveopment and a team for documentation means that on discrepancies between the teams the implemented behaviour is not documented.

Please document the way the software works on `import ./b.js`: it reads b.ts.

**Comment by orta** [comment]
I'm on the compiler team... In my opinion, you should wait until it's not experimental and we have support for it.

That said, you're welcome to use the classic hack, but there's a whole lot of stuff necessary for us to support correct module resolution which still hasn't been decided by the modules working group - we're not going to be supporting it until decisions have been made and are finalized, it's the same thing we do with emcascript features.

**Comment by dilyanpalauzov** [comment]
In typescript `import ./b.ts` does not work, I have to use instead `import ./b.js`or `import ./b`.

But if I use babel’s preset-typescript to just cut the type hints from rollup, rollup cannot find b, unless I use `import ./b.ts`.

There are two kinds of ES6 modules:
* a directory module, where `import ./b` means to handle b as directory containing files, if b is a   directory, or
* a file module, where `import ./b` means to handle b as a file-module, if b is a file.

In particular `import ICAL as * from ical.js` does mean to use [ical.js as directory-module](https://github.com/mozilla-comm/ical.js/).

In my use case, `b.ts` exists and `b` does not exist, so I want to use `import ./b.ts`.

Please align the behaviour of typescript to the ES6-module behaviour, when it comes to imports:

* file extensions are ignored
* if X is a directory `import X as * from ./X` handles ./X as directory module
* if X is a file `import X as * from ./X` handles ./X as file module

For X = Y.ts
* if Y.ts is a file `import X as * from ./Y.ts` does not read Y.js

If X=Y.js is a directory
* `import X as * from Y.js` looks for the directory Y.js in node_modules/

**Comment by orta** [comment]
Hi - the website repo isn't really the right place for this discussion, there's already a lot of ongoing in the issues noted in https://github.com/microsoft/TypeScript/pull/35148
