### ISSUE TITLE
Error span squiggles are still off

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#428]
![image](https://user-images.githubusercontent.com/972891/77972620-c5fc3800-72a6-11ea-9f9e-4fe704b7e322.png)

**Comment by orta** [comment]
Ah, I bet this is because I don't force everyone to use the same monospace font (figure it was less important) but they can have different character widths.

Looks like everyone's gonna have to have the same monospace font

**Comment by orta** [comment]
I've given this a shot in https://github.com/microsoft/TypeScript-Website/commit/1baf0916ac5d6309a18baec155ca584b1260e60c

Can you try tomorrow once it's deployed please

**Comment by orta** [comment]
Confirming this didn't work on my windows box

**Comment by orta** [comment]
OK, I think what I'll do instead is have spans inside the code which indicate where to show the errors rather than lining up via pixel distances

**Comment by amcasey** [comment]
![image](https://user-images.githubusercontent.com/10508071/78056184-8a5e7e00-7339-11ea-9b3e-8808b1b79ffa.png)

**Comment by DanielRosenwasser** [comment]
Same issue - happens on my Windows and Android devices.

**Comment by orta** [comment]
Confirmed that this works on old Edge on windows

**Comment by orta** [comment]
Well, not #433 that old, but not edgium - which also is fine
