### ISSUE TITLE
Handbook CSS doesn't correctly collapse responsively anymore 

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#434]
**Improvement Idea:** Get back to the 3 tiers of the handbook cropping

https://twitter.com/orta/status/1236734674162069504

**Why:** It's a regression, maybe #431 might have triggered it

**Comment by tjamesmac** [comment]
Yeah sorry about that, I think removing `overflow: hidden` is what caused the layout to break. I can revert it and try again if that makes it any easier?

**Comment by orta** [comment]
It's no worries, I'll look at it! It could just be as simple as "overflow-x" or "overflow-y" instead
