### ISSUE TITLE
lib.d.ts doesn't include lib.iterator.d.ts probably?

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#44]
https://www.typescriptlang.org/play/?downlevelIteration=true&target=1#code/DYUwLgBA2gdHAeBdCBeCAidQ

**Comment by orta** [comment]
These come from https://github.com/microsoft/monaco-typescript/blob/master/src/lib/lib.ts and look hand-cded

**Comment by orta** [comment]
This is fine in the 3.7 playground - https://www.typescriptlang.org/play/?ts=3.7-Beta#code/DYUwLgBA2gdHAeBdCBeCAidQ
