### ISSUE TITLE
Playground: never loads (404)

### ISSUE THREAD

**Issue by connor4312** [microsoft/TypeScript-Website#445]
Opening the playground (in incognito/no caches) does not work

![image](https://user-images.githubusercontent.com/2230985/78409640-074e5980-75bf-11ea-86fd-1fb013c80590.png)

**Repro:** Try to open the playground

**Code**: N/A

**Expected behavior:** I can load it

**Actual behavior:** It doesn't load 😮

**Comment by willmtemple** [comment]
Same issue here in both Chromium and Firefox on Linux.

**Comment by maclockard** [comment]
same for FF 71 on MacOS

**Comment by orta** [comment]
Interesting - this doesn't seem to be happening to me
<img width="758" alt="Screen Shot 2020-04-03 at 7 41 12 PM" src="https://user-images.githubusercontent.com/49038/78412890-265ee280-75e3-11ea-8940-ba8d9d29d724.png">

**Comment by orta** [comment]
oh - this was the same issue as https://github.com/microsoft/TypeScript-Website/issues/446 (they had a `/v2/` prefix)

Closing as it's fixed 👍
