### ISSUE TITLE
Idea: Main links are broken

### ISSUE THREAD

**Issue by peter-hoa** [microsoft/TypeScript-Website#446]
The main links along the top of the website are all broken.

Where did the playground link go???

eg:

Arrive at the site, and see this:

<img width="944" alt="Image 2020-04-03 at 5 38 33 PM" src="https://user-images.githubusercontent.com/49166958/78410455-f9ee9a80-75d1-11ea-98fe-89f69ec3152f.png">

Click on the 'Documentation', 'Download', 'Community' or 'Tools' link, and I see similar to this:

<img width="824" alt="Image 2020-04-03 at 5 40 04 PM" src="https://user-images.githubusercontent.com/49166958/78410515-2f938380-75d2-11ea-9cf7-c34f15fd72f5.png">

Perhaps the site is still being deployed or something, but, right now, yeah, it's kinda broken.

**Comment by peter-hoa** [comment]
Ok, this problem seems to have been resolved.  It would still be good to have the playground link available directly at the top of the main site banner, with the other top-level links.

**Comment by orta** [comment]
Hi, sorry - I was updating #447 

RE: toolbar changes - there's https://github.com/microsoft/TypeScript-Website/issues/417
