### ISSUE TITLE
Docs: Several of broken links in contents menu when navigating through docs

### ISSUE THREAD

**Issue by adstr123** [microsoft/TypeScript-Website#447]
This issue is the same as issues #320, #379, #420 but those issues have been closed, in some cases with the implication that the issue was fixed. It is not, or perhaps has sufferred a regression.

**Issue:**
When navigating from one page to another using the menu on the left, many of the links result in the "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." message.

We will take the example of being on the [Declaration Files: By Example](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html) page, trying to move to the [Declaration Files: Introduction](https://www.typescriptlang.org/v2/docs/handbook/declaration-files/introduction.html) page (broken link on the Introduction URL as copies from the By Example page link).

**Recommended Fix:**
In all cases this is because the link points to the new URL structure:
`https://www.typescriptlang.org/v2/docs/handbook/declaration-files/introduction.html`

Replacing this URL with the old structure works fine:
`https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html`

**Browser:**
MacOS 10.15.3 Firefox Developer Edition 75.0b11

**Comment by orta** [comment]
Oh, I know this, I accidentally left the "run from this subfolder" command in the deploy - fixing now, should be deployed in ~5-10m

**Comment by orta** [comment]
Here's the build: https://github.com/microsoft/TypeScript-Website/actions/runs/70230067

**Comment by orta** [comment]
Alright - that's fully deployed and running on the site. Thanks for the issue!
