### ISSUE TITLE
Playground: Cursor position problem

### ISSUE THREAD

**Issue by bhuppal** [microsoft/TypeScript-Website#448]
Editor giving trouble to moving cursor to the end of the string. 

![BugPlaygroundIssue](https://user-images.githubusercontent.com/4120729/78414714-7346b700-75eb-11ea-94bf-bdda964d0c30.JPG)

**Repro:**

**Code**
// Welcome to the TypeScript Playground, this is a website
// which gives you a chance to write, share and learn TypeScript.

// You could think of it in three ways:
//
//  - A place to learn TypeScript in a place where nothing can break
//  - A place to experiment with TypeScript syntax, and share the URLs with others
//  - A sandbox to experiment with different compiler features of TypeScript

const anExampleVariable = "Hello World"
console.log(anExampleVariable)

// To learn more about the language, click above in "Examples" or "What's New".
// Otherwise, get started by removing these comments and the world is your playground.
export enum filterCategory {
    Campaigns = "Campaigns",
    Pipelines = "Pipelines",
    Clients = "Clients",
    Nonclients = "Non-clients",
}
public filterCategory
```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```
![Uploading BugPlaygroundIssue.JPG…]()

**Expected behavior:**
The cursor should able to move to "y" letter from the word "filterCategory"
**Actual behavior:**
Cursor stuck up after "o" and not able to move forward the cursor.

**Comment by orta** [comment]
Hrm, I can't reproduce this [with the code you offered](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgALSgAIKgBIwWaBjunt6EJORU6V7i1Qy1EthOoJzwsRnMJmag0k4M8cVllV21VpAAHkSUyJw0EvKaPi3+NIJ4mwzL-C6g9o6W2KAAqgBKADLC27FJsZBkgrMVly7SeDLOqgFZrCgbLY7UDcCjJZJfSCbExIAgUdxkUAIhiodhOYQpJq+VrUYIITiCGhmACiywYiGqkAAao4KAxpO5QABeUAAIgAEjBoBhwPAyNFeYpyYJ4O4AsLmAAKGl0hnuFmUdnuACUwRUOHqHjIXkQYucgPYNE+bjMzHYDGYkH4sGg6kS7PgehEXl5tPpjMEvKSmN54AcqAA5MIAHKQCS8oIqADynzI20ETq0kEOqEcClc0jwoCcpp0Iyw+hQCEQkOEF2tEjF0REBg4mK6LDYXG4QTBYpoSPYiCx6IUZAAwjjIMwxUWAN6KScMhgUZgU7l8pcEFdrwO8RS0KgwDL6De8w9EV2cfS8-fj11I1DCHm8+8UR97xTR+DmB+bZ98t+nAlC677-reigAL7BAQ7AcuoI7QGOk4KDOZB4MEQA)

On Chrome, Edge or Safari in macOS 

Any chance you can give me some more steps to repro?

**Comment by orta** [comment]
Nor on edge on windows

**Comment by bhuppal** [comment]
Its happening on Chrome, **Still I can reproduce with the version "80.0.3987.149"**. After updating the chrome, its not happening. I attached the code URL.

**Google Chrome
Version 80.0.3987.149 (Official Build) (64-bit)**

https://www.typescriptlang.org/play#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCoASMFmgY7p7ehCTkVOle4jUMdRLYTqCc8LEZzCZmoNJODPHFZZXVtZYYkAAeRJTInDQS8po+rf40gnjbDKv8LqD2jpbYoACqAEoAMsK7sUmxkGSCc+VVQQuaTwVb1UBrDYULY7PagbgUZLJH6QbYmJAECjuMigZEMVDsJzCFLNXxtajBBCcQQ0MwAUVWDEQNUgADVHBQGNJ3KAALygABEAAkYNAMOB4GRogLFFTBPB3AExcwABT0xnM9zsyhc9wASmCKhwDQ8ZC8iElzhB7Bo3zcZmY7AYzEg-Fg0HUiS58D0Ii8AoZTJZggFSRxAvADlQAHJhAA5SASAVBFQAeW+ZF2gldWkgx1QjgUrmkeFATgtOlGWH0KAQiBhwiudokkuiIgMHBx3RYbC43CCJUhkpoqPYiFxWIUZAAwvjIMxJaWAN6KWfMhgUZjUvmCtcEDdbkO8RS0KgwDL6HcC09ED2cfQC4-Tj2o1DCfkC58UV9HxRx+DmC+2zvoK-6cKU7rfsBj6KAAvooBDsNy6gTtAU6zgoC5kHgQA


**Entire source code:**
  export enum filterCategory {
Campaigns = "Campaigns",
Pipelines = "Pipelines",
Clients = "Clients",
Nonclients = "Non-clients",
}
public filterCategory

**Comment by bhuppal** [comment]
Please see the attached video capture.
Even after updating the Chrome browser, re-opened its not working as we expected.
[TypeScript_ Playground - An online editor for exploring TypeScript and JavaScript - Google Chrome 2020-04-04 11-42-35.zip](https://github.com/microsoft/TypeScript-Website/files/4431834/TypeScript_.Playground.-.An.online.editor.for.exploring.TypeScript.and.JavaScript.-.Google.Chrome.2020-04-04.11-42-35.zip)

**Comment by orta** [comment]
Hrm, I can't reproduce the bug on Windows with Chrome - #453 wondered if somehow the scrolling offsets ended up wrong but I'm not sure

**Comment by Bibliofile** [comment]
No error logs for me, the cursor should be at the end of the line here.

![image](https://user-images.githubusercontent.com/6462247/78458974-f19a6c00-7672-11ea-86b2-8cd5882452db.png)

**Comment by bhuppal** [comment]
![image](https://user-images.githubusercontent.com/4120729/78459492-519b0d80-7687-11ea-963f-58ed585149a7.png)

I see 2 errors in the log.

![image](https://user-images.githubusercontent.com/4120729/78459518-88712380-7687-11ea-9874-59dda33b7a93.png)

**Comment by orta** [comment]
OK, since the last release I changed the default font - I'll switch it back to the default

**Comment by bhuppal** [comment]
> OK, since the last release I changed the default font - I'll switch it back to the default

Thanks for your reply

**Comment by orta** [comment]
Deploying, might be about 30m - https://github.com/microsoft/TypeScript-Website/actions/runs/70858711

**Comment by bhuppal** [comment]
After the build, now its working without any issues. Great job Orta.

**Comment by bhuppal** [comment]
![image](https://user-images.githubusercontent.com/4120729/78464951-e1f44500-76bd-11ea-969a-2d5852a9b942.png)

After the build, its working fine.
