### ISSUE TITLE
Docs: type assertion example missing angle brackets "<type>"

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/TypeScript-Website#452]
**Page URL:** 

https://www.typescriptlang.org/docs/handbook/basic-types.html#type-assertions

**Issue:** 

```pre
let strLength: number = (someValue).length;
```

should ne

```pre
let strLength: number = (<string>someValue).length;
```

**Recommended Fix:** 

**Browser:**

**Comment by orta** [comment]
Looks like this is a twoslash bug - #405 should fix it

**Comment by orta** [comment]
Confirmed 405 - didn't fix it
