### ISSUE TITLE
Docs: [enhancement] with additional example for indexable types

### ISSUE THREAD

**Issue by rajinder-yadav** [microsoft/TypeScript-Website#454]
**Page URL:** 

https://www.typescriptlang.org/docs/handbook/interfaces.html#indexable-types

**Issue:** 

An additional example for indexable type would help more people.

**Recommended Fix:** 

## Indexing using string

```ts
interface NumberMap {
  [key: string]: number;
}

let myArray: NumberMap;
myArray = {"Bob": 12, "Fred": 45};

let val: number = myArray["Fred"];
console.log(val);  // -> 45
```

**Browser:**

**Comment by orta** [comment]
There's a whole doc on these now: https://www.typescriptlang.org/docs/handbook/2/indexed-access-types.html
