### ISSUE TITLE
Docs: TypeScript Quick Start Broken

### ISSUE THREAD

**Issue by SamJakob** [microsoft/TypeScript-Website#455]
**Page URL:** https://www.typescriptlang.org/docs/handbook/release-notes/overview

**Issue:** This is missing as a result of the documentation update.

**Recommended Fix:** Redirect to the relevant part of the new documentation.

This ranks #1 on Google for 'TypeScript setup'.

**Comment by orta** [comment]
Looks like we'll probably need to make a specific redirect to the `.html` https://www.typescriptlang.org/docs/handbook/release-notes/overview.html

**Comment by orta** [comment]
I sneaked a fix for this in https://github.com/microsoft/TypeScript-Website/pull/468/files#diff-e71f2c63a8b17b1b8bab2be20685d386R21
