### ISSUE TITLE
Docs: error coming from google search results page

### ISSUE THREAD

**Issue by altano** [microsoft/TypeScript-Website#460]
**Page URL:** https://www.typescriptlang.org/v2/en/tsconfig/

**Issue:** 
> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Browser:** Firefox

Was the second result on [this google search results page](https://www.google.com/search?client=firefox-b-1-d&q=typescript+typeacquisition)

**Comment by orta** [comment]
Ah yeah, not much I can do there - those URLs are temporary. Thanks for the issue!

For now - https://www.typescriptlang.org//tsconfig/

**Comment by altano** [comment]
I think you mean https://www.typescriptlang.org/tsconfig/ :)
