### ISSUE TITLE
Playground: Errors in console when using CTRL+A

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/TypeScript-Website#462]
The playground prints errors in the console when using CTRL+A after there are some statements in the program - [playground](https://www.typescriptlang.org/play?#code/OQVwzgpgBGAuBOBLAxrYBYAUMg9gOzigA8oBeKeCARxEUoAphgBKIA)

I spent a few minutes looking into this but wasn't able to find a quick fix. It looks like this might be coming out of Monaco?

![image](https://user-images.githubusercontent.com/19329837/78464436-ef520500-76a6-11ea-88d8-e35b3e4bb680.png)

**Code**

```ts
'use strict'
const x = require('')
```

**Expected behavior:**

No errors in console

**Actual behavior:**

Errors in console

**Comment by orta** [comment]
Yeah, this will be in Monaco-typescript - probably in the codex code

**Comment by orta** [comment]
( They don't have open issues, so this is a reasonable place to put it )

**Comment by orta** [comment]
This is fixed in the nightly builds, and will show up in the 4.0 release of ts' monaco
