### ISSUE TITLE
Playground: ERR Executed JavaScript Failed:  [ERR]: Unexpected token 'export' 

### ISSUE THREAD

**Issue by bhuppal** [microsoft/TypeScript-Website#463]
When I hit "Run" button, getting the "Executed Transpiled TypeScript" error appears on the screen.

![image](https://user-images.githubusercontent.com/4120729/78465028-a5751900-76be-11ea-8dfe-30ca45bafe11.png)

Please see the attached video in zip file
[TypeScript_ Playground - An online editor for exploring TypeScript and JavaScript - Google Chrome 2020-04-04 21-53-42.zip](https://github.com/microsoft/TypeScript-Website/files/4432826/TypeScript_.Playground.-.An.online.editor.for.exploring.TypeScript.and.JavaScript.-.Google.Chrome.2020-04-04.21-53-42.zip)

**Repro:**

**Code**
export enum filterCategory {
Campaigns = "Campaigns",
Pipelines = "Pipelines",
Clients = "Clients",
Nonclients = "Non-clients",
}

 const filterCategoryList = [filterCategory.Campaigns, filterCategory.Clients];

 console.log(filterCategory.Campaigns);

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Comment by orta** [comment]
Tricky - this is working as intended. We just `eval` the code, and your JS code includes `export` which can't be in eval'd JS code.

Maybe in the future there could be support for calling your script an ES Module - I dunno what the eval states look like for that though.
