### ISSUE TITLE
Docs: Missing image on page

### ISSUE THREAD

**Issue by RostislavDugin** [microsoft/TypeScript-Website#466]
**Page URL:** https://www.typescriptlang.org/docs/handbook/typescript-tooling-in-5-minutes.html

**Issue:** Visual Studio image in bottom of the page is not visible

**Recommended Fix:** the image on route https://www.typescriptlang.org/assets/images/docs/greet_person.png is not accessible. Check if the link is correct.

![image](https://user-images.githubusercontent.com/11681795/78500784-2e449100-7761-11ea-8663-a4f3d7afbc01.png)

**Comment by orta** [comment]
Thanks! fixed
