### ISSUE TITLE
Docs: Content overlined on TSConfig Reference page

### ISSUE THREAD

**Issue by Nicd** [microsoft/TypeScript-Website#470]
**Page URL:** https://www.typescriptlang.org/tsconfig#noStrictGenericChecks

**Issue:** Content after "no strict generic checks" is overlined. The overline starts in a code block and continues to the end of the page.

**Browser:** Firefox 74.0 on macOS.

![Screenshot 2020-04-06 at 10 27 47](https://user-images.githubusercontent.com/273137/78533272-609dcf00-77f1-11ea-8139-5a4062c18750.png)

EDIT: Content in the footer is also overlined:

![Screenshot 2020-04-06 at 10 30 09](https://user-images.githubusercontent.com/273137/78533429-a195e380-77f1-11ea-8137-f0fd59432ff5.png)

**Comment by Nicd** [comment]
It seems the generics in the code blocks are rendered as HTML in the output. `<S>` matches the strikethrough HTML tag and strikes through the rest of the page. The `<S>` is here: https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/noStrictGenericChecks.md

**Comment by orta** [comment]
Great catch! This got fixed by #405  - http://www.staging-typescript.org/en/tsconfig#noStrictGenericChecks

Will be deployed the next time we use the v2 site
