### ISSUE TITLE
Docs: A row in the Discriminating Unions example is barely visible

### ISSUE THREAD

**Issue by spaguette** [microsoft/TypeScript-Website#472]
**Page URL:** https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions

**Issue:** I can barely see the text in the first row of the table, where the shared "state" property of the union type is shown

**Recommended Fix:** Please apply the font color which is more contrast to the background of the row, for example, black.

**Browser:** Google Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**OS:** MacOS Catalina Version 10.15.4

![image](https://user-images.githubusercontent.com/9496522/78555235-e24f2600-780c-11ea-81a5-3a9c271b2d4e.png)

**Comment by orta** [comment]
ah, dark mode - my constant enemy
