### ISSUE TITLE
Docs: The type definition in the Generics section is missing

### ISSUE THREAD

**Issue by mitul45** [microsoft/TypeScript-Website#474]
**Page URL:** https://www.typescriptlang.org/v2/docs/handbook/typescript-in-5-minutes.html#generics

**Issue:**  The `backpack` should be initialized with `<string>` type.
```
declare const backpack: Backpack;
```

should be
```
declare const backpack: Backpack<string>;
```

**Recommended Fix:** Not sure what would fix it since the MD file already has the correct version: https://github.com/microsoft/TypeScript-Website/blob/v2/packages/handbook-v1/en/tutorials/TS%20for%20JS%20Programmers.md#generics.

**Browser:** I tried it in Firefox and Chrome and the behavior is same in both of them.

**Comment by orta** [comment]
This is semi-fixed on staging, but there's not been a deploy to production yet

**Comment by orta** [comment]
#473 was the fix

**Comment by orta** [comment]
The fix is deployed now - thanks
