### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by gonzus** [microsoft/TypeScript-Website#476]
**Page URL:** https://www.typescriptlang.org/v2/docs/handbook/typescript-from-scratch.html

**Issue:** Text says `Here’s the error TypeScript found` but there is no error displayed after the two lines of JS code.

**Recommended Fix:** Add proper error as reported by TypeScript.

**Browser:** Tried in Chrome (80.0.3987.162) and Firefox (74.0 (64-bit)). In fact, checked the repo file `packages/handbook-v1/en/tutorials/TS for the New Programmer.md` and it doesn't have the expected content.

**Comment by orta** [comment]
Thanks, fixed with https://github.com/microsoft/TypeScript-Website/commit/69e8baca17654903b8004275adf4223d9f15159e - will be in the next deploy

**Comment by gonzus** [comment]
Great, but shouldn't there be an actual error listed after line 63?

**Comment by orta** [comment]
Not in the markdown, the code sample will be emit an error from the compiler 

http://typescriptlang.org/v2/dev/twoslash
