### ISSUE TITLE
Idea: Change order of items in Handbook Navigation for better UX

### ISSUE THREAD

**Issue by taghikhavari** [microsoft/TypeScript-Website#484]
**Improvement Idea:**
Change the order of items in Handbook Navigation for modules and namespaces to a better conceptually order

**Why:**
Usually when developers want to read documents they starts from top to bottom and in "Module Resolution" and "Namespaces and Modules" sections we have some kind of dependency on "Modules" and "Namespaces" sections and right now we have to go back and forth because the order isn't conceptually right

**Alternative ideas:**

**Comment by orta** [comment]
PR was submitted 👍  thanks
