### ISSUE TITLE
JavaScript files in the playground don't show errors

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#49]
Honestly not sure what's up with that, did a dive into it earlier but haven't figured - maybe it's in Monaco typescript?

**Comment by orta** [comment]
This is fixed now in 3.7 builds

**Comment by dragomirtitian** [comment]
I think this should be reopened. There are no errors again in the [playground](https://www.typescriptlang.org/play/index.html?ssl=5&ssc=1&pln=1&pc=1&useJavaScript=true#code/PQKhAIAEBcE8AcCm4DeA7ArgWwEaIE4C+4IwAsAFAA2i04AztPgJZoDmA8vgEID2vNAIZpwAXnAAiCQG5KjFuy58BiYWPAAzQVXqJZFea049+QtADpovAKIAPeLzSI00ZtoAUASn1A):

**Comment by orta** [comment]
Looks like that is fixed in the 3.7.5 deploy I made for the v3, lets just switch the 3.7 to use that instead: https://www.typescriptlang.org/play/index.html?ts=3.7.5#code/PQKhAIAEBcE8AcCm4DeA7ArgWwEaIE4C+4IwAsAFAA2i04AztPgJZoDmA8vgEID2vNAIZpwAXnAAiCQG5KjFuy58BiYWPAAzQVXqJZFea049+QtADpovAKIAPeLzSI00ZtoAUASn1A

**Comment by dragomirtitian** [comment]
@orta  Are you sure? I still see no errors with your link, if I switch to JS that is (your sample is configured to TS, switching the version resets it to TS).

![image](https://user-images.githubusercontent.com/8193316/72847270-e60dea80-3caa-11ea-8a43-5fe9f5d916cc.png)

**Comment by orta** [comment]
hrmmmm, good point, I'm seeing the same on the beta too - let's re-open

**Comment by orta** [comment]
[For myself](https://www.typescriptlang.org/play/index.html?ts=3.8.0-dev.20200119&useJavaScript=true#code/PTAEAEBcGcFoGMAWBTeBrAsAKGyUAhAT1ABNkAzAQwFcAbSUAFUIAdkBleAJwEsWGSAe2TQAdgHIGLLoIBuPMqGRcZXUAFsR0SgHMeonbjD7oC5KABSlWZU69+AOlABJUdEjJKJUJBQ-BgrT6OqA80KDkgvDU0MjegqJGoNJyCsGgvEig0NQsLIJcDJFqcTyQBdAO2EmM1Fyi6QlKKhWgiIIA7siyygA0oeHSyJCQxJ7QhE6uoJRJoyw88JS0luwRPLTI-csrvpSQ4uFcyACO1DzH3uU+daKgTcxsdnyQScqqGlq6IgMzJCTpXzmSK0WiddLwQTqTSiSAALmqWE2DHUhHYkF4BlAAF5QAAiACMACYAMx4gDc2FR6MxIVxAG8AL6UnBYPCMRBhDSUYjuSiFfx-byUUBghiCcgZOLZM48HQ6TbhExmUCEQR1JIWNbkDbIJwAdU5m2ykA2Kw6BTQ6WViisNme-H6auobWsyCSIvIyA6-kC4WuOoAHj4ULFmqpKoi8AAxArZKHmCUh8wYxZW5Thir9DqcrLO0gJSQRZDIWhJSGKJCUAw-aDtOjeRCUPLIURO9WgJZ3GLmLUAESiM1EokEkH2PAS0Dmgh8pZWjw43BeoBz+2TPlYtfrtG8ACNkAjWcAAFTHiDzcz09y00AAH1ATMZoGPwGwyI0aNTBgA8lxv7uACtUAYXFCVJCkqU-Wlf3-ID4BAh9mSjMBDUWRBVQ7LspS8DQCkTO4UGOOElEDSh1BYTY4QA6AhHgWAcjyApXiPMAAE1MPVHdSFQWh+RTPwqA2OpzGoBpyKY6tIH6XdiA8UFghqTcHQYa45RHY511EZBAwYd4CkPN9hg-ZwdHUuIAFEWjUUDiTJFk8CgOA1LwyCaWCGDAOAnFEJZJJ2JdLCew3NhQlEL1jlEeBzHkEUgQiMEfSTCsUxndRKDQd02TAKsa39GdnTUO1bCXfhiO0siKIPZLYHIBKgA)

**Comment by orta** [comment]
Fixed again in https://github.com/microsoft/TypeScript-Website/commit/8782d0dbfd72f19d46deb5123533dd7f6b623329
