### ISSUE TITLE
Squiggles seem to add spaces

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#490]
![image](https://user-images.githubusercontent.com/972891/78946238-0c0b8580-7a77-11ea-9a33-629ea1ff8807.png)

![image](https://user-images.githubusercontent.com/972891/78946269-22b1dc80-7a77-11ea-84aa-7a74b2271b1e.png)

**Comment by orta** [comment]
This was on purpose, but if it feels like it's an accident I'd prefer it to not 👍

**Comment by orta** [comment]
I think you fixed this, but it's not there as of #495
