### ISSUE TITLE
Sample outlets shouldn't spill over as much (or at least, not at all on the right)

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#492]
![image](https://user-images.githubusercontent.com/972891/78947678-e41e2100-7a7a-11ea-9bc7-e522f435cfbe.png)

**Comment by orta** [comment]
Fixed in #495

**Comment by orta** [comment]
Definitely fixed in 02bc1eef8a681f3f2bb36af746464f85af26983f
