### ISSUE TITLE
Squiggle misalignment in docs

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#493]
![image](https://user-images.githubusercontent.com/972891/78951305-88f22b80-7a86-11ea-8a14-bbc85eb3848b.png)

https://testsite-typescript-41eeb979-7eaa-4c74-9d47-9d182c7b61ab.azurewebsites.net/docs/handbook/basic-types.html

**Comment by orta** [comment]
Fixed in #495 

Will need to test for the removal of the scrollbar though
