### ISSUE TITLE
Community page in website

### ISSUE THREAD

**Issue by remojansen** [microsoft/TypeScript-Website#5]
I would like to suggest to add a "community page". Something like the following:

![untitled](https://cloud.githubusercontent.com/assets/10656223/12351098/22120a06-bb73-11e5-8293-8d4f195f142e.png)

There are some communities out there already:

https://twitter.com/typescriptpdx
https://twitter.com/var_tsbr
https://twitter.com/DubTypeScript
https://twitter.com/TypeScriptFR

But I think it would be great to encourage it more :smile:

**Comment by orta** [comment]
Moved this over to the website repo, I'd like to have something like this and this is a good list to start with

**Comment by ondrej-merkun** [comment]
I can work on this.

**Comment by ondrej-merkun** [comment]
Wait, isn't this already kinda implemented?

![Screenshot 2019-10-26 at 00 20 50](https://user-images.githubusercontent.com/19146450/67607956-9771b280-f786-11e9-984c-48e748bc3ba8.png)
![Screenshot 2019-10-26 at 00 20 43](https://user-images.githubusercontent.com/19146450/67607960-993b7600-f786-11e9-998b-c9b1666d3d35.png)

**Comment by orta** [comment]
Hah, yeah, this is a 2016 issue - let's close this out
