### ISSUE TITLE
tsconfig reference page could use a little bit of intro

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#505]
I think that the tsconfig.json reference (https://www.typescriptlang.org/en/tsconfig) could give some background on what a `tsconfig.json` is, why it's useful for creating a reusable build environment, and why it's useful for editors.

Also briefly talking about `jsconfig.json` would be useful, and is important so that a search for `jsconfig.json` will bring them to either the VS/VS Code resources or the TypeScript site.

**Comment by orta** [comment]
#527  brings in a localized space for this

There's a balance on because we have an existing page on the tsconfig - http://www.staging-typescript.org/docs/handbook/tsconfig-json.html

Perhaps a subset of that could move here, and then be more forceful on sending people over in that handbook page
