### ISSUE TITLE
Module: twoslash integration with external types

### ISSUE THREAD

**Issue by pveyes** [microsoft/TypeScript-Website#513]
I'm trying to add twoslash to code examples for my blog, some of them has dependency to 3rd party modules. Here's an example:

````md

```ts twoslash
import React from 'react'

const Context = React.createContext('')
```
````

When passing the code through twoslash by calling `twoslasher(code, 'ts')` I got 

```
Expected:
// @errors: 2307

  [2307] - Cannot find module 'react'.
```

One thing that I've tried was using `fsMap` by including `@types/react/index.d.ts` in the `fsMap`

```ts
const fsMap = new Map<string, string>();
const reactDts = fs.readFileSync(require.resolve('@types/react/index.d.ts'), 'utf-8')
fsMap.set('react', reactDts)
const results = twoslasher(code, 'ts', undefined, undefined, undefined, fsMap)
```

I've confirmed that `reactDts` includes type definition of react. 

Additional context
 - `twoslash`: v0.3.0
 - `typescript`: v3.8.3
 - Not using gatsby or gatsby-remark-shiki-twoslash.

**Improvement Idea:**

When run in node environment, automatically include all `@types` from `node_modules`.

**Why:**

I think most people would assume that `twoslash` should behave similarly with `tsc` where it automatically includes external types from `node_modules`

**Alternative ideas:**

Provide a way to include list of `@types/*` dependency when running `twoslash`

---

It's possible that I implement this the wrong way, so any pointer is appreciated.

**Comment by orta** [comment]
This needs to be solved at gatsby-remark-shiki-twoslash level - twoslash shouldn't have side-effects like automatically acquiring types. I validated that twoslash would work fine if the types were in the map with this test

```ts
gatsby-remark-shiki-twoslashimport { twoslasher } from "../src/index"
import { createDefaultMapFromNodeModules } from "@typescript/vfs"

const dt = `
declare namespace G {
      function hasMagic(pattern: string, options?: IOptions): boolean;
}        
export = G;
`

it("works with a dependency in @types for the project", () => {
  const fsMap = createDefaultMapFromNodeModules({})
  fsMap.set("/node_modules/@types/glob/index.d.ts", dt)

  const file = `
import glob from "glob"
glob.hasMagic("OK")
//   ^?
  `
  const result = twoslasher(file, "ts", undefined, undefined, undefined, fsMap)
  expect(result.errors).toEqual([])
  expect(result.queries[0].text.includes("hasMagic")).toBeTruthy()
})
```

What I think needs to happen is that in gatsby-remark-shiki-twoslash - it looks to see if your module has "import" in the code - if it does, then it fills the fsMap with the project's `node_modules/@types/` dependencies. 

Ideally the types dependencies gets set as a singleton so we only do the fs work once, and then subsequent parses of code with imports don't get that hit

**Comment by orta** [comment]
I think `createDefaultMapFromNodeModules` should probably get renamed too - it _only_ get lib DTS files, and that name would definitely be confusing.

**Comment by pveyes** [comment]
Ok so turns out I did made a stupid mistake, I've tried using `@types/react/index.d.ts` in `fsMap`but I didn't add `/node_modules` prefix. It works now! Thank you so much!

Do you think we should update the README in either `ts-twoslasher` or `typescript-vfs` to add how to include dts from `@types/*` dependency? I can help creating a PR for this

**Comment by orta** [comment]
Hah, it happens!

I think it makes sense to have a note in ts-twoslash - and I also think there should probably be a function in `typescript-vfs` which sets up a map with the lib files and all the `@types` modules too
