### ISSUE TITLE
Playground: Property 'includes' does not exist on type 'number[]'

### ISSUE THREAD

**Issue by mfbx9da4** [microsoft/TypeScript-Website#519]
[Playground can be found here](https://www.typescriptlang.org/play/index.html?target=99&ssl=1&ssc=1&pln=3&pc=1#code/MYewdgzgLgBAhjAvDA2gRgDQwExYCz4C6AUHAHQCWYwANgK4AmAphABRoCUxQA)

    const a = [1, 2, 4, 4]
    a.includes(1)

I am using the latest settings in the playground with ESNext and typescript 3.8.3[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/pjBZT.png

[Also on stackoverflow](https://stackoverflow.com/questions/61234164/typescript-playground-property-includes-does-not-exist-on-type-number?noredirect=1#comment108337263_61234164)

**Comment by orta** [comment]
I thought that https://github.com/microsoft/monaco-typescript/pull/55 would fix it, but running on nightly didn't seem to include it - https://www.typescriptlang.org/play/?ts=3.9.0-dev.20200415#code/MYewdgzgLgBAhjAvDA2gXQFBA

**Comment by orta** [comment]
This is fixed in nightlies, and will be fixed in the 4.0 version of the playground this week
