### ISSUE TITLE
Playground: Port The Flow Graph to a playground plugin

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#520]
**Repro:** There is code in the compiler to print a text chart of the code flow analysis graph, we should make this easy to use (because I couldn't figure it out how to use it after reading the code)

**Code**: https://github.com/microsoft/TypeScript/blob/d68295e74e4897f588e73edf72089eb238904f02/src/debug/dbg.ts#L14

**Comment by orta** [comment]
Got quite far: https://github.com/orta/playground-code-show-flow

**Comment by orta** [comment]
This is in

**Comment by MartinJohns** [comment]
This doesn't work anymore, at least not for me (Chrome on Windows). The plugin shows nothing, and there's significant slowness when I enable it.
