### ISSUE TITLE
Playground:  Links in Examples and Whats New

### ISSUE THREAD

**Issue by gcrev93** [microsoft/TypeScript-Website#524]
I have to press a link (i.e. Hello World, Async Await) twice for it to open. The first time you click, it changes the url and the second time actually loads the example. 

Before the click
![image](https://user-images.githubusercontent.com/5778170/79615468-7e5c1580-80c8-11ea-85e6-9e4f1a4011aa.png)

After the first click
![image](https://user-images.githubusercontent.com/5778170/79615502-90d64f00-80c8-11ea-89d6-8305e7e2e2c4.png)

After the second click
![image](https://user-images.githubusercontent.com/5778170/79615515-9895f380-80c8-11ea-918e-4021269d5e9b.png)

**Repro:**

To repro, try clicking a link that falls under the Example or Whats New category of the TS Playground

**Comment by orta** [comment]
I believe I fixed this with https://github.com/microsoft/TypeScript-Website/commit/38936754a23b58652923111f507e4a15f944d51e
