### ISSUE TITLE
Spelling Mistake | TypeScruot > TypeScript

### ISSUE THREAD

**Issue by zraineri** [microsoft/TypeScript-Website#529]
**Url:** https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions
**Section:** Version selection with typesVersions
**Paragraph:** 4
**Error:** TypeScruot
**Valid:** TypeScript

**Comment by orta** [comment]
Thanks! This will be fixed on the next deploy
