### ISSUE TITLE
Issues with transitive dependencies and multiple files in ATA?

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#53]
In

```
import { parse } from "acorn";
```

`parse` has an `any` type, which is unexpected - probably because it's not resolving the `estree` dependency.

Similarly, if I write

```
import Vue from "vue";

new Vue({
  /**/
})
```

even with `esModuleInterop`, I get a lot of issues where I get no signature help.

**Comment by orta** [comment]
I chatted with @andrewbranch about this - could be because we're not generating `package.json`s in memory which might help the virtual FS work in the browser

**Comment by orta** [comment]
I tested adding package.jsons over the weekend, it did not fix this - boo

**Comment by orta** [comment]
There's been a lot of incremental improvements for ATA in the last few weeks, and these examples all work now:

![Screen Shot 2021-03-10 at 9 08 00 AM](https://user-images.githubusercontent.com/49038/110604548-1ef37200-8180-11eb-9594-af1a4a04f8c4.png)

![Screen Shot 2021-03-10 at 9 07 23 AM](https://user-images.githubusercontent.com/49038/110604471-08e5b180-8180-11eb-8b7e-ca1dd79491ce.png)
