### ISSUE TITLE
Idea: Docs as pdf

### ISSUE THREAD

**Issue by Spanoudakhs** [microsoft/TypeScript-Website#534]
Can you please add a downloadable pdf version of the docs in the site that is indexed and have links that are working ?

I really find it difficult to read through something successfully If I can not annotate on it .

**Comment by orta** [comment]
In the long term I was planning to generate an epub for the v2 handbook - I guess the same tooling might be able to make a pdf. It won't be every page though, I'd recommend building your own tooling for that sort of thing because not every site can be built statically.

**Comment by orta** [comment]
I found https://github.com/kcartlidge/nodepub which might be enough

**Comment by Spanoudakhs** [comment]
@orta I have created a puppeteer nodejs script that automates the creation of an indexed pdf out of documentation web sites like typescript .

**Comment by orta** [comment]
I built out an epub over the weekend: http://www.staging-typescript.org/docs/handbook/ - I just need to add a PDF export also 👍
