### ISSUE TITLE
Idea: Playground url shortener

### ISSUE THREAD

**Issue by JesusTheHun** [microsoft/TypeScript-Website#541]
Playground currently share url is a `base64` of the code, which is kinda ok I guess, but it gets really big really fast and it become un-shareable on platform such as discord.

Having a url shortener would be great to be able to share on platform such as discord.
To avoid most of the workload you can activate the shortener only if the url is longer than X or on user demand, or both. 

X<Discord> = 2000

**Comment by orta** [comment]
There's a playground plugin for this: https://github.com/gillchristian/tsplay.dev/tree/master/playground#typescript-playground-link-shortener
