### ISSUE TITLE
Module: (typescript-vfs) Dump all projects from path(tsconfig)

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript-Website#545]
**Improvement Idea:**
Provide a way to dump all files existed in disk into memory

**Why:**
If we'd like to use symbol or types with some project.

**Alternative ideas:**

**Comment by orta** [comment]
Like a helper function for adding an existing dir from the FS into the Map?

**Comment by Kingwl** [comment]
Yes, but also something to read and iterate the project folds.
Similar to https://github.com/HearTao/ts-upgrade/pull/25/files#diff-648bdf4caee0b054cf28245ac1c77cb1R72-R94 (I spend whole afternoon in this)

**Comment by DanielRosenwasser** [comment]
I think we don't have enough context for what you've been trying to do and how we could help. Could you elaborate a bit?
