### ISSUE TITLE
Docs: Advanced Types.md: definition of Fish had gone

### ISSUE THREAD

**Issue by wataash** [microsoft/TypeScript-Website#549]
**Page URL:** 

https://www.typescriptlang.org/docs/handbook/advanced-types.html

**Issue:** 

https://github.com/microsoft/TypeScript-Website/blob/a667a55ac1a0dbadc7ac0a54f02149b02046b5e5/packages/handbook-v1/en/Advanced%20Types.md#L11
refers to `Fish` wihtout definition, which had gone to `Unions and Intersections.md` in the following PR.

- https://github.com/microsoft/TypeScript-Website/pull/294
- https://github.com/microsoft/TypeScript-Website/commit/8eb359e83cfa#diff-a2c92f1db92017f034fd32ed99788828L157-L160

**Recommended Fix:** 

Let `Advanced Types.md` redisplay the definition of `Fish` or use a simpler type such like:

```ts
function isNumber(id: number | string): id is number {
  return (id as Fish).swim !== undefined;
}

// instead of using Fish:
// function isFish(pet: Fish | Bird): pet is Fish {
//   return (pet as Fish).swim !== undefined;
// }

isNumber(0); // true
isNumber('0'); // false
```
**Browser:**

**Comment by orta** [comment]
Agree

**Comment by orta** [comment]
This page is deprecated, and replaced in the handbook v2, but it looks like I never really addressed the point in advanced types though - bah
