### ISSUE TITLE
package.json disallows Node 14

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript-Website#554]
Update [package.json:"engines"](https://github.com/microsoft/TypeScript-Website/blob/v2/package.json#L7) to permit running under Node 14

**Comment by orta** [comment]
Sure, I'm open to it being node 13 and above. It's explicitly 13 right now.

**Comment by orta** [comment]
Sure, I'm open to this - I thought it was

**Comment by orta** [comment]
It now says greater than 13 👍
