### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by sably** [microsoft/TypeScript-Website#557]
**Page URL:** https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html

**Issue:** in last line says `jim.log`   not a function ?!

**Recommended Fix:** 

**Browser:**

**Comment by orta** [comment]
Yeah, we should probably drop that example completely - the mixins docs has many different examples and I only really trust the playground example: https://www.typescriptlang.org/play/?q=265#example/mixins
