### ISSUE TITLE
“rbrace” instead of “}” in error preview

### ISSUE THREAD

**Issue by acutmore** [microsoft/TypeScript-Website#558]
![0053FAB9-EAEB-40A3-A8E2-B78EB2CC8445](https://user-images.githubusercontent.com/4369552/81466718-aae8e600-91cb-11ea-9945-ea5018b23636.jpeg)

From homescreen, few carousel clicks in.

Mobile WebKit. Haven’t tested to see if also reproducible on desktop.

**Comment by orta** [comment]
Thanks!
