### ISSUE TITLE
Consider making landing page examples feel closer to a real editor

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#565]
I've been consistently asked "why don't the code samples look like a real editor?" and this is something I kind of agree with, especially since we've put so much work into highlighting the docs.

![image](https://user-images.githubusercontent.com/972891/81485033-2c0da080-91ff-11ea-99fd-5ad9a250a919.png)

I know the intent was to try to hint at what the differences are between JS and TS code (which is why the type declarations/annotations are colored differently) but I'm not sure if that's getting in the way seeing how TypeScript is concretely used. In fact, if you look at languages like Kotlin, Swift, and Scala, their landing pages all use either samples or images that are reminiscent of dark themed editors.

![image](https://user-images.githubusercontent.com/972891/81485045-4182ca80-91ff-11ea-8b32-3dc242ee6eec.png)

![image](https://user-images.githubusercontent.com/972891/81485051-52334080-91ff-11ea-8040-bb87cd45e6aa.png)

![image](https://user-images.githubusercontent.com/972891/81485060-637c4d00-91ff-11ea-817a-00ebfea06e20.png)

I think a subtle nod to VS Code on our site might not be too out of the question.

If we still want to call out the differences between TS and JS, one thing I could imagine is an actual highlighting/overlay/burnout on the interesting portions of the code. It's a little subtle in the following image, but not much more subtle than the current landing page snippets.

![image](https://user-images.githubusercontent.com/972891/81484906-45fab380-91fe-11ea-9812-016981dbd09a.png)

**Comment by orta** [comment]
I think if we switch to a more representational version of the editor then we'd probably have to drop the before/after metaphor and likely the 'these are the tokens added to JS' that it currently does. come up with something else completely - last time I tried this I couldn't get it fitting in the visual space on mobile.

Some rough ideas: 

### Keep some abstraction, but lean harder into VSCode-like

![Screen Shot 2020-05-11 at 10 17 11 AM](https://user-images.githubusercontent.com/49038/81571938-97c34b00-9370-11ea-9947-cd17e6ef2d6d.png)

- ditches the 2nd editor and uses that space to show 'filenames' as titles of sections
- re-use the errors panel to show the info 
- I'd probably have to find a new way to indicate 'next'

[(filled varient)](https://user-images.githubusercontent.com/49038/81572187-e670e500-9370-11ea-9e88-9987db565d18.png which looks closer to vscode)

### Go all in on VS Code

![Screen Shot 2020-05-11 at 10 17 36 AM](https://user-images.githubusercontent.com/49038/81571984-a7429400-9370-11ea-9a4d-164dc8d58b50.png)

- Switches to use interactive images with vscode as the code editor
- re-use the file explorer to highlight different examples
- [can add highlights to indicate things we want people to look at](https://user-images.githubusercontent.com/49038/81573265-3bf9c180-9372-11ea-9b17-e6c261a7b5c1.png)
- [could instead be a full bleed highlight](https://user-images.githubusercontent.com/49038/81573430-7c593f80-9372-11ea-86c2-54ed3239f8b3.png)

Obviously these aren't the only ways it could go but that's keeping the existing above the fold metaphors of:

- TS is JS with Types (so you might already know it)
- JS Tooling is powered by TS
- TS helps you scale codebases by giving errors where they didn't exist 

For example the Kotlin above the fold looks like: 

 - Kotlin is a modern OSS language
 - Kotlin can can be used for X
 - What has changed in Kotlin

We could switch out one/some of the current messages with "TypeScript helps you do X at scale" and X could be "electron apps", "massive websites" - there's a lot of potentials

**Comment by DanielRosenwasser** [comment]
I think that visually I prefer some variation of the filled look-alike or the screenshot. Functionally, I think it might be frustrating if I couldn't copy/paste or something though. I do t

Something I really like from what you've done is that you have a `try` button, which I think might really get a user to try out the playground.

> re-use the file explorer to highlight different examples

I like this idea now that it's been explained to me, but my first guess was that each of the un-selected files were some helper library code that I shouldn't be paying attention to. Maybe that's from the name `react-prop-types` which could maybe be named something else. Maybe an alternative is to use the tab list to give a stronger sense of left <-> right order.

**Comment by orta** [comment]
We paired on this yesterday: 
![Screen Shot 2020-05-22 at 7 43 25 AM](https://user-images.githubusercontent.com/49038/82664576-f9e93f00-9bff-11ea-9f86-0148fe726067.png)
