### ISSUE TITLE
Docs: typescriptlang.org/docs/home.html links to 3.5 release notes instead of 3.9 release notes

### ISSUE THREAD

**Issue by dilyanpalauzov** [microsoft/TypeScript-Website#579]
https://www.typescriptlang.org/docs/home.html says:

“ Familiar With TypeScript already?” → ‘’Release Notes 3.5 Release Notes“.  It shall state instead 3.9 Release notes and link to the 3.9 release notes.

**Comment by HolgerJeromin** [comment]
This link should be probably replaced with the generic: https://www.typescriptlang.org/docs/handbook/release-notes/overview.html

And all download links should be like this:
https://marketplace.visualstudio.com/search?term=TypeScriptTeam&target=VS&vsVersion=vs2019&sortBy=UpdatedDate

**Comment by orta** [comment]
Yeah, on the old website none of this is automated - I agree, we should just use those overview pages on the old site for now 👍

**Comment by dilyanpalauzov** [comment]
When will the old website, which happens to be also the current website, be replaced with the v2 website?

**Comment by orta** [comment]
As soon as it can, I'm unsure on the timeline
