### ISSUE TITLE
Docs: Search button does not open a search box

### ISSUE THREAD

**Issue by cellog** [microsoft/TypeScript-Website#583]
**Page URL:** 
https://www.typescriptlang.org/docs/handbook/type-inference.html

**Issue:** 
Click "Search" and nothing happens

**Recommended Fix:** 

**Browser:** 
Chrome 81

**Comment by cellog** [comment]
for more context: I just realized that when I clicked "Search Docs" that it was an input. The display did not change at all, the only indication that it is in fact a text input is the blinking cursor. I have dark mode enabled. The solution is to change something (anything) about the text input's appearance to indicate that it is possible to type

**Comment by orta** [comment]
Yeah, this must be an OS thing too - I get a big blue highlight around my text input, so didn't feel the need to add something extra. Will add some kind of active state highlight.
