### ISSUE TITLE
Docs: 'Try v2 Beta Page' link not hidden and not working on docs/home.html and mobile

### ISSUE THREAD

**Issue by markhaslam** [microsoft/TypeScript-Website#592]
**Page URL:** https://www.typescriptlang.org/docs/home.html (and any docs/* page?)

**Issue:** The "Try v2 Beta Page" button/link in the top right corner of the page doesn’t work.
On mobile the the link doesn't work on any page. It looks like it is intended to stay hidden on the docs/home.html page and hidden any time on mobile, but is now being set to always be displayed.

This is happening because of the following code starting on line 119 of the docs/home.html page on the production branch. It looks like the line setting the link to display block (the first one not in the if statement) is unintentional maybe. (I put a comment next to that line):

```html
<a id='try-beta' style="display:none;">Try v2 Beta Page</a>
        <script>
          const tryBeta = document.getElementById("try-beta")
          tryBeta.style.display = "block";  <!-- Unintentional? -->
          const mobile = window.outerWidth < 800
          const isHome = document.location.pathname === "/docs/home.html"
          if (!mobile && !isHome) {
            tryBeta.style.display = "block";

            tryBeta.onclick = () => {
              document.location  = "https://www.staging-typescript.org/" + document.location.pathname
            }
          }
        </script>
```

**Recommended Fix:** Removing that line in the script that is making the link  always display block could be removed and it should solve the problem. But is that is what is intended? Is there still a reason not to allow mobile to go to v2 docs? (I thought it was nice on mobile, great job on v2  🙌 ).

Slight side note as well. I noticed that [https://www.typescriptlang.org/v2/](https://www.typescriptlang.org/v2/) now works, is that where the link should point now instead of [https://www.staging-typescript.org/](https://www.staging-typescript.org/)?

I am happy to submit a PR for a fix if you let me know what is wanted 🙂.

**Browser:** Reproduced on multiple browsers

**Comment by orta** [comment]
I think I skipped the mobile link because I couldn't find a good space for it design wise! I'm open to having it in. The staging link is preferred because the `v2/` links will break when that site becomes production, but staging links will never break

But yeah, that looks like a bug for usre

**Comment by markhaslam** [comment]
That makes sense.

Then to fix the bug I think we just need to remove the line which is making the link always display: 
```javascript
tryBeta.style.display = "block";
```

**Comment by orta** [comment]
I've opted to instead add a design for mobile, and only hide on the home page

![Screen Shot 2020-05-19 at 1 39 34 PM](https://user-images.githubusercontent.com/49038/82359720-43eedc80-99d6-11ea-8082-3a8b9ee38883.png)

**Comment by markhaslam** [comment]
Awesome! I think that's a better solution, and it looks nice.

I do think there might be a bug still. It looks like with your fix it is still going to display that link on that home page, where the link does not work. I made a comment in your [commit](https://github.com/microsoft/TypeScript-Website/commit/6037d71ccc8aa99f4acd288622e0eaef0de4cc18).
