### ISSUE TITLE
Improve documentation for "module" and "moduleResolution" options

### ISSUE THREAD

**Issue by tangobravo** [microsoft/TypeScript-Website#594]
packages/tsconfig-reference/copy/en/options/module.md mentions "You very likely want CommonJS", without any further explanation.

I've got a webpack project that uses ts-loader, with typescript's target set to ES6. Removing the explicit module config (which was previously "CommonJS") defaulted it to ES6. I then had to explicitly add `"moduleResolution": "node"` to get it to build. The built bundle with these changes is about 25% smaller (I think because ES6 modules make tree-shaking in webpack easier?)

Looking for more info on whether this was a reasonable setup took me to https://www.typescriptlang.org/v2/en/tsconfig#moduleResolution where the status of that option is listed as deprecated. To me seeing the option described as "deprecated" also suggested that I maybe shouldn't be overriding the default (which becomes "classic" when module is "ES6").

I'm pretty new to the whole JS ecosystem (but a long-time dev in other languages) and this is all pretty confusing.

After more general reading around, I've found a couple of bugs that I think now clears things up for me:
https://github.com/microsoft/TypeScript/issues/11434
https://github.com/microsoft/TypeScript/issues/35876

Firstly I'd love confirmation that `"module": "ES6", "moduleResolution": "node"` is a reasonable choice in a webpack project (perhaps even the best choice when targeting ES6?).

Assuming I'd right, I'd recommend improving the description of the options around this - strongly recommending 'node' moduleResolution for all projects and removing the deprecated status flag (unless the default is updated to be node regardless of module setting), and perhaps expanding on the "You very likely want CommonJS" comment on the module option.

**Comment by orta** [comment]
Yeah, I agree - calling the option deprecated is just plain wrong here. I think it's worth looking over both module and moduleResolution again.

To my knowledge, `"module": "ES6", "moduleResolution": "node"` are reasonable choices, though it kinda depends on your `target` option I suppose.
