### ISSUE TITLE
Mapped types: MappedTypeModifiers not documented

### ISSUE THREAD

**Issue by beaucollins** [microsoft/TypeScript-Website#595]
The modifiers for ["Mapped types"](https://github.com/microsoft/TypeScript-Handbook/blob/master/pages/Advanced%20Types.md#mapped-types) are not fully documented.

[Introduced in v2.8-rc](https://github.com/microsoft/TypeScript/commit/a629acd8fd4844742fdd01ab6cf55afa9377db0e):
 - `IncludeReadonly` (`+readonly`)
 - `ExcludeReadonly` (`-readonly`)
 - `IncludeOptional` (`+?`)
 - `ExcludeOptional` (`-?`)

The Pull Request introducing them documents them well: https://github.com/Microsoft/TypeScript/pull/21919

> With this PR we provide the ability for a mapped type to either add or remove a particular modifier. Specifically, a `readonly` or `?` property modifier in a mapped type can now be prefixed with either `+` or `-` to indicate that the modifier should be added or removed.
>
> ```
> type Required<T> = { [P in keyof T]-?: T[P] };
> ```

**Comment by thw0rted** [comment]
Can we get a priority assigned for this?  As far as I've been able to tell, these aren't actually "not fully documented", they are 100% undocumented, unless you count the original PR as documentation.  The Include/Exclude Optional operators are particularly difficult to search for -- I saw one used in some example code without any explanation, had no idea what it did, no clue what to search for.  Most popular search engines aren't going to give you any results for the literal `-?`... then what?

These operators need a formal name, and they need to appear in the [Mapped Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types) section of the handbook.

**Comment by thw0rted** [comment]
I just discovered [the relevant section of the TS 2.8 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#improved-control-over-mapped-type-modifiers) so I guess some docs have been written, but they didn't make it into the relevant Handbook section yet.

**Comment by orta** [comment]
We'll be adding a Mapped Types page to the "Type Manipulation" section to the v2 docs, https://www.typescriptlang.org/docs/handbook/2/types-from-types.html - this should end up in there 👍🏻

**Comment by orta** [comment]
These are in the v2 docs 👍🏻
