### ISSUE TITLE
Name of font `JetBrains Mono` issue

### ISSUE THREAD

**Issue by abc1236762** [microsoft/TypeScript-Website#607]
**Improvement Idea:**

https://github.com/microsoft/TypeScript-Website/blob/a21551b6febd4f13f686a407c8695f027ae65add/packages/typescriptlang-org/src/style/globals.scss#L31
https://github.com/microsoft/TypeScript-Website/blob/a21551b6febd4f13f686a407c8695f027ae65add/packages/typescriptlang-org/src/templates/markdown-twoslash.scss#L48
https://github.com/microsoft/TypeScript-Website/blob/a21551b6febd4f13f686a407c8695f027ae65add/packages/typescriptlang-org/src/templates/markdown-twoslash.scss#L135
https://github.com/microsoft/TypeScript-Website/blob/a21551b6febd4f13f686a407c8695f027ae65add/packages/gatsby-remark-shiki-twoslash/README.md#L154

Each `Jet Brains Mono` should be changed to `JetBrains Mono`.

**Why:**

Since 
https://github.com/microsoft/TypeScript-Website/blob/a21551b6febd4f13f686a407c8695f027ae65add/packages/typescriptlang-org/src/components/layout/fonts.scss#L2
![圖片](https://user-images.githubusercontent.com/11353779/82833909-fe5c7300-9ef1-11ea-8911-ae58cb2b5fc2.png)

**Alternative ideas:**

**Comment by orta** [comment]
👍
