### ISSUE TITLE
Docs: The link of 3.9 release note is same of 3.8's

### ISSUE THREAD

**Issue by c7h12** [microsoft/TypeScript-Website#608]
![image](https://user-images.githubusercontent.com/705184/82884235-0d850480-9f76-11ea-9f9b-936d9239f65d.png)

![image](https://user-images.githubusercontent.com/705184/82883939-aff0b800-9f75-11ea-8a47-5ceed155661e.png)

**Page URL:** 

**Issue:** 

**Recommended Fix:** 

**Browser:**

**Comment by orta** [comment]
Fixed, thanks!
