### ISSUE TITLE
Playground: Emit target doesn't seem to work when language is JS

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-Website#614]
Try setting the language to ES5 with code like

```ts
function tag() { }

tag `hello

world`;
```

The output isn't downleveled.

https://www.typescriptlang.org/play?target=0&ts=4.0.0-dev.20200525&useJavaScript=true#code/GYVwdgxgLglg9mABFAhgcwBQEpEG9EC+AsAFCmpqIAGAFgKYA2DcppA7nAE4MAmVA3EA

**Comment by orta** [comment]
I wonder if this is transpiled at all - might just return the JS
