### ISSUE TITLE
Playground: Exceptions in console if when editor emptied

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/TypeScript-Website#615]
![image](https://user-images.githubusercontent.com/1312662/82950182-8a7fa080-9fad-11ea-9abb-53a72e6aa926.png)

**Repro:**

1. Open DevTools
1. <kbd>Ctrl</kbd>+<kbd>A</kbd> in playground editor area
1. <kbd>Delete</kbd>

**Code**

```ts
```

You actually need to make no code there 😄 

**Expected behavior:**
No error in console

**Actual behavior:**
Exception in console as soon as you remove last character from editor

**Comment by orta** [comment]
Fixed by https://github.com/microsoft/monaco-typescript/pull/62
