### ISSUE TITLE
Idea: Improve document layout

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#622]
The toplevel url is `docs/handbook`, but it's a bunch of things and only one of them is the handlbook proper (and if anything, it will be really confusing when people refer to it: "is it the handbook-*handbook* page or something else?").

It would be nice to leave just the handbook here, move the other documents into their own directories, and combine this "toplevel handbook" page with the content of `docs/home`.  (And I think that this toplevel handbook page is better, so I'd rather see the giant gray boxes become entries in more boxes on it.)

**Comment by orta** [comment]
It's a nice idea, but I'm not breaking backwards compatibility with the current website for URLs. 

This does leave us free to use a different URL structure for the v2 handbook though.

**Comment by elibarzilay** [comment]
(Right, this is of course for a later stage, plus a possible mapping to keep external links happy...)
