### ISSUE TITLE
Idea: Relative links

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#623]
Many places have absolute links, like `/docs/handbook/declaration-files/library-structures.html`, wouldn't it be much better to stick with relative links as much as possible, to make file moving easier?

**Comment by orta** [comment]
This has come up a few times, the old website didn't have a 1 to 1 match of file names to their web addresses and in keeping to their URLs we have to keep this constraint too. 

A new handbook wouldn't need that constraint.

**Comment by elibarzilay** [comment]
Are you talking about existing links?  If so, then maybe some server mapping of URLs?
