### ISSUE TITLE
Docs: emdashes in text

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#625]
There are many places where a single "-" dash is used instead of a "—".  It looks particularly horrible when rendered as pdf/epub text...

The same probably applies for quotes in text.

(This is a point that I raised before, on the handbook repo IIRC, and Ryan said something about pushing it to the renderer -- but it's still there and it looks like rendering will not change in a substantial way...  There might be an option though, even the simple commonmark implementation handles quotes and `---`s with the smart option.)

**Comment by orta** [comment]
that's probably a markdown renderer option somewhere, yeah
