### ISSUE TITLE
Docs: Improve section titles

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#626]
* "Quick Start" sounds more tempting than "Get Started" in an "I won't spend much time and I'll know enough" kind of way.

* "Handbook Reference" should be "Language Reference" or "TypeScript Reference", or just "Reference".

* "Tutorials" is a bit confusing -- I think that something like "Tool Tutorials" or "Tools and Tutorials" or similar would clarify it.

**Comment by orta** [comment]
Cool, yeah, a bunch of these make sense. A lot of it is carrying the existing handbooks current structure 👍 

This is the long-term goal for the overall sitemap: https://www.figma.com/file/Sew0DK1pRVPVXF6aAarfQHjk/Sitemap?node-id=0%3A1

**Comment by mtmulch** [comment]
I believe I can help with this. 

Can you please confirm this is the correct page?

https://www.typescriptlang.org/docs
