### ISSUE TITLE
Docs: Move "Migrating from JavaScript" to a new toplevel box?

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#627]
"Migrating from JavaScript" sounds like an important enough document (and different from the other entries in the tutorials section) to go into its own toplevel box, with links to the sections.

**Comment by orta** [comment]
Yep, that's a goal!

**Comment by orta** [comment]
This is in now, there's now a "JavaScript" section which is focused on JS users using TS tooling
