### ISSUE TITLE
Idea: Remove (or revise+trim) short descriptions on handbook page?

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#628]
I generally don't like the short descriptions below each box heading, since they don't contribute any useful information.  For example, "Get Started", plus the link texts makes it obvious that it's an overview for the listed starting points.  I think that with the other suggestion for improving the titles, most or all of these could go away.

**Comment by orta** [comment]
It started without the paragraphs, but looked too sparse without them and so I added them. I'd rather they not get removed.

The goal was to make it look similar to the overview pages on docs.microsoft.com - https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-3.1

**Comment by elibarzilay** [comment]
I think that here it is more problematic, maybe just trim them to look more like tag lines unless more is needed?  Specifically:

| Get an overview of TypeScript from different starting points depending on your background.

This is completely obvious+redundant.  Maybe "quick introductions based on your background or preference"?

| A start to finish overview of TypeScript, with the goals to get you productive for daily usage.

Maybe "A good first read for daily work in TS"?

| Deep dives into how TypeScript works in particular cases.

"Deep dive reference material"?

| Step by step tutorials how TypeScript works with different tools.

"Using TypeScript in several environments"?

| Learn how to write declaration files to describe existing JavaScript.

Maybe add "for DT enthusiasts" or some other DT reference?  (See separate issue somewhere.)

| Understand how TypeScript is configured.

"Compiler configuration reference"?

**Comment by orta** [comment]
Yeah, that totally makes sense 👍
