### ISSUE TITLE
Idea: Implement a `// ---continued---` thing

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#630]
I've seen how `// ---cut---` is used, but there's the obvious problem with it of repeating some code over and over, and repetition is a sin...  Another problem that this leads to is the bad way that some texts are written, where you have some main text to read

    function foo() {
      // and then you continue the text in a comment
      ...
    }

This not only looks bad and wrong ([badong](https://www.youtube.com/watch?v=O6_P_ZWwJ3Q)), it's probably an accessibility issue with readers that treat the code differently than the text...

So --- what if there was a `// ---continued---` which makes it connect the code chunks with the following, render the whole thing, and split the rendered results back into the text?  That would solve both problems easily, and will make it easier to have extended examples in many places.

**Comment by orta** [comment]
I'm not really a fan of this, but I'd accept a PR adding it to twoslash, and integration into the rendering pipeline. It was how Andrew built it for his blog.

IMO each code sample being completely sufficient means:

 - playground links can be guaranteed to work
 -  the rendering of each code sample is self sufficient in things like compiler flags 
 - the sample compiler doesn't need to know about the page's state and previous compiler results
 - that the order of how code samples come together doesn't matter

In exchange for some redundancy in code samples which only authors see

**Comment by elibarzilay** [comment]
This should not break the self-sufficient feature since each bunch of `continue`s are one block.  Another way to view it is that this:

    code();
    // ---continue---
    ```
    blah blah blah
    ```ts twoslash
    moreCode();

is almost a syntactic sugar for:

    code();

    // blah blah blah

    moreCode();

except that the verbiage in the middle is splitting the HTML presentation (but PG links would still show the whole thing).  So there's no state to maintain --- just compile the whole (concatenated) chunk of code and split the results.

The order does matter, of course, but if you really want to show how some code A compiles given some code B that is described later (which should be extremely rare), then you can still `---cut---`.  (That is, I'm *not* talking about some complicated literate programming thing.)

**Comment by elibarzilay** [comment]
Oh, and one more comment -- looks like there's already a possible small mistake in `TS for JS Programmers.md` because of it.  It has a bunch of occurrences of

```
interface User {
  name: string;
  id: number;
}
```

and I'm guessing that the intention was to hide all except for the first.

**Comment by orta** [comment]
I've been wondering about some sort of helper syntax which allows for directly importing a subset of a file:

````
```ts twoslash-prefix
type A = {}
// ---a---
type B = {}
// ---b---
type C = {}
// ---c---
```
This file above would not be rendered by the renderer. This would be a normal <p>

```ts twoslash
// ---prefix-a--- ( only A)
const a:A = {}
```

Then you can ....

```ts twoslash
// ---prefix-c--- ( A / B / C available)
const a: A = {}
const b :B = {}
const c :C = {}
```

````

**Comment by elibarzilay** [comment]
The reason I suggested a "continued" thing rather than some games like this one is that it makes writing texts very natural: there are *many* cases where some text describes some feature by adding more code on top of existing code.  This, IME, is by far the most common case of writing such documentations.

What you're suggesting sounds more difficult to remember, and it would make editing more difficult too because often you'll want to edit the hidden prefix, forcing you to jump up and down in the source.

All of that, and it still doesn't support the "continued" style of editing since (IIUC) to do so you'll need to enter the whole interaction first, then repeat parts of it while including the hidden prefix to make each snippet work.  (And if this is indeed true, then it's a disaster, since I might have edited the visible B part but forgot to update it in the hidden copy.)
