### ISSUE TITLE
Docs: packages/handbook-v1/en/declaration files/Introduction.md -- DT mention

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#633]
`packages/handbook-v1/en/declaration files/Introduction.md`, top:

If this is text is geared towards DT publishers, it should be clear in the beginning of the text --- or at least mentioned as common reason to read it.

**Comment by orta** [comment]
Agree, the introduction now has an opening paragraph to send those folks off to a different page
