### ISSUE TITLE
Docs: packages/handbook-v1/en/declaration files/Introduction.md -- redundant section?

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#634]
`packages/handbook-v1/en/declaration files/Introduction.md`, `# Sections`:

This section is redundant...

(Insert some cleverness about how this issue is written in letters...)

**Comment by orta** [comment]
I think this is covered in https://github.com/microsoft/TypeScript-Website/pull/543 - just need to find some time to come back to it

**Comment by elibarzilay** [comment]
I looked and it's still there, and GH won't let me add a comment on a line that is not in the change, so leaving it open as a reminder.  (If you prefer I'll do a quick PR instead.)

**Comment by orta** [comment]
I think this is fixed, at least I don't see a `Sections`  section in that doc anymore :D
