### ISSUE TITLE
Docs: packages/handbook-v1/en/declaration files/Introduction.md -- subsection links

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#635]
`packages/handbook-v1/en/declaration files/Introduction.md`, starting at `## Library Structures`:

In the following, the sections are introduced with a short blurb, and you have to search for the link in that blurb.  Would be better to use something like a description-list, where each header is a link to the document, and change the text to drop the name of the section.  For example:

    * [Library Structure](...):

      Helps you ...

    * [By Example](...):

      Many times ... guide us. Here you will see many common ...

    etc

Or by making the headers links (which should work with most md renderers.)

**Comment by orta** [comment]
Thanks, yeah, I think the re-write of the DT sections makes this less of an issue, in part because each section isn't a one-to-one direct map to a template anymore but gives you a more general sense and links to the different templates at the end
