### ISSUE TITLE
Docs: packages/handbook-v1/en/tutorials/DOM Manipulation.md -- link URLs

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#636]
`packages/handbook-v1/en/tutorials/DOM Manipulation.md`, bottom:

Why is this showing the URL text instead of making it just a link?
(And if it's intended, then md has the `<https://...>` syntax.)

**Comment by orta** [comment]
yeah, makes sense to have them as as inline links

I'd like to get around to building a related section #482 for these
