### ISSUE TITLE
Docs: packages/typescriptlang-org/src/lib/handbookNavigation.ts -- too many items in "Declaration Files"

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#637]
`packages/typescriptlang-org/src/lib/handbookNavigation.ts`: several `title: "Template: ..."` entries.

There are several `Template: ...` entries in this, which makes the "Declaration Files" too long.  Better to drop them, since there is already an existing link to a page that lists them.  (This would also make it more difficult to miss the links after all of the templates).

**Comment by orta** [comment]
long term the goal is to support third level disclosure navigation so these would live in a section called templates 👍 , for now though I'd rather it that section be too long than they be really hard to find though

**Comment by elibarzilay** [comment]
In that case they should move so they're below the Templates link, no?

**Comment by orta** [comment]
Maybe, that files a bit anemic (And ideally could be padded out) - I put them here because they are all referenced in http://www.staging-typescript.org/docs/handbook/declaration-files/library-structures.html though

**Comment by orta** [comment]
There's work on improving them in https://github.com/microsoft/TypeScript-Website/pull/543

**Comment by orta** [comment]
That's now fixed in the nav because the site supports sub-navs
