### ISSUE TITLE
Docs: packages/typescriptlang-org/src/lib/handbookNavigation.ts -- order of entries in "Project Configuration"

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#638]
`packages/typescriptlang-org/src/lib/handbookNavigation.ts`: `title: "TSConfig Reference"`

The tsconfig reference section should come after the `tsconfig.json` page since that one is an introduction.

Also, since we're in the tsconfig manual, a title of just "Reference" might be better.

**Comment by orta** [comment]
Agree on the order! Fix coming in a PR today. 

WRT to the title, I think I still prefer it for consistency with the 'JSDoc Reference' and that I call it the TSConfig reference everywhere else in the site.
