### ISSUE TITLE
Docs: packages/typescriptlang-org/src/lib/handbookNavigation.ts -- "Nightly builds" title

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#640]
`packages/typescriptlang-org/src/lib/handbookNavigation.ts`:
`{ id: "nightly-builds", title: "Nightly Builds" }`

This entry is unrelated to tsconfig, so it would be better if moved to the a different section -- maybe "Tutorials" (since it's talking about using the nightly in different tools, and assuming that its title changes), or maybe move to the toplevel `docs/home` page?

**Comment by orta** [comment]
Yeah agere, I'd like some kind of performance or debugging section with this in, but it came from the old site and I don't want to break URLs 👍

**Comment by orta** [comment]
I think in the long-term I want a "Scaling TypeScript" section, where this can live, for now it's just a werid outlier in all categories which I can't really get rid of
