### ISSUE TITLE
Docs: packages/typescriptlang-org/src/templates/pages/docs/handbook/index.tsx -- toplevel title

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#641]
`packages/typescriptlang-org/src/templates/pages/docs/handbook/index.tsx`, `<h1>` header

* This is the title for the toplevel page, and given that the actual handbook is just one part of it, the title should be something like "TypeScript Documentation" otherwise people won't know what "handbook means"...

* The following "The handbook will help you learn" paragraph is also redundant (like the short summeries in the boxes).

* Since the epub/pdf is a rendering of the handbook part, the links to them is better placed in the handbook box.  This would also be needed to have similar "paper" renderings of other parts.

**Comment by orta** [comment]
I shifted around a bunch of the navigational structures this weekend, which takes all of these into account - thanks!
