### ISSUE TITLE
Docs: packages/handbook-v1/en/tutorials/TS for JS Programmers.md --- ^? comments?

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#643]
`packages/handbook-v1/en/tutorials/TS for JS Programmers.md`

I'm not sure what the purpose of the two `^?` comments, but something is wrong with them as can be seen [on the rendering](http://www.staging-typescript.org/docs/handbook/typescript-in-5-minutes.html):

* There are two of these comments in the file, but the first one doesn't render anything.  (So this is probably some bug.)

* Looking at the second one I'm guessing that the intention is to show the type of what the `^` points to.  But it shows the type incorrectly as `string` -- what it points to (in the condition) is still a union, as the hover text shows.

Maybe both are a simple off-by-one error of referencing the following line instead of the previous one, making the first disappear and the second one wrong?  It would also explain the indentation in this case:
![image](https://user-images.githubusercontent.com/185905/83206620-41e7f480-a11f-11ea-9f76-a0bfb8554ac9.png)

Another minor thing: this second `^?` has the `//` at the beginning instead of indented, which breaks the visual flow.

**Comment by orta** [comment]
looks like a twoslash bug to me

**Comment by orta** [comment]
This twoslash bug got fixed, thanks
