### ISSUE TITLE
Idea: Avoid the clever ligature

### ISSUE THREAD

**Issue by elibarzilay** [microsoft/TypeScript-Website#644]
Looks like there's something that does the clever font ligature thing to show some text differently.  I think that it's not a good idea here.  *Especially* on newbie oriented pages, since it's just waiting for someone to scratch their head looking for the `≤` or `≡` key.

To make it worse, some of these look bad: `≤` has huge spaces around it, and `===` becomes an extra long `≡` with uneven lines:
![image](https://user-images.githubusercontent.com/185905/83206620-41e7f480-a11f-11ea-9f76-a0bfb8554ac9.png)

(And yes, I see that the actual text is still proper, but it's confusing to read.)

**Comment by orta** [comment]
Yeah, that' a good call

**Comment by orta** [comment]
Cascadia is probably too dark for me to be happy with it long term, but I've given it a shot in #680

**Comment by elibarzilay** [comment]
I generally *prefer* heavier fonts, makes it much easier to read code quickly; I've been a Consolas fan since it came out...

(And BTW, I still see the older ligature thing on the site...)
(BTW#2, I see that there's a lot of `style="color: #..."` -- wouldn't it be better to use a stylesheet for that?)

**Comment by orta** [comment]
Weird, I'm not? Maybe you had the old version cached - I'm explicitly asking for the version without in the CSS?

![Screen Shot 2020-06-16 at 1 09 38 PM](https://user-images.githubusercontent.com/49038/84805690-a84f8c80-afd2-11ea-8949-bfdb84f1b7b3.png)
[src](https://www.staging-typescript.org/docs/handbook/unions-and-intersections.html#union-types)

Re: 2, that's still in the air for WRT https://github.com/octref/shiki/issues/33

**Comment by kaznovac** [comment]
I personally find ligatures mentally tiresome to read, I would prefer an option to disable them.

I'd guess for newcomer to the language or to programming practice in general might be confusing to read symbols that are not available on keyboard; and might be interpreted that TS language operates on ligatures and they are part of the syntax.

**Comment by orta** [comment]
The new site shouldn't have had ligatures for the last two weeks:

![image](https://user-images.githubusercontent.com/49038/86017305-dfba3200-b9f1-11ea-9d14-ccebf3090f8b.png)

Going to close, open to people showing repos

**Comment by DHowett** [comment]
@orta Hey, we recent released an update to Cascadia that offers a variable weight axis if you'd like to lighten the weight on the handbook at all. I found this issue because I noticed y'all using it in the wild, and I just wanted to say thanks! :smile:

**Comment by sceutre** [comment]
fwiw I see the ligatures on the new site.  I'm on Windows 10 using Microsoft Edge Version 84.0.522.52 (Official build) (64-bit).  I tried clearing my cache to no avail.  I do have Microsoft Terminal preview installed and it has installed a Cascadia Mono locally if that makes any difference. 

![Annotation 2020-08-05 173308](https://user-images.githubusercontent.com/1341832/89477382-f87cdc80-d741-11ea-956f-f809b73bbeb5.png)
![Annotation 2020-08-05 173359](https://user-images.githubusercontent.com/1341832/89477385-fc106380-d741-11ea-84dd-5dde7cb6443e.png)

**Comment by orta** [comment]
Thanks both - I switched to the lighter font (SemiLight, it felt just right @DHowett) but it looks like I must have included the version with ligatures - I'll switch it over tomorrow. Thanks for the report @sceutre
