### ISSUE TITLE
Docs: Link to the PDF of the handbook is broken

### ISSUE THREAD

**Issue by JohnFarrellGit** [microsoft/TypeScript-Website#656]
**Page URL:** https://www.typescriptlang.org/docs/handbook/

**Issue:** The pdf link goes to: https://www.typescriptlang.org/assets/typescript-handbook-beta.pdf
Displayed in the browser is: The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Recommended Fix:** I noticed this [commit ](https://github.com/microsoft/TypeScript-Website/commit/3e37a1846f7cd65cda6bc8f4cbc438854776114d) added the PDF to the .gitIgnore, I imagine that is related(?)

**Browser:** Chrome version 83.0.4103.61

**Comment by orta** [comment]
Interesting! Looks like it's a part of the production build process - for now http://www.staging-typescript.org/assets/typescript-handbook-beta.pdf works!

**Comment by orta** [comment]
This should be fixed next time it's deployed (Saturday)
