### ISSUE TITLE
Docs: VS Code plugin link

### ISSUE THREAD

**Issue by camelid** [microsoft/TypeScript-Website#659]
**Page URL:** 
https://www.typescriptlang.org/#download-links

**Issue:** 
The TypeScript plugin link for VS Code just links to the VS Code website, not the plugin, whereas the links for other editors do link to the plugin.

**Recommended Fix:** 
Link directly to the plugin.

**Browser:** 
Firefox

**Comment by orta** [comment]
VS Code doesn't have a plugin, it's built in - all the others need a plugin 👍

**Comment by camelid** [comment]
Okay, good to know :)
