### ISSUE TITLE
Docs: Create React App: react-scripts-ts is deprecated 

### ISSUE THREAD

**Issue by bdirgo** [microsoft/TypeScript-Website#668]
**Page URL:** 
https://www.typescriptlang.org/docs/handbook/react.html#create-our-new-project

**Issue:** 
The first step of running `create-react-app` with the react-scripts-ts option gives a depreciation warning. 

```
create-react-app my-app --scripts-version=react-scripts-ts
```

```
The react-scripts-ts package is deprecated. TypeScript is now supported native
ly in Create React App. You can use the --template typescript option instead whe
n generating your app to include TypeScript support. Would you like to continue 
using react-scripts-ts?
```
**Recommended Fix:** 
The output from the recommended template in the warning is not quite the same output as the react-script-ts. Maybe add a note about the script being depreciated? Maybe support the new recommended template in the tutorial?

**Browser:** 
Running in the terminal on macOS

**Comment by orta** [comment]
We'll probably move this out of the TypeScript docs in some form I think, there are better resources with more incentives to stay up to date for TS + React

**Comment by orta** [comment]
Fixed in https://github.com/microsoft/TypeScript-Website/pull/774
