### ISSUE TITLE
Playground "helpfully" removes `declare` keyword on reformatting

### ISSUE THREAD

**Issue by jcalz** [microsoft/TypeScript-Website#67]
For some reason the Playground likes to "reformat" away the `declare` keyword on variable and class declarations.  I'm sure it does this for a reason, but it causes issues with formerly ambient variables becoming "used before being assigned".  And there's no "undo reformat" so someone has to manually re-add `declare` back in where needed.

Example:
```ts
// BORING OLD STAY-WHERE-YOU-PUT-THEM DECLARATIONS //
declare function declaredFunction(): void;
declare namespace DeclaredNameSpace {}

// 🎩✨🐇 MAGICALLY DISAPPEARING DECLARATIONS 🐇✨🎩
declare const declaredConst: string;
declare var declaredVar: string;
declare let declaredLet: string;
declare class DeclaredClass { prop: string; }
declare enum DeclaredEnum {}

// EXTRA FUN... MAGICALLY CHANGED MODULE! //
module Foo {}
```
[Playground link](http://www.typescriptlang.org/play//#code/PTAECEHkCUEkDkDipIBkAioDKAVAggJoC0A6gBICi0FRBkAqkQAr05E6UCyo6FAwqjzQ8OWJHhZQIAFAATAKYBjADYBDAE7zQAMwCuAO0UAXAJYB7faAUqN82QDEDx8-oAUASgBcoAG5mTsgDcckpqmqD6qgC28gDOAA6qilroobay8NHyWInJoADeAL7S0iCggDwbgJX7gBTkgLwbgOA7oJx4iLB8eKioBDywWHhMTBRCCMi8AkIiYhKgDdVVITbhihaxRlZpmrJ8K0beq+om+gDmwdZhWj4a64t2AGoae0YHx6cbWsrya2fpqJ+PzycFudQDZYrEeG8tmowQVQPF1GZ4v9DidQMVvuF5PpdFEITdZBRsbiiiUyhQABo4YSgez0eAAOkZTRabQ6XVAfDIeCQFEwnEg6HoqAoAEIpMBpFEzLJdB8aWYzAVikA)

[ᴀʟᴛ]-[ꜱʜɪꜰᴛ]-[ꜰ]

```ts
// BORING OLD STAY-WHERE-YOU-PUT-THEM DECLARATIONS //
declare function declaredFunction(): void;
declare namespace DeclaredNameSpace {

}

// 🎩✨🐇 MAGICALLY DISAPPEARING DECLARATIONS 🐇✨🎩
const declaredConst: string;
var declaredVar: string;
let declaredLet: string;
class DeclaredClass {
  prop: string;
}
enum DeclaredEnum {}

// EXTRA FUN... MAGICALLY CHANGED MODULE! //
namespace Foo {

}
```
[Playground link](http://www.typescriptlang.org/play//#code/PTAECEHkCUEkDkDipIBkAioDKAVAggJoC0A6gBICi0FRBkAqkQAr05E6UCyo6FAwqjzQ8OWJHhZQIAFAATAKYBjADYBDAE7zQAMwCuAO0UAXAJYB7faAUqN82QDEDx8-oAUASgBcoAG5mTsgDcckpqmqD6qgC28gDOAA6qilroobay8NHyWInJoADe0tIAvkUgoIA8G4CV+4AU5IC8G4DgO6CceIiwfHioqAQ8sFh4TEwUQgjIvAJCImISoI011dKKFrFGVmmasnzLRt4r6ib6AObBPhprNhsAahq7RvtHwcryq9ZhdqjPt-fHi2qxsTx1nY+H8AYVQKB4uozPEvgcfqV5PpdFFARc7BRkaj8qVpOUKAANHDCUD2ejwAB0VOarXanW6oD4ZDwSAomE4kHQ9FQFAAhFJgNJIjEEkktPYzGYCkVSkA)

**Comment by orta** [comment]
Interesting, must be a bug in prettier - I'm not sure if we are using the latest version of it. 

I'd like to replace it with the typescript formatter - if you want to give that a shot?

**Comment by jcalz** [comment]
> if you want to give that a shot?

Me? But my job is to point at stuff that's broken and laugh derisively, not to actually make anything *better*.

In all seriousness, I'm not sure I'll be able to get to it (or even know how to begin) but I'll post here if I do.  Thanks!

**Comment by orta** [comment]
Hah, no worries - I tried updating prettier and it did the same thing. Either the API usage in playground is wrong (maybe it thinks it's outputting JS?) or switching to TS's format is the right answer. 

I have to re-create the formatter in the future, so I'll move it to use TS's then. Otherwise you're welcome to get to it anytime sooner.

**Comment by orta** [comment]
The formatter now uses TypeScripts formatter - so we're good on this now 👍
