### ISSUE TITLE
Playground: AST Viewer freezes browser

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript-Website#675]
AST Viewer freezes the entire browser

**Repro:**
- Open v3 Playground and enable AST Viewer in the settings
- Copy the contents from https://raw.githubusercontent.com/AlCalzone/node-zwave-js/d70d60a862b67ca2c255ba21a30aed8f559ab1a8/src/lib/commandclass/BinarySwitchCC.ts into the editor
- Open AST tab

**Code**
see repro

**Expected behavior:**
AST tab shows AST

**Actual behavior:**
Browser freezes (the same happens on https://ts-ast-viewer.com btw.)

**Comment by orta** [comment]
This is likely to be implemented via https://github.com/microsoft/monaco-typescript/pull/65 - I just got to build it now
