### ISSUE TITLE
Docs: Certificate of https://typescriptlang.org isn't valid

### ISSUE THREAD

**Issue by danpintara** [microsoft/TypeScript-Website#677]
**Page URL:** https://typescriptlang.org

**Issue:** Certificate of [the website](https://typescriptlang.org) is invalid. It shows a message like this on Google Chrome:
> This server could not prove that it is typescriptlang.org; its security certificate is from *.oneroute.microsoft.com.

**Recommended Fix:** Use the correct certificate for it.

**Browser:** Google Chrome, Firefox, even `curl`. (browser-agnostic)

<img width="699" alt="Screen Shot 2020-06-14 at 3 56 48 PM" src="https://user-images.githubusercontent.com/63753461/84589298-b62cd280-ae57-11ea-95d9-64e7883cca73.png">

**Comment by orta** [comment]
You need to use `www.` for the website, this is an limitation we've not got fixed yet

**Comment by danpintara** [comment]
Yes, I know that the `www.` one works. I just a person to prefers not to use `www.` because it looks nicer without it, but okay then. Thank you for informing me, @orta.
