### ISSUE TITLE
Update peaceiris/actions-gh-pages

### ISSUE THREAD

**Issue by peaceiris** [microsoft/TypeScript-Website#68]
- [TypeScript-Website/deploy-release.yml at bf96f5b768b61acf567b00bca73bea687e7d7306 · microsoft/TypeScript-Website](https://github.com/microsoft/TypeScript-Website/blob/bf96f5b768b61acf567b00bca73bea687e7d7306/.github/workflows/deploy-release.yml)
- [TypeScript-Website/deploy-staging.yml at bf96f5b768b61acf567b00bca73bea687e7d7306 · microsoft/TypeScript-Website](https://github.com/microsoft/TypeScript-Website/blob/bf96f5b768b61acf567b00bca73bea687e7d7306/.github/workflows/deploy-staging.yml)

Please use the latest version. Check the latest README.

- [Releases · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/releases)

And, please do not use `GITHUB_TOKEN`, use `ACTIONS_DEPLOY_KEY` or `PERSONAL_TOKEN` 
  - cf. https://github.com/peaceiris/actions-gh-pages/issues/9

**Comment by orta** [comment]
Hah, that last one explains why I had so much trouble doing this myself manually

**Comment by orta** [comment]
In this case, we're OK - the TypeScript website doesn't rely on GitHub pages. We have it hooked up to azure which reads specific branches in a gh-pages like fashion. Thanks for the ping though!
