### ISSUE TITLE
Playground: Feature request: Allow selecting version that not merged into master branch yet

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript-Website#689]
Therefore we can try new TypeScript features.

For example, select version "Pull Requests", then input "https://github.com/microsoft/TypeScript/pull/29317" (Negated types PR). Then the playground will download the PR version to play with new features without clone and build.

**Comment by orta** [comment]
This already happens if a team member requests a packaged version: https://github.com/microsoft/TypeScript/pull/38923#issuecomment-638518896 

I'm not sure about whether we want a UI for it, but all of the pre-release versions are documented in https://github.com/orta/make-monaco-builds#cdnd

**Comment by Jack-Works** [comment]
What if for an arbitrary PR? Do I have to wait for a team member pack it?

**Comment by orta** [comment]
Yep

**Comment by orta** [comment]
You can just request it and we'll do one
