### ISSUE TITLE
Playground: Problem with accessibility of the navigation bar

### ISSUE THREAD

**Issue by infinnie** [microsoft/TypeScript-Website#691]
The hover state of links in the navigation bar has a low color contrast against the background (\#8c6b2b v \#000, which only passes AA for large text).

![image](https://user-images.githubusercontent.com/8168391/85245724-15ec3480-b47b-11ea-8d07-c678815d791e.png)

**Repro:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
Link text should either have a brighter color or be bolder with the color \#8c6b2b when hovered.

**Actual behavior:**

**Comment by orta** [comment]
This should be fixed when we switch back to blue next week

**Comment by infinnie** [comment]
> This should be fixed when we switch back to blue next week

The blue color used, as I remember, had an even lower color contrast against the \#8c6b2b color.

**Comment by orta** [comment]
this should be fixed by https://github.com/orta/typescript-play/commit/4ff7ef15212bdbea65b9e6bc950ff0dda0542f8f
