### ISSUE TITLE
Idea: Fix styles 'small-device-button-sidebar'

### ISSUE THREAD

**Issue by dandelionadia** [microsoft/TypeScript-Website#693]
It looks like `small-device-button-sidebar` styles is broken. It would be nice to add proper padding and fixed position svg element inside of the button.

Let me know if it need to be fixed.

![Annotation 2020-06-22 124520](https://user-images.githubusercontent.com/33199975/85279177-4a192280-b486-11ea-9089-9f9efeb8d0eb.png)

**Comment by orta** [comment]
Sure, give it a shot! Should be centered
