### ISSUE TITLE
Docs: Type Alias vs. Interface guidance seems outdated

### ISSUE THREAD

**Issue by daprahamian** [microsoft/TypeScript-Website#697]
**Page URL:** https://www.typescriptlang.org/docs/handbook/advanced-types.html#interfaces-vs-type-aliases

**Issue:** The following description:

```
In older versions of TypeScript, type aliases couldn’t be extended or implemented from (nor could they extend/implement other types). As of version 2.7, type aliases can be extended by creating a new intersection type e.g. type Cat = Animal & { purrs: true }.
```

seems to contradict the next paragraph:

```
Because an ideal property of software is being open to extension, you should always use an interface over a type alias if possible.
```

It seems like the first paragraph implies that type aliases are now "open to extension", so the justification for interfaces does not make sense.

**Recommended Fix:** I'm not sure, I'm just looking for some updated guidance on using a type alias vs an interface.

**Browser:** Chrome

**Comment by orta** [comment]
Agree, this isn't a great way to pitch it, we do a better job in the playground examples https://www.staging-typescript.org/play?q=276#example/types-vs-interfaces

**Comment by orta** [comment]
I've taken a look at this twice, and I think I've got a better explanation in staging now.
