### ISSUE TITLE
Support using the target + lib options to resolve d.ts per playground session

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#7]
> I was trying to help someone with a problem using Object.entries but the playground didn't think it existed. The options panel is great, but doesn't offer a way to specify the lib option. This is a fairly troublesome issue when trying to help people with their modern, up-to-date code.

> Perhaps a short-term easy fix would be to default to the latest libs?

> Eventually, being able to specify libs (or even a full tsconfig.json as suggested in #4) would probably be best.

**Comment by tjcrowder** [comment]
@orta - The original issue on orta/typescript-play had much more context and other suggestions as well. I didn't think to capture a copy of it, and now the Issues tab is turned off there and I can't get to the old issue anymore. Could you turn them on long enough to copy the entire issue, please?

**Comment by orta** [comment]
I've added the extra paragraph from your original post 👍

**Comment by orta** [comment]
This got update to ES2015 - so for now I'll close it

**Comment by orta** [comment]
I've been using this as the catch-all for grabbing the right lib files for the TS Playground - so we'll keep it here

**Comment by apieceofbart** [comment]
What about stuff like `Array.prototype.includes` ?

**Comment by orta** [comment]
That's what this issue is about - I shipped a deploy change which makes the nightly builds use the ESNext build last week, so you can test out what it will be like for 4.0 here: https://www.staging-typescript.org/play?ts=next

**Comment by apieceofbart** [comment]
@orta wow, this looks awesome! thanks a lot!

**Comment by orta** [comment]
https://github.com/microsoft/monaco-typescript/pull/64 - will unlock this feature

**Comment by iugo** [comment]
use `Object.fromEntries()`

setting: "lib": ["ES2019"]

**Comment by orta** [comment]
This is in

**Comment by adaamz** [comment]
@orta I don't see the `lib` option in TSConfig options tab, was this added or what is the resolution for this issue?

**Comment by orta** [comment]
You can use twoslash notation to define your own lib: `// @lib: ["thing", "other"]`  - I'm not sure if I'll ever give it a UI

**Comment by majellin24** [comment]
For anyone arriving here looking for how to enable this like me, I was not able to use the notation mentioned above like:
`// @lib: ["thing", "other"]`

I tried several variations and other settings changed before bothering to look into some of the other tickets in which this was mentioned.

To potentially save someone a few minutes, the way I was able to get it to work was the following: 
```
/// <reference lib="es2015" />
/// <reference lib="dom" />
```
