### ISSUE TITLE
Playground: Low contrast on regex literals

### ISSUE THREAD

**Issue by willmtemple** [microsoft/TypeScript-Website#710]
Regular expression literals are highlighted in a lime green color that is extremely difficult to read in the light theme (incidentally, I miss the old dark theme).

![image](https://user-images.githubusercontent.com/666532/85933967-bbdfda80-b891-11ea-8aa2-c192c1cb8cbd.png)

(Linux Firefox 77.0.1)

**Comment by orta** [comment]
Thanks! Yeah, that colour choice was *bad* - fixes now. 

Dark mode is still around, it just respects OS choice ATM
