### ISSUE TITLE
Playground: Can't cut text selection

### ISSUE THREAD

**Issue by lazytype** [microsoft/TypeScript-Website#714]
Both Ctrl+C and right-click -> context menu -> "Cut" do not actually cut the text, nor is the text copied into clipboard

**Expected behavior:**
Selected text is removed and exists in clipboard

**Actual behavior:**
Nothing happens

**Comment by orta** [comment]
Is this maybe OS specific? This seems to work fine on my machine

**Comment by lazytype** [comment]
I'm using Firefox on Windows. Firefox on MacOS seems to behave correctly as well as Edge on Windows.
