### ISSUE TITLE
Playground: Page becomes unusable after going to info about TS Configs

### ISSUE THREAD

**Issue by WORMSS** [microsoft/TypeScript-Website#715]
Page becomes unusable after going to info about TS Configs

![image](https://user-images.githubusercontent.com/1384537/85993945-fa3edc00-b9ee-11ea-9cc1-59d536381f2a.png)

![image](https://user-images.githubusercontent.com/1384537/85993952-fd39cc80-b9ee-11ea-8885-d340a09d74e6.png)

**Repro:**

1. Clicking on an 'INFO' link
2. Clicking back on the browser
3. Observe the page unusable. Downloading TypeScript never goes away, Dropdowns are unclickable.
4. Observe a refresh is the only way to get the page working again.

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**
Things work.

**Actual behavior:**
Things not work. 
3. Observe the page unusable. Downloading TypeScript never goes away, Dropdowns are unclickable.
4. Observe a refresh is the only way to get the page working again.

**Comment by orta** [comment]
We'll need to make sure these links aren't picked up as being Gatsby's fast links (or maybe have the playground detect whether it was brought back via one and re-load from scratch )

**Comment by orta** [comment]
I opted for the latter in #779
