### ISSUE TITLE
Docs: page "Type Checking JavaScript Files" is incomplete in V2

### ISSUE THREAD

**Issue by trongthanh** [microsoft/TypeScript-Website#717]
**Page URL:** https://www.staging-typescript.org/docs/handbook/type-checking-javascript-files.html

**Issue:** It is incomplete, compared to [V1 version][V1].

**Recommended Fix:** Its content should be complete like in [V1][V1]

**Browser:** Not applicable. It is related to generated HTML contents.

[V1]: https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html

**Comment by orta** [comment]
This got split out, looks like the link at the end got missed: https://www.staging-typescript.org/docs/handbook/jsdoc-supported-types.html

**Comment by orta** [comment]
Fixed in #722
