### ISSUE TITLE
Docs: UX of tsconfig document need to be improve

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript-Website#721]
**Page URL:** https://www.staging-typescript.org/tsconfig

**Issue:** The document isn't clear about which option items belong to `compilerOptions` scope. I can only guess those by scrolling down to Compiler Options heading. This is not good because if I jump from the outside/directly to a specific option item in the page, I would likely see the float menu of `compilerOptions` (it is not even have the 'Compiler Options' label on it). This causes bad experience on skimming and scanning the document due to misunderstanding the option position/placement.

**Recommended Fix:**     
I would like to offer 2 suggestions:

1.  At the document index (`#full-option-list`) should be separate carefully which items belongs to which scope (in this case, most of them belongs to `compilerOptions` right.)
1. At the float menu (`#sticky`) should have `Compiler Options` label, or anything similar to indicate the reader that the item they are reading is belong to the `compilerOptions` scope.

**Browser:** This is not technique bug so this should be no concern.

Please considering to improve document UX so we could speed up the looking up task and prevented from misunderstanding.

**Comment by orta** [comment]
These are good ideas
