### ISSUE TITLE
Pluck Utility Type or Expanded Documentation

### ISSUE THREAD

**Issue by nhannah** [microsoft/TypeScript-Website#723]
## Search Terms

lookup types
Pluck
indexed access types
2.1

## Suggestion

Documentation for Lookup types using to pluck directly from another type seems to only exist in extensive form in the [2.1 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html). It would be good to have this at a minimum noted within the main documentation as element access in this fashion is lacking in the docs. It also seems syntactically out of place in type creation. A utility type such as `type Pluck<T, K extends keyof T> = T[K];` seems more appropriate in common use.

## Use Cases

Types coming from packages that you want to match a portion of. E.g. in the example below I want to grab a selection of images from the package that returns PhotoIdentifier and map them down to just images. Separately I want to create some additional images to concat to that same array, but then I need to recreate a portion of the type or use element access that looks out of place in types. i.e. `type Image = CameraRoll.PhotoIdentifier['node']['image'];` I believe it would be preferred syntactically to use `type Image = Pluck<Pluck<CameraRoll.PhotoIdentifier, 'node'>, 'image'>;`.

## Examples

```
  interface PhotoIdentifier {
    node: {
      type: string,
      group_name: string,
      image: {
        filename: string,
        uri: string,
        height: number,
        width: number,
        fileSize: number,
        isStored?: boolean,
        playableDuration: number,
      },
      timestamp: number,
      location?: {
        latitude?: number,
        longitude?: number,
        altitude?: number,
        heading?: number,
        speed?: number,
      },
    };
  }

type Image = Pluck<Pluck<CameraRoll.PhotoIdentifier, 'node'>, 'image'>;
```

## Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

**Comment by orta** [comment]
Agree - we now have a doc in the handbook v2 specifically on this topic in the "types from types" section: http://localhost:8000/docs/handbook/2/indexed-access-types.html
