### ISSUE TITLE
Playground: Scrolling up when cursor is on the editor doesn't work. 

### ISSUE THREAD

**Issue by mohsen1** [microsoft/TypeScript-Website#724]
**Repro:**
* move cursor to header to scroll up to make editor be on top of page
* try to scroll down when cursor is on the edtior

**Expected behavior:**
Should scroll up
**Actual behavior:**
Gets stuck

This is Chrome on macOS

**Comment by orta** [comment]
I'm pretty sure this is how monaco always behaves, so I think this is likely a "working as designed"

**Comment by orta** [comment]
Yep, going to close
