### ISSUE TITLE
Docs: allowUnreachableCode described backwards and with misleading default

### ISSUE THREAD

**Issue by mattdmorgan** [microsoft/TypeScript-Website#727]
**Page URL:** https://www.typescriptlang.org/v2/en/tsconfig#allowUnreachableCode

**Issue:** First sentence is "Set to false to disable warnings about unreachable code", but instead you set the value to `true` to disable warnings. Also, the default is described as being `false`, but the actual default is `undefined` which as of https://github.com/microsoft/TypeScript/issues/24026 has different behavior: `undefined` gives warnings about unreachable code, while `false` gives errors.

The same two issues apply to the allowUnusedLabels documentation just below it.

**Comment by orta** [comment]
Great! Thanks, I've updated these docs

**Comment by mattdmorgan** [comment]
Looks like the PR addresses allowUnreachableCode; fwiw, the same applies to allowUnusedLabels.
