### ISSUE TITLE
Idea: HOver

### ISSUE THREAD

**Issue by Seilax** [microsoft/TypeScript-Website#730]
**It will be much better, if u add a hover on your CSS, for the links.**

**Because it's sweet**

**I don't know, maybe ¯\_(ツ)_/¯**

**Comment by orta** [comment]
Agree

**Comment by Seilax** [comment]
You can also had a border-radius on the buttons, to attenuate the edges. Rounded shapes are fashionable ;)
![image](https://user-images.githubusercontent.com/67839724/86832842-ff5bf500-c098-11ea-9d1b-303c6ef4a1ba.png)

**Comment by orta** [comment]
Re: localization - sure, there's instructions in https://github.com/microsoft/TypeScript-Website/issues/100 

Re: the rest, that site only has a few more weeks left before it's moving to https://www.staging-typescript.org be the main site
