### ISSUE TITLE
Docs: /v2/tsconfig/ 404 not found

### ISSUE THREAD

**Issue by stringparts** [microsoft/TypeScript-Website#732]
**Page URL:** [/v2/tsconfig/](https://www.typescriptlang.org/v2/tsconfig/)

**Issue:**  
No longer exists, and responds with "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

This page is ranked high for some Google search results and might be linked from external blogs/posts. 

**Recommended Fix:**  
Redirect to the new page (/tsconfig?)

**Comment by orta** [comment]
Yeah, the `/v2` approach was flawed approach to staging, I'll rip that bandaid off next week

**Comment by stringparts** [comment]
Now [/tsconfig](https://www.typescriptlang.org/tsconfig/) also 404s. It is also one of the top search results for "typescript compiler options"

**Comment by stringparts** [comment]
For anyone else looking, the correct v2 page URL for this specific doc is [staging-typescript.org/tsconfig](https://www.staging-typescript.org/tsconfig).

There is a broken link from the [v1 page](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html).

**Comment by orta** [comment]
Ah, looks like I hadn't pushed the commit which fixes those links, that should come around with the next deploy.

**Comment by orta** [comment]
That should be fixed now
