### ISSUE TITLE
Idea: Make the docs available offline

### ISSUE THREAD

**Issue by ebeloded** [microsoft/TypeScript-Website#733]
**Improvement Idea:**

It would be great if the TypeScript website with all of its docs was available offline.

**Why:**

It is almost an expectation in modern development tooling that the documentation is available offline. Good examples are Vue with its ecosystem and Svelte/Sapper websites.

**Comment by orta** [comment]
I'm not sold on any of the web infra for running the site offline yet

For now there is the epub/pdf versions of the handbook

**Comment by David-Else** [comment]
@orta The PDF on the staging site had tear lines in the text at the base of each page, now on the production site, I can't find it. Is it still there? Thanks!

**Comment by orta** [comment]
I moved the [link down to live with the handbook section](https://www.typescriptlang.org/docs)

![Screen Shot 2020-08-05 at 6 06 58 PM](https://user-images.githubusercontent.com/49038/89468895-6a572500-d746-11ea-8a2b-3bf91315053e.png)

I've not really found a great way to generate the PDF yet, the current version takes the epub and converts it to a PDF, but it really is just a big set of markdown -> HTML files so there's space to improve

**Comment by David-Else** [comment]
Thanks for the quick reply!

I am afraid there is still something wrong with the PDF generation. See the screenshot, it includes Firefox and Gnome's built-in  PDF reader output:

![Screenshot from 2020-08-05 23-11-13](https://user-images.githubusercontent.com/12832280/89469413-4230eb80-d771-11ea-9f9e-76f82ab89580.png)

**Comment by orta** [comment]
The PDF and Epub renderers got a bunch of work for the v2 release, they are pretty good now 👍🏻
