### ISSUE TITLE
Idea: Make site "Tutorials > Using Babel with Typescript" work

### ISSUE THREAD

**Issue by svnba** [microsoft/TypeScript-Website#735]
**Improvement Idea:** Make site [Tutorials > Using Babel with Typescript](https://www.typescriptlang.org/docs/handbook/babel-with-typescript.html) work again.

**Why:** 
* Link in navigation sidebar is not working
* Navigating to site [Using Babel with Typescript](https://www.typescriptlang.org/docs/handbook/babel-with-typescript.html) gives the error "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

**Alternative ideas:** none

**Comment by orta** [comment]
Thanks!
