### ISSUE TITLE
Docs: `Record<K, T>` definition is misleading

### ISSUE THREAD

**Issue by lcswillems** [microsoft/TypeScript-Website#736]
**Page URL:**
https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkt

**Issue:**
It is written: "Constructs a type with a set of properties K of type T." which is wrong.

Because this code is correct TypeScript:
```tsx
interface PageInfo {
  title: string;
}

type Page = "home" | "about" | "contact";

const a = {
  about: { title: "about" },
  contact: { title: "contact" },
  home: { title: "home" },
  test: { title: "test" }
}

const b: Record<Page, PageInfo> = a;
```

But `b` is not a set of properties K of type T.

**Recommended Fix:**

I don't know.

**Comment by orta** [comment]
This is [excess property checking](https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks) - see the [playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgApwOYQJIhge2QG8AoZZMYMAGwgC5kBnMKUDAbhIF8SSwBPAA4p0WZAF5kAIgAW+ALYQpyAD7S4AI3wBXMMrVSE+cIj2deRkM2QaGAJQhGoAEwA8oiABo0mHHnwAfBLEZMiaOmAMRBRUtAxS4brKXJ6hlmCmUTE09NLppsmp5HKKWZQ58SVKyCmhkMxlsblS9Xo13JxAA)

**Comment by lcswillems** [comment]
I don't see the link with the issue. I gave you an example where `b` is of type `Record<Page, PageInfo>` but is not a set of properties `Page` of type `PageInfo`.

I think the issue should be reopened.
