### ISSUE TITLE
Playground: Font Too Thin And Dim on macOS Catalina

### ISSUE THREAD

**Issue by Zehua-Chen** [microsoft/TypeScript-Website#743]
The font in the playground seems as thin and dim as the font in VS Code when macOS has just changed its text rendering implementation (I think it was Mojave?) This problem was fixed later on by VS Code. It was never an issue with the old playground in Safari, but it is an issue now. If I can access the old playground, I can share an image of how it used to look.

<img width="245" alt="Screen Shot 2020-07-05 at 21 15 35" src="https://user-images.githubusercontent.com/31496190/86549469-516c1180-bf05-11ea-8212-0d23716d1314.png">

**Repro:**

1. Open the playground
2. Type something

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.

class Foo {
  foo(): void {
  }
}
```

**Expected behavior:**
The font should be thicker and brighter

**Actual behavior:**
The font is very thin and dim

**Comment by orta** [comment]
Here's a comparison:

![Screen Shot 2020-07-06 at 9 24 12 AM](https://user-images.githubusercontent.com/49038/86598189-c6256700-bf6a-11ea-91a9-155deae5c67f.png)

This is `-webkit-font-smoothing: antialiased;` which is enabled on the root, I think maybe switching it on the playground's monaco instance to only happen on retina screens is an acceptable trade-off

**Comment by Zehua-Chen** [comment]
Actually not tempering with `-webkit-font-smoothing` at all gives a much better result. 
<img width="1235" alt="Screen Shot 2020-07-06 at 10 43 53" src="https://user-images.githubusercontent.com/31496190/86612482-cd9e3d80-bf75-11ea-94b3-ae61bb33b30a.png">
<img width="1225" alt="Screen Shot 2020-07-06 at 10 44 04" src="https://user-images.githubusercontent.com/31496190/86612490-cf680100-bf75-11ea-881e-a16b777c964e.png">

Also, what does "You Can Do This" mean? Does it mean you are going to fix it or does it mean I can fix it?

**Comment by orta** [comment]
You're welcome to add it to the website otherwise I'll get around to it, but I do only want it removed from the content inside the playground instance on the v2 site, I wasn't sold on it everywhere 👍
