### ISSUE TITLE
Module: Fix twoslash tooltip flicker on border hover

### ISSUE THREAD

**Issue by okasi** [microsoft/TypeScript-Website#744]
**Improvement Idea:**

Make the twoslash tooltip not flicker when hovering the cursor on the border.

**Why:**

Can be a seizure trigger for people with epilepsy.

**Comment by okasi** [comment]
closes https://github.com/microsoft/TypeScript-Website/pull/745

**Comment by okasi** [comment]
closes https://github.com/microsoft/TypeScript-Website/pull/745

**Comment by orta** [comment]
Thanks!
