### ISSUE TITLE
Nightly version in Playground is out of date

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/TypeScript-Website#75]
Mentioned here https://twitter.com/jasvir/status/1178831986053373952

When I pick Nightly version in Playground I don't have functionality that was merged in master and available in `typescript@next` (e.g. features from #33178, #32064)

Looks like `@typescript-deploys/monaco-editor@nightly` is requested and it points to build from PR (`3.7.0-pr-33473-14`), but I would expect that `@next` should be requested so `3.7.0-dev.20191001` will be loaded instead.

**Comment by orta** [comment]
This will be fixed when staging is deployed today with the 3.7.0 beta: http://testsite-typescript-41eeb979-7eaa-4c74-9d47-9d182c7b61ab.azurewebsites.net/play/index.html?ts=Nightly

**Comment by IllusionMH** [comment]
Opps, sorry if this one was known issue - haven't found duplicate issues.

P.S. New design looks great!

![image](https://user-images.githubusercontent.com/1312662/65959295-4528c480-e45a-11e9-8bc3-b3372891e6fd.png)
Old version has a bit better line spacing and no overlap with shortcuts background.

**Comment by IllusionMH** [comment]
Strange, but looks like it still doesn't work as expected.
[Playground link](https://www.typescriptlang.org/play/index.html?ts=Nightly#code/CYUwxgNghgTiAEA3WSoQFzwHYFcC2ARiDPAD7wDOALjAJZYDmA3ALABQ7oksCAZjljBVaAeyzwoFCsSoBlGvQYAKAB6ZqdRgEpWbLtDjx+g4WIlSZAOXxEYqzLkLEdncAb4Cho8ZOkwqliCIxPbYQc667BQA7rRUYAAW8EpUAJ4ADiAivKgQWvAA3uzwJfBgkggABhqKlejFpY2+MvKaysh5uo2NBHBQANaRbI3l0vCVjrZ1Dd3mfgE2IR0uw7PwvSADQ42gvFA4EFT1q7PN-oHBdsu6AL7s7MZeZmdUSmBiwHHemFBYqQA08DwFAYAH51AptD8LP4KGUPl8zEUTvBaDklABCd5YT6mLD5ZFreBUBIwETRcYAR2iIGptJplS6pTubBZD08eKBB2E6QgqVCAn6WHJWEBqUwguF0XxhRmcxkKQyWRyKngAF4NfAAESTYhalZNGGvNKZbLwVLqzU6xYwfVMkovaxOOwqA2lR02pSpFZyuBUHAwcSqgBU5tu9zYQA)
[Screenshot](https://user-images.githubusercontent.com/1312662/66034425-e1fa6900-e511-11e9-8e35-fec1c3b447de.png)



Looks like it now pulls `tsWorker.js` with expected version (at least comment is `monaco-typescript version: 3.7.0-dev.20191001`) but link above has errors that should be there.

Works fine with local install of `3.7.0-dev.20191001` in VS Code
[Screenshot](https://user-images.githubusercontent.com/1312662/66034226-85974980-e511-11e9-878b-94e322bbb81f.png)

**Comment by orta** [comment]
Looks like there were some bugs in the deploy process which mean it was shipping 3.6 as the nightly, this is fixed with https://github.com/orta/make-monaco-builds/commit/395e755fe5e3ab31a2e5a3e951cd4aeb022044e5 and from tomorrow the nightly should get fixed with the latest build 👍

**Comment by orta** [comment]
This is now working fine with nightly builds (or at least, the nightly build definitely includes 3.7 syntax) - so I'm calling this one done.

**Comment by IllusionMH** [comment]
Yep, works great. Haven't found good change to check last week. But today https://github.com/microsoft/TypeScript/pull/33821 works as expected 👍
