### ISSUE TITLE
Module: @typescipt/vfs "addFilesForTypesIntoFolder" add non-type files

### ISSUE THREAD

**Issue by hipstersmoothie** [microsoft/TypeScript-Website#753]
When I use `addFilesForTypesIntoFolder` it will add the following file types and break the TS compilation

![Screen Shot 2020-07-08 at 12 55 12 PM](https://user-images.githubusercontent.com/1192452/86964010-44743b80-c11a-11ea-9751-64b2c8feeaa1.png)

```ts
const ts = require("typescript");
const fs = require("fs");
const path = require("path");
const {
  createSystem,
  createVirtualTypeScriptEnvironment,
  createDefaultMapFromNodeModules,
  addFilesForTypesIntoFolder,
} = require("@typescript/vfs");

const complierOptions = {
  jsx: ts.JsxEmit.React,
  module: ts.ModuleKind.CommonJS,
  target: ts.ScriptTarget.ES2016,
};

// Create a map of all files + libs
const fsMap = createDefaultMapFromNodeModules(complierOptions);
addFilesForTypesIntoFolder(fsMap);

const acquiredTypes = {};
const file = `
import React from 'react';

React.`;
fsMap.set("index.ts", file);

console.log(fsMap.keys());

// Create a system with those files
const system = createSystem(fsMap);

// Load the system into TypeScript env
const env = createVirtualTypeScriptEnvironment(
  system,
  Array.from(fsMap.keys()),
  ts,
  complierOptions
);

const completions = env.languageService.getCompletionsAtPosition(
  "index.ts",
  file.length,
  {}
);

if (completions) {
  console.log(JSON.stringify(completions.entries.slice(0, 10), null, 2));
} else {
  console.log("No completions found!");
}
```

It probably shouldn't add these files but I may also be using the VFS wrong

**Comment by hipstersmoothie** [comment]
I can fix the above if update the function to only include `.d.ts` files.

![Screen Shot 2020-07-08 at 12 56 05 PM](https://user-images.githubusercontent.com/1192452/86964087-64a3fa80-c11a-11ea-843d-91645f9e7b50.png)

But once I fix that I'm still left with these errors:

![Screen Shot 2020-07-08 at 12 56 56 PM](https://user-images.githubusercontent.com/1192452/86964187-82715f80-c11a-11ea-8b71-72324351f96b.png)

Which come from these files

![Screen Shot 2020-07-08 at 12 57 29 PM](https://user-images.githubusercontent.com/1192452/86964219-96b55c80-c11a-11ea-835e-e94638d6e55d.png)

It seems like I would have to implement something that typescript is already doing and choose the correct .d.ts file to add? I'm unsure

**Comment by orta** [comment]
We chatted in the discord: I'd accept a PR adding a function which makes a new system which is FS backed which should solve both issues

**Comment by orta** [comment]
These ideas have shipped
