### ISSUE TITLE
React Handbook Deprecated Ref to TSLint

### ISSUE THREAD

**Issue by ccarcaci** [microsoft/TypeScript-Website#765]
In the React handbook:
https://www.typescriptlang.org/docs/handbook/react.html

I've found a reference to TSLint which has been deprecated.
https://medium.com/palantir/tslint-in-2019-1a144c2317a9

The create-react-app in fact doesn't add TSLint refs.

**Comment by orta** [comment]
This page is still in the v2 site, but should probably be a stub which redirects to the React docs, and to the react cheatsheets repo: https://github.com/typescript-cheatsheets/react-typescript-cheatsheet

**Comment by orta** [comment]
Fixed in https://github.com/microsoft/TypeScript-Website/pull/774
