### ISSUE TITLE
Idea: Bigger font-size

### ISSUE THREAD

**Issue by Krutsch** [microsoft/TypeScript-Website#796]
First: Congratulations on the new layout 🎉.
I started reading the docs quite recently and noticed the difference immediately. One thing, that kind of takes my joy of reading though, is the shrinked font size (on mobile) - due to the new layout. I could zoom in but scrolling horizontally is also not so enjoyable.
Hope this helps 👍🏼

**Comment by orta** [comment]
Hi there, thanks! 

In this case the body fonts are the same size across the old site, the new site (16px Segoe UI regular) irregardless of mobile/desktop - is there anything in particular that stands out to you?

**Comment by Krutsch** [comment]
Oh, really? Maybe my brain tricked me into thinking that it got smaller. 
This is how it looks for me. The phone screen is half an arm length to one arm length away from my eyes.

![Screenshot_20200723-070226__01__01](https://user-images.githubusercontent.com/45216083/88257316-5a0a6900-ccb5-11ea-98f8-909327605369.jpg)


And in comparison to another project's doc site:
![Screenshot_20200723-070946__01](https://user-images.githubusercontent.com/45216083/88257065-d486b900-ccb4-11ea-9397-190923e92203.jpg)

**Comment by orta** [comment]
Well, I can't disagree with those screenshots  - looks like the old site has a smaller font 👍 maybe it had some extra CSS somewhere

The old version will be gone soon, till then I'd recommend using staging: https://www.staging-typescript.org/

**Comment by Krutsch** [comment]
Ah, now I see what happened here: I was using new version somehow - did it land on production last week?
And then recently it switched to the old version (with the white background). 
Yes, it is more readable on the staging link. Many thanks.

I will close this then.
