### ISSUE TITLE
Debate what to do about replaceState not removing history

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#8]
I'm pained to remove the current set query hash on a compile behavior because the old way used to lose data for me.

> Having the code in the URL is great when you're ready for that, but doing it on every change (or so) fills up your history with fairly useless entries:

See: https://github.com/orta/typescript-play/issues/6

**Comment by tjcrowder** [comment]
@orta - Since Issues is turned off, the link there doesn't work. Could you turn them back on long enough to capture the full description of the original issue?

**Comment by tjcrowder** [comment]
The current behavior of filling up the history list is a big problem. Typing a moderate example means your history is just completely filled.

To avoid data loss, I suggest storing the latest code in local storage and filling in that code in the editor if the hash fragment doesn't have any. (I thought the old playground did that...?) So if you navigate away without saving and go *"Doh!"* and go back, the code is still there, but your browser history isn't chock-a-block. An affirmative user action (Ctrl+S or clicking a button) would update the hash fragment (and add a history entry).

**Comment by orta** [comment]
This is now a toggleable option in the v2 version of the playground: https://www.typescriptlang.org/v2/en/play

**Comment by tjcrowder** [comment]
@orta - **Fantastic**!! That's really great news, this was bothering me just the other day.

v2 looks terrific! Love the Export menu, the Log tab... All sorts of goodness here.

Any chance of an Export menu item to just copy the playground link (without markdown wrapping)? I tried Ctrl+S but it triggered the standard browser web page save. I wish I could say I had time to implement it myself and do a PR, but I won't for at *least* a couple of weeks...

**Comment by orta** [comment]
OK, I'm closing this, the option is available  if folks want it off in v2
