### ISSUE TITLE
Translation Request: This Page in Your Language

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#805]
Hello!

ja: @bobstrange @DuGlaser @sasurau4 @Quramy
es: @KingDarBoja @fanyCaz
zh: @Kingwl @laosb 
pt: @khaosdoctor @alvarocamillont  @danilofuchs 

I have just added a new feature which kinda _requires_ translating. Normally I **do not** want to make requests about translations, which is why English fallback is totally OK in my mind. For this feature though, I really do need to have it translated for anything to make sense. Sorry!

In #802 I added a popup when you are on a page which is not your browsers language, and there is a native version. 

![](https://user-images.githubusercontent.com/49038/88483879-baf5a380-cf38-11ea-8372-cc4a48e1d19e.png)

There are two design elements:

- "In En" in the top nav
- "This page is available in English" at the bottom

So, I am on a Chinese page, but my browser is in English, so it offers the English page.

However, if I were on a Spanish page on a Japanese browser, the link would redirect correctly but the text would say "Available in English" right now! 😸 This makes it very weird. 

Can you add the equivalent to this file: [`/packages/typescriptlang-org/src/copy/inYourLanguage.ts`](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/typescriptlang-org/src/copy/inYourLanguage.ts)

So, for Portugese it would look something like:

```diff
export const inYourLanguage: Record<
  string,
  { body: string; open: string; cancel: string; shorthand: string }
 > = {
  en: {
    shorthand: "In En",
    body: "This page is available in English",
    open: "Go",
    cancel: "Don't ask again",
  },
+  pt: {
+    shorthand: "Em Pt",
+    body: "Isso pagina tem em Portugues",
+    open: "Avancar",
+    cancel: "Nao pergunte novamente",
+  },
}
```

You should be able to see it in action at:

- https://www.staging-typescript.org/zh
-  https://www.staging-typescript.org/pt

**Comment by KingDarBoja** [comment]
Sure, glad to help with this task 🚀

**Comment by danilofuchs** [comment]
Sure! I will create a PR for the Portuguese version

**Comment by danilofuchs** [comment]
Just a note, @orta: The `don't ask again` button may overflow depending on the translation:
![image](https://user-images.githubusercontent.com/17657014/88490050-0c208a00-cf6f-11ea-8003-f530ce229619.png)

**Comment by orta** [comment]
I'll improve the layout, thanks @danilofuchs  - who knows if German could ever fit into a space like that

Thanks everyone! - I'll keep this open till I fix the layout issue
