### ISSUE TITLE
TS Playground does not provide ES2017 Object types

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-Website#82]
**TypeScript Version:**  Playground

**Search Terms:** playground es2017

**Code**

```ts
Object.entries({}) // Property 'entries' does not exist on type 'ObjectConstructor'.
```

**Expected behavior:** It should get no error.

**Actual behavior:** It does get one.

**Playground Link:** https://www.typescriptlang.org/play/?ssl=1&ssc=18&pln=1&pc=1#code/PIIwVgpgxgLgdBAdjATgSwgZwBQG8C+AlEA

**Related Issues:** 

Couldn't find a relevant place to post an issue. @orta, is it being maintained on https://github.com/orta/typescript-play ?

**Comment by orta** [comment]
I think this is about the default lib.d.ts which comes with monaco-typescript

As right now there isn't a way to configure your lib options inside the playground

**Comment by mikeaustin** [comment]
If someone is exploring the use of TypeScript, this isn't good. "Wow, TS doesn't even support Object.values()". I spent a few minutes toying with the target, Googling, then finally found this thread. I could see if this was a third party site, but this is the official language site. Kudos to the language.

**Comment by orta** [comment]
Limited time and limited resources, @mikeaustin - you're welcome to take a look at it though before I get back to it though?

**Comment by mikeaustin** [comment]
I can look into it (clone repo, look around), but I probably don't have enough context to work on it. I'll ask questions as they come up.

**Comment by David-Else** [comment]
@orta  Please fix this. I can't ask for help with half my issues on forums as I can't provide a working example using the playground.

At the moment the playground is broken for modern JS syntax. `Object.entries` is in common use now. Thanks!

**Comment by orta** [comment]
Making sure this is linked to #7

**Comment by orta** [comment]
@RyanCavanaugh  brought up the idea that maybe the playground should just ship with ESNext's bundled dts instead which is probably the right solution

**Comment by devuxer** [comment]
@orta, What about the idea of exposing the "lib" compiler option, or is that something the Monaco editor is unable to support?

**Comment by orta** [comment]
This should probably be closed now that https://github.com/microsoft/monaco-typescript/pull/64 exists, once this is in released built then I was planning on adding a lib option
