### ISSUE TITLE
Docs: Add note on watchman dependency

### ISSUE THREAD

**Issue by danilofuchs** [microsoft/TypeScript-Website#820]
**Page URL:** https://github.com/microsoft/TypeScript-Website/blob/v2/README.md

**Issue:** `watchman` is required to develop the website, but it is not mentioned in the getting started docs.

![image](https://user-images.githubusercontent.com/17657014/88960643-34afc900-d27a-11ea-9730-0548000bf761.png)

**Recommended Fix:** A note stating that users must have it installed first

**Comment by orta** [comment]
This is fixed in v2
