### ISSUE TITLE
Bug: bootstrap script not working properly

### ISSUE THREAD

**Issue by danilofuchs** [microsoft/TypeScript-Website#821]
After running `yarn bootstrap` and `yarn start`, I get this error:
```
Cannot find module '<dir>/TypeScript-Website/node_modules/gatsby-remark-shiki-twoslash/dist/index.js'.
Please verify that the package  .json has a valid "main" entry
```

![image](https://user-images.githubusercontent.com/17657014/88961618-a9cfce00-d27b-11ea-8cb8-c7a4688c49ce.png)

Only after I do a manual `cd packages/gatsby-remark-shiki-twoslash` and `yarn build`, the dist folder is generated, but with many warnings:
![image](https://user-images.githubusercontent.com/17657014/88962334-ad178980-d27c-11ea-9eba-37dc2b3da189.png)

Other packages also do not seem to be building correctly when using the bootstrap script.

Environment:
Fails both on Node 13.14.0 and 14.7.0
Yarn 2.1.1 (workspace)

**Comment by danilofuchs** [comment]
It seems many build scripts are being skipped with `NOOP`

![image](https://user-images.githubusercontent.com/17657014/88962719-3202a300-d27d-11ea-847e-b15a263aaf8c.png)

Maybe this is specific to Yarn 2

**Comment by orta** [comment]
Cool, good feedback - I was going to look a this over the weekend @danilofuchs https://github.com/microsoft/TypeScript-Website/issues/817

**Comment by danilofuchs** [comment]
Nice! Should I keep this issue open or do I close it, and track the other?
