### ISSUE TITLE
Branding site is currently down

### ISSUE THREAD

**Issue by adamalston** [microsoft/TypeScript-Website#825]
**Page URL:** https://www.typescriptlang.org/branding

**Issue:** Site currently returns an error
> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

**Recommended Fix:** The site was up 2 days ago when was referencing it for a citation. In the time since then, it appears to have gone down. Looking through commits, I don't see anything that would have broken it.

**Browser:** Firefox 78.0.2, Safari 13.1.2

**Comment by orta** [comment]
You can use staging for now: https://www.staging-typescript.org/branding

You copied the link during the weekend when we've been testing the new website 👍 - we should be shipping mid next week
