### ISSUE TITLE
Add refactoring support to monaco-typescript

### ISSUE THREAD

**Issue by Kingwl** [microsoft/TypeScript-Website#838]
**Repro:**

https://www.staging-typescript.org/play?ts=4.0.0-pr-39832-5

**Expected behavior:**
The new refactor provided by language service should available.

**Actual behavior:**
Nothing.

**Comment by orta** [comment]
I'm not sure if refactors are available in monaco-typescript, only fixits

**Comment by Kingwl** [comment]
I'm not enough familer to monaco-edito, but are there any possibility to provide the refactor?

**Comment by orta** [comment]
Feasible, yes! 

Happening too soon, no, mainly because I'm unsure of my wrk week (site goes live today) and I'm off next week

**Comment by Kingwl** [comment]
It's not a big deal. Enjoy your holiday. :XD

**Comment by Kingwl** [comment]
I'd like to start work on this.

**Comment by orta** [comment]
OK, cool - fork monaco-typescript  and look inside the TypeScriptWorker.ts - I think that's probably where it will need to live

**Comment by Kingwl** [comment]
Seems refactor is a bit different. It's need register & exec command in editor？
