### ISSUE TITLE
Docs: Cookie banner on the new website looks... unfinished?

### ISSUE THREAD

**Issue by filipsobol** [microsoft/TypeScript-Website#846]
Hi 👋

**Page URL:** https://www.typescriptlang.org/

**Issue:** Cookie banner on the new website looks like a placeholder. It currently says "We use optional cookies to provide... read [here](https://www.typescriptlang.org/link).", the link is broken and "More info" button just opens a modal with the following text:
```
Manage cookie preferences
Most Microsoft sites... 
```

**Recommended Fix:** Replace placeholder with actual cookie banner.

**Browser:** Firefox

**Comment by orta** [comment]
This seems to be an odd issue around localization, think we've got a fix

**Comment by orta** [comment]
I've not had any reports of this today - so I'm going to assume my fix worked out
