### ISSUE TITLE
Contradictions in document 

### ISSUE THREAD

**Issue by harshakumar347** [microsoft/TypeScript-Website#859]
https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html

In this page 
Following statement 
![statement1](https://user-images.githubusercontent.com/25246216/89528577-e9149680-d808-11ea-991a-5072b5c0a559.png)

**is in contradiction with below following statements please provide clear explanation** 

Statement 2 

![statement2](https://user-images.githubusercontent.com/25246216/89528659-077a9200-d809-11ea-9a4b-73d5c77b2684.png)

Statement 3

![statement3](https://user-images.githubusercontent.com/25246216/89528667-0b0e1900-d809-11ea-8b7f-886e7a78e1a1.png)

**Comment by orta** [comment]
Compiler errors don't stop emitting the JavaScript code, JS in JS out, even though TS will offer error messages it won't stop the build
