### ISSUE TITLE
Docs: All contents below JSX are commented out

### ISSUE THREAD

**Issue by MJochim** [microsoft/TypeScript-Website#865]
**Page URL:** https://www.typescriptlang.org/tsconfig

**Issue:** All contents below JSX are invisible.

**Recommended Fix:** The HTML source includes the following comment, but the closing `-->` is missing: `<!-- This is blocked on https://github.com/microsoft/TypeScript-Website/issues/860`. This kills all content below it.

**Comment by orta** [comment]
haha, oops - thanks fix is shipped https://github.com/microsoft/TypeScript-Website/commit/24f32ee4a6c4be472f9052d77dc0d31e9e98b5d3 and being deployed now
