### ISSUE TITLE
Bug: tsconfig reference looks bad on mobile

### ISSUE THREAD

**Issue by ascott18** [microsoft/TypeScript-Website#871]
First off, totally loving the new site!

On the tsconfig reference, headers are overlapping, columns too narrow to see much of anything in them.  Pixel 3 XL.

![Screenshot_20200806-213526](https://user-images.githubusercontent.com/5017521/89609643-4fabab80-d82d-11ea-944b-4ad846a7e406.png)

**Comment by orta** [comment]
Hrm, tricky. I don't think it's a good answer to have them top to bottom as a single list, that's just too much scrolling and using find on mobile is generally about 500 taps I've found and so I've never used it. That makes navigating the 100+ options real bad. 

I think this will probably require switching out that nav with an  auto-completing textbox and a jump to that flag button
