### ISSUE TITLE
Docs: Example does not compile

### ISSUE THREAD

**Issue by EdorianDark** [microsoft/TypeScript-Website#909]
**Page URL:** https://www.typescriptlang.org/docs/handbook/iterators-and-generators.html

**Issue:** 
This does not compile:
````
let pets = new Set(["Cat", "Dog", "Hamster"]);
pets["species"] = "mammals";

for (let pet in pets) {
  console.log(pet); // "species"
}

for (let pet of pets) {
  console.log(pet); // "Cat", "Dog", "Hamster"
}
````
And the error is:

    Element implicitly has an 'any' type because expression of type '"species"' can't be used to index type 'Set<string>'. Property 'species' does not exist on type 'Set<string>'.

**Recommended Fix:** 
Make it compile.
It also is very confusing for someone new to Typescript

**Browser:** 
It is an compile error, browser not relevant

**Comment by brandoncroberts** [comment]
This is not actually a compile error, rather that `pets["species"] = "mammals";` is an incorrect usage of a JavaScript `Set` object. 
If you refer [to MDN Set Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set), you will see that a Set is not meant to be modified or even accessed using this bracket notation.
