### ISSUE TITLE
Playground mobile editing support is not perfect

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-Website#91]
- On android you can't delete text
- On iOS the popover doesn't allow pasting

These could be fixed by either:

 - Android/iOS support being improved in monaco
 - Switching monaco with something else in mobile

**Comment by MicahZoltu** [comment]
Playground vNext on Android Firefox can no longer scroll.  When you touch/drag inside the editor window, the whole window scrolls but the editor window does not scroll.  This means you can only see the top bits of any shared playground link on Android Firefox.

**Comment by karlhorky** [comment]
I guess this one can be added to the list @orta (encountered this today, also on staging):

- On Android Chrome, long-press does not allow for pasting (context menu appears instead)

**Comment by Lonli-Lokli** [comment]
Still unusable and not friendly on mobile.
Is there alternative? Stackblitz isn't good too.

**Comment by zyf0330** [comment]
Long press cannot select and delete in Android chrome
