### ISSUE TITLE
Playground: Typescript 3.3.3 showing v3.3.3333

### ISSUE THREAD

**Issue by tanhauhau** [microsoft/TypeScript-Website#946]
<img width="355" alt="Screenshot 2020-08-20 at 11 42 34 PM" src="https://user-images.githubusercontent.com/2338632/90794286-316ea100-e33f-11ea-9973-1d050f34544e.png">

**Repro:**

**Code**

```ts
// A *self-contained* demonstration of the problem follows...
// Test this by running `tsc` on the command-line, rather than through another build tool such as Gulp, Webpack, etc.
```

**Expected behavior:**

**Actual behavior:**

**Comment by orta** [comment]
Yep, not a bug! This was the version we released on npm haha

https://www.npmjs.com/package/typescript
