### ISSUE TITLE
What's new assertion functions example is wrong/misleading

### ISSUE THREAD

**Issue by arv** [microsoft/TypeScript-Website#95]
https://github.com/microsoft/TypeScript-Website/blob/e264e03eac3c3e52657e1c200a377c200ea90fed/Examples/en/3-7/Types%20and%20Code%20Flow/Assertion%20Functions.ts#L43-L63

The following line

```ts
declare const oneOfFirstFiveNumbers: 1 | 2 | 3 | 4 | 5
```

should probably be

```ts
declare const oneOfFirstFiveNumbers: 1 | 2 | 3 | 4 | 5
```

Especially since `1 | 2 | 3 | 4 | 5` is `7` and that is not what the example text allows

**Comment by orta** [comment]
Ha - good point

**Comment by orta** [comment]
Fixed in https://github.com/microsoft/TypeScript-Website/commit/061d91745c9b717d08615a944938efb5d04b52ee
