### ISSUE TITLE
Playground: stuck waiting for unpkg.com

### ISSUE THREAD

**Issue by AlCalzone** [microsoft/TypeScript-Website#97]
**TypeScript Version:**  not applicable

**Search Terms:** playground unpkg

**Code**
![grafik](https://user-images.githubusercontent.com/17641229/67500387-de767f80-f682-11e9-9512-01e25201d856.png)

**Expected behavior:**
The playground loads immediately, then fetches 3rd party definitions

**Actual behavior:**
The playground is stuck waiting for unpkg.com.

**Playground Link:**
Not applicable. Open the playground with a very limited bandwidth.

**Related Issues:** none

**Comment by orta** [comment]
It would be feasible for the playground to host copies of all the monaco-editors we offer in the dropdown, re-hosting them could be an automated step in the install pipeline.

I'll take a look when I get back for the v3 unless unpkg gets real bad. Can't really move off it for ATA though.

**Comment by AlCalzone** [comment]
> Can't really move off it for ATA though.

Can't that be deferred until the editor was initially loaded? So one can at least start typing while ATA happens in the background?

**Comment by orta** [comment]
Yeah ATA is totally async and deffered, what you're seeing is the downloading of Monaco in which case you can't type anything because it's not loaded the editor yet

**Comment by AlCalzone** [comment]
Ok, then feel free to close this.

**Comment by orta** [comment]
Closing, the v3 playground keeps all of the essential code on it's [own CDN](https://github.com/orta/make-monaco-builds/) - only ATA and Playground plugins come from unpkg (which are non-essential, and non-blocking)
