### ISSUE TITLE
Playground: code with errors no longer shows compiled version

### ISSUE THREAD

**Issue by connor4312** [microsoft/TypeScript-Website#982]
Previously, the TypeScript playground would still show the compiled code even if there were errors. This was _super_ useful as a scratch pad I could paste into if I wanted to get plain JS code I could play around with in a repl or toy script. However, it now seems that no output is show if there are any errors.

![image](https://user-images.githubusercontent.com/2230985/91626762-e0763280-e966-11ea-9f2c-a3f0b7c3af15.png)

**Repro:** Open https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUBKAXIgInAUwGcA5OKAUQA8YpEBvAKEUQCcCoRWkAWAJgDcjAL5A

**Code**

```ts
function foo(): DoesNotExit {
  return 42;
}
```

**Expected behavior:**  `function foo() { return 42 }` appears on the right hand side

**Actual behavior:** Nothing appears on the right hand size

**Comment by orta** [comment]
It should handle this, looks like there's an error in the developer console:
![Screen Shot 2020-08-29 at 1 21 30 PM](https://user-images.githubusercontent.com/49038/91642569-6abba680-e9fa-11ea-99e5-7da21ab66a45.png)
